import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib.Combinatorics.SimpleGraph.Extremal.Turan
import Mathlib.Combinatorics.SimpleGraph.Finite
import Mathlib.Data.Finset.Card
import Mathlib.Tactic

/-!
# Finite Extremal Graph and Relation Lemmas

Reusable finite counting lemmas for extremal-graph reductions.  The directed
relation lemmas support arguments where many unordered graph edges each choose
one directed witness, and a pigeonhole step then produces a row with many
outgoing witnesses.
-/

open scoped BigOperators

namespace AppliedModelingLib
namespace Math
namespace FiniteRelation

variable {V : Type*}

/-- All ordered pairs satisfying a finite binary relation. -/
def directedPairFinset [Fintype V] (R : V → V → Prop) [DecidableRel R] :
    Finset (V × V) :=
  Finset.univ.filter fun p => R p.1 p.2

/-- The row of all targets related to a fixed source. -/
def rowFinset [Fintype V] (R : V → V → Prop) [DecidableRel R] (i : V) :
    Finset V :=
  Finset.univ.filter fun j => R i j

@[simp] theorem mem_directedPairFinset [Fintype V]
    (R : V → V → Prop) [DecidableRel R] {p : V × V} :
    p ∈ directedPairFinset R ↔ R p.1 p.2 := by
  simp [directedPairFinset]

@[simp] theorem mem_rowFinset [Fintype V]
    (R : V → V → Prop) [DecidableRel R] {i j : V} :
    j ∈ rowFinset R i ↔ R i j := by
  simp [rowFinset]

/-- Counting ordered relation witnesses by first coordinate. -/
theorem card_directedPairFinset_eq_sum_card_rowFinset
    [Fintype V] (R : V → V → Prop) [DecidableRel R] :
    (directedPairFinset R).card = ∑ i : V, (rowFinset R i).card := by
  classical
  rw [directedPairFinset]
  have hmaps :
      ((Finset.univ.filter fun p : V × V => R p.1 p.2 : Finset (V × V)) : Set (V × V)).MapsTo
        Prod.fst (Finset.univ : Finset V) := by
    intro p _hp
    simp
  rw [Finset.card_eq_sum_card_fiberwise hmaps]
  refine Finset.sum_congr rfl ?_
  intro i _hi
  refine Finset.card_bij
    (s := (Finset.univ.filter fun p : V × V => R p.1 p.2).filter
      fun p => Prod.fst p = i)
    (t := rowFinset R i) (fun p _hp => p.2) ?_ ?_ ?_
  · intro p hp
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hp
    simp [rowFinset, hp.2 ▸ hp.1]
  · intro p hp q hq hpq
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hp hq
    exact Prod.ext (hp.2.trans hq.2.symm) (by simpa using hpq)
  · intro j hj
    refine ⟨(i, j), ?_, rfl⟩
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    simpa [rowFinset] using hj

/--
Pigeonhole for finite directed relations: if the number of ordered witnesses is
strictly larger than `card V * q`, some row has more than `q` witnesses.
-/
theorem exists_row_card_gt_of_card_mul_lt_directedPairFinset
    [Fintype V] (R : V → V → Prop) [DecidableRel R] {q : ℕ}
    (h : Fintype.card V * q < (directedPairFinset R).card) :
    ∃ i : V, q < (rowFinset R i).card := by
  classical
  by_contra hnone
  push Not at hnone
  have hsum :
      ∑ i : V, (rowFinset R i).card ≤ ∑ _i : V, q := by
    exact Finset.sum_le_sum fun i _hi => hnone i
  have hcard :
      (directedPairFinset R).card ≤ Fintype.card V * q := by
    rw [card_directedPairFinset_eq_sum_card_rowFinset]
    refine hsum.trans ?_
    simp [Finset.sum_const]
  exact (not_lt_of_ge hcard) h

/--
Real-valued average form of the directed-relation pigeonhole lemma.
-/
theorem exists_row_card_gt_of_real_card_mul_lt_directedPairFinset
    [Fintype V] (R : V → V → Prop) [DecidableRel R] {q : ℕ}
    (h : (Fintype.card V : ℝ) * (q : ℝ) < ((directedPairFinset R).card : ℝ)) :
    ∃ i : V, q < (rowFinset R i).card := by
  have hnat : Fintype.card V * q < (directedPairFinset R).card := by
    exact_mod_cast h
  exact exists_row_card_gt_of_card_mul_lt_directedPairFinset R hnat

/--
Non-strict average form: if there are at least `card V * q` ordered witnesses,
with `q > 0` and a nonempty vertex type, some row has at least `q` witnesses.
-/
theorem exists_row_card_ge_of_card_mul_le_directedPairFinset
    [Fintype V] [Nonempty V] (R : V → V → Prop) [DecidableRel R] {q : ℕ}
    (hq : 0 < q) (h : Fintype.card V * q ≤ (directedPairFinset R).card) :
    ∃ i : V, q ≤ (rowFinset R i).card := by
  classical
  by_contra hnone
  push Not at hnone
  have hrow : ∀ i : V, (rowFinset R i).card ≤ q - 1 := by
    intro i
    exact Nat.le_pred_of_lt (hnone i)
  have hsum :
      ∑ i : V, (rowFinset R i).card ≤ ∑ _i : V, (q - 1) := by
    exact Finset.sum_le_sum fun i _hi => hrow i
  have hcard_le :
      (directedPairFinset R).card ≤ Fintype.card V * (q - 1) := by
    rw [card_directedPairFinset_eq_sum_card_rowFinset]
    refine hsum.trans ?_
    simp [Finset.sum_const]
  have hstrict : Fintype.card V * (q - 1) < Fintype.card V * q := by
    exact Nat.mul_lt_mul_of_pos_left (Nat.pred_lt (Nat.ne_of_gt hq)) Fintype.card_pos
  exact (not_lt_of_ge h) (hcard_le.trans_lt hstrict)

/--
For the undirected graph generated by symmetrizing a directed relation, every
edge has at least one directed relation witness.  Consequently the number of
undirected edges is at most the number of directed witnesses.
-/
theorem card_edgeSet_fromRel_le_card_directedPairFinset
    [Fintype V] [DecidableEq V] (R : V → V → Prop) [DecidableRel R] :
    Fintype.card (SimpleGraph.fromRel R).edgeSet ≤ (directedPairFinset R).card := by
  classical
  rw [SimpleGraph.card_edgeSet]
  refine Finset.card_le_card_of_surjOn
    (s := directedPairFinset R) (t := (SimpleGraph.fromRel R).edgeFinset)
    (fun p : V × V => s(p.1, p.2)) ?_
  intro e he
  induction e using Sym2.ind with
  | h a b =>
      simp only [Finset.mem_coe, SimpleGraph.mem_edgeFinset, SimpleGraph.mem_edgeSet] at he
      rcases he with ⟨_hne, hab | hba⟩
      · refine ⟨(a, b), ?_, rfl⟩
        simpa [directedPairFinset] using hab
      · refine ⟨(b, a), ?_, Sym2.eq_swap⟩
        simpa [directedPairFinset] using hba

end FiniteRelation

namespace FiniteGraph

variable {V : Type*}

/-- A finite graph and its complement partition the complete graph's edges. -/
theorem card_edgeFinset_add_card_compl_edgeFinset
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] :
    G.edgeFinset.card + Gᶜ.edgeFinset.card = (Fintype.card V).choose 2 := by
  classical
  have hdisj : Disjoint G.edgeFinset Gᶜ.edgeFinset := by
    rw [SimpleGraph.disjoint_edgeFinset]
    exact disjoint_compl_right
  calc
    G.edgeFinset.card + Gᶜ.edgeFinset.card =
        (G.edgeFinset ∪ Gᶜ.edgeFinset).card := by
          exact (Finset.card_union_of_disjoint hdisj).symm
    _ = ((⊤ : SimpleGraph V).edgeFinset).card := by
          congr 1
          ext e
          induction e using Sym2.ind with
          | h a b =>
              by_cases hne : a = b
              · subst b
                simp [SimpleGraph.mem_edgeFinset]
              · by_cases hG : G.Adj a b
                · simp [SimpleGraph.mem_edgeFinset, SimpleGraph.mem_edgeSet, hne, hG]
                · simp [SimpleGraph.mem_edgeFinset, SimpleGraph.mem_edgeSet, hne, hG]
    _ = (Fintype.card V).choose 2 :=
          SimpleGraph.card_edgeFinset_top_eq_card_choose_two

/--
If the complement has at most `U` edges, then the graph has at least
`choose(card V, 2) - U` edges.
-/
theorem card_edgeFinset_ge_choose_sub_of_compl_card_le
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {U : ℕ}
    (hU : Gᶜ.edgeFinset.card ≤ U) :
    (Fintype.card V).choose 2 - U ≤ G.edgeFinset.card := by
  have htotal := card_edgeFinset_add_card_compl_edgeFinset G
  omega

/--
Turán lower-bound wrapper for a graph whose complement is `(r+1)`-clique-free.
This is the paper-source move "apply Turán to the complement, hence lower-bound
the original graph's edge count".
-/
theorem card_edgeFinset_ge_choose_sub_turanBound_of_compl_cliqueFree
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {r : ℕ}
    (hcf : Gᶜ.CliqueFree (r + 1)) :
    let n := Fintype.card V
    n.choose 2 -
      ((n ^ 2 - (n % r) ^ 2) * (r - 1) / (2 * r) + (n % r).choose 2) ≤
        G.edgeFinset.card := by
  classical
  dsimp
  refine card_edgeFinset_ge_choose_sub_of_compl_card_le (G := G) ?_
  simpa using hcf.card_edgeFinset_le

/--
Turán lower-bound wrapper indexed by the forbidden clique size `s`, instead of
the number of Turán parts `s - 1`.
-/
theorem card_edgeFinset_ge_choose_sub_turanBound_of_compl_cliqueFree_card
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {s : ℕ}
    (hs : 0 < s) (hcf : Gᶜ.CliqueFree s) :
    let n := Fintype.card V
    let r := s - 1
    n.choose 2 -
      ((n ^ 2 - (n % r) ^ 2) * (r - 1) / (2 * r) + (n % r).choose 2) ≤
        G.edgeFinset.card := by
  classical
  dsimp
  have hsucc : s - 1 + 1 = s := Nat.sub_add_cancel (Nat.succ_le_of_lt hs)
  have hcf' : Gᶜ.CliqueFree ((s - 1) + 1) := by
    simpa [hsucc] using hcf
  simpa using
    card_edgeFinset_ge_choose_sub_turanBound_of_compl_cliqueFree
      (G := G) (r := s - 1) hcf'

/--
Coarse real-valued Turán consequence in the form used in source proofs: if
the complement is `(r+1)`-clique-free, then `G` has at least
`n^2/(2r) - n/2` edges.
-/
theorem card_edgeFinset_real_ge_sq_div_two_mul_sub_half_of_compl_cliqueFree
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {r : ℕ}
    (hr : 0 < r) (hcf : Gᶜ.CliqueFree (r + 1)) :
    let n := Fintype.card V
    (n : ℝ) ^ 2 / (2 * (r : ℝ)) - (n : ℝ) / 2 ≤
      (G.edgeFinset.card : ℝ) := by
  classical
  dsimp
  let n := Fintype.card V
  have hcomp_le_turan :
      Gᶜ.edgeFinset.card ≤ (SimpleGraph.turanGraph n r).edgeFinset.card := by
    have hcf_le := hcf.card_edgeFinset_le (r := r)
    simpa [n, SimpleGraph.card_edgeFinset_turanGraph] using hcf_le
  have hcomp_mul_nat :
      2 * r * Gᶜ.edgeFinset.card ≤ (r - 1) * n ^ 2 := by
    exact
      (Nat.mul_le_mul_left (2 * r) hcomp_le_turan).trans
        (SimpleGraph.mul_card_edgeFinset_turanGraph_le (n := n) (r := r))
  have hcomp_mul_real :
      (2 : ℝ) * (r : ℝ) * (Gᶜ.edgeFinset.card : ℝ) ≤
        ((r - 1 : ℕ) : ℝ) * (n : ℝ) ^ 2 := by
    exact_mod_cast hcomp_mul_nat
  have hr_real_pos : 0 < (r : ℝ) := by exact_mod_cast hr
  have hcomp_le :
      (Gᶜ.edgeFinset.card : ℝ) ≤
        ((r - 1 : ℕ) : ℝ) * (n : ℝ) ^ 2 / (2 * (r : ℝ)) := by
    have hden_pos : 0 < (2 : ℝ) * (r : ℝ) := by positivity
    rw [le_div_iff₀ hden_pos]
    ring_nf
    simpa [mul_assoc, mul_left_comm, mul_comm] using hcomp_mul_real
  have htotal := card_edgeFinset_add_card_compl_edgeFinset G
  have htotal_real :
      (G.edgeFinset.card : ℝ) + (Gᶜ.edgeFinset.card : ℝ) =
        (n.choose 2 : ℝ) := by
    exact_mod_cast htotal
  have hchoose_real :
      (n.choose 2 : ℝ) = (n : ℝ) * ((n : ℝ) - 1) / 2 := by
    simpa using (Nat.cast_choose_two (K := ℝ) n)
  have hcomp_le' :
      (Gᶜ.edgeFinset.card : ℝ) ≤
        ((r : ℝ) - 1) * (n : ℝ) ^ 2 / (2 * (r : ℝ)) := by
    have hr_sub :
        ((r - 1 : ℕ) : ℝ) = (r : ℝ) - 1 := by
      rw [Nat.cast_sub (Nat.succ_le_of_lt hr)]
      norm_num
    simpa [hr_sub] using hcomp_le
  have hG_eq :
      (G.edgeFinset.card : ℝ) =
        (n : ℝ) * ((n : ℝ) - 1) / 2 - (Gᶜ.edgeFinset.card : ℝ) := by
    linarith
  rw [hG_eq]
  have hden_pos : 0 < (2 : ℝ) * (r : ℝ) := by positivity
  calc
    (n : ℝ) ^ 2 / (2 * (r : ℝ)) - (n : ℝ) / 2
        ≤ (n : ℝ) * ((n : ℝ) - 1) / 2 -
            (((r : ℝ) - 1) * (n : ℝ) ^ 2 / (2 * (r : ℝ))) := by
          field_simp [hr_real_pos.ne', hden_pos.ne']
          ring_nf
          exact le_rfl
    _ ≤ (n : ℝ) * ((n : ℝ) - 1) / 2 - (Gᶜ.edgeFinset.card : ℝ) := by
          linarith

/--
If every `n`-element vertex set contains an edge of `G`, then the complement
has no `n`-clique.  This packages the source equivalence between "no
independent set of size `n`" and "the complement is `n`-clique-free".
-/
theorem compl_cliqueFree_of_forall_finset_exists_adj
    [Fintype V] [DecidableEq V] (G : SimpleGraph V) [DecidableRel G.Adj] {n : ℕ}
    (h : ∀ s : Finset V, s.card = n →
      ∃ i ∈ s, ∃ j ∈ s, i ≠ j ∧ G.Adj i j) :
    Gᶜ.CliqueFree n := by
  intro s hs
  rw [SimpleGraph.isNClique_iff] at hs
  rcases h s hs.2 with ⟨i, hi, j, hj, hij, hadj⟩
  have hcomp_adj : Gᶜ.Adj i j := hs.1 hi hj hij
  have hnot_adj : ¬ G.Adj i j := (SimpleGraph.compl_adj G i j).mp hcomp_adj |>.2
  exact hnot_adj hadj

end FiniteGraph

namespace Graph

variable {V W : Type*}

/--
An edge-constant vertex label is constant on a preconnected graph.  This is
the path-chaining step used when local overlap identities propagate through a
connected overlap graph.
-/
theorem eq_of_adj_eq_of_preconnected {G : SimpleGraph V}
    (hpreconnected : G.Preconnected) (label : V → W)
    (hlabel : ∀ ⦃u v : V⦄, G.Adj u v → label u = label v)
    (u v : V) : label u = label v := by
  have hreachable : Relation.ReflTransGen G.Adj u v :=
    (SimpleGraph.reachable_iff_reflTransGen u v).mp (hpreconnected u v)
  induction hreachable using Relation.ReflTransGen.head_induction_on with
  | refl => rfl
  | head hstep _ ih => exact (hlabel hstep).trans ih

/--
The connected-graph version of `eq_of_adj_eq_of_preconnected`.  The
nonemptiness part of connectedness is not needed after the two vertices are
given explicitly.
-/
theorem eq_of_adj_eq_of_connected {G : SimpleGraph V}
    (hconnected : G.Connected) (label : V → W)
    (hlabel : ∀ ⦃u v : V⦄, G.Adj u v → label u = label v)
    (u v : V) : label u = label v :=
  eq_of_adj_eq_of_preconnected hconnected.preconnected label hlabel u v

end Graph

namespace FiniteRelation

variable {V : Type*}

/--
If every `s`-element set contains an edge in the graph generated by a directed
relation, then the directed relation has at least the corresponding complement
Turán number of witnesses.
-/
theorem card_directedPairFinset_ge_choose_sub_turanBound_of_forall_finset_exists_fromRel_adj
    [Fintype V] [DecidableEq V] (R : V → V → Prop) [DecidableRel R] {s : ℕ}
    (hs : 0 < s)
    (h : ∀ t : Finset V, t.card = s →
      ∃ i ∈ t, ∃ j ∈ t, i ≠ j ∧ (SimpleGraph.fromRel R).Adj i j) :
    let n := Fintype.card V
    let r := s - 1
    n.choose 2 -
      ((n ^ 2 - (n % r) ^ 2) * (r - 1) / (2 * r) + (n % r).choose 2) ≤
        (directedPairFinset R).card := by
  classical
  dsimp
  have hcf :
      (SimpleGraph.fromRel R)ᶜ.CliqueFree s :=
    FiniteGraph.compl_cliqueFree_of_forall_finset_exists_adj
      (G := SimpleGraph.fromRel R) h
  have hedge :
      let n := Fintype.card V
      let r := s - 1
      n.choose 2 -
        ((n ^ 2 - (n % r) ^ 2) * (r - 1) / (2 * r) + (n % r).choose 2) ≤
          (SimpleGraph.fromRel R).edgeFinset.card :=
    FiniteGraph.card_edgeFinset_ge_choose_sub_turanBound_of_compl_cliqueFree_card
      (G := SimpleGraph.fromRel R) hs hcf
  have hle :
      (SimpleGraph.fromRel R).edgeFinset.card ≤ (directedPairFinset R).card := by
    rw [← SimpleGraph.card_edgeSet (G := SimpleGraph.fromRel R)]
    exact card_edgeSet_fromRel_le_card_directedPairFinset (V := V) R
  exact hedge.trans hle

/--
Coarse real-valued Turán lower bound for a directed relation after
symmetrizing it into a graph.  This is the source-friendly form behind
`m^2/(2r) - m/2` edge-count estimates.
-/
theorem card_directedPairFinset_real_ge_sq_div_two_mul_sub_half_of_forall_finset_exists_fromRel_adj
    [Fintype V] [DecidableEq V] (R : V → V → Prop) [DecidableRel R] {s : ℕ}
    (hs : 1 < s)
    (h : ∀ t : Finset V, t.card = s →
      ∃ i ∈ t, ∃ j ∈ t, i ≠ j ∧ (SimpleGraph.fromRel R).Adj i j) :
    let n := Fintype.card V
    let r := s - 1
    (n : ℝ) ^ 2 / (2 * (r : ℝ)) - (n : ℝ) / 2 ≤
      ((directedPairFinset R).card : ℝ) := by
  classical
  dsimp
  have hr : 0 < s - 1 := Nat.sub_pos_of_lt hs
  have hcf :
      (SimpleGraph.fromRel R)ᶜ.CliqueFree s :=
    FiniteGraph.compl_cliqueFree_of_forall_finset_exists_adj
      (G := SimpleGraph.fromRel R) h
  have hsucc : s - 1 + 1 = s := Nat.sub_add_cancel (by omega : 1 ≤ s)
  have hcf' : (SimpleGraph.fromRel R)ᶜ.CliqueFree ((s - 1) + 1) := by
    simpa [hsucc] using hcf
  have hG_lower :
      (Fintype.card V : ℝ) ^ 2 / (2 * ((s - 1 : ℕ) : ℝ)) -
          (Fintype.card V : ℝ) / 2 ≤
        ((SimpleGraph.fromRel R).edgeFinset.card : ℝ) :=
    FiniteGraph.card_edgeFinset_real_ge_sq_div_two_mul_sub_half_of_compl_cliqueFree
      (G := SimpleGraph.fromRel R) (r := s - 1) hr hcf'
  have hgraph_to_pairs :
      (SimpleGraph.fromRel R).edgeFinset.card ≤ (directedPairFinset R).card := by
    rw [← SimpleGraph.card_edgeSet (G := SimpleGraph.fromRel R)]
    exact card_edgeSet_fromRel_le_card_directedPairFinset (V := V) R
  have hgraph_to_pairs_real :
      ((SimpleGraph.fromRel R).edgeFinset.card : ℝ) ≤
        ((directedPairFinset R).card : ℝ) := by
    exact_mod_cast hgraph_to_pairs
  exact hG_lower.trans hgraph_to_pairs_real

/--
Source-form Turán-plus-pigeonhole lemma for directed relations.  If every
`s`-set has an edge after symmetrization and the coarse Turán lower bound beats
`card V * q`, then some row has more than `q` directed witnesses.
-/
theorem exists_row_card_gt_of_real_card_mul_lt_coarse_turan_of_forall_finset_exists_fromRel_adj
    [Fintype V] [DecidableEq V] (R : V → V → Prop) [DecidableRel R] {s q : ℕ}
    (hs : 1 < s)
    (h : ∀ t : Finset V, t.card = s →
      ∃ i ∈ t, ∃ j ∈ t, i ≠ j ∧ (SimpleGraph.fromRel R).Adj i j)
    (havg :
      let n := Fintype.card V
      let r := s - 1
      (n : ℝ) * (q : ℝ) <
        (n : ℝ) ^ 2 / (2 * (r : ℝ)) - (n : ℝ) / 2) :
    ∃ i : V, q < (rowFinset R i).card := by
  classical
  have hpair :
      let n := Fintype.card V
      let r := s - 1
      (n : ℝ) ^ 2 / (2 * (r : ℝ)) - (n : ℝ) / 2 ≤
        ((directedPairFinset R).card : ℝ) :=
    card_directedPairFinset_real_ge_sq_div_two_mul_sub_half_of_forall_finset_exists_fromRel_adj
      (R := R) hs h
  exact
    exists_row_card_gt_of_real_card_mul_lt_directedPairFinset
      (R := R) (q := q) (havg.trans_le hpair)

end FiniteRelation
end Math
end AppliedModelingLib
