import CGGG20SelectiveInformationAcquisition.MainTheorems
import Mathlib.Probability.Independence.Basic
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-!
# Screening-and-allocation source model

The main results of the paper concern a *pair* consisting of a randomized
screening policy and an allocation policy.  This file records that outer
optimization problem directly and proves the fixed-screening reduction used by
the threshold-replacement arguments.  The underlying allocation theorem lives
in `MainTheorems`; no optimality-preservation fact is assumed here.
-/

open scoped BigOperators

namespace CGGG20SelectiveInformationAcquisition

open MeasureTheory

noncomputable section

/-- The complete vector of utility estimates observed after screening. -/
def postScreeningEstimateVector
    {Applicant Outcome Group : Type*} [MeasurableSpace Outcome]
    (D : MeasureGroupAllocationData Applicant Outcome Group) (outcome : Outcome) :
    Applicant → ℝ :=
  fun item => D.posteriorUtility item outcome

/-- The sigma-algebra generated by the paper's full post-screening estimate vector. -/
noncomputable abbrev postScreeningEstimateSigma
    {Applicant Outcome Group : Type*} [MeasurableSpace Outcome]
    (D : MeasureGroupAllocationData Applicant Outcome Group) : MeasurableSpace Outcome :=
  MeasurableSpace.comap (postScreeningEstimateVector D) inferInstance

theorem postScreeningEstimateVector_measurable
    {Applicant Outcome Group : Type*} [MeasurableSpace Outcome]
    (D : MeasureGroupAllocationData Applicant Outcome Group) :
    Measurable (postScreeningEstimateVector D) :=
  measurable_pi_lambda _ D.posteriorUtility_measurable

theorem postScreeningEstimateSigma_le
    {Applicant Outcome Group : Type*} [MeasurableSpace Outcome]
    (D : MeasureGroupAllocationData Applicant Outcome Group) :
    postScreeningEstimateSigma D ≤ (inferInstance : MeasurableSpace Outcome) :=
  (postScreeningEstimateVector_measurable D).comap_le

/--
An admissible source screening policy: each applicant is independently selected
with a probability in the unit interval.  The post-screening model below binds
the resulting Bernoulli variables to the selected probabilities.
-/
structure ScreeningPolicy (Applicant : Type*) where
  probability : Applicant → ℝ
  probability_bounds : ∀ item, 0 ≤ probability item ∧ probability item ≤ 1

instance {Applicant : Type*} : CoeFun (ScreeningPolicy Applicant) (fun _ => Applicant → ℝ) where
  coe policy := policy.probability

/--
Under the paper's clarified source-model reading, an applicant's displayed
post-screening estimate remains their conditional expected utility even after
conditioning on the *entire* vector of estimates observed by the lender.

The paper permits allocation rules of the form `A(hat U)`, rather than rules
depending only on `hat U_i`. This full-vector posterior reading supplies the
source's realized-to-posterior utility bridge for every such allocation rule.
-/
abbrev full_vector_posterior_sufficiency
    {Applicant Outcome Group : Type*} [MeasurableSpace Outcome]
    (D : ScreeningPolicy Applicant →
      MeasureGroupAllocationData Applicant Outcome Group)
    (actualUtility : Applicant → Outcome → ℝ) : Prop :=
  ∀ (p : ScreeningPolicy Applicant) item,
    (D p).posteriorUtility item =ᵐ[(D p).law]
      (D p).law[actualUtility item | postScreeningEstimateSigma (D p)]

/--
The paper's post-screening allocation model.  For each screening-probability
vector, `post` is the probability distribution of the post-screening utility
estimates.  Its screening indicators have the exact joint law of independent
Bernoulli draws with the selected probabilities, and the post-screening utility
is the source's prior-or-screened conditional estimate according to that draw.
Groups and costs remain fixed before screening.  The two displayed bridge
fields are the source's conditional-expectation identities
`E[A_i U_i] = E[A_i hat U_i]`, including their groupwise form.
-/
structure ScreeningAllocationData
    (Applicant Outcome Group : Type*) [Fintype Applicant] [MeasurableSpace Outcome] where
  /-- Expected screening cost for each applicant. -/
  screenCost : Applicant → ℝ
  /-- Allocation costs are fixed before screening. -/
  allocCost : Applicant → ℝ
  /-- The source's realized utility random variables. -/
  actualUtility : Applicant → Outcome → ℝ
  /-- The post-screening allocation model induced by a screening policy. -/
  post : ScreeningPolicy Applicant → MeasureGroupAllocationData Applicant Outcome Group
  /-- Whether this applicant is screened in a post-screening outcome. -/
  screened : Applicant → Outcome → Bool
  /-- Screening indicators are measurable random variables. -/
  screened_measurable : ∀ item, Measurable (screened item)
  /-- The prior conditional expected utility before screening. -/
  priorUtility : Applicant → ℝ
  /-- The conditional expected utility after the applicant is screened. -/
  screenedUtility : Applicant → Outcome → ℝ
  /-- The lender's estimate is the prior or screened conditional estimate. -/
  posterior_utility_from_screening :
    ∀ (p : ScreeningPolicy Applicant) item outcome,
      (post p).posteriorUtility item outcome =
        if screened item outcome then screenedUtility item outcome else priorUtility item
  /-- The applicant groups are fixed before screening. -/
  group : Applicant → Group
  post_group : ∀ p, (post p).group = group
  /-- Screening changes information, not the cost of allocating to an applicant. -/
  post_allocCost : ∀ p, (post p).allocCost = allocCost
  /-- Every post-screening law is the source's probability distribution. -/
  post_probability : ∀ p, IsProbabilityMeasure (post p).law
  /-- The complete screening vector has the independent Bernoulli product law. -/
  screening_independent_bernoulli :
    ∀ (p : ScreeningPolicy Applicant) (bits : Applicant → Bool),
      (post p).law {outcome | ∀ item, screened item outcome = bits item} =
        ∏ item : Applicant,
          ENNReal.ofReal (if bits item then p item else 1 - p item)
  /--
  The screening coin vector is exogenous to the applicants' potential utility
  and post-screening-information vector.  This is the approved sequential
  reading of the source model: the policy randomizes whom to screen after the
  latent applicant information is fixed, rather than changing that information
  through the choice of `p`.
  -/
  screening_exogenous_to_potential_utilities :
    ∀ p,
      ProbabilityTheory.IndepFun
        (fun outcome => fun item => screened item outcome)
        (fun outcome => fun item =>
          (actualUtility item outcome, screenedUtility item outcome))
        (post p).law
  /--
  The joint law of potential realized utilities and screened conditional
  utilities is fixed before the screening policy is selected.  Together with
  `screening_exogenous_to_potential_utilities`, this rules out a policy-indexed
  change to the latent population.
  -/
  potential_utility_law_invariant :
    ∀ p p',
      Measure.map
          (fun outcome => fun item =>
            (actualUtility item outcome, screenedUtility item outcome))
          (post p).law =
        Measure.map
          (fun outcome => fun item =>
            (actualUtility item outcome, screenedUtility item outcome))
          (post p').law
  /-- Every post-screening law is finite, as required for its expectations. -/
  post_finite : ∀ p, IsFiniteMeasure (post p).law
  /-- Realized utilities are integrable under every policy-induced source law. -/
  actual_utility_integrable :
    ∀ (p : ScreeningPolicy Applicant) item,
      Integrable (actualUtility item) (post p).law
  /--
  Under the clarified source-model reading, the post-screening estimate is the
  conditional expectation of realized utility given the entire information
  vector available to the lender.  This makes explicit the reading used by the
  source's full-vector allocation rule `A(hat U)`.
  -/
  posterior_utility_is_condExp_observed :
    full_vector_posterior_sufficiency post actualUtility

namespace ScreeningAllocationData

variable {Applicant Outcome Group : Type*}
variable [Fintype Applicant] [MeasurableSpace Outcome]

/-- A randomized screening policy is a probability vector. -/
def ScreeningPolicyBounds (p : ScreeningPolicy Applicant) : Prop :=
  ∀ item, 0 ≤ p item ∧ p item ≤ 1

/-- Expected screening expenditure. -/
noncomputable def screeningSpend
    (D : ScreeningAllocationData Applicant Outcome Group)
    (p : ScreeningPolicy Applicant) : ℝ :=
  ∑ item : Applicant, D.screenCost item * p item

/-- A source allocation policy after screening: its input is the full vector of
post-screening utility estimates, as in the paper's `A(hat U)` notation. -/
abbrev PostScreeningAllocationRule (Applicant : Type*) :=
  (Applicant → ℝ) → Applicant → ℝ

/-- Evaluate a source allocation rule on the post-screening estimate vector. -/
def evaluatePostScreeningAllocationRule
    (D : ScreeningAllocationData Applicant Outcome Group)
    (screening : ScreeningPolicy Applicant)
    (rule : PostScreeningAllocationRule Applicant) :
    MeasureGroupAllocationData.AllocationPolicy Applicant Outcome :=
  fun item outcome =>
    rule (fun applicant => (D.post screening).posteriorUtility applicant outcome) item

/--
A source policy pair: a screening vector and an allocation rule whose only
run-time input is the entire post-screening estimate vector.  The evaluated
allocation is deliberately derived from that rule, rather than supplied as an
arbitrary `Outcome →` function.
-/
structure PolicyPair (D : ScreeningAllocationData Applicant Outcome Group) where
  screening : ScreeningPolicy Applicant
  allocationRule : PostScreeningAllocationRule Applicant
  /-- The source's `A(hat U)` is a measurable rule of the observed estimate vector. -/
  allocationRule_measurable :
    ∀ item, Measurable fun estimates => allocationRule estimates item

/-- The allocation executed by a source policy pair. -/
def PolicyPair.allocation
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair) :
    MeasureGroupAllocationData.AllocationPolicy Applicant Outcome :=
  D.evaluatePostScreeningAllocationRule pair.screening pair.allocationRule

/-- A source pair's allocation is measurable in precisely its observed estimate vector. -/
theorem PolicyPair.allocation_observed_measurable
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair) (item : Applicant) :
    Measurable[postScreeningEstimateSigma (D.post pair.screening)]
      (pair.allocation item) := by
  simpa [PolicyPair.allocation, evaluatePostScreeningAllocationRule,
    postScreeningEstimateVector] using
    (pair.allocationRule_measurable item).comp
      (comap_measurable (postScreeningEstimateVector (D.post pair.screening)))

/-- The source pair's allocation is an ordinary measurable allocation policy as well. -/
theorem PolicyPair.allocation_measurable
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair) :
    MeasureGroupAllocationData.AllocationPolicyMeasurable pair.allocation := by
  intro item
  exact (pair.allocation_observed_measurable item).mono
    (postScreeningEstimateSigma_le (D.post pair.screening)) le_rfl

/-- The realized-utility contribution of a bounded source allocation is integrable. -/
theorem PolicyPair.allocation_mul_actualUtility_integrable
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair)
    (hbounded : MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation)
    (item : Applicant) :
    Integrable
      (fun outcome => pair.allocation item outcome * D.actualUtility item outcome)
      (D.post pair.screening).law := by
  letI : IsFiniteMeasure (D.post pair.screening).law := D.post_finite pair.screening
  have hbound :
      ∀ᵐ outcome ∂(D.post pair.screening).law, ‖pair.allocation item outcome‖ ≤ (1 : ℝ) :=
    ae_of_all _ fun outcome => by
      exact abs_le.mpr
        ⟨by linarith [(hbounded item outcome).1], (hbounded item outcome).2⟩
  exact (D.actual_utility_integrable pair.screening item).bdd_mul
    (pair.allocation_measurable item).aestronglyMeasurable hbound

/-- The posterior-utility contribution of a bounded source allocation is integrable. -/
theorem PolicyPair.allocation_mul_posteriorUtility_integrable
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair)
    (hbounded : MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation)
    (item : Applicant) :
    Integrable
      (fun outcome =>
        pair.allocation item outcome *
          (D.post pair.screening).posteriorUtility item outcome)
      (D.post pair.screening).law :=
  (D.post pair.screening).toMeasureCostAwareData.policy_mul_posteriorUtility_integrable
    pair.allocation pair.allocation_measurable hbounded item

/-- A bounded source allocation has the same realized and posterior utility for one item. -/
theorem PolicyPair.integral_actualUtility_eq_posteriorUtility
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair)
    (hbounded : MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation)
    (item : Applicant) :
    (∫ outcome,
      pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law) =
      ∫ outcome,
        pair.allocation item outcome *
          (D.post pair.screening).posteriorUtility item outcome ∂(D.post pair.screening).law := by
  letI : IsFiniteMeasure (D.post pair.screening).law := D.post_finite pair.screening
  have hle : postScreeningEstimateSigma (D.post pair.screening) ≤
      (inferInstance : MeasurableSpace Outcome) :=
    postScreeningEstimateSigma_le (D.post pair.screening)
  have halloc : StronglyMeasurable[postScreeningEstimateSigma (D.post pair.screening)]
      (pair.allocation item) :=
    (pair.allocation_observed_measurable item).stronglyMeasurable
  have hactual : Integrable (D.actualUtility item) (D.post pair.screening).law :=
    D.actual_utility_integrable pair.screening item
  have hproduct : Integrable
      (pair.allocation item * D.actualUtility item) (D.post pair.screening).law := by
    simpa only [Pi.mul_apply] using
      pair.allocation_mul_actualUtility_integrable hbounded item
  calc
    (∫ outcome,
      pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law) =
        ∫ outcome,
          (D.post pair.screening).law[
            pair.allocation item * D.actualUtility item |
              postScreeningEstimateSigma (D.post pair.screening)] outcome ∂(D.post pair.screening).law := by
          simpa only [Pi.mul_apply] using
            (integral_condExp (μ := (D.post pair.screening).law)
              (m := postScreeningEstimateSigma (D.post pair.screening))
              (m₀ := (inferInstance : MeasurableSpace Outcome))
              hle (f := pair.allocation item * D.actualUtility item)).symm
    _ = ∫ outcome,
          pair.allocation item outcome *
            (D.post pair.screening).law[D.actualUtility item |
              postScreeningEstimateSigma (D.post pair.screening)] outcome ∂(D.post pair.screening).law := by
          apply integral_congr_ae
          simpa only [Pi.mul_apply] using
            (MeasureTheory.condExp_mul_of_stronglyMeasurable_left halloc hproduct hactual)
    _ = ∫ outcome,
          pair.allocation item outcome *
            (D.post pair.screening).posteriorUtility item outcome ∂(D.post pair.screening).law := by
          apply integral_congr_ae
          filter_upwards [D.posterior_utility_is_condExp_observed pair.screening item] with outcome hposterior
          rw [hposterior]

/-- A bounded source allocation has equal total realized and posterior utility. -/
theorem PolicyPair.actual_utility_eq_posterior
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair)
    (hbounded : MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation) :
    (∫ outcome,
      ∑ item : Applicant,
        pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law) =
      (D.post pair.screening).expectedPosteriorUtility pair.allocation := by
  unfold MeasureGroupAllocationData.expectedPosteriorUtility
    MeasureCostAwareData.expectedPosteriorUtility
  calc
    (∫ outcome,
      ∑ item : Applicant,
        pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law) =
        ∑ item : Applicant,
          ∫ outcome,
            pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law := by
          exact MeasureTheory.integral_finset_sum Finset.univ
            (fun item _ => pair.allocation_mul_actualUtility_integrable hbounded item)
    _ = ∑ item : Applicant,
          ∫ outcome,
            pair.allocation item outcome *
              (D.post pair.screening).posteriorUtility item outcome ∂(D.post pair.screening).law := by
          refine Finset.sum_congr rfl ?_
          intro item _
          exact pair.integral_actualUtility_eq_posteriorUtility hbounded item
    _ = ∫ outcome,
          ∑ item : Applicant,
            pair.allocation item outcome *
              (D.post pair.screening).posteriorUtility item outcome ∂(D.post pair.screening).law := by
          symm
          exact MeasureTheory.integral_finset_sum Finset.univ
            (fun item _ => pair.allocation_mul_posteriorUtility_integrable hbounded item)

/-- A bounded source allocation has equal realized and posterior utility in every group. -/
theorem PolicyPair.actual_group_utility_eq_posterior
    {D : ScreeningAllocationData Applicant Outcome Group}
    (pair : D.PolicyPair)
    (g : Group)
    (hbounded : MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation) :
    letI : DecidableEq Group := Classical.decEq Group
    (∫ outcome,
      ∑ item : Applicant,
        if (D.post pair.screening).group item = g then
          pair.allocation item outcome * D.actualUtility item outcome
        else 0 ∂(D.post pair.screening).law) =
      (D.post pair.screening).expectedGroupPosteriorUtility g pair.allocation := by
  classical
  unfold MeasureGroupAllocationData.expectedGroupPosteriorUtility
  calc
    (∫ outcome,
      ∑ item : Applicant,
        if (D.post pair.screening).group item = g then
          pair.allocation item outcome * D.actualUtility item outcome
        else 0 ∂(D.post pair.screening).law) =
        ∑ item : Applicant,
          ∫ outcome,
            if (D.post pair.screening).group item = g then
              pair.allocation item outcome * D.actualUtility item outcome
            else 0 ∂(D.post pair.screening).law := by
          apply MeasureTheory.integral_finset_sum Finset.univ
          intro item _
          by_cases hgroup : (D.post pair.screening).group item = g
          · simpa [hgroup] using pair.allocation_mul_actualUtility_integrable hbounded item
          · simp [hgroup]
    _ = ∑ item : Applicant,
          ∫ outcome,
            if (D.post pair.screening).group item = g then
              pair.allocation item outcome *
                (D.post pair.screening).posteriorUtility item outcome
            else 0 ∂(D.post pair.screening).law := by
          refine Finset.sum_congr rfl ?_
          intro item _
          by_cases hgroup : (D.post pair.screening).group item = g
          · simp [hgroup, pair.integral_actualUtility_eq_posteriorUtility hbounded item]
          · simp [hgroup]
    _ = ∫ outcome,
          ∑ item : Applicant,
            if (D.post pair.screening).group item = g then
              pair.allocation item outcome *
                (D.post pair.screening).posteriorUtility item outcome
            else 0 ∂(D.post pair.screening).law := by
          symm
          apply MeasureTheory.integral_finset_sum Finset.univ
          intro item _
          by_cases hgroup : (D.post pair.screening).group item = g
          · simpa [hgroup] using pair.allocation_mul_posteriorUtility_integrable hbounded item
          · simp [hgroup]

/-- Feasibility for the paper's inequality-diversity pair optimization problem. -/
noncomputable def PairSourceFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop := by
  classical
  exact ScreeningPolicyBounds pair.screening ∧
    MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation ∧
      MeasureGroupAllocationData.AllocationPolicyMeasurable pair.allocation ∧
        D.screeningSpend pair.screening +
            (D.post pair.screening).expectedCost pair.allocation ≤ budget ∧
          ∀ g, diversityTarget g ≤
            (D.post pair.screening).expectedGroupPosteriorUtility g pair.allocation

/-- Optimality over all source-admissible screening-and-allocation pairs. -/
def PairSourceOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop :=
  D.PairSourceFeasible budget diversityTarget pair ∧
    ∀ other, D.PairSourceFeasible budget diversityTarget other →
      (D.post other.screening).expectedPosteriorUtility other.allocation ≤
        (D.post pair.screening).expectedPosteriorUtility pair.allocation

/-- Feasibility for the paper's equality-diversity pair optimization problem. -/
noncomputable def PairSourceEqualityFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop := by
  classical
  exact ScreeningPolicyBounds pair.screening ∧
    MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation ∧
      MeasureGroupAllocationData.AllocationPolicyMeasurable pair.allocation ∧
        D.screeningSpend pair.screening +
            (D.post pair.screening).expectedCost pair.allocation ≤ budget ∧
          ∀ g, (D.post pair.screening).expectedGroupPosteriorUtility g pair.allocation =
            equalityTarget g

/-- Equality-diversity optimality over all source-admissible policy pairs. -/
def PairSourceEqualityOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop :=
  D.PairSourceEqualityFeasible budget equalityTarget pair ∧
    ∀ other, D.PairSourceEqualityFeasible budget equalityTarget other →
      (D.post other.screening).expectedPosteriorUtility other.allocation ≤
        (D.post pair.screening).expectedPosteriorUtility pair.allocation

/-- The same pair feasibility, written in the paper's realized-utility terms. -/
noncomputable def PairActualFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop := by
  classical
  exact ScreeningPolicyBounds pair.screening ∧
    MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation ∧
      MeasureGroupAllocationData.AllocationPolicyMeasurable pair.allocation ∧
        D.screeningSpend pair.screening +
            (D.post pair.screening).expectedCost pair.allocation ≤ budget ∧
          ∀ g, diversityTarget g ≤
            ∫ outcome,
              ∑ item : Applicant,
                if (D.post pair.screening).group item = g then
                  pair.allocation item outcome * D.actualUtility item outcome
                else 0 ∂(D.post pair.screening).law

/-- Pair optimality written in the paper's realized-utility terms. -/
def PairActualOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop :=
  D.PairActualFeasible budget diversityTarget pair ∧
    ∀ other, D.PairActualFeasible budget diversityTarget other →
      (∫ outcome,
        ∑ item : Applicant,
          other.allocation item outcome * D.actualUtility item outcome ∂(D.post other.screening).law) ≤
        ∫ outcome,
          ∑ item : Applicant,
            pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law

/-- Equality feasibility written in the source's realized-utility terms. -/
noncomputable def PairActualEqualityFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop := by
  classical
  exact ScreeningPolicyBounds pair.screening ∧
    MeasureGroupAllocationData.AllocationPolicyBounds pair.allocation ∧
      MeasureGroupAllocationData.AllocationPolicyMeasurable pair.allocation ∧
        D.screeningSpend pair.screening +
            (D.post pair.screening).expectedCost pair.allocation ≤ budget ∧
          ∀ g,
            (∫ outcome,
              ∑ item : Applicant,
                if (D.post pair.screening).group item = g then
                  pair.allocation item outcome * D.actualUtility item outcome
                else 0 ∂(D.post pair.screening).law) = equalityTarget g

/-- Equality-pair optimality in the source's realized-utility terms. -/
def PairActualEqualityOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ)
    (pair : D.PolicyPair) : Prop :=
  D.PairActualEqualityFeasible budget equalityTarget pair ∧
    ∀ other, D.PairActualEqualityFeasible budget equalityTarget other →
      (∫ outcome,
        ∑ item : Applicant,
          other.allocation item outcome * D.actualUtility item outcome ∂(D.post other.screening).law) ≤
        ∫ outcome,
          ∑ item : Applicant,
            pair.allocation item outcome * D.actualUtility item outcome ∂(D.post pair.screening).law

theorem pairActualFeasible_iff_pairSourceFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ) (pair : D.PolicyPair) :
    D.PairActualFeasible budget diversityTarget pair ↔
      D.PairSourceFeasible budget diversityTarget pair := by
  classical
  constructor
  · rintro ⟨hp, ha, hmeas, hbudget, hgroup⟩
    refine ⟨hp, ha, hmeas, hbudget, ?_⟩
    intro g
    rw [← pair.actual_group_utility_eq_posterior g ha]
    exact hgroup g
  · rintro ⟨hp, ha, hmeas, hbudget, hgroup⟩
    refine ⟨hp, ha, hmeas, hbudget, ?_⟩
    intro g
    rw [pair.actual_group_utility_eq_posterior g ha]
    exact hgroup g

theorem pairActualEqualityFeasible_iff_pairSourceEqualityFeasible
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ) (pair : D.PolicyPair) :
    D.PairActualEqualityFeasible budget equalityTarget pair ↔
      D.PairSourceEqualityFeasible budget equalityTarget pair := by
  classical
  constructor
  · rintro ⟨hp, ha, hmeas, hbudget, hgroup⟩
    refine ⟨hp, ha, hmeas, hbudget, ?_⟩
    intro g
    rw [← pair.actual_group_utility_eq_posterior g ha]
    exact hgroup g
  · rintro ⟨hp, ha, hmeas, hbudget, hgroup⟩
    refine ⟨hp, ha, hmeas, hbudget, ?_⟩
    intro g
    rw [pair.actual_group_utility_eq_posterior g ha]
    exact hgroup g

theorem pairActualOptimal_iff_pairSourceOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ) (pair : D.PolicyPair) :
    D.PairActualOptimal budget diversityTarget pair ↔
      D.PairSourceOptimal budget diversityTarget pair := by
  classical
  constructor
  · rintro ⟨hfeasible, hoptimal⟩
    refine ⟨(D.pairActualFeasible_iff_pairSourceFeasible budget diversityTarget pair).mp hfeasible, ?_⟩
    intro other hother
    have hother_actual :=
      D.pairActualFeasible_iff_pairSourceFeasible budget diversityTarget other |>.mpr hother
    have h := hoptimal other hother_actual
    rw [other.actual_utility_eq_posterior hother_actual.2.1,
      pair.actual_utility_eq_posterior hfeasible.2.1] at h
    exact h
  · rintro ⟨hfeasible, hoptimal⟩
    refine ⟨(D.pairActualFeasible_iff_pairSourceFeasible budget diversityTarget pair).mpr hfeasible, ?_⟩
    intro other hother
    have hother_source :=
      D.pairActualFeasible_iff_pairSourceFeasible budget diversityTarget other |>.mp hother
    have h := hoptimal other hother_source
    rw [← other.actual_utility_eq_posterior hother.2.1,
      ← pair.actual_utility_eq_posterior hfeasible.2.1] at h
    exact h

theorem pairActualEqualityOptimal_iff_pairSourceEqualityOptimal
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ) (pair : D.PolicyPair) :
    D.PairActualEqualityOptimal budget equalityTarget pair ↔
      D.PairSourceEqualityOptimal budget equalityTarget pair := by
  classical
  constructor
  · rintro ⟨hfeasible, hoptimal⟩
    refine ⟨(D.pairActualEqualityFeasible_iff_pairSourceEqualityFeasible budget equalityTarget pair).mp hfeasible, ?_⟩
    intro other hother
    have hother_actual :=
      D.pairActualEqualityFeasible_iff_pairSourceEqualityFeasible budget equalityTarget other |>.mpr hother
    have h := hoptimal other hother_actual
    rw [other.actual_utility_eq_posterior hother_actual.2.1,
      pair.actual_utility_eq_posterior hfeasible.2.1] at h
    exact h
  · rintro ⟨hfeasible, hoptimal⟩
    refine ⟨(D.pairActualEqualityFeasible_iff_pairSourceEqualityFeasible budget equalityTarget pair).mpr hfeasible, ?_⟩
    intro other hother
    have hother_source :=
      D.pairActualEqualityFeasible_iff_pairSourceEqualityFeasible budget equalityTarget other |>.mp hother
    have h := hoptimal other hother_source
    rw [← other.actual_utility_eq_posterior hother.2.1,
      ← pair.actual_utility_eq_posterior hfeasible.2.1] at h
    exact h

/--
Transfer pair optimality to a feasible replacement that weakly improves the
source objective.  Both pairs use `PostScreeningAllocationRule`, so the
comparison remains within the paper's `A(hat U)` policy class.
-/
theorem pairSourceOptimal_of_feasible_improvement
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (diversityTarget : Group → ℝ)
    (original replacement : D.PolicyPair)
    (horiginal : D.PairSourceOptimal budget diversityTarget original)
    (hreplacement_feasible : D.PairSourceFeasible budget diversityTarget replacement)
    (hutility :
      (D.post original.screening).expectedPosteriorUtility original.allocation ≤
        (D.post replacement.screening).expectedPosteriorUtility replacement.allocation) :
    D.PairSourceOptimal budget diversityTarget replacement :=
  ⟨hreplacement_feasible, fun other hother => (horiginal.2 other hother).trans hutility⟩

/-- Equality-diversity counterpart of `pairSourceOptimal_of_feasible_improvement`. -/
theorem pairSourceEqualityOptimal_of_feasible_improvement
    (D : ScreeningAllocationData Applicant Outcome Group)
    (budget : ℝ) (equalityTarget : Group → ℝ)
    (original replacement : D.PolicyPair)
    (horiginal : D.PairSourceEqualityOptimal budget equalityTarget original)
    (hreplacement_feasible : D.PairSourceEqualityFeasible budget equalityTarget replacement)
    (hutility :
      (D.post original.screening).expectedPosteriorUtility original.allocation ≤
        (D.post replacement.screening).expectedPosteriorUtility replacement.allocation) :
    D.PairSourceEqualityOptimal budget equalityTarget replacement :=
  ⟨hreplacement_feasible, fun other hother => (horiginal.2 other hother).trans hutility⟩

end ScreeningAllocationData

end

end CGGG20SelectiveInformationAcquisition
