import AppliedModelingLib.Queueing.MM1.TwoSided.Trajectory
import AppliedModelingLib.Queueing.MM1.TwoSided.PathCylinder
import Mathlib.Probability.Kernel.Invariance

/-!
# Two-sided embedded trajectories with an explicit reverse kernel

This module gives a small, kernel-level construction of an integer-indexed
embedded trajectory.  Its nonnegative half is a stationary forward trajectory
with kernel `K`; conditional on its state at zero, its negative half is an
independent trajectory generated by a supplied reverse kernel `Kr`.

The required two-coordinate compatibility is `ReversePairBalance`: after
reversing the `π ⊗ₘ Kr` pair, it is the forward stationary pair `π ⊗ₘ K`.
From this we prove one checked adjacent-window shift law.  We also identify
the exact cross-zero three-coordinate law and derive its one-step shift
comparison from that same pair balance, through an explicit conditional-Fubini
calculation; a Markov-factorization extension gives the corresponding
four-coordinate shift.  We deliberately do *not* claim full
integer-shift invariance, a continuous-time construction, Palm conditioning,
or PASTA.
-/

namespace AppliedModelingLib.Probability.Queueing

open MeasureTheory ProbabilityTheory Preorder

noncomputable section

variable {α : Type*} [MeasurableSpace α]

/-- The first step of a conditional homogeneous trajectory has its supplied
transition-kernel law. -/
theorem conditionalHomogeneousTrajKernel_map_one
    {K : Kernel α α} [IsMarkovKernel K] :
    (conditionalHomogeneousTrajKernel K).map (fun x => x 1) = K := by
  unfold conditionalHomogeneousTrajKernel
  rw [Kernel.map_comp, Kernel.map_traj_succ_self]
  unfold homogeneousTrajKernel
  rw [Kernel.comp_assoc]
  rw [Kernel.deterministic_comp_deterministic
    (measurable_zeroHistory (α := α)) (measurable_pi_apply _)]
  simpa [zeroHistory, Function.comp_def, Kernel.id] using (Kernel.comp_id K)

/-- Given a forward trajectory, draw a reverse-time tail from the reverse
kernel at the forward time-zero state. -/
noncomputable def conditionalReverseTailKernel (Kr : Kernel α α)
    [IsMarkovKernel Kr] : Kernel (ℕ → α) (ℕ → α) :=
  (conditionalHomogeneousTrajKernel Kr) ∘ₖ
    Kernel.deterministic (fun x : ℕ → α => x 0) (measurable_pi_apply 0)

instance (Kr : Kernel α α) [IsMarkovKernel Kr] :
    IsMarkovKernel (conditionalReverseTailKernel Kr) := by
  unfold conditionalReverseTailKernel
  infer_instance

/-- The first negative-time coordinate of the conditional reverse tail has
the reverse transition-kernel law from the forward state at zero. -/
theorem conditionalReverseTailKernel_map_one
    {Kr : Kernel α α} [IsMarkovKernel Kr] :
    (conditionalReverseTailKernel Kr).map (fun x => x 1) =
      Kr ∘ₖ Kernel.deterministic (fun x : ℕ → α => x 0) (measurable_pi_apply 0) := by
  unfold conditionalReverseTailKernel
  rw [Kernel.map_comp, conditionalHomogeneousTrajKernel_map_one]

/-- The source law: first draw a forward stationary trajectory, then a
reverse tail conditional only on its time-zero state. -/
noncomputable def forwardReverseTwoSidedSourceMeasure (π : Measure α)
    (K Kr : Kernel α α) [IsMarkovKernel K] [IsMarkovKernel Kr] :
    Measure ((ℕ → α) × (ℕ → α)) :=
  stationaryTrajMeasure π K ⊗ₘ conditionalReverseTailKernel Kr

/-- Splice a nonnegative forward trajectory and a reverse-time tail into an
integer-indexed path. -/
def spliceForwardReverse (z : (ℕ → α) × (ℕ → α)) : ℤ → α
  | Int.ofNat n => z.1 n
  | Int.negSucc n => z.2 (n + 1)

theorem measurable_spliceForwardReverse : Measurable (spliceForwardReverse (α := α)) := by
  apply measurable_pi_lambda
  intro i
  cases i with
  | ofNat n => exact (measurable_pi_apply n).comp measurable_fst
  | negSucc n => exact (measurable_pi_apply (n + 1)).comp measurable_snd

/-- The two-sided embedded path with a forward kernel and an explicit reverse
kernel. -/
noncomputable def forwardReverseTwoSidedTrajMeasure (π : Measure α)
    (K Kr : Kernel α α) [IsMarkovKernel K] [IsMarkovKernel Kr] :
    Measure (ℤ → α) :=
  (forwardReverseTwoSidedSourceMeasure π K Kr).map spliceForwardReverse

/-- Pair-balance saying that the reverse one-step coupling becomes the
forward coupling after swapping its coordinates. -/
def Kernel.ReversePairBalance (π : Measure α) (K Kr : Kernel α α) : Prop :=
  (π ⊗ₘ Kr).map Prod.swap = π ⊗ₘ K

/-- Forgetting the reverse tail recovers exactly the forward stationary
trajectory law. -/
theorem forwardReverseTwoSidedSourceMeasure_map_forward
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedSourceMeasure π K Kr).map Prod.fst =
      stationaryTrajMeasure π K := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  change (forwardReverseTwoSidedSourceMeasure π K Kr).fst = stationaryTrajMeasure π K
  unfold forwardReverseTwoSidedSourceMeasure
  rw [Measure.fst_compProd]

/-- The source law of the time-zero state and first reverse-time state is the
composition product `π ⊗ₘ Kr`. -/
theorem forwardReverseTwoSidedSourceMeasure_map_zero_reverseOne
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (z.1 0, z.2 1)) = π ⊗ₘ Kr := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let μ : Measure (ℕ → α) := stationaryTrajMeasure π K
  let f : (ℕ → α) → α := fun x => x 0
  have hf : Measurable f := measurable_pi_apply 0
  let e : ((ℕ → α) × (ℕ → α)) → (ℕ → α) × α :=
    Prod.map id (fun x : ℕ → α => x 1)
  have he : Measurable e :=
    measurable_id.prodMap (measurable_pi_apply 1)
  have hpair : Measurable (fun p : (ℕ → α) × α => (f p.1, p.2)) :=
    hf.comp measurable_fst |>.prodMk measurable_snd
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (z.1 0, z.2 1)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map
          e).map
            (fun p => (f p.1, p.2)) := by
          symm
          rw [Measure.map_map hpair he]
          rfl
    _ = (μ ⊗ₘ (conditionalReverseTailKernel Kr).map (fun x : ℕ → α => x 1)).map
          (fun p => (f p.1, p.2)) := by
          unfold forwardReverseTwoSidedSourceMeasure
          rw [← Measure.compProd_map (μ := μ) (κ := conditionalReverseTailKernel Kr)
            (measurable_pi_apply 1)]
    _ = (μ ⊗ₘ (Kr ∘ₖ Kernel.deterministic f hf)).map
          (fun p => (f p.1, p.2)) := by
          rw [conditionalReverseTailKernel_map_one]
    _ = (μ.map f) ⊗ₘ Kr := by
          exact Measure.compProd_map_input μ Kr f hf
    _ = π ⊗ₘ Kr := by
          change (stationaryTrajMeasure π K).map (fun x => x 0) ⊗ₘ Kr = π ⊗ₘ Kr
          rw [stationaryTrajMeasure_zero_marginal]

/-- The negative/cross-zero adjacent pair has the reverse stationary pair law
with its coordinates swapped. -/
theorem forwardReverseTwoSidedTrajMeasure_crossZeroPair
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (x (-1 : ℤ), x 0)) = (π ⊗ₘ Kr).map Prod.swap := by
  unfold forwardReverseTwoSidedTrajMeasure
  rw [Measure.map_map
    (Measurable.prodMk (measurable_pi_apply (-1 : ℤ)) (measurable_pi_apply 0))
    measurable_spliceForwardReverse]
  change (forwardReverseTwoSidedSourceMeasure π K Kr).map
    (fun z => (z.2 1, z.1 0)) = (π ⊗ₘ Kr).map Prod.swap
  let g : ((ℕ → α) × (ℕ → α)) → α × α := fun z => (z.1 0, z.2 1)
  have hg : Measurable g :=
    ((measurable_pi_apply 0).comp measurable_fst).prodMk
      ((measurable_pi_apply 1).comp measurable_snd)
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (z.2 1, z.1 0)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map g).map Prod.swap := by
          symm
          rw [Measure.map_map measurable_swap hg]
          rfl
    _ = (π ⊗ₘ Kr).map Prod.swap := by
          change ((forwardReverseTwoSidedSourceMeasure π K Kr).map
            (fun z => (z.1 0, z.2 1))).map Prod.swap = _
          rw [forwardReverseTwoSidedSourceMeasure_map_zero_reverseOne]

/-- The nonnegative adjacent pair is the stationary forward one-step law. -/
theorem forwardReverseTwoSidedTrajMeasure_zeroOnePair
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hstationary : Kernel.Invariant K π) :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (x 0, x (1 : ℤ))) = π ⊗ₘ K := by
  unfold forwardReverseTwoSidedTrajMeasure
  rw [Measure.map_map
    (Measurable.prodMk (measurable_pi_apply 0) (measurable_pi_apply (1 : ℤ)))
    measurable_spliceForwardReverse]
  change (forwardReverseTwoSidedSourceMeasure π K Kr).map
    (fun z => (z.1 0, z.1 1)) = π ⊗ₘ K
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (z.1 0, z.1 1)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map Prod.fst).map
          (fun x => (x 0, x 1)) := by
          symm
          rw [Measure.map_map
            ((measurable_pi_apply 0).prodMk (measurable_pi_apply 1)) measurable_fst]
          rfl
    _ = (stationaryTrajMeasure π K).map (fun x => (x 0, x 1)) := by
          rw [forwardReverseTwoSidedSourceMeasure_map_forward]
    _ = π ⊗ₘ K := by
          exact stationaryTrajMeasure_consecutivePair hstationary 0

/-- Pair balance gives a checked one-edge shift consistency law for the
explicit-reverse two-sided path.  This is deliberately only the adjacent
two-coordinate window, not a claim of full path-law shift invariance. -/
theorem Kernel.ReversePairBalance.forwardReverseTwoSidedTrajMeasure_adjacent_shift
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hbalance : Kernel.ReversePairBalance π K Kr)
    (hstationary : Kernel.Invariant K π) :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (x (-1 : ℤ), x 0)) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (x 0, x (1 : ℤ))) := by
  rw [forwardReverseTwoSidedTrajMeasure_crossZeroPair,
    forwardReverseTwoSidedTrajMeasure_zeroOnePair hstationary, hbalance]

/-- Reorder the forward/reverse conditional triple
`((X₀, X₁), X₋₁)` into the cross-zero temporal order
`((X₋₁, X₀), X₁)`. -/
def rotateForwardReverseTriple (p : (α × α) × α) : (α × α) × α :=
  ((p.2, p.1.1), p.1.2)

theorem measurable_rotateForwardReverseTriple :
    Measurable (rotateForwardReverseTriple (α := α)) := by
  exact ((measurable_snd.prodMk (measurable_fst.comp measurable_fst))).prodMk
    (measurable_snd.comp measurable_fst)

/-- The source-law factorization of the first forward pair and first reverse
state.  The reverse state is conditionally generated from `X₀`, independently
of the forward future given that state. -/
theorem forwardReverseTwoSidedSourceMeasure_zeroOne_reverseOne
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => ((z.1 0, z.1 1), z.2 1)) =
      (π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let μ : Measure (ℕ → α) := stationaryTrajMeasure π K
  let f : (ℕ → α) → α × α := fun x => (x 0, x 1)
  let g : α × α → α := Prod.fst
  have hf : Measurable f := (measurable_pi_apply 0).prodMk (measurable_pi_apply 1)
  have hg : Measurable g := measurable_fst
  let e : ((ℕ → α) × (ℕ → α)) → (ℕ → α) × α :=
    Prod.map id (fun x : ℕ → α => x 1)
  have he : Measurable e := measurable_id.prodMap (measurable_pi_apply 1)
  have hpair : Measurable (fun p : (ℕ → α) × α => (f p.1, p.2)) :=
    hf.comp measurable_fst |>.prodMk measurable_snd
  have hpairlaw : μ.map f = π ⊗ₘ K := by
    change (stationaryTrajMeasure π K).map (fun x => (x 0, x 1)) = π ⊗ₘ K
    simpa using (stationaryTrajMeasure_zero_n_pair (π := π) (K := K) 1)
  have hKrprod : Kr ∘ₖ Kernel.deterministic g hg = Kr.prodMkRight α := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => ((z.1 0, z.1 1), z.2 1)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map e).map
          (fun p => (f p.1, p.2)) := by
          symm
          rw [Measure.map_map hpair he]
          rfl
    _ = (μ ⊗ₘ (conditionalReverseTailKernel Kr).map (fun x : ℕ → α => x 1)).map
          (fun p => (f p.1, p.2)) := by
          unfold forwardReverseTwoSidedSourceMeasure
          rw [← Measure.compProd_map (μ := μ) (κ := conditionalReverseTailKernel Kr)
            (measurable_pi_apply 1)]
    _ = (μ ⊗ₘ (Kr ∘ₖ Kernel.deterministic (g ∘ f) (hg.comp hf))).map
          (fun p => (f p.1, p.2)) := by
          rw [conditionalReverseTailKernel_map_one]
          rfl
    _ = (μ.map f) ⊗ₘ (Kr ∘ₖ Kernel.deterministic g hg) := by
          exact Measure.compProd_map_through μ Kr f hf g hg
    _ = (π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α := by
          rw [hpairlaw, hKrprod]

/-- The cross-zero three-coordinate window has the explicit law obtained by
sampling `(X₀,X₁)` from the forward kernel, sampling `X₋₁` from `Kr` at
`X₀`, and rotating the resulting triple into temporal order. -/
theorem forwardReverseTwoSidedTrajMeasure_crossZeroTriple
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))) =
      ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple := by
  have hsource : Measurable (fun z : (ℕ → α) × (ℕ → α) =>
      ((z.1 0, z.1 1), z.2 1)) :=
    (((measurable_pi_apply 0).comp measurable_fst).prodMk
      ((measurable_pi_apply 1).comp measurable_fst)).prodMk
        ((measurable_pi_apply 1).comp measurable_snd)
  unfold forwardReverseTwoSidedTrajMeasure
  rw [Measure.map_map
    (((measurable_pi_apply (-1 : ℤ)).prodMk (measurable_pi_apply 0)).prodMk
      (measurable_pi_apply (1 : ℤ)))
    measurable_spliceForwardReverse]
  change (forwardReverseTwoSidedSourceMeasure π K Kr).map
    (fun z => ((z.2 1, z.1 0), z.1 1)) = _
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => ((z.2 1, z.1 0), z.1 1)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map
          (fun z => ((z.1 0, z.1 1), z.2 1))).map rotateForwardReverseTriple := by
          symm
          rw [Measure.map_map measurable_rotateForwardReverseTriple hsource]
          rfl
    _ = ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple := by
          rw [forwardReverseTwoSidedSourceMeasure_zeroOne_reverseOne]

/-- The first wholly nonnegative three-coordinate window has the usual
forward Markov factorization. -/
theorem forwardReverseTwoSidedTrajMeasure_zeroOneTwoTriple
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) =
      (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by
  have hforward : Measurable (fun x : ℕ → α => ((x 0, x 1), x 2)) :=
    ((measurable_pi_apply 0).prodMk (measurable_pi_apply 1)).prodMk
      (measurable_pi_apply 2)
  have hKprod : K ∘ₖ Kernel.deterministic Prod.snd measurable_snd = K.prodMkLeft α := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  unfold forwardReverseTwoSidedTrajMeasure
  rw [Measure.map_map
    (((measurable_pi_apply 0).prodMk (measurable_pi_apply (1 : ℤ))).prodMk
      (measurable_pi_apply (2 : ℤ)))
    measurable_spliceForwardReverse]
  change (forwardReverseTwoSidedSourceMeasure π K Kr).map
    (fun z => ((z.1 0, z.1 1), z.1 2)) = _
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => ((z.1 0, z.1 1), z.1 2)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map Prod.fst).map
          (fun x => ((x 0, x 1), x 2)) := by
          symm
          rw [Measure.map_map hforward measurable_fst]
          rfl
    _ = (stationaryTrajMeasure π K).map (fun x => ((x 0, x 1), x 2)) := by
          rw [forwardReverseTwoSidedSourceMeasure_map_forward]
    _ = (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by
          rw [stationaryTrajMeasure_zero_pair_succ_recurrence (π := π) (K := K) 1,
            stationaryTrajMeasure_zero_n_pair (π := π) (K := K) 1, hKprod]
          simp

/-- An explicit finite-window compatibility condition for the cross-zero and
one-step-forward triples.  Its two sides are concrete composition-product
laws, so this is not a claim of full shift invariance.  The theorem below
shows that `ReversePairBalance` entails this condition. -/
def Kernel.ReverseTripleWindowBalance (π : Measure α) (K Kr : Kernel α α) : Prop :=
  ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple =
    (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α

/-- Under the explicit three-coordinate balance hypothesis, the cross-zero
window and its one-step forward shift have the same law.  This remains only a
three-coordinate finite-window result. -/
theorem Kernel.ReverseTripleWindowBalance.forwardReverseTwoSidedTrajMeasure_triple_shift
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hbalance : Kernel.ReverseTripleWindowBalance π K Kr) :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) := by
  rw [forwardReverseTwoSidedTrajMeasure_crossZeroTriple,
    forwardReverseTwoSidedTrajMeasure_zeroOneTwoTriple, hbalance]

/-- Sampling `Kr` after an independent `K` draw that shares the same input is
the product kernel `K ×ₖ Kr`. -/
private theorem compProd_prodMkRight_eq_prod
    (K Kr : Kernel α α) [IsMarkovKernel K] [IsMarkovKernel Kr] :
    K ⊗ₖ Kr.prodMkRight α = K ×ₖ Kr := by
  ext x s hs
  rw [Kernel.compProd_apply hs, Kernel.prod_apply' K Kr x hs]
  simp only [Kernel.prodMkRight_apply]

/-- Swap the first two coordinates of a nested triple, preserving its last
coordinate. -/
private def swapFirstPairTriple (p : (α × α) × α) : (α × α) × α :=
  ((p.1.2, p.1.1), p.2)

private theorem measurable_swapFirstPairTriple :
    Measurable (swapFirstPairTriple (α := α)) := by
  exact ((measurable_snd.comp measurable_fst).prodMk
    (measurable_fst.comp measurable_fst)).prodMk measurable_snd

/-- Swap the two conditionally independent kernel outputs while retaining the
common input coordinate. -/
private def swapInnerTriple (p : α × (α × α)) : α × (α × α) :=
  (p.1, (p.2.2, p.2.1))

private theorem measurable_swapInnerTriple :
    Measurable (swapInnerTriple (α := α)) := by
  exact measurable_fst.prodMk
    ((measurable_snd.comp measurable_snd).prodMk (measurable_fst.comp measurable_snd))

/-- Conditional Fubini for the two branches drawn from the common state:
after putting the triple in temporal order, sampling `K` then `Kr` is the
same as sampling `Kr` then `K`. -/
private theorem conditional_fubini_forward_reverse_triple
    {π : Measure α} [IsProbabilityMeasure π] (K Kr : Kernel α α)
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple =
      ((π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α).map swapFirstPairTriple := by
  have hA : (π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α =
      (π ⊗ₘ (K ×ₖ Kr)).map MeasurableEquiv.prodAssoc.symm := by
    calc
      (π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α =
          (π ⊗ₘ (K ⊗ₖ Kr.prodMkRight α)).map MeasurableEquiv.prodAssoc.symm := by
            symm
            exact Measure.compProd_assoc
      _ = (π ⊗ₘ (K ×ₖ Kr)).map MeasurableEquiv.prodAssoc.symm := by
            rw [compProd_prodMkRight_eq_prod]
  have hB : (π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α =
      (π ⊗ₘ (Kr ×ₖ K)).map MeasurableEquiv.prodAssoc.symm := by
    calc
      (π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α =
          (π ⊗ₘ (Kr ⊗ₖ K.prodMkRight α)).map MeasurableEquiv.prodAssoc.symm := by
            symm
            exact Measure.compProd_assoc
      _ = (π ⊗ₘ (Kr ×ₖ K)).map MeasurableEquiv.prodAssoc.symm := by
            rw [compProd_prodMkRight_eq_prod]
  have hswap : (π ⊗ₘ (K ×ₖ Kr)).map swapInnerTriple = π ⊗ₘ (Kr ×ₖ K) := by
    calc
      (π ⊗ₘ (K ×ₖ Kr)).map swapInnerTriple =
          (π ⊗ₘ (K ×ₖ Kr)).map (Prod.map id Prod.swap) := by
            rfl
      _ = π ⊗ₘ (K ×ₖ Kr).map Prod.swap := by
            rw [← Measure.compProd_map measurable_swap]
      _ = π ⊗ₘ (Kr ×ₖ K) := by
            rw [Kernel.map_prod_swap]
  have hcompat :
      (rotateForwardReverseTriple (α := α) ∘ MeasurableEquiv.prodAssoc.symm) =
        (swapFirstPairTriple (α := α) ∘ MeasurableEquiv.prodAssoc.symm) ∘
          swapInnerTriple := by
    funext q
    rcases q with ⟨x, z, y⟩
    rfl
  calc
    ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple =
        ((π ⊗ₘ (K ×ₖ Kr)).map MeasurableEquiv.prodAssoc.symm).map
          rotateForwardReverseTriple := by rw [hA]
    _ = (π ⊗ₘ (K ×ₖ Kr)).map
          (rotateForwardReverseTriple ∘ MeasurableEquiv.prodAssoc.symm) := by
          rw [Measure.map_map measurable_rotateForwardReverseTriple
            MeasurableEquiv.prodAssoc.symm.measurable]
    _ = (π ⊗ₘ (K ×ₖ Kr)).map
          ((swapFirstPairTriple ∘ MeasurableEquiv.prodAssoc.symm) ∘
            swapInnerTriple) := by rw [hcompat]
    _ = ((π ⊗ₘ (K ×ₖ Kr)).map swapInnerTriple).map
          (swapFirstPairTriple ∘ MeasurableEquiv.prodAssoc.symm) := by
          symm
          rw [Measure.map_map
            (measurable_swapFirstPairTriple.comp
              MeasurableEquiv.prodAssoc.symm.measurable)
            measurable_swapInnerTriple]
    _ = (π ⊗ₘ (Kr ×ₖ K)).map
          (swapFirstPairTriple ∘ MeasurableEquiv.prodAssoc.symm) := by
          rw [hswap]
    _ = ((π ⊗ₘ (Kr ×ₖ K)).map MeasurableEquiv.prodAssoc.symm).map
          swapFirstPairTriple := by
          symm
          rw [Measure.map_map measurable_swapFirstPairTriple
            MeasurableEquiv.prodAssoc.symm.measurable]
    _ = ((π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α).map swapFirstPairTriple := by
          rw [hB]

/-- Transport the pair swap through the remaining `K` branch. -/
private theorem lift_pair_swap_through_triple
    {π : Measure α} [IsProbabilityMeasure π] (K Kr : Kernel α α)
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    ((π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α).map swapFirstPairTriple =
      ((π ⊗ₘ Kr).map Prod.swap) ⊗ₘ K.prodMkLeft α := by
  have hKswap : K.prodMkLeft α ∘ₖ
      Kernel.deterministic Prod.swap measurable_swap = K.prodMkRight α := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    ((π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α).map swapFirstPairTriple =
        ((π ⊗ₘ Kr) ⊗ₘ (K.prodMkLeft α ∘ₖ
          Kernel.deterministic Prod.swap measurable_swap)).map
          (fun p => (Prod.swap p.1, p.2)) := by
          rw [hKswap]
          rfl
    _ = ((π ⊗ₘ Kr).map Prod.swap) ⊗ₘ K.prodMkLeft α := by
          exact Measure.compProd_map_input (π ⊗ₘ Kr) (K.prodMkLeft α)
            Prod.swap measurable_swap

/-- Pair balance already entails the explicit three-coordinate balance: the
only extra step is Fubini reordering of the two conditionally independent
kernel draws. -/
theorem Kernel.ReversePairBalance.reverseTripleWindowBalance
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hbalance : Kernel.ReversePairBalance π K Kr) :
    Kernel.ReverseTripleWindowBalance π K Kr := by
  unfold Kernel.ReverseTripleWindowBalance
  calc
    ((π ⊗ₘ K) ⊗ₘ Kr.prodMkRight α).map rotateForwardReverseTriple =
        ((π ⊗ₘ Kr) ⊗ₘ K.prodMkRight α).map swapFirstPairTriple := by
          exact conditional_fubini_forward_reverse_triple K Kr
    _ = ((π ⊗ₘ Kr).map Prod.swap) ⊗ₘ K.prodMkLeft α := by
          exact lift_pair_swap_through_triple K Kr
    _ = (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by rw [hbalance]

/-- The adjacent pair-balance condition also gives the checked
three-coordinate shift comparison.  This is still not a theorem of full
integer-shift invariance. -/
theorem Kernel.ReversePairBalance.forwardReverseTwoSidedTrajMeasure_triple_shift
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hbalance : Kernel.ReversePairBalance π K Kr) :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) := by
  exact hbalance.reverseTripleWindowBalance.forwardReverseTwoSidedTrajMeasure_triple_shift

/-- Sampling two kernels from a common input, then retaining the first output
while sampling the second branch, is the product kernel. -/
private theorem compProd_prodMkRight_eq_prod_branches
    {β γ δ : Type*} [MeasurableSpace β] [MeasurableSpace γ] [MeasurableSpace δ]
    (A : Kernel β γ) (B : Kernel β δ) [IsMarkovKernel A] [IsMarkovKernel B] :
    A ⊗ₖ B.prodMkRight γ = A ×ₖ B := by
  ext x s hs
  rw [Kernel.compProd_apply hs, Kernel.prod_apply' A B x hs]
  simp only [Kernel.prodMkRight_apply]

/-- Swap the two outputs drawn independently from the first component. -/
private def swapBranchOutputs
    {β γ δ : Type*} (p : (β × γ) × δ) : (β × δ) × γ :=
  ((p.1.1, p.2), p.1.2)

private theorem measurable_swapBranchOutputs
    {β γ δ : Type*} [MeasurableSpace β] [MeasurableSpace γ] [MeasurableSpace δ] :
    Measurable (swapBranchOutputs (β := β) (γ := γ) (δ := δ)) := by
  exact ((measurable_fst.comp measurable_fst).prodMk measurable_snd).prodMk
    (measurable_snd.comp measurable_fst)

/-- The corresponding swap after reassociating the three coordinates. -/
private def swapInnerBranches
    {β γ δ : Type*} (p : β × (γ × δ)) : β × (δ × γ) :=
  (p.1, (p.2.2, p.2.1))

private theorem measurable_swapInnerBranches
    {β γ δ : Type*} [MeasurableSpace β] [MeasurableSpace γ] [MeasurableSpace δ] :
    Measurable (swapInnerBranches (β := β) (γ := γ) (δ := δ)) := by
  exact measurable_fst.prodMk
    ((measurable_snd.comp measurable_snd).prodMk (measurable_fst.comp measurable_snd))

/-- Conditional Fubini for two kernels sampled independently from a common
input.  This is a kernel-level statement, with no reversibility or path
stationarity assumption. -/
private theorem conditional_fubini_branches
    {β γ δ : Type*} [MeasurableSpace β] [MeasurableSpace γ] [MeasurableSpace δ]
    {μ : Measure β} [IsProbabilityMeasure μ]
    (A : Kernel β γ) (B : Kernel β δ) [IsMarkovKernel A] [IsMarkovKernel B] :
    ((μ ⊗ₘ A) ⊗ₘ B.prodMkRight γ).map
        (swapBranchOutputs (β := β) (γ := γ) (δ := δ)) =
      (μ ⊗ₘ B) ⊗ₘ A.prodMkRight δ := by
  have hA : (μ ⊗ₘ A) ⊗ₘ B.prodMkRight γ =
      (μ ⊗ₘ (A ×ₖ B)).map MeasurableEquiv.prodAssoc.symm := by
    calc
      (μ ⊗ₘ A) ⊗ₘ B.prodMkRight γ =
          (μ ⊗ₘ (A ⊗ₖ B.prodMkRight γ)).map MeasurableEquiv.prodAssoc.symm := by
            symm
            exact Measure.compProd_assoc
      _ = (μ ⊗ₘ (A ×ₖ B)).map MeasurableEquiv.prodAssoc.symm := by
            rw [compProd_prodMkRight_eq_prod_branches]
  have hB : (μ ⊗ₘ B) ⊗ₘ A.prodMkRight δ =
      (μ ⊗ₘ (B ×ₖ A)).map MeasurableEquiv.prodAssoc.symm := by
    calc
      (μ ⊗ₘ B) ⊗ₘ A.prodMkRight δ =
          (μ ⊗ₘ (B ⊗ₖ A.prodMkRight δ)).map MeasurableEquiv.prodAssoc.symm := by
            symm
            exact Measure.compProd_assoc
      _ = (μ ⊗ₘ (B ×ₖ A)).map MeasurableEquiv.prodAssoc.symm := by
            rw [compProd_prodMkRight_eq_prod_branches]
  have hswap : (μ ⊗ₘ (A ×ₖ B)).map
      (swapInnerBranches (β := β) (γ := γ) (δ := δ)) = μ ⊗ₘ (B ×ₖ A) := by
    calc
      (μ ⊗ₘ (A ×ₖ B)).map
          (swapInnerBranches (β := β) (γ := γ) (δ := δ)) =
          (μ ⊗ₘ (A ×ₖ B)).map (Prod.map id Prod.swap) := by rfl
      _ = μ ⊗ₘ (A ×ₖ B).map Prod.swap := by
            rw [← Measure.compProd_map measurable_swap]
      _ = μ ⊗ₘ (B ×ₖ A) := by rw [Kernel.map_prod_swap]
  have hcompat :
      (swapBranchOutputs (β := β) (γ := γ) (δ := δ) ∘
        MeasurableEquiv.prodAssoc.symm) =
        MeasurableEquiv.prodAssoc.symm ∘
          swapInnerBranches (β := β) (γ := γ) (δ := δ) := by
    funext q
    rcases q with ⟨x, y, z⟩
    rfl
  calc
    ((μ ⊗ₘ A) ⊗ₘ B.prodMkRight γ).map
        (swapBranchOutputs (β := β) (γ := γ) (δ := δ)) =
        ((μ ⊗ₘ (A ×ₖ B)).map MeasurableEquiv.prodAssoc.symm).map
          (swapBranchOutputs (β := β) (γ := γ) (δ := δ)) := by rw [hA]
    _ = (μ ⊗ₘ (A ×ₖ B)).map
          (swapBranchOutputs (β := β) (γ := γ) (δ := δ) ∘
            MeasurableEquiv.prodAssoc.symm) := by
          rw [Measure.map_map measurable_swapBranchOutputs
            MeasurableEquiv.prodAssoc.symm.measurable]
    _ = (μ ⊗ₘ (A ×ₖ B)).map
          (MeasurableEquiv.prodAssoc.symm ∘
            swapInnerBranches (β := β) (γ := γ) (δ := δ)) := by rw [hcompat]
    _ = ((μ ⊗ₘ (A ×ₖ B)).map
          (swapInnerBranches (β := β) (γ := γ) (δ := δ))).map
            MeasurableEquiv.prodAssoc.symm := by
          symm
          rw [Measure.map_map MeasurableEquiv.prodAssoc.symm.measurable
            measurable_swapInnerBranches]
    _ = (μ ⊗ₘ (B ×ₖ A)).map MeasurableEquiv.prodAssoc.symm := by rw [hswap]
    _ = (μ ⊗ₘ B) ⊗ₘ A.prodMkRight δ := by rw [hB]

/-- The first three forward states of the stationary trajectory have the
ordinary two-step Markov factorization. -/
private theorem stationaryTrajMeasure_zeroOneTwo_law
    {π : Measure α} [IsProbabilityMeasure π] {K : Kernel α α}
    [IsMarkovKernel K] :
    (stationaryTrajMeasure π K).map (fun x => ((x 0, x 1), x 2)) =
      (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  have hKprod : K ∘ₖ Kernel.deterministic Prod.snd measurable_snd = K.prodMkLeft α := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    (stationaryTrajMeasure π K).map (fun x => ((x 0, x 1), x 2)) =
        (stationaryTrajMeasure π K).map (fun x => (x 0, x 1)) ⊗ₘ
          (K ∘ₖ Kernel.deterministic Prod.snd measurable_snd) := by
            exact stationaryTrajMeasure_zero_pair_succ_recurrence 1
    _ = (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by
          rw [stationaryTrajMeasure_zero_n_pair 1, hKprod, pow_one]

/-- The first forward triple and the first reverse state have the explicit
composition-product law used to extend the cross-zero window. -/
private theorem forwardReverseTwoSidedSourceMeasure_zeroOneTwo_reverseOne
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (((z.1 0, z.1 1), z.1 2), z.2 1)) =
      ((π ⊗ₘ K) ⊗ₘ K.prodMkLeft α) ⊗ₘ
        (Kr.prodMkRight α).prodMkRight α := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let μ : Measure (ℕ → α) := stationaryTrajMeasure π K
  let f : (ℕ → α) → (α × α) × α := fun x => ((x 0, x 1), x 2)
  let g : (α × α) × α → α := fun p => p.1.1
  let e : ((ℕ → α) × (ℕ → α)) → (ℕ → α) × α :=
    Prod.map id (fun x : ℕ → α => x 1)
  have hf : Measurable f :=
    ((measurable_pi_apply 0).prodMk (measurable_pi_apply 1)).prodMk
      (measurable_pi_apply 2)
  have hg : Measurable g := measurable_fst.comp measurable_fst
  have he : Measurable e := measurable_id.prodMap (measurable_pi_apply 1)
  have hpair : Measurable (fun p : (ℕ → α) × α => (f p.1, p.2)) :=
    hf.comp measurable_fst |>.prodMk measurable_snd
  have hflaw : μ.map f = (π ⊗ₘ K) ⊗ₘ K.prodMkLeft α := by
    exact stationaryTrajMeasure_zeroOneTwo_law
  have hKrprod :
      Kr ∘ₖ Kernel.deterministic g hg = (Kr.prodMkRight α).prodMkRight α := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (fun z => (((z.1 0, z.1 1), z.1 2), z.2 1)) =
        ((forwardReverseTwoSidedSourceMeasure π K Kr).map e).map
          (fun p => (f p.1, p.2)) := by
          symm
          rw [Measure.map_map hpair he]
          rfl
    _ = (μ ⊗ₘ (conditionalReverseTailKernel Kr).map (fun x : ℕ → α => x 1)).map
        (fun p => (f p.1, p.2)) := by
          unfold forwardReverseTwoSidedSourceMeasure
          rw [← Measure.compProd_map (μ := μ) (κ := conditionalReverseTailKernel Kr)
            (measurable_pi_apply 1)]
    _ = (μ ⊗ₘ (Kr ∘ₖ Kernel.deterministic (g ∘ f) (hg.comp hf))).map
        (fun p => (f p.1, p.2)) := by
          rw [conditionalReverseTailKernel_map_one]
          rfl
    _ = (μ.map f) ⊗ₘ (Kr ∘ₖ Kernel.deterministic g hg) := by
          exact Measure.compProd_map_through μ Kr f hf g hg
    _ = ((π ⊗ₘ K) ⊗ₘ K.prodMkLeft α) ⊗ₘ
        (Kr.prodMkRight α).prodMkRight α := by
          rw [hflaw, hKrprod]

/-- A forward four-coordinate prefix factors through its first three states
and the ordinary Markov transition. -/
private theorem stationaryTrajMeasure_zeroOneTwoThree_factor
    {π : Measure α} [IsProbabilityMeasure π] {K : Kernel α α}
    [IsMarkovKernel K] :
    (stationaryTrajMeasure π K).map
        (fun x => (((x 0, x 1), x 2), x 3)) =
      (stationaryTrajMeasure π K).map (fun x => ((x 0, x 1), x 2)) ⊗ₘ
        K.prodMkLeft (α × α) := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let hist : (ℕ → α) → (i : Finset.Iic 2) → α := Preorder.frestrictLe 2
  let triple : ((i : Finset.Iic 2) → α) → (α × α) × α :=
    fun y => ((y ⟨0, Finset.mem_Iic.mpr (by omega)⟩,
      y ⟨1, Finset.mem_Iic.mpr (by omega)⟩),
      y ⟨2, Finset.mem_Iic.mpr le_rfl⟩)
  let historyNext : (ℕ → α) → ((i : Finset.Iic 2) → α) × α :=
    fun x => (hist x, x 3)
  let tripleNext : ((i : Finset.Iic 2) → α) × α → ((α × α) × α) × α :=
    fun p => (triple p.1, p.2)
  have hhist : Measurable hist := measurable_frestrictLe 2
  have htriple : Measurable triple :=
    ((measurable_pi_apply _).prodMk (measurable_pi_apply _)).prodMk
      (measurable_pi_apply _)
  have hhistoryNext : Measurable historyNext :=
    hhist.prodMk (measurable_pi_apply _)
  have htripleNext : Measurable tripleNext :=
    htriple.comp measurable_fst |>.prodMk measurable_snd
  have hrec := stationaryTrajMeasure_prefix_succ (π := π) (K := K) 2
  have hKprod :
      K ∘ₖ Kernel.deterministic Prod.snd measurable_snd = K.prodMkLeft (α × α) := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    (stationaryTrajMeasure π K).map (fun x => (((x 0, x 1), x 2), x 3)) =
        ((stationaryTrajMeasure π K).map historyNext).map tripleNext := by
          rw [Measure.map_map htripleNext hhistoryNext]
          rfl
    _ = ((stationaryTrajMeasure π K).map hist ⊗ₘ
        (K ∘ₖ Kernel.deterministic
          (fun y : (i : Finset.Iic 2) → α =>
            y ⟨2, Finset.mem_Iic.mpr le_rfl⟩)
          (measurable_pi_apply _))).map tripleNext := by
          rw [hrec]
    _ = ((stationaryTrajMeasure π K).map hist).map triple ⊗ₘ
        (K ∘ₖ Kernel.deterministic Prod.snd measurable_snd) := by
          exact Measure.compProd_map_through _ K triple htriple
            Prod.snd measurable_snd
    _ = (stationaryTrajMeasure π K).map (fun x => ((x 0, x 1), x 2)) ⊗ₘ
        K.prodMkLeft (α × α) := by
          rw [Measure.map_map htriple hhist, hKprod]
          rfl

/-- The wholly nonnegative four-coordinate window of the explicit-reverse
construction has the ordinary forward Markov factorization. -/
theorem forwardReverseTwoSidedTrajMeasure_zeroOneTwoThree_factor
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x 0, x (1 : ℤ)), x (2 : ℤ)), x (3 : ℤ))) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) ⊗ₘ K.prodMkLeft (α × α) := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let q : (ℕ → α) → ((α × α) × α) × α :=
    fun x => (((x 0, x 1), x 2), x 3)
  let t : (ℕ → α) → (α × α) × α :=
    fun x => ((x 0, x 1), x 2)
  have hq : Measurable q :=
    (((measurable_pi_apply 0).prodMk (measurable_pi_apply 1)).prodMk
      (measurable_pi_apply 2)).prodMk (measurable_pi_apply 3)
  have ht : Measurable t :=
    ((measurable_pi_apply 0).prodMk (measurable_pi_apply 1)).prodMk
      (measurable_pi_apply 2)
  have hqZ : Measurable (fun x : ℤ → α =>
      (((x 0, x (1 : ℤ)), x (2 : ℤ)), x (3 : ℤ))) :=
    (((measurable_pi_apply 0).prodMk (measurable_pi_apply (1 : ℤ))).prodMk
      (measurable_pi_apply (2 : ℤ))).prodMk (measurable_pi_apply (3 : ℤ))
  have htZ : Measurable (fun x : ℤ → α =>
      ((x 0, x (1 : ℤ)), x (2 : ℤ))) :=
    ((measurable_pi_apply 0).prodMk (measurable_pi_apply (1 : ℤ))).prodMk
      (measurable_pi_apply (2 : ℤ))
  calc
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x 0, x (1 : ℤ)), x (2 : ℤ)), x (3 : ℤ))) =
        (forwardReverseTwoSidedSourceMeasure π K Kr).map
          (fun z => q z.1) := by
          unfold forwardReverseTwoSidedTrajMeasure
          rw [Measure.map_map hqZ measurable_spliceForwardReverse]
          rfl
    _ = ((forwardReverseTwoSidedSourceMeasure π K Kr).map Prod.fst).map q := by
          symm
          rw [Measure.map_map hq measurable_fst]
          rfl
    _ = (stationaryTrajMeasure π K).map q := by
          rw [forwardReverseTwoSidedSourceMeasure_map_forward]
    _ = (stationaryTrajMeasure π K).map t ⊗ₘ K.prodMkLeft (α × α) := by
          exact stationaryTrajMeasure_zeroOneTwoThree_factor
    _ = ((forwardReverseTwoSidedSourceMeasure π K Kr).map Prod.fst).map t ⊗ₘ
        K.prodMkLeft (α × α) := by
          rw [forwardReverseTwoSidedSourceMeasure_map_forward]
    _ = (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) ⊗ₘ K.prodMkLeft (α × α) := by
          congr 1
          unfold forwardReverseTwoSidedTrajMeasure
          rw [Measure.map_map htZ measurable_spliceForwardReverse]
          rw [Measure.map_map ht measurable_fst]
          rfl

/-- Turn a forward-pair/reverse-branch/future-step tuple into temporal order. -/
private def rotateForwardReverseQuad
    (p : ((α × α) × α) × α) : ((α × α) × α) × α :=
  (((p.1.2, p.1.1.1), p.1.1.2), p.2)

private theorem measurable_rotateForwardReverseQuad :
    Measurable (rotateForwardReverseQuad (α := α)) := by
  exact (((measurable_snd.comp measurable_fst).prodMk
    (measurable_fst.comp measurable_fst |>.comp measurable_fst)).prodMk
      (measurable_snd.comp measurable_fst |>.comp measurable_fst)).prodMk measurable_snd

/-- The cross-zero four-coordinate window factors through its three-coordinate
prefix and the ordinary forward transition. -/
theorem forwardReverseTwoSidedTrajMeasure_crossZeroQuad_factor
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr] :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x (-1 : ℤ), x 0), x (1 : ℤ)), x (2 : ℤ))) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))) ⊗ₘ K.prodMkLeft (α × α) := by
  have hprob : IsProbabilityMeasure (stationaryTrajMeasure π K) := by
    unfold stationaryTrajMeasure
    infer_instance
  letI : IsProbabilityMeasure (stationaryTrajMeasure π K) := hprob
  let M : Measure (α × α) := π ⊗ₘ K
  let A : Kernel (α × α) α := K.prodMkLeft α
  let B : Kernel (α × α) α := Kr.prodMkRight α
  have hA : IsMarkovKernel A := by
    dsimp [A]
    infer_instance
  letI : IsMarkovKernel A := hA
  have hB : IsMarkovKernel B := by
    dsimp [B]
    infer_instance
  letI : IsMarkovKernel B := hB
  have hM : IsProbabilityMeasure M := by
    dsimp [M]
    infer_instance
  letI : IsProbabilityMeasure M := hM
  let sourceQuad : (ℕ → α) × (ℕ → α) → ((α × α) × α) × α :=
    fun z => (((z.2 1, z.1 0), z.1 1), z.1 2)
  let initialBranches : (ℕ → α) × (ℕ → α) → ((α × α) × α) × α :=
    fun z => (((z.1 0, z.1 1), z.1 2), z.2 1)
  let crossTriple : (ℤ → α) → (α × α) × α :=
    fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))
  let initialToCross : ((α × α) × α) × α → ((α × α) × α) × α :=
    rotateForwardReverseQuad ∘
      swapBranchOutputs (β := α × α) (γ := α) (δ := α)
  have hsourceQuad : Measurable sourceQuad :=
    (((((measurable_pi_apply 1).comp measurable_snd).prodMk
      ((measurable_pi_apply 0).comp measurable_fst)).prodMk
        ((measurable_pi_apply 1).comp measurable_fst)).prodMk
          ((measurable_pi_apply 2).comp measurable_fst))
  have hinitialBranches : Measurable initialBranches :=
    (((((measurable_pi_apply 0).comp measurable_fst).prodMk
      ((measurable_pi_apply 1).comp measurable_fst)).prodMk
        ((measurable_pi_apply 2).comp measurable_fst)).prodMk
          ((measurable_pi_apply 1).comp measurable_snd))
  have hquadZ : Measurable (fun x : ℤ → α =>
      (((x (-1 : ℤ), x 0), x (1 : ℤ)), x (2 : ℤ))) :=
    (((measurable_pi_apply (-1 : ℤ)).prodMk (measurable_pi_apply 0)).prodMk
      (measurable_pi_apply (1 : ℤ))).prodMk (measurable_pi_apply (2 : ℤ))
  have htripleZ : Measurable crossTriple :=
    ((measurable_pi_apply (-1 : ℤ)).prodMk (measurable_pi_apply 0)).prodMk
      (measurable_pi_apply (1 : ℤ))
  have hsourceLaw := forwardReverseTwoSidedSourceMeasure_zeroOneTwo_reverseOne
    (π := π) (K := K) (Kr := Kr)
  have hfubini := conditional_fubini_branches (μ := M) A B
  have hsourceRelation : sourceQuad = initialToCross ∘ initialBranches := by
    funext z
    rfl
  have hinitialToCross : Measurable initialToCross :=
    measurable_rotateForwardReverseQuad.comp measurable_swapBranchOutputs
  have hAfromTriple :
      K ∘ₖ Kernel.deterministic
        (Prod.snd ∘ rotateForwardReverseTriple (α := α))
        (measurable_snd.comp measurable_rotateForwardReverseTriple) =
        A.prodMkRight α := by
    dsimp [A]
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  have hquadRotate : rotateForwardReverseQuad (α := α) =
      fun p => (rotateForwardReverseTriple p.1, p.2) := by
    rfl
  have hKprodTriple :
      K ∘ₖ Kernel.deterministic Prod.snd measurable_snd = K.prodMkLeft (α × α) := by
    rw [Kernel.comp_deterministic_eq_comap]
    rfl
  calc
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x (-1 : ℤ), x 0), x (1 : ℤ)), x (2 : ℤ))) =
        (forwardReverseTwoSidedSourceMeasure π K Kr).map sourceQuad := by
          unfold forwardReverseTwoSidedTrajMeasure
          rw [Measure.map_map hquadZ measurable_spliceForwardReverse]
          rfl
    _ = (forwardReverseTwoSidedSourceMeasure π K Kr).map
        (initialToCross ∘ initialBranches) := by rw [hsourceRelation]
    _ = ((forwardReverseTwoSidedSourceMeasure π K Kr).map initialBranches).map
        initialToCross := by
          symm
          rw [Measure.map_map hinitialToCross hinitialBranches]
    _ = (((M ⊗ₘ A) ⊗ₘ B.prodMkRight α).map
        (swapBranchOutputs (β := α × α) (γ := α) (δ := α))).map
          (rotateForwardReverseQuad (α := α)) := by
          rw [hsourceLaw]
          change (((M ⊗ₘ A) ⊗ₘ B.prodMkRight α).map
            ((rotateForwardReverseQuad (α := α)) ∘
              swapBranchOutputs (β := α × α) (γ := α) (δ := α))) = _
          symm
          rw [Measure.map_map measurable_rotateForwardReverseQuad
            measurable_swapBranchOutputs]
    _ = ((M ⊗ₘ B) ⊗ₘ A.prodMkRight α).map
          (rotateForwardReverseQuad (α := α)) := by rw [hfubini]
    _ = ((M ⊗ₘ B).map rotateForwardReverseTriple) ⊗ₘ
        K.prodMkLeft (α × α) := by
          rw [hquadRotate, ← hAfromTriple]
          calc
            Measure.map (fun p => (rotateForwardReverseTriple p.1, p.2))
                (M ⊗ₘ B ⊗ₘ
                  (K ∘ₖ Kernel.deterministic
                    (Prod.snd ∘ rotateForwardReverseTriple)
                    (measurable_snd.comp measurable_rotateForwardReverseTriple))) =
                Measure.map rotateForwardReverseTriple (M ⊗ₘ B) ⊗ₘ
                  (K ∘ₖ Kernel.deterministic Prod.snd measurable_snd) := by
                    exact Measure.compProd_map_through (M ⊗ₘ B) K
                      rotateForwardReverseTriple measurable_rotateForwardReverseTriple
                      Prod.snd measurable_snd
            _ = _ := by rw [hKprodTriple]
    _ = (forwardReverseTwoSidedTrajMeasure π K Kr).map crossTriple ⊗ₘ
        K.prodMkLeft (α × α) := by
          rw [← forwardReverseTwoSidedTrajMeasure_crossZeroTriple]

/-- Pair balance transports the cross-zero four-coordinate window one step
forward.  This is a finite-window result, not full integer-shift invariance. -/
theorem Kernel.ReversePairBalance.forwardReverseTwoSidedTrajMeasure_quad_shift
    {π : Measure α} [IsProbabilityMeasure π] {K Kr : Kernel α α}
    [IsMarkovKernel K] [IsMarkovKernel Kr]
    (hbalance : Kernel.ReversePairBalance π K Kr) :
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x (-1 : ℤ), x 0), x (1 : ℤ)), x (2 : ℤ))) =
      (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x 0, x (1 : ℤ)), x (2 : ℤ)), x (3 : ℤ))) := by
  calc
    (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x (-1 : ℤ), x 0), x (1 : ℤ)), x (2 : ℤ))) =
        (forwardReverseTwoSidedTrajMeasure π K Kr).map
          (fun x => ((x (-1 : ℤ), x 0), x (1 : ℤ))) ⊗ₘ K.prodMkLeft (α × α) := by
          exact forwardReverseTwoSidedTrajMeasure_crossZeroQuad_factor
    _ = (forwardReverseTwoSidedTrajMeasure π K Kr).map
          (fun x => ((x 0, x (1 : ℤ)), x (2 : ℤ))) ⊗ₘ K.prodMkLeft (α × α) := by
          rw [hbalance.forwardReverseTwoSidedTrajMeasure_triple_shift]
    _ = (forwardReverseTwoSidedTrajMeasure π K Kr).map
        (fun x => (((x 0, x (1 : ℤ)), x (2 : ℤ)), x (3 : ℤ))) := by
          symm
          exact forwardReverseTwoSidedTrajMeasure_zeroOneTwoThree_factor

end

end AppliedModelingLib.Probability.Queueing
