import PG24NoisyMatchingMarkets.Theorem2LiteralBasicRegularWindow
import Mathlib.Tactic

/-!
# PG24 Literal Basic Markets

This source-model carrier keeps the primitive finite-preference economy fixed
while allowing a literal basic instance to be constructed at every clearing
cutoff.  It is the bridge from an all-stable-cutoffs statement to the selected
cutoff analysis used by the attenuation and amplification proofs.
-/

open Filter MeasureTheory
open AppliedModelingLib.Matching

namespace PG24NoisyMatchingMarkets

noncomputable section

universe u v

/--
One finite basic-model economy before a clearing cutoff is selected.  Its
outcome law is literally the student law times iid college noise; demand is
the source most-preferred-affordable rule and capacity regularity is the
paper's per-college condition.
-/
structure PG24LiteralBasicMarket
    (C : ℕ) (noiseLaw eta : Measure ℝ) (totalSupply alpha : ℝ)
    (StudentType : Type u) [MeasurableSpace StudentType]
    (Cutoff : Type v) where
  studentLaw : Measure StudentType
  studentLaw_isProbability : IsProbabilityMeasure studentLaw
  value : StudentType → ℝ
  value_measurable : Measurable value
  value_marginal : Measure.map value studentLaw = eta
  demand :
    PG24FinitePreferredDemand
      (StudentType × (Fin (C + 1) → ℝ)) (Fin (C + 1)) Cutoff
  /-- A student's strict college ranking is part of their type, before noise is drawn. -/
  studentPreferenceRank : StudentType → Fin (C + 1) → ℕ
  studentPreferenceRank_injective :
    ∀ student : StudentType, Function.Injective (studentPreferenceRank student)
  /-- Realized college-noise changes affordability, never the student's ranking. -/
  demand_preferenceRank_eq_studentPreferenceRank :
    ∀ (student : StudentType) (noise : Fin (C + 1) → ℝ) (college : Fin (C + 1)),
      demand.preferenceRank (student, noise) college = studentPreferenceRank student college
  demand_outcomeLaw_eq_iid :
    demand.outcomeLaw =
      studentLaw.prod (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
  capacity : Fin (C + 1) → ℝ
  totalCapacity_eq : (∑ college : Fin (C + 1), capacity college) = totalSupply
  approximateScore : (StudentType × (Fin (C + 1) → ℝ)) → Fin (C + 1) → ℝ
  demand_globalScore_eq_approximateScore :
    ∀ (P : Cutoff) (outcome : StudentType × (Fin (C + 1) → ℝ))
      (college : Fin (C + 1)),
      demand.globalScore P outcome college = approximateScore outcome college
  basic_score :
    ∀ (outcome : StudentType × (Fin (C + 1) → ℝ))
      (college : Fin (C + 1)),
      approximateScore outcome college = value outcome.1 + outcome.2 college
  capacity_regular : capacityRegular capacity alpha (C + 1)

/--
The basic source economy together with the global restrictions fixed in the
paper's model section.  This is a source-model bundle only: it contains no
selected cutoff or theorem conclusion.  The underlying literal market records
the student/value law, iid-noise outcome law, preferences, capacities, and
capacity regularity; these three fields retain the global probability and
total-supply hypotheses stated outside that market record.
-/
structure PG24BasicEconomySourceData
    (C : ℕ) (noiseLaw eta : Measure ℝ) (totalSupply alpha : ℝ)
    (StudentType : Type u) [MeasurableSpace StudentType]
    (Cutoff : Type v) where
  noiseLaw_isProbability : IsProbabilityMeasure noiseLaw
  totalSupply_pos : 0 < totalSupply
  totalSupply_lt_one : totalSupply < 1
  market : PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff

namespace PG24LiteralBasicMarket

variable {C : ℕ} {noiseLaw eta : Measure ℝ} {totalSupply alpha : ℝ}
variable {StudentType : Type u} [MeasurableSpace StudentType]
variable {Cutoff : Type v}

/-- Exact source clearing for the literal finite-preference market. -/
def marketClearing
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (P : Cutoff) : Prop :=
  ∀ college : Fin (C + 1),
    market.demand.aggregateDemand P college = market.capacity college

/-- A literal basic matching is stable exactly when clearing cutoff demand realizes it. -/
def isStable
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (matching : StudentType × (Fin (C + 1) → ℝ) → Option (Fin (C + 1))) : Prop :=
  ∃ P : Cutoff, market.marketClearing P ∧ matching = market.demand.demandAt P

/-- The cutoff market generated by the primitive literal basic economy. -/
noncomputable def sourceMarket
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff) :
    PG24SourceCutoffMarket
      (StudentType × (Fin (C + 1) → ℝ)) (Fin (C + 1)) Cutoff where
  demandAt := market.demand.demandAt
  aggregateDemand := market.demand.aggregateDemand
  capacity := market.capacity
  isStable := market.isStable
  marketClearing := market.marketClearing
  representedByCutoff := fun matching P => matching = market.demand.demandAt P

/-- The literal basic market has the required stable/cutoff characterization. -/
noncomputable def supplyDemand
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff) :
    SupplyDemandInterface market.sourceMarket.toCutoffMarket where
  stable_iff_exists_marketClearing_cutoff := by
    intro matching
    rfl
  marketClearing_induces_stable := by
    intro P hclearing
    exact ⟨market.demand.demandAt P, ⟨P, hclearing, rfl⟩, rfl⟩

/-- Exact literal clearing derives the generic capacity interface. -/
noncomputable def clearingCapacity
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff) :
    MarketClearingCapacityInterface market.sourceMarket.toCutoffMarket where
  marketClearing_aggregateDemand_eq_capacity := by
    intro P hclearing college
    exact hclearing college

/-- The primitive iid sampling data recovered from a literal basic market. -/
noncomputable def sampling
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    [IsProbabilityMeasure noiseLaw] :
    PG24CoalitionSourceSampling C noiseLaw eta StudentType
      (StudentType × (Fin (C + 1) → ℝ)) where
  studentLaw := market.studentLaw
  studentLaw_isProbability := market.studentLaw_isProbability
  outcomeLaw := market.demand.outcomeLaw
  outcomeLaw_isProbability := by
    letI : IsProbabilityMeasure market.studentLaw := market.studentLaw_isProbability
    rw [market.demand_outcomeLaw_eq_iid]
    infer_instance
  commonValue := market.value
  commonValue_measurable := market.value_measurable
  commonValue_map := market.value_marginal
  sourceStudent := Prod.fst
  coalitionNoise := Prod.snd
  sourceCoordinates_measurable := by
    change Measurable (fun outcome : StudentType × (Fin (C + 1) → ℝ) => outcome)
    exact measurable_id
  sourceCoordinates_map := by
    change Measure.map id market.demand.outcomeLaw =
      market.studentLaw.prod (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
    simpa only [Measure.map_id] using market.demand_outcomeLaw_eq_iid

/-- A clearing cutoff produces literal source-stable data at that cutoff. -/
noncomputable def literalAt
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (P : Cutoff)
    (hclearing : market.marketClearing P)
    [IsProbabilityMeasure noiseLaw] :
    PG24LiteralSourceStableData C noiseLaw eta totalSupply StudentType
      (StudentType × (Fin (C + 1) → ℝ)) (Fin (C + 1)) Cutoff where
  demand := market.demand
  sampling := market.sampling
  sampling_outcomeLaw_eq := rfl
  capacity := market.capacity
  totalCapacity_eq := market.totalCapacity_eq
  selectedCutoff := P
  selectedCutoff_clearing := hclearing
  approximateScore := market.approximateScore
  demand_globalScore_eq_approximateScore :=
    market.demand_globalScore_eq_approximateScore
  coalitionEmbedding := Function.Embedding.refl _
  coalition_score_ae := Filter.Eventually.of_forall (fun outcome college => by
    change market.approximateScore outcome college =
      market.value outcome.1 + outcome.2 college
    exact market.basic_score outcome college)

/--
The selected literal basic instance constructed from a clearing cutoff.  No
matching probability, tail estimate, or cutoff geometry is stored here.
-/
noncomputable def basicInstanceAt
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (P : Cutoff)
    (hclearing : market.marketClearing P)
    [IsProbabilityMeasure noiseLaw] :
    PG24LiteralBasicTwoScaleInstance C noiseLaw eta totalSupply alpha
      StudentType Cutoff where
  studentLaw := market.studentLaw
  studentLaw_isProbability := market.studentLaw_isProbability
  value := market.value
  value_measurable := market.value_measurable
  value_marginal := market.value_marginal
  literal := market.literalAt P hclearing
  sampling_outcomeLaw_eq_iid := by
    change market.demand.outcomeLaw =
      market.studentLaw.prod (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
    exact market.demand_outcomeLaw_eq_iid
  coalitionEmbedding_id := fun _ => rfl
  basic_score := by
    intro P' outcome college
    change market.demand.globalScore P' outcome college =
      market.value outcome.1 + outcome.2 college
    rw [market.demand_globalScore_eq_approximateScore]
    exact market.basic_score outcome college
  capacity_regular := market.capacity_regular

/-- The constructed analytic cutoff vector is the literal cutoff coordinates. -/
theorem basicInstanceAt_selectedCutoffVector
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (P : Cutoff)
    (hclearing : market.marketClearing P)
    [IsProbabilityMeasure noiseLaw] :
    (market.basicInstanceAt P hclearing).selectedCutoffVector =
      market.demand.cutoffCoordinates P :=
  rfl

/-- A clearing cutoff's literal demand assignment is stable in its source market. -/
theorem basicInstanceAt_selectedMatching_stable
    (market :
      PG24LiteralBasicMarket C noiseLaw eta totalSupply alpha StudentType Cutoff)
    (P : Cutoff)
    (hclearing : market.marketClearing P)
    [IsProbabilityMeasure noiseLaw] :
    (market.literalAt P hclearing).sourceMarket.toCutoffMarket.Stable
      ((market.literalAt P hclearing).demand.demandAt P) := by
  exact ⟨P, hclearing, rfl⟩

end PG24LiteralBasicMarket

end

end PG24NoisyMatchingMarkets
