import PG24NoisyMatchingMarkets.Theorem1SelectedCutoffGeometry
import PG24NoisyMatchingMarkets.Theorem3IidExpectedMaximumLog
import PG24NoisyMatchingMarkets.Theorem3LargeGapAsymptotics
import PG24NoisyMatchingMarkets.Theorem3LargeGapBridge
import PG24NoisyMatchingMarkets.Theorem3RankedLargeGapProbability
import PG24NoisyMatchingMarkets.Theorem3LargeGapScale
import Mathlib.Tactic

/-!
# PG24 Theorem 1 large-gap qualitative endpoint

The Case 2 high endpoint follows from the ordinary lower-tail behavior of a
probability measure once the source's rounded cutoff gap dominates the iid
maximum center.  It does not invoke the source's unjustified one-draw
Chebyshev rate.
-/

open Filter Topology MeasureTheory Asymptotics

namespace PG24NoisyMatchingMarkets

noncomputable section

/-- The positive cutoff-gap exponent generated by the source Case 2 scales. -/
def theorem1TailLargeGapExponent (beta gamma : ℝ) : ℝ :=
  theorem1TailPhi1 beta gamma + theorem1TailPhi3 beta gamma -
    theorem1TailPhi2 beta gamma

theorem theorem1TailLargeGapExponent_pos {beta gamma : ℝ}
    (hbeta : 0 < beta) (hgamma : 0 < gamma) :
    0 < theorem1TailLargeGapExponent beta gamma := by
  unfold theorem1TailLargeGapExponent
  rw [theorem1Tail_phi1_add_phi3_sub_phi2_eq_beta_gamma_div hbeta hgamma]
  exact div_pos (mul_pos hbeta hgamma) (theorem1TailDenom_pos hbeta hgamma)

theorem theorem1TailPhi4_neg {beta gamma : ℝ}
    (hbeta : 0 < beta) (hgamma : 0 < gamma) :
    theorem1TailPhi4 beta gamma < 0 := by
  have hden_pos : 0 < theorem1TailDenom beta gamma :=
    theorem1TailDenom_pos hbeta hgamma
  have hfrac_lt : beta * gamma / theorem1TailDenom beta gamma < beta / 2 := by
    rw [div_lt_iff₀ hden_pos]
    unfold theorem1TailDenom
    nlinarith [mul_pos hbeta hgamma]
  unfold theorem1TailPhi4
  linarith

/--
The literal rounded Case 2 gap scale has a polynomial lower bound.  This is
the rounding-sensitive fact needed to compare the expected maximum with the
finite rank gap.
-/
theorem theorem1RoundedLargeGapScale_eventually_ge_half_rpow
    {beta gamma : ℝ} (hbeta : 0 < beta) (hgamma : 0 < gamma) :
    ∀ᶠ C : ℕ in atTop,
      (1 / 2 : ℝ) * Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2) ≤
        (theorem3DenseGapBlockCount C
          (theorem1TailPhi2 beta gamma)
          (theorem1TailPhi3 beta gamma) : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
  have hblock_lower :=
    theorem3DenseGapBlockCount_eventually_ge_floor_lowerScale
      (denseExponent := theorem1TailPhi2 beta gamma)
      (prefixExponent := theorem1TailPhi3 beta gamma)
      (width := theorem1TailPhi1 beta gamma)
      (gapExponent := theorem1TailLargeGapExponent beta gamma)
      (theorem1TailPhi2_pos hbeta hgamma).le
      (theorem1TailPhi1_neg hbeta hgamma)
      (theorem1TailLargeGapExponent_pos hbeta hgamma)
      (by rfl)
  filter_upwards [hblock_lower, eventually_ge_atTop 1] with C hblock_lower hC_one
  have hC_pos : 0 < C := lt_of_lt_of_le Nat.zero_lt_one hC_one
  have hC_real_pos : 0 < (C : ℝ) := by
    exact_mod_cast hC_pos
  have hlowerExponent_pos :
      0 < theorem1TailLargeGapExponent beta gamma / 2 -
        theorem1TailPhi1 beta gamma := by
    have hgap_pos := theorem1TailLargeGapExponent_pos hbeta hgamma
    have hwidth_neg := theorem1TailPhi1_neg hbeta hgamma
    linarith
  have hC_real_one : (1 : ℝ) ≤ (C : ℝ) := by
    exact_mod_cast hC_one
  have hlower_power_one :
      1 ≤ Real.rpow (C : ℝ)
        (theorem1TailLargeGapExponent beta gamma / 2 -
          theorem1TailPhi1 beta gamma) :=
    Real.one_le_rpow hC_real_one hlowerExponent_pos.le
  have hfloor_lower :
      Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2 -
            theorem1TailPhi1 beta gamma) / 2 ≤
        (⌊Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2 -
            theorem1TailPhi1 beta gamma)⌋₊ : ℝ) :=
    (Nat.div_two_lt_floor hlower_power_one).le
  have hblock_lower_real :
      (⌊Real.rpow (C : ℝ)
        (theorem1TailLargeGapExponent beta gamma / 2 -
          theorem1TailPhi1 beta gamma)⌋₊ : ℝ) ≤
        (theorem3DenseGapBlockCount C
          (theorem1TailPhi2 beta gamma)
          (theorem1TailPhi3 beta gamma) : ℝ) := by
    exact_mod_cast hblock_lower
  have hwidth_nonneg :
      0 ≤ Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) :=
    Real.rpow_nonneg (Nat.cast_nonneg C) _
  have hpower_product :
      Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2 -
            theorem1TailPhi1 beta gamma) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) =
        Real.rpow (C : ℝ) (theorem1TailLargeGapExponent beta gamma / 2) := by
    calc
      Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2 -
            theorem1TailPhi1 beta gamma) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) =
          Real.rpow (C : ℝ)
            ((theorem1TailLargeGapExponent beta gamma / 2 -
              theorem1TailPhi1 beta gamma) + theorem1TailPhi1 beta gamma) :=
        (Real.rpow_add hC_real_pos _ _).symm
      _ = Real.rpow (C : ℝ) (theorem1TailLargeGapExponent beta gamma / 2) := by
        congr 1
        ring
  calc
    (1 / 2 : ℝ) * Real.rpow (C : ℝ)
        (theorem1TailLargeGapExponent beta gamma / 2) =
        (Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2 -
            theorem1TailPhi1 beta gamma) / 2) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
      rw [← hpower_product]
      ring
    _ ≤ (⌊Real.rpow (C : ℝ)
        (theorem1TailLargeGapExponent beta gamma / 2 -
          theorem1TailPhi1 beta gamma)⌋₊ : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) :=
      mul_le_mul_of_nonneg_right hfloor_lower hwidth_nonneg
    _ ≤ (theorem3DenseGapBlockCount C
        (theorem1TailPhi2 beta gamma)
        (theorem1TailPhi3 beta gamma) : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) :=
      mul_le_mul_of_nonneg_right hblock_lower_real hwidth_nonneg

theorem theorem1Tail_log_isLittleO_roundedLargeGapScale
    {beta gamma : ℝ} (hbeta : 0 < beta) (hgamma : 0 < gamma) :
    (fun C : ℕ => Real.log (C : ℝ)) =o[atTop]
      fun C : ℕ =>
        (theorem3DenseGapBlockCount C
          (theorem1TailPhi2 beta gamma)
          (theorem1TailPhi3 beta gamma) : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
  have hhalf_gap_pos : 0 < theorem1TailLargeGapExponent beta gamma / 2 := by
    linarith [theorem1TailLargeGapExponent_pos hbeta hgamma]
  have hlog_power :
      (fun C : ℕ => Real.log (C : ℝ)) =o[atTop]
        fun C : ℕ => Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2) := by
    simpa [Function.comp_def] using
      (isLittleO_log_rpow_atTop hhalf_gap_pos).comp_tendsto
        tendsto_natCast_atTop_atTop
  have hpower_bigO :
      (fun C : ℕ => Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2)) =O[atTop]
        fun C : ℕ =>
          (theorem3DenseGapBlockCount C
            (theorem1TailPhi2 beta gamma)
            (theorem1TailPhi3 beta gamma) : ℝ) *
            Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
    refine IsBigO.of_bound 2 ?_
    filter_upwards [theorem1RoundedLargeGapScale_eventually_ge_half_rpow
      hbeta hgamma] with C hscale_lower
    have hpower_nonneg :
        0 ≤ Real.rpow (C : ℝ)
          (theorem1TailLargeGapExponent beta gamma / 2) :=
      Real.rpow_nonneg (Nat.cast_nonneg C) _
    have hscale_nonneg :
        0 ≤ (theorem3DenseGapBlockCount C
          (theorem1TailPhi2 beta gamma)
          (theorem1TailPhi3 beta gamma) : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
      linarith
    rw [Real.norm_of_nonneg hpower_nonneg, Real.norm_of_nonneg hscale_nonneg]
    linarith
  exact hlog_power.trans_isBigO hpower_bigO

theorem theorem1Tail_mean_add_phi4_isLittleO_roundedLargeGapScale
    {beta gamma : ℝ} (hbeta : 0 < beta) (hgamma : 0 < gamma)
    {mean : ℕ → ℝ}
    (hmean : Tendsto (fun C : ℕ => mean C / Real.log (C : ℝ))
      atTop (nhds 0)) :
    (fun C : ℕ => mean C +
      Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma)) =o[atTop]
      fun C : ℕ =>
        (theorem3DenseGapBlockCount C
          (theorem1TailPhi2 beta gamma)
          (theorem1TailPhi3 beta gamma) : ℝ) *
          Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) := by
  let scale : ℕ → ℝ := fun C =>
    (theorem3DenseGapBlockCount C
      (theorem1TailPhi2 beta gamma)
      (theorem1TailPhi3 beta gamma) : ℝ) *
      Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma)
  have hmean_small : mean =o[atTop] scale :=
    (theorem3_isLittleO_log_of_div_log_tendsto_zero hmean).trans
      (by simpa [scale] using
        theorem1Tail_log_isLittleO_roundedLargeGapScale hbeta hgamma)
  have hscale_toTop : Tendsto scale atTop atTop := by
    simpa [scale, theorem1TailLargeGapExponent] using
      (theorem3DenseGapBlockCount_mul_rpow_tendsto_atTop
        (denseExponent := theorem1TailPhi2 beta gamma)
        (prefixExponent := theorem1TailPhi3 beta gamma)
        (width := theorem1TailPhi1 beta gamma)
        (gapExponent := theorem1TailLargeGapExponent beta gamma)
        (theorem1TailPhi2_pos hbeta hgamma).le
        (theorem1TailPhi1_neg hbeta hgamma)
        (theorem1TailLargeGapExponent_pos hbeta hgamma)
        (by rfl))
  have hphi4_zero : Tendsto
      (fun C : ℕ => Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma))
      atTop (nhds 0) := by
    have hneg := theorem1TailPhi4_neg hbeta hgamma
    have hrewrite : theorem1TailPhi4 beta gamma =
        -(-theorem1TailPhi4 beta gamma) := by ring
    rw [hrewrite]
    exact (tendsto_rpow_neg_atTop (by linarith)).comp
      tendsto_natCast_atTop_atTop
  have hphi4_small :
      (fun C : ℕ => Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma)) =o[atTop]
        scale := by
    have hsmall_one :
        (fun C : ℕ => Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma)) =o[atTop]
          (fun _ : ℕ => (1 : ℝ)) :=
      (isLittleO_one_iff ℝ).mpr hphi4_zero
    have hone_scale : (fun _ : ℕ => (1 : ℝ)) =o[atTop] scale := by
      rw [isLittleO_one_left_iff]
      exact tendsto_norm_atTop_atTop.comp hscale_toTop
    exact hsmall_one.trans hone_scale
  simpa [scale] using hmean_small.add hphi4_small

/--
For any actual cutoff sequence satisfying the derived large-gap alternative,
the source Case 2 threshold has full-market affordance approaching one.  The
proof uses a single low-cutoff college only through the probability-tail
limit, not a hidden single-draw variance premise.
-/
theorem theorem1_ranked_largeGap_full_affordance_eventually
    (noiseLaw : Measure ℝ) [IsProbabilityMeasure noiseLaw]
    {maxVariance : ℕ → ℝ} {beta gamma epsilon : ℝ}
    (hbeta : betaMaxConcentratingVariance maxVariance beta)
    (hgamma : 0 < gamma)
    (hvariance : source_assumption_iid_beta_max_variance_bound
      noiseLaw maxVariance)
    {cutoff : ∀ C : ℕ, Fin (C + 1) → ℝ}
    (hlarge_gap : ∀ᶠ C : ℕ in atTop,
      theorem3RankedCutoffNat C (cutoff C) 0 +
          (theorem3DenseGapBlockCount C
            (theorem1TailPhi2 beta gamma)
            (theorem1TailPhi3 beta gamma) : ℝ) *
            Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) <
        theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)))
    (hepsilon : 0 < epsilon) :
    ∀ᶠ C : ℕ in atTop,
      1 - epsilon <
        cutoffAffordanceProbability
          (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
          (Finset.univ : Finset (Fin (C + 1)))
          (theorem3RankedCutoffNat C (cutoff C)
            (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)) -
            AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
              (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw)) C -
            Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma))
          (cutoff C) := by
  let rank : ℕ → ℕ := fun C =>
    theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)
  let gapLower : ℕ → ℝ := fun C =>
    (theorem3DenseGapBlockCount C
      (theorem1TailPhi2 beta gamma)
      (theorem1TailPhi3 beta gamma) : ℝ) *
      Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma)
  let mean : ℕ → ℝ :=
    AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
      (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw))
  let slack : ℕ → ℝ := fun C => mean C +
    Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma)
  let value : ℕ → ℝ := fun C =>
    theorem3RankedCutoffNat C (cutoff C) (rank C) - slack C
  have hmean_log : Tendsto
      (fun C : ℕ => mean C / Real.log (C : ℝ)) atTop (nhds 0) := by
    dsimp [mean]
    exact theorem3_iidExpectedMaximum_div_log_tendsto_zero_of_beta
      noiseLaw hbeta hvariance
  have hslack_little : slack =o[atTop] gapLower := by
    simpa [slack, mean, gapLower] using
      (theorem1Tail_mean_add_phi4_isLittleO_roundedLargeGapScale
        hbeta.1 hgamma hmean_log)
  have hgap_toTop : Tendsto gapLower atTop atTop := by
    simpa [gapLower, theorem1TailLargeGapExponent] using
      (theorem3DenseGapBlockCount_mul_rpow_tendsto_atTop
        (denseExponent := theorem1TailPhi2 beta gamma)
        (prefixExponent := theorem1TailPhi3 beta gamma)
        (width := theorem1TailPhi1 beta gamma)
        (gapExponent := theorem1TailLargeGapExponent beta gamma)
        (theorem1TailPhi2_pos hbeta.1 hgamma).le
        (theorem1TailPhi1_neg hbeta.1 hgamma)
        (theorem1TailLargeGapExponent_pos hbeta.1 hgamma)
        (by rfl))
  have hrank_gap : ∀ᶠ C : ℕ in atTop,
      theorem3RankedCutoffNat C (cutoff C) 0 + gapLower C <
        theorem3RankedCutoffNat C (cutoff C) (rank C) := by
    simpa [rank, gapLower] using hlarge_gap
  have hsemantic_gap := theorem3_ranked_cutoff_gap_of_ranked_gap hrank_gap
  have hvalue_below_high_rank : ∀ᶠ C : ℕ in atTop,
      cutoff C (theorem3RankedCollege C (cutoff C)
        ⟨min (rank C) C, Nat.lt_succ_of_le (Nat.min_le_right _ _)⟩) -
          value C ≤ slack C := by
    filter_upwards with C
    rw [← theorem3RankedCutoffNat_eq_cutoff_rankedCollege C (cutoff C) (rank C)]
    dsimp [value]
    linarith
  have hresult :=
    theorem3_fullAffordance_eventually_one_sub_lt_of_cutoff_gap_of_isLittleO
      noiseLaw
      (fun C => theorem3RankedCollege C (cutoff C)
        ⟨min 0 C, Nat.lt_succ_of_le (Nat.min_le_right _ _)⟩)
      (fun C => theorem3RankedCollege C (cutoff C)
        ⟨min (rank C) C, Nat.lt_succ_of_le (Nat.min_le_right _ _)⟩)
      hsemantic_gap hvalue_below_high_rank hgap_toTop hslack_little epsilon hepsilon
  filter_upwards [hresult] with C hC
  dsimp [value, rank, mean, slack] at hC
  simp only [← Real.rpow_eq_pow] at hC
  have hthreshold :
      theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)) -
          (AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
            (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw)) C +
            Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma)) =
        theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)) -
          AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
            (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw)) C -
          Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma) := by
    ring
  rw [hthreshold] at hC
  exact hC

/--
The repaired large-gap endpoint converges to full-market affordance one.  This
is the qualitative consequence supported by the beta-max premise; it does not
claim the unsupported one-draw polynomial rate from the source proof.
-/
theorem theorem1_ranked_largeGap_full_affordance_tendsto_one
    (noiseLaw : Measure ℝ) [IsProbabilityMeasure noiseLaw]
    {maxVariance : ℕ → ℝ} {beta gamma : ℝ}
    (hbeta : betaMaxConcentratingVariance maxVariance beta)
    (hgamma : 0 < gamma)
    (hvariance : source_assumption_iid_beta_max_variance_bound
      noiseLaw maxVariance)
    {cutoff : ∀ C : ℕ, Fin (C + 1) → ℝ}
    (hlarge_gap : ∀ᶠ C : ℕ in atTop,
      theorem3RankedCutoffNat C (cutoff C) 0 +
          (theorem3DenseGapBlockCount C
            (theorem1TailPhi2 beta gamma)
            (theorem1TailPhi3 beta gamma) : ℝ) *
            Real.rpow (C : ℝ) (theorem1TailPhi1 beta gamma) <
        theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma))) :
    Tendsto (fun C : ℕ =>
      cutoffAffordanceProbability
        (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
        (Finset.univ : Finset (Fin (C + 1)))
        (theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)) -
          AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
            (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw)) C -
          Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma))
        (cutoff C)) atTop (nhds 1) := by
  rw [tendsto_order]
  constructor
  · intro lower hlower
    have hepsilon_pos : 0 < 1 - lower := by linarith
    filter_upwards [theorem1_ranked_largeGap_full_affordance_eventually
      noiseLaw hbeta hgamma hvariance hlarge_gap hepsilon_pos] with C hC
    have hrearrange : 1 - (1 - lower) = lower := by ring
    rw [hrearrange] at hC
    exact hC
  · intro upper hupper
    filter_upwards with C
    exact lt_of_le_of_lt
      (cutoffAffordanceProbability_le_one
        (Measure.pi (fun _ : Fin (C + 1) => noiseLaw))
        (Finset.univ : Finset (Fin (C + 1)))
        (theorem3RankedCutoffNat C (cutoff C)
          (theorem3EarlyPrefixRank C (theorem1TailPhi3 beta gamma)) -
          AppliedModelingLib.Probability.expectedTopOrderStatisticSeq
            (fun n : ℕ => Measure.pi (fun _ : Fin (n + 1) => noiseLaw)) C -
          Real.rpow (C : ℝ) (theorem1TailPhi4 beta gamma))
        (cutoff C)) hupper

end

end PG24NoisyMatchingMarkets
