import AppliedModelingLib.Alignment.Axioms.LinearModel
import Mathlib.Order.Interval.Finset.Fin
import Mathlib.Order.PiLex

/-!
# Leximax Copeland subject to Pareto optimality

This module starts the constructive side of Ge et al. (2024), Section 4.  It
keeps the feature-linear feasibility predicate explicit, and defines the two
ingredients of LCPO on a finite profile:

* a candidate's Copeland score, the number of strict-majority pairwise wins;
* the feasible rankings that also honour every unanimous comparison.

The latter is precisely the ``subject to PO'' restriction in the paper.  The
sequential leximax choice and the four-axiom theorem are developed from these
definitions below rather than assumed as properties of an opaque rule.
-/

namespace GeEtAl2024AlignmentAxioms

open AppliedModelingLib.Alignment.Axioms
open AppliedModelingLib.SocialChoice.Ranking

/-- The number of opponents that `candidate` beats by a strict voter majority. -/
def copelandScore {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n) : ℕ :=
  (Finset.univ.filter
    (fun opponent => StrictMajorityPrefers profile candidate opponent)).card

/-- The opponents placed below one candidate in a fixed ranking. -/
noncomputable def strictPreferenceWinnerSet {n : ℕ} (ranking : Ranking n)
    (candidate : Candidate n) : Finset (Candidate n) := by
  classical
  exact Finset.univ.filter (fun opponent => StrictlyPrefers ranking candidate opponent)

/-- A ranking respects the Pareto restrictions generated by one profile. -/
def RespectsPareto {Voter : Type*} {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n) : Prop :=
  ∀ first second,
    UniversallyPreferred profile first second → StrictlyPrefers ranking first second

/-- Pareto-respect for a finite profile is decidable. -/
instance instDecidableRespectsPareto {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n) :
    Decidable (RespectsPareto profile ranking) := by
  unfold RespectsPareto
  letI (first second : Candidate n) :
      Decidable (UniversallyPreferred profile first second →
        StrictlyPrefers ranking first second) := inferInstance
  letI (first : Candidate n) :
      Decidable (∀ second : Candidate n,
        UniversallyPreferred profile first second → StrictlyPrefers ranking first second) :=
    Fintype.decidableForallFintype
  exact Fintype.decidableForallFintype

/-- The rankings among which LCPO makes its sequential Copeland choices. -/
def ParetoFeasibleRanking {Voter : Type*} {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (ranking : Ranking n) : Prop :=
  feasible ranking ∧ RespectsPareto profile ranking

/-- The finite LCPO search domain for one profile. -/
noncomputable def paretoFeasibleRankings {Voter : Type*} {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n) :
    Finset (Ranking n) := by
  classical
  exact Finset.univ.filter (ParetoFeasibleRanking feasible profile)

/-- The position-indexed sequence of Copeland scores used by leximax LCPO. -/
noncomputable def copelandScoreVector {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n) :
    Lex (Candidate n → ℕ) :=
  toLex fun position => copelandScore profile (ranking position)

/-- A Copeland score refined by the fixed, lower-index-first tie break. -/
noncomputable def copelandTieKey {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n) : ℕ :=
  copelandScore profile candidate * Fintype.card (Candidate n) +
    (Fintype.card (Candidate n) - 1 - candidate.val)

/-- The position-indexed fixed-tie Copeland key vector. -/
noncomputable def copelandTieKeyVector {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n) :
    Lex (Candidate n → ℕ) :=
  toLex fun position => copelandTieKey profile (ranking position)

/-- Every submitted ranking respects all unanimous comparisons. -/
theorem submittedRanking_respectsPareto
    {Voter : Type*} {n : ℕ} (profile : RankingProfile Voter n) (voter : Voter) :
    RespectsPareto profile (profile voter) := by
  intro first second hunanimous
  exact hunanimous voter

/--
Under the paper's feasible-input assumption, the LCPO search domain is
nonempty: any submitted ranking is both feasible and Pareto-respecting.
-/
theorem exists_paretoFeasibleRanking
    {Voter : Type*} [Nonempty Voter] {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (hprofile : FeasibleProfile feasible profile) :
    ∃ ranking, ParetoFeasibleRanking feasible profile ranking := by
  let voter : Voter := Classical.choice (inferInstance : Nonempty Voter)
  refine ⟨profile voter, hprofile voter, submittedRanking_respectsPareto profile voter⟩

/-- Membership in the finite LCPO search domain is exactly Pareto-feasibility. -/
theorem mem_paretoFeasibleRankings_iff
    {Voter : Type*} {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (ranking : Ranking n) :
    ranking ∈ paretoFeasibleRankings feasible profile ↔
      ParetoFeasibleRanking feasible profile ranking := by
  classical
  unfold paretoFeasibleRankings
  simp

/-- The finite LCPO search domain is nonempty on every source-feasible profile. -/
theorem paretoFeasibleRankings_nonempty
    {Voter : Type*} [Nonempty Voter] {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (hprofile : FeasibleProfile feasible profile) :
    (paretoFeasibleRankings feasible profile).Nonempty := by
  obtain ⟨ranking, hranking⟩ := exists_paretoFeasibleRanking feasible profile hprofile
  exact ⟨ranking, (mem_paretoFeasibleRankings_iff feasible profile ranking).mpr hranking⟩

/--
The finite leximax-Copeland choice.  It selects an admissible ranking whose
position-indexed Copeland-score vector is lexicographically maximal; this is
equivalent to the source's sequential description.
-/
noncomputable def leximaxCopelandScoreVector
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) : Lex (Candidate n → ℕ) := by
  classical
  let searchDomain := paretoFeasibleRankings feasible profile
  let scoreVectors := searchDomain.image (copelandScoreVector profile)
  have hsearchDomain : searchDomain.Nonempty :=
    paretoFeasibleRankings_nonempty feasible profile hprofile
  have hscoreVectors : scoreVectors.Nonempty := by
    obtain ⟨ranking, hranking⟩ := hsearchDomain
    exact ⟨copelandScoreVector profile ranking,
      Finset.mem_image.mpr ⟨ranking, hranking, rfl⟩⟩
  exact scoreVectors.max' hscoreVectors

/-- A ranking witnessing the maximal finite Copeland-score vector. -/
noncomputable def leximaxCopelandSelection
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    { ranking // ranking ∈ paretoFeasibleRankings feasible profile ∧
      copelandScoreVector profile ranking =
        leximaxCopelandScoreVector feasible profile hprofile } := by
  classical
  let searchDomain := paretoFeasibleRankings feasible profile
  let scoreVectors := searchDomain.image (copelandScoreVector profile)
  have hsearchDomain : searchDomain.Nonempty :=
    paretoFeasibleRankings_nonempty feasible profile hprofile
  have hscoreVectors : scoreVectors.Nonempty := by
    obtain ⟨ranking, hranking⟩ := hsearchDomain
    exact ⟨copelandScoreVector profile ranking,
      Finset.mem_image.mpr ⟨ranking, hranking, rfl⟩⟩
  have hExists : ∃ ranking, ranking ∈ searchDomain ∧
      copelandScoreVector profile ranking =
        leximaxCopelandScoreVector feasible profile hprofile := by
    have hmaxMember := Finset.max'_mem scoreVectors hscoreVectors
    obtain ⟨ranking, hranking, hvector⟩ := Finset.mem_image.mp hmaxMember
    exact ⟨ranking, hranking, hvector⟩
  exact ⟨Classical.choose hExists, Classical.choose_spec hExists⟩

/-- The constructed finite leximax-Copeland outcome. -/
noncomputable def leximaxCopelandOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) : Ranking n :=
  (leximaxCopelandSelection feasible profile hprofile).val

/-- The constructed leximax outcome belongs to LCPO's admissible search domain. -/
theorem leximaxCopelandOutcome_mem_paretoFeasibleRankings
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    leximaxCopelandOutcome feasible profile hprofile ∈
    paretoFeasibleRankings feasible profile := by
  exact (leximaxCopelandSelection feasible profile hprofile).property.1

/-- The constructed outcome's score vector dominates every admissible one. -/
theorem copelandScoreVector_le_leximaxCopelandOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) (contender : Ranking n)
    (hcontender : contender ∈ paretoFeasibleRankings feasible profile) :
    copelandScoreVector profile contender ≤
      copelandScoreVector profile (leximaxCopelandOutcome feasible profile hprofile) := by
  classical
  have hselection := (leximaxCopelandSelection feasible profile hprofile).property.2
  change copelandScoreVector profile contender ≤
    copelandScoreVector profile ↑(leximaxCopelandSelection feasible profile hprofile)
  rw [hselection]
  unfold leximaxCopelandScoreVector
  dsimp
  apply Finset.le_max'
  exact Finset.mem_image.mpr ⟨contender, hcontender, rfl⟩

/-- The maximal fixed-tie Copeland key vector over the finite LCPO domain. -/
noncomputable def fixedTieLCPOKeyVector
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) : Lex (Candidate n → ℕ) := by
  classical
  let searchDomain := paretoFeasibleRankings feasible profile
  let keyVectors := searchDomain.image (copelandTieKeyVector profile)
  have hsearchDomain : searchDomain.Nonempty :=
    paretoFeasibleRankings_nonempty feasible profile hprofile
  have hkeyVectors : keyVectors.Nonempty := by
    obtain ⟨ranking, hranking⟩ := hsearchDomain
    exact ⟨copelandTieKeyVector profile ranking,
      Finset.mem_image.mpr ⟨ranking, hranking, rfl⟩⟩
  exact keyVectors.max' hkeyVectors

/-- A ranking witnessing the maximal fixed-tie Copeland key vector. -/
noncomputable def fixedTieLCPOSelection
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    { ranking // ranking ∈ paretoFeasibleRankings feasible profile ∧
      copelandTieKeyVector profile ranking = fixedTieLCPOKeyVector feasible profile hprofile } := by
  classical
  let searchDomain := paretoFeasibleRankings feasible profile
  let keyVectors := searchDomain.image (copelandTieKeyVector profile)
  have hsearchDomain : searchDomain.Nonempty :=
    paretoFeasibleRankings_nonempty feasible profile hprofile
  have hkeyVectors : keyVectors.Nonempty := by
    obtain ⟨ranking, hranking⟩ := hsearchDomain
    exact ⟨copelandTieKeyVector profile ranking,
      Finset.mem_image.mpr ⟨ranking, hranking, rfl⟩⟩
  have hExists : ∃ ranking, ranking ∈ searchDomain ∧
      copelandTieKeyVector profile ranking = fixedTieLCPOKeyVector feasible profile hprofile := by
    have hmaxMember := Finset.max'_mem keyVectors hkeyVectors
    obtain ⟨ranking, hranking, hvector⟩ := Finset.mem_image.mp hmaxMember
    exact ⟨ranking, hranking, hvector⟩
  exact ⟨Classical.choose hExists, Classical.choose_spec hExists⟩

/-- The constructed finite LCPO outcome with fixed candidate-order tie breaking. -/
noncomputable def fixedTieLCPOOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) : Ranking n :=
  (fixedTieLCPOSelection feasible profile hprofile).val

/-- The fixed-tie outcome belongs to LCPO's finite Pareto-feasible domain. -/
theorem fixedTieLCPOOutcome_mem_paretoFeasibleRankings
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    fixedTieLCPOOutcome feasible profile hprofile ∈ paretoFeasibleRankings feasible profile :=
  (fixedTieLCPOSelection feasible profile hprofile).property.1

/-- The fixed-tie outcome's key vector dominates every admissible one. -/
theorem copelandTieKeyVector_le_fixedTieLCPOOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) (contender : Ranking n)
    (hcontender : contender ∈ paretoFeasibleRankings feasible profile) :
    copelandTieKeyVector profile contender ≤
      copelandTieKeyVector profile (fixedTieLCPOOutcome feasible profile hprofile) := by
  classical
  have hselection := (fixedTieLCPOSelection feasible profile hprofile).property.2
  change copelandTieKeyVector profile contender ≤
    copelandTieKeyVector profile ↑(fixedTieLCPOSelection feasible profile hprofile)
  rw [hselection]
  unfold fixedTieLCPOKeyVector
  dsimp
  apply Finset.le_max'
  exact Finset.mem_image.mpr ⟨contender, hcontender, rfl⟩

/-- A candidate placed first in a ranking is strictly above every other candidate. -/
theorem strictlyPrefers_of_firstChoice_eq
    {n : ℕ} (ranking : Ranking n) {candidate other : Candidate n}
    (hfirst : firstChoice ranking = candidate) (hother : other ≠ candidate) :
    StrictlyPrefers ranking candidate other := by
  rw [← hfirst, StrictlyPrefers, rankOf_firstChoice]
  have hne : rankOf ranking other ≠ 0 := by
    intro hzero
    apply hother
    calc
      other = ranking (rankOf ranking other) := by simp [rankOf]
      _ = ranking 0 := congrArg ranking hzero
      _ = candidate := hfirst
  exact Fin.pos_iff_ne_zero.2 hne

/--
Moving a candidate upward, while preserving the order of every other pair,
cannot reverse a pair already headed by that candidate.  This is the finite
permutation core of the source's ``elevating a candidate'' operation.
-/
theorem strictlyPrefers_preserved_of_elevatesCandidate
    {n : ℕ} (original updated : Ranking n) (candidate other : Candidate n)
    (helevates : ElevatesCandidate original updated candidate)
    (hpreference : StrictlyPrefers original candidate other) :
    StrictlyPrefers updated candidate other := by
  classical
  unfold ElevatesCandidate at helevates
  rcases helevates with ⟨hcandidateRank, hotherOrder⟩
  have hother_ne_candidate : other ≠ candidate := by
    intro heq
    subst other
    exact not_strictlyPrefers_self original candidate hpreference
  by_contra hnot
  have hreverse : StrictlyPrefers updated other candidate := by
    unfold StrictlyPrefers at hnot ⊢
    have hne : rankOf updated candidate ≠ rankOf updated other := by
      intro heq
      apply hother_ne_candidate
      have happly := congrArg updated heq
      simpa [rankOf] using happly.symm
    exact (lt_or_gt_of_ne hne).resolve_left hnot
  let oldEarly : Finset (Candidate n) :=
    (Finset.Iio (rankOf original candidate)).image original
  let newBeforeOther : Finset (Candidate n) :=
    (Finset.Iio (rankOf updated other)).image updated
  have hsubset : oldEarly ⊆ newBeforeOther := by
    intro alternative halt
    obtain ⟨position, hposition, hpositionEq⟩ := Finset.mem_image.mp halt
    subst alternative
    have hpositionLt : position < rankOf original candidate := by
      simpa using hposition
    have hposition_ne_candidate : original position ≠ candidate := by
      intro heq
      have hpositionRank : position = rankOf original candidate := by
        calc
          position = rankOf original (original position) := by simp [rankOf]
          _ = rankOf original candidate := congrArg (rankOf original) heq
      exact (ne_of_lt hpositionLt) hpositionRank
    have hposition_preferred : StrictlyPrefers original (original position) candidate := by
      simpa [StrictlyPrefers, rankOf] using hpositionLt
    have hposition_other : StrictlyPrefers original (original position) other :=
      lt_trans hposition_preferred hpreference
    have hupdatedPreference : StrictlyPrefers updated (original position) other :=
      (hotherOrder (original position) other hposition_ne_candidate hother_ne_candidate).mp
        hposition_other
    refine Finset.mem_image.mpr ⟨rankOf updated (original position), ?_, ?_⟩
    · simpa [StrictlyPrefers] using hupdatedPreference
    · simp [rankOf]
  have hcard : oldEarly.card ≤ newBeforeOther.card := Finset.card_le_card hsubset
  have holdEarlyCard : oldEarly.card = (rankOf original candidate).val := by
    unfold oldEarly
    rw [Finset.card_image_of_injective _ original.injective, Fin.card_Iio]
  have hnewBeforeCard : newBeforeOther.card = (rankOf updated other).val := by
    unfold newBeforeOther
    rw [Finset.card_image_of_injective _ updated.injective, Fin.card_Iio]
  rw [holdEarlyCard, hnewBeforeCard] at hcard
  exact (by
    have hcandidateRankVal : (rankOf updated candidate).val ≤
        (rankOf original candidate).val := hcandidateRank
    have hreverseVal : (rankOf updated other).val <
        (rankOf updated candidate).val := hreverse
    omega)

/-- Every elevated profile preserves comparisons already won by its elevated candidate. -/
theorem profileElevatesCandidate_preserves_candidate_preference
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (individual : Voter) (hpreference : StrictlyPrefers (original individual) candidate other) :
    StrictlyPrefers (updated individual) candidate other := by
  rcases helevates with ⟨helevates, hotherVoters⟩
  by_cases hsame : individual = voter
  · subst individual
    exact strictlyPrefers_preserved_of_elevatesCandidate
      (original voter) (updated voter) candidate other helevates hpreference
  · rw [hotherVoters individual hsame]
    exact hpreference

/-- Comparisons between candidates other than the elevated one are unchanged. -/
theorem profileElevatesCandidate_preserves_other_preference
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate first second : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hfirst : first ≠ candidate) (hsecond : second ≠ candidate) (individual : Voter) :
    (StrictlyPrefers (original individual) first second ↔
      StrictlyPrefers (updated individual) first second) := by
  rcases helevates with ⟨helevates, hotherVoters⟩
  by_cases hsame : individual = voter
  · subst individual
    exact helevates.2 first second hfirst hsecond
  · rw [hotherVoters individual hsame]

/-- A total ranking orients every pair of distinct candidates in one direction. -/
theorem strictlyPrefers_or_reverse_of_ne
    {n : ℕ} (ranking : Ranking n) {first second : Candidate n} (hne : first ≠ second) :
    StrictlyPrefers ranking first second ∨ StrictlyPrefers ranking second first := by
  unfold StrictlyPrefers
  have hrankNe : rankOf ranking first ≠ rankOf ranking second := by
    intro heq
    apply hne
    have happly := congrArg ranking heq
    simpa [rankOf] using happly
  exact lt_or_gt_of_ne hrankNe

/--
If an update has elevated `candidate`, a comparison placing another candidate
above it after the update already placed that candidate above it before.
-/
theorem profileElevatesCandidate_reverse_preference
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (individual : Voter)
    (hupdated : StrictlyPrefers (updated individual) other candidate) :
    StrictlyPrefers (original individual) other candidate := by
  have hne : other ≠ candidate := by
    intro heq
    subst other
    exact not_strictlyPrefers_self (updated individual) candidate hupdated
  by_contra horiginal
  obtain hforward | hreverse :=
    strictlyPrefers_or_reverse_of_ne (original individual) hne
  · exact horiginal hforward
  · have hpreserved := profileElevatesCandidate_preserves_candidate_preference
      original updated voter candidate other helevates individual hreverse
    exact (lt_asymm hpreserved) hupdated

/-- A strict-majority win of the elevated candidate remains a strict-majority win. -/
theorem strictMajorityPrefers_preserved_of_profileElevatesCandidate
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hmajority : StrictMajorityPrefers original candidate other) :
    StrictMajorityPrefers updated candidate other := by
  classical
  unfold StrictMajorityPrefers StrictMajority votersSatisfying at hmajority ⊢
  apply lt_of_lt_of_le hmajority
  apply Nat.mul_le_mul_left
  apply Finset.card_le_card
  intro individual hindividual
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hindividual ⊢
  exact profileElevatesCandidate_preserves_candidate_preference
    original updated voter candidate other helevates individual hindividual

/-- A strict-majority comparison against the elevated candidate cannot be newly created. -/
theorem strictMajorityPrefers_reverse_of_profileElevatesCandidate
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hmajority : StrictMajorityPrefers updated other candidate) :
    StrictMajorityPrefers original other candidate := by
  classical
  unfold StrictMajorityPrefers StrictMajority votersSatisfying at hmajority ⊢
  apply lt_of_lt_of_le hmajority
  apply Nat.mul_le_mul_left
  apply Finset.card_le_card
  intro individual hindividual
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hindividual ⊢
  exact profileElevatesCandidate_reverse_preference
    original updated voter candidate other helevates individual hindividual

/-- Strict-majority comparisons not involving the elevated candidate are unchanged. -/
theorem strictMajorityPrefers_iff_of_profileElevatesCandidate_other
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate first second : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hfirst : first ≠ candidate) (hsecond : second ≠ candidate) :
    (StrictMajorityPrefers original first second ↔
      StrictMajorityPrefers updated first second) := by
  classical
  constructor <;> intro hmajority
  · unfold StrictMajorityPrefers StrictMajority votersSatisfying at hmajority ⊢
    have hsets : (Finset.univ.filter (fun individual =>
        StrictlyPrefers (original individual) first second)) =
        Finset.univ.filter (fun individual =>
          StrictlyPrefers (updated individual) first second) := by
      ext individual
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact profileElevatesCandidate_preserves_other_preference
        original updated voter candidate first second helevates hfirst hsecond individual
    rw [hsets] at hmajority
    exact hmajority
  · unfold StrictMajorityPrefers StrictMajority votersSatisfying at hmajority ⊢
    have hsets : (Finset.univ.filter (fun individual =>
        StrictlyPrefers (updated individual) first second)) =
        Finset.univ.filter (fun individual =>
          StrictlyPrefers (original individual) first second) := by
      ext individual
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact (profileElevatesCandidate_preserves_other_preference
        original updated voter candidate first second helevates hfirst hsecond individual).symm
    rw [hsets] at hmajority
    exact hmajority

/-- Elevating a candidate weakly increases its Copeland score. -/
theorem copelandScore_le_of_profileElevatesCandidate
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate) :
    copelandScore original candidate ≤ copelandScore updated candidate := by
  classical
  rw [copelandScore, copelandScore]
  apply Finset.card_le_card
  intro other hother
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hother ⊢
  exact strictMajorityPrefers_preserved_of_profileElevatesCandidate
    original updated voter candidate other helevates hother

/-- Every other candidate's Copeland score weakly decreases after an elevation. -/
theorem copelandScore_after_le_of_profileElevatesCandidate_other
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hother : other ≠ candidate) :
    copelandScore updated other ≤ copelandScore original other := by
  classical
  rw [copelandScore, copelandScore]
  apply Finset.card_le_card
  intro opponent hopponent
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hopponent ⊢
  by_cases hopponentEq : opponent = candidate
  · subst opponent
    exact strictMajorityPrefers_reverse_of_profileElevatesCandidate
      original updated voter candidate other helevates hopponent
  · exact (strictMajorityPrefers_iff_of_profileElevatesCandidate_other
      original updated voter candidate other opponent helevates hother hopponentEq).mpr hopponent

/-- A unanimous comparison headed by the elevated candidate remains unanimous. -/
theorem universallyPreferred_preserved_of_profileElevatesCandidate
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hunanimous : UniversallyPreferred original candidate other) :
    UniversallyPreferred updated candidate other := by
  intro individual
  exact profileElevatesCandidate_preserves_candidate_preference
    original updated voter candidate other helevates individual (hunanimous individual)

/-- Unanimous comparisons not involving the elevated candidate are unchanged. -/
theorem universallyPreferred_iff_of_profileElevatesCandidate_other
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate first second : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hfirst : first ≠ candidate) (hsecond : second ≠ candidate) :
    (UniversallyPreferred original first second ↔
      UniversallyPreferred updated first second) := by
  constructor <;> intro hunanimous <;> intro individual
  · exact (profileElevatesCandidate_preserves_other_preference
      original updated voter candidate first second helevates hfirst hsecond individual).mp
        (hunanimous individual)
  · exact (profileElevatesCandidate_preserves_other_preference
      original updated voter candidate first second helevates hfirst hsecond individual).mpr
        (hunanimous individual)

/-- A unanimous comparison against the elevated candidate cannot be newly created. -/
theorem universallyPreferred_reverse_of_profileElevatesCandidate
    {Voter : Type*} {n : ℕ} (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hunanimous : UniversallyPreferred updated other candidate) :
    UniversallyPreferred original other candidate := by
  intro individual
  exact profileElevatesCandidate_reverse_preference
    original updated voter candidate other helevates individual (hunanimous individual)

/-- A Pareto-respecting output headed by `candidate` rules out unanimous opposition to it. -/
theorem not_universallyPreferred_against_firstChoice_of_respectsPareto
    {Voter : Type*} {n : ℕ} (profile : RankingProfile Voter n) (outcome : Ranking n)
    (candidate other : Candidate n) (hrespects : RespectsPareto profile outcome)
    (hfirst : firstChoice outcome = candidate) (hother : other ≠ candidate) :
    ¬ UniversallyPreferred profile other candidate := by
  intro hunanimous
  have houtputOther : StrictlyPrefers outcome other candidate :=
    hrespects other candidate hunanimous
  have houtputCandidate : StrictlyPrefers outcome candidate other :=
    strictlyPrefers_of_firstChoice_eq outcome hfirst hother
  exact (lt_asymm houtputOther) houtputCandidate

/--
After an elevation, every ranking respecting the updated Pareto restrictions
also respects the original restrictions, provided the original selected winner
had no unanimous opposition.
-/
theorem respectsPareto_original_of_respectsPareto_updated
    {Voter : Type*} [Nonempty Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate : Candidate n) (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hnoOpposition : ∀ other, other ≠ candidate → ¬ UniversallyPreferred original other candidate)
    (ranking : Ranking n) (hupdated : RespectsPareto updated ranking) :
    RespectsPareto original ranking := by
  intro first second hunanimous
  by_cases hfirst : first = candidate
  · subst first
    have hsecond : second ≠ candidate := by
      intro heq
      subst second
      let individual : Voter := Classical.choice (inferInstance : Nonempty Voter)
      exact not_strictlyPrefers_self (original individual) candidate (hunanimous individual)
    exact hupdated candidate second
      (universallyPreferred_preserved_of_profileElevatesCandidate
        original updated voter candidate second helevates hunanimous)
  · by_cases hsecond : second = candidate
    · subst second
      exact False.elim (hnoOpposition first hfirst hunanimous)
    · exact hupdated first second
        ((universallyPreferred_iff_of_profileElevatesCandidate_other
          original updated voter candidate first second helevates hfirst hsecond).mp hunanimous)

/--
An original Pareto-respecting ranking headed by the elevated candidate remains
Pareto-respecting after the profile update.
-/
theorem respectsPareto_updated_of_respectsPareto_original_firstChoice
    {Voter : Type*} [Nonempty Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate : Candidate n) (helevates : ProfileElevatesCandidate original updated voter candidate)
    (ranking : Ranking n) (horiginal : RespectsPareto original ranking)
    (hfirstRanking : firstChoice ranking = candidate) :
    RespectsPareto updated ranking := by
  intro first second hunanimous
  by_cases hfirst : first = candidate
  · subst first
    have hsecond : second ≠ candidate := by
      intro heq
      subst second
      let individual : Voter := Classical.choice (inferInstance : Nonempty Voter)
      exact not_strictlyPrefers_self (updated individual) candidate (hunanimous individual)
    exact strictlyPrefers_of_firstChoice_eq ranking hfirstRanking hsecond
  · by_cases hsecond : second = candidate
    · subst second
      have horiginalUnanimous := universallyPreferred_reverse_of_profileElevatesCandidate
        original updated voter candidate first helevates hunanimous
      have hrankingOther : StrictlyPrefers ranking first candidate :=
        horiginal first candidate horiginalUnanimous
      have hrankingCandidate : StrictlyPrefers ranking candidate first :=
        strictlyPrefers_of_firstChoice_eq ranking hfirstRanking hfirst
      exact False.elim ((lt_asymm hrankingOther) hrankingCandidate)
    · exact horiginal first second
        ((universallyPreferred_iff_of_profileElevatesCandidate_other
          original updated voter candidate first second helevates hfirst hsecond).mpr hunanimous)

/--
A strict-majority top choice beats every distinct opponent pairwise.  This is
the finite counting fact used in the majority-consistency part of Theorem 4.3.
-/
theorem strictMajorityPrefers_of_majorityTopChoice
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) {candidate other : Candidate n}
    (hmajority : MajorityTopChoice profile candidate) (hother : other ≠ candidate) :
    StrictMajorityPrefers profile candidate other := by
  classical
  unfold MajorityTopChoice at hmajority
  unfold StrictMajorityPrefers
  unfold StrictMajority at hmajority ⊢
  apply lt_of_lt_of_le hmajority
  apply Nat.mul_le_mul_left
  apply Finset.card_le_card
  intro voter hvoter
  simp only [votersSatisfying, Finset.mem_filter, Finset.mem_univ, true_and] at hvoter ⊢
  exact strictlyPrefers_of_firstChoice_eq (profile voter) hvoter hother

/-- No candidate is a strict-majority winner over itself. -/
theorem not_strictMajorityPrefers_self
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n) :
    ¬ StrictMajorityPrefers profile candidate candidate := by
  classical
  unfold StrictMajorityPrefers StrictMajority votersSatisfying
  have hempty : Finset.univ.filter
      (fun voter => StrictlyPrefers (profile voter) candidate candidate) = ∅ := by
    apply Finset.eq_empty_iff_forall_notMem.2
    intro voter hvoter
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hvoter
    exact not_strictlyPrefers_self (profile voter) candidate hvoter
  rw [hempty]
  simp

/-- A Copeland score is at most the number of other candidates. -/
theorem copelandScore_le_numberOfOtherCandidates
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n) :
    copelandScore profile candidate ≤ Fintype.card (Candidate n) - 1 := by
  classical
  rw [copelandScore]
  have hsubset : Finset.univ.filter
      (fun opponent => StrictMajorityPrefers profile candidate opponent) ⊆
      Finset.univ.erase candidate := by
    intro opponent hopponent
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hopponent
    simp only [Finset.mem_erase, Finset.mem_univ, and_true]
    intro heq
    subst opponent
    exact not_strictMajorityPrefers_self profile candidate hopponent
  calc
    (Finset.univ.filter (fun opponent =>
      StrictMajorityPrefers profile candidate opponent)).card ≤
        (Finset.univ.erase candidate).card := Finset.card_le_card hsubset
    _ = Fintype.card (Candidate n) - 1 := by
      rw [Finset.card_erase_of_mem (Finset.mem_univ candidate), Finset.card_univ]

/--
A strict-majority top choice attains the largest possible Copeland score.
-/
theorem copelandScore_eq_numberOfOtherCandidates_of_majorityTopChoice
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n)
    (hmajority : MajorityTopChoice profile candidate) :
    copelandScore profile candidate = Fintype.card (Candidate n) - 1 := by
  classical
  apply Nat.le_antisymm
  · exact copelandScore_le_numberOfOtherCandidates profile candidate
  · rw [copelandScore]
    have hsubset : Finset.univ.erase candidate ⊆ Finset.univ.filter
        (fun opponent => StrictMajorityPrefers profile candidate opponent) := by
      intro opponent hopponent
      simp only [Finset.mem_erase, Finset.mem_univ, and_true] at hopponent
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact strictMajorityPrefers_of_majorityTopChoice profile hmajority hopponent
    calc
      Fintype.card (Candidate n) - 1 = (Finset.univ.erase candidate).card := by
        rw [Finset.card_erase_of_mem (Finset.mem_univ candidate), Finset.card_univ]
      _ ≤ (Finset.univ.filter (fun opponent =>
        StrictMajorityPrefers profile candidate opponent)).card := Finset.card_le_card hsubset

/-- Strict majorities cannot point in both directions on one pair. -/
theorem not_strictMajorityPrefers_reverse
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) {first second : Candidate n}
    (hforward : StrictMajorityPrefers profile first second) :
    ¬ StrictMajorityPrefers profile second first := by
  classical
  intro hreverse
  let forwardVoters : Finset Voter := votersSatisfying
    (fun voter => StrictlyPrefers (profile voter) first second)
  let reverseVoters : Finset Voter := votersSatisfying
    (fun voter => StrictlyPrefers (profile voter) second first)
  have hdisjoint : Disjoint forwardVoters reverseVoters := by
    refine Finset.disjoint_left.2 ?_
    intro voter hforwardMem hreverseMem
    simp only [forwardVoters, reverseVoters, votersSatisfying,
      Finset.mem_filter, Finset.mem_univ, true_and] at hforwardMem hreverseMem
    exact (lt_asymm hforwardMem) hreverseMem
  have hcard_union : forwardVoters.card + reverseVoters.card ≤ Fintype.card Voter := by
    calc
      forwardVoters.card + reverseVoters.card = (forwardVoters ∪ reverseVoters).card :=
        (Finset.card_union_of_disjoint hdisjoint).symm
      _ ≤ Finset.univ.card := Finset.card_le_card (by
        intro voter _
        exact Finset.mem_univ voter)
      _ = Fintype.card Voter := Finset.card_univ
  have hforwardCard : Fintype.card Voter < 2 * forwardVoters.card := by
    simpa only [forwardVoters, StrictMajorityPrefers, StrictMajority] using hforward
  have hreverseCard : Fintype.card Voter < 2 * reverseVoters.card := by
    simpa only [reverseVoters, StrictMajorityPrefers, StrictMajority] using hreverse
  omega

/-- A top-score candidate is the unique such candidate when it has a strict-majority top vote. -/
theorem copelandScore_eq_max_implies_eq_majorityTopChoice
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate other : Candidate n)
    (hmajority : MajorityTopChoice profile candidate)
    (hotherScore : copelandScore profile other = Fintype.card (Candidate n) - 1) :
    other = candidate := by
  classical
  by_contra hne
  have hotherBeats : StrictMajorityPrefers profile other candidate := by
    rw [copelandScore] at hotherScore
    by_contra hnot
    have hsubset : Finset.univ.filter
        (fun opponent => StrictMajorityPrefers profile other opponent) ⊆
        (Finset.univ.erase other).erase candidate := by
      intro opponent hopponent
      simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hopponent
      simp only [Finset.mem_erase]
      refine ⟨?_, ?_, Finset.mem_univ _⟩
      · intro heq
        subst opponent
        exact hnot hopponent
      · intro heq
        subst opponent
        exact not_strictMajorityPrefers_self profile other hopponent
    have hcard : (Finset.univ.filter
        (fun opponent => StrictMajorityPrefers profile other opponent)).card ≤
        ((Finset.univ.erase other).erase candidate).card := Finset.card_le_card hsubset
    have hcardErase : ((Finset.univ.erase other).erase candidate).card =
        Fintype.card (Candidate n) - 2 := by
      have hcandidate_ne_other : candidate ≠ other := by
        intro heq
        exact hne heq.symm
      calc
        ((Finset.univ.erase other).erase candidate).card =
            (Finset.univ.erase other).card - 1 :=
          Finset.card_erase_of_mem (Finset.mem_erase.2
            ⟨hcandidate_ne_other, Finset.mem_univ candidate⟩)
        _ = (Fintype.card (Candidate n) - 1) - 1 := by
          rw [Finset.card_erase_of_mem (Finset.mem_univ other), Finset.card_univ]
        _ = Fintype.card (Candidate n) - 2 := by omega
    rw [hotherScore, hcardErase] at hcard
    have htwo : 2 ≤ Fintype.card (Candidate n) := by
      simp [Candidate]
    omega
  have hcandidateBeats : StrictMajorityPrefers profile candidate other :=
    strictMajorityPrefers_of_majorityTopChoice profile hmajority (by
      intro heq
      exact hne heq)
  exact not_strictMajorityPrefers_reverse profile hcandidateBeats hotherBeats

/-- Two rankings agree before a given position. -/
def AgreesBefore {n : ℕ} (reference contender : Ranking n)
    (position : Candidate n) : Prop :=
  ∀ earlier, earlier < position → contender earlier = reference earlier

/--
`candidate` can be placed at `position` while retaining the already selected
prefix and the LCPO feasibility and Pareto restrictions.
-/
def CanPlaceAt {Voter : Type*} {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (selectedPrefix : Ranking n)
    (position candidate : Candidate n) : Prop :=
  ∃ contender, ParetoFeasibleRanking feasible profile contender ∧
    AgreesBefore selectedPrefix contender position ∧ contender position = candidate

/--
The source definition of a leximax Copeland subject-to-PO outcome: it is a
Pareto-feasible ranking and, at every position, has a maximal Copeland score
among all candidates that can extend the prefix selected so far.  Ties are
left arbitrary, exactly as in the paper.
-/
def IsLCPOOutcome {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (outcome : Ranking n) : Prop :=
  ParetoFeasibleRanking feasible profile outcome ∧
  ∀ position candidate,
    CanPlaceAt feasible profile outcome position candidate →
      copelandScore profile candidate ≤ copelandScore profile (outcome position)

/-- A rule applies the LCPO sequential-choice condition on every feasible input profile. -/
def IsLCPOSelector {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop)
    (rule : LinearRankAggregationRule Voter n feasible) : Prop :=
  ∀ profile, FeasibleProfile feasible profile → IsLCPOOutcome feasible profile (rule.run profile)

/-- The finite lexicographic maximizer satisfies LCPO's sequential condition. -/
theorem leximaxCopelandOutcome_isLCPOOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    IsLCPOOutcome feasible profile (leximaxCopelandOutcome feasible profile hprofile) := by
  refine ⟨(mem_paretoFeasibleRankings_iff feasible profile
    (leximaxCopelandOutcome feasible profile hprofile)).mp
      (leximaxCopelandOutcome_mem_paretoFeasibleRankings feasible profile hprofile), ?_⟩
  intro position candidate hcanPlace
  obtain ⟨contender, hcontender, hprefix, hposition⟩ := hcanPlace
  have hcontenderMem : contender ∈ paretoFeasibleRankings feasible profile :=
    (mem_paretoFeasibleRankings_iff feasible profile contender).mpr hcontender
  have hvectorLe := copelandScoreVector_le_leximaxCopelandOutcome feasible profile hprofile
    contender hcontenderMem
  have hcomponentLe : copelandScore profile (contender position) ≤
      copelandScore profile (leximaxCopelandOutcome feasible profile hprofile position) := by
    apply Pi.apply_le_of_toLex hvectorLe
    intro earlier hearlier
    rw [hprefix earlier hearlier]
  simpa [hposition] using hcomponentLe

/--
The total linear-rank-aggregation rule induced by finite leximax Copeland.
The source model only invokes it on feasible profiles; `fallback` makes the
Lean function total outside that domain without affecting its source behavior.
-/
noncomputable def leximaxCopelandRule
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (fallback : Ranking n) (hfallback : feasible fallback) :
    LinearRankAggregationRule Voter n feasible where
  run profile := by
    classical
    exact if hprofile : FeasibleProfile feasible profile then
      leximaxCopelandOutcome feasible profile hprofile
    else fallback
  output_feasible profile := by
    classical
    split
    · exact (leximaxCopelandOutcome_isLCPOOutcome feasible profile _).1.1
    · exact hfallback

/-- The constructed finite leximax-Copeland rule is an LCPO selector. -/
theorem leximaxCopelandRule_isLCPOSelector
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (fallback : Ranking n) (hfallback : feasible fallback) :
    IsLCPOSelector feasible (leximaxCopelandRule (Voter := Voter) feasible fallback hfallback) := by
  intro profile hprofile
  simp only [leximaxCopelandRule, dif_pos hprofile]
  exact leximaxCopelandOutcome_isLCPOOutcome feasible profile hprofile

/--
A fixed, profile-independent Copeland tie break: lower candidate indices win a
score tie.  This makes explicit the fixed tie-breaking convention needed by
the source's winner-monotonicity argument.
-/
def CopelandBetter {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (first second : Candidate n) : Prop :=
  copelandScore profile second < copelandScore profile first ∨
    (copelandScore profile first = copelandScore profile second ∧ first < second)

/-- The finite fixed-tie Copeland comparison is decidable. -/
instance instDecidableCopelandBetter {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (first second : Candidate n) :
    Decidable (CopelandBetter profile first second) := by
  unfold CopelandBetter
  infer_instance

/-- The numerical fixed-tie key strictly represents the `CopelandBetter` order. -/
theorem copelandTieKey_lt_of_copelandBetter
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (first second : Candidate n)
    (hbetter : CopelandBetter profile first second) :
    copelandTieKey profile second < copelandTieKey profile first := by
  unfold CopelandBetter at hbetter
  unfold copelandTieKey
  have hcard : Fintype.card (Candidate n) = n + 2 := by simp [Candidate]
  have hfirstLt : first.val < Fintype.card (Candidate n) := by
    simpa [Candidate] using first.isLt
  have hsecondLt : second.val < Fintype.card (Candidate n) := by
    simpa [Candidate] using second.isLt
  have hcardPos : 0 < Fintype.card (Candidate n) := by
    simp [Candidate]
  rcases hbetter with hscore | ⟨hscore, hindex⟩
  · have hremainder : Fintype.card (Candidate n) - 1 - second.val <
        Fintype.card (Candidate n) := by
      omega
    calc
      copelandScore profile second * Fintype.card (Candidate n) +
          (Fintype.card (Candidate n) - 1 - second.val) <
          copelandScore profile second * Fintype.card (Candidate n) +
            Fintype.card (Candidate n) := Nat.add_lt_add_left hremainder _
      _ = (copelandScore profile second + 1) * Fintype.card (Candidate n) := by
        rw [Nat.add_mul, one_mul]
      _ ≤ copelandScore profile first * Fintype.card (Candidate n) :=
        Nat.mul_le_mul_right _ (Nat.succ_le_of_lt hscore)
      _ ≤ copelandScore profile first * Fintype.card (Candidate n) +
          (Fintype.card (Candidate n) - 1 - first.val) := Nat.le_add_right _ _
  · have hindexVal : first.val < second.val := hindex
    rw [hscore]
    apply Nat.add_lt_add_left
    omega

/-- LCPO's sequential condition with the fixed Copeland tie break. -/
def IsFixedTieLCPOOutcome {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (outcome : Ranking n) : Prop :=
  ParetoFeasibleRanking feasible profile outcome ∧
  ∀ position candidate,
    CanPlaceAt feasible profile outcome position candidate →
      ¬ CopelandBetter profile candidate (outcome position)

/-- The finite fixed-key maximizer satisfies the fixed-tie LCPO condition. -/
theorem fixedTieLCPOOutcome_isFixedTieLCPOOutcome
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) :
    IsFixedTieLCPOOutcome feasible profile (fixedTieLCPOOutcome feasible profile hprofile) := by
  refine ⟨(mem_paretoFeasibleRankings_iff feasible profile
    (fixedTieLCPOOutcome feasible profile hprofile)).mp
      (fixedTieLCPOOutcome_mem_paretoFeasibleRankings feasible profile hprofile), ?_⟩
  intro position candidate hcanPlace hbetter
  obtain ⟨contender, hcontender, hprefix, hposition⟩ := hcanPlace
  have hcontenderMem : contender ∈ paretoFeasibleRankings feasible profile :=
    (mem_paretoFeasibleRankings_iff feasible profile contender).mpr hcontender
  have hvectorLe := copelandTieKeyVector_le_fixedTieLCPOOutcome feasible profile hprofile
    contender hcontenderMem
  have hcomponentLe : copelandTieKey profile (contender position) ≤
      copelandTieKey profile (fixedTieLCPOOutcome feasible profile hprofile position) := by
    apply Pi.apply_le_of_toLex hvectorLe
    intro earlier hearlier
    rw [hprefix earlier hearlier]
  have hkeyLt := copelandTieKey_lt_of_copelandBetter profile candidate
    (fixedTieLCPOOutcome feasible profile hprofile position) hbetter
  rw [← hposition] at hkeyLt
  exact (not_lt_of_ge hcomponentLe) hkeyLt

/--
If one Pareto-feasible ranking orders every earlier position strictly ahead of
every later position under the fixed Copeland tie break, then it is the unique
fixed-tie LCPO outcome.  The proof chooses the earliest disagreement and uses
the reference ranking as a feasible prefix extension at that position.
-/
theorem isFixedTieLCPOOutcome_eq_of_strictCopelandBetter
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (outcome reference : Ranking n)
    (houtcome : IsFixedTieLCPOOutcome feasible profile outcome)
    (hreference : ParetoFeasibleRanking feasible profile reference)
    (hstrict : ∀ earlier later : Candidate n, earlier < later →
      CopelandBetter profile (reference earlier) (reference later)) :
    outcome = reference := by
  classical
  by_contra hne
  let differing : Finset (Candidate n) :=
    Finset.univ.filter (fun position => outcome position ≠ reference position)
  have hexists : ∃ position, outcome position ≠ reference position := by
    by_contra hnone
    push_neg at hnone
    exact hne (by
      ext position
      exact congrArg Fin.val (hnone position))
  obtain ⟨witness, hwitness⟩ := hexists
  have hdiffering : differing.Nonempty := by
    refine ⟨witness, ?_⟩
    simp only [differing, Finset.mem_filter, Finset.mem_univ, true_and]
    exact hwitness
  let position : Candidate n := differing.min' hdiffering
  have hpositionMem : position ∈ differing := Finset.min'_mem differing hdiffering
  have hpositionDiff : outcome position ≠ reference position := by
    simpa only [differing, Finset.mem_filter, Finset.mem_univ, true_and] using hpositionMem
  have hprefix : ∀ earlier : Candidate n, earlier < position →
      outcome earlier = reference earlier := by
    intro earlier hearlier
    by_contra hdiff
    have hearlierMem : earlier ∈ differing := by
      simp only [differing, Finset.mem_filter, Finset.mem_univ, true_and]
      exact hdiff
    have hposition_le : position ≤ earlier := Finset.min'_le differing earlier hearlierMem
    exact (not_le_of_gt hearlier) hposition_le
  let later : Candidate n := rankOf reference (outcome position)
  have hreference_later : reference later = outcome position := by
    simp only [later, rankOf]
    exact reference.apply_symm_apply _
  have hposition_lt_later : position < later := by
    by_contra hnot
    have hlater_le : later ≤ position := le_of_not_gt hnot
    rcases lt_or_eq_of_le hlater_le with hlater_lt | hlater_eq
    · have hlater_value : outcome later = reference later := hprefix later hlater_lt
      have hsame : outcome later = outcome position :=
        hlater_value.trans hreference_later
      exact (ne_of_lt hlater_lt) (outcome.injective hsame)
    · apply hpositionDiff
      calc
        outcome position = reference later := hreference_later.symm
        _ = reference position := congrArg reference hlater_eq
  have hcanPlace : CanPlaceAt feasible profile outcome position (reference position) :=
    ⟨reference, hreference, fun earlier hearlier => (hprefix earlier hearlier).symm, rfl⟩
  have hbetter : CopelandBetter profile (reference position) (outcome position) := by
    have h := hstrict position later hposition_lt_later
    rwa [hreference_later] at h
  exact houtcome.2 position (reference position) hcanPlace hbetter

/-- The total finite LCPO rule with a fixed, profile-independent tie break. -/
noncomputable def fixedTieLCPO
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (fallback : Ranking n) (hfallback : feasible fallback) :
    LinearRankAggregationRule Voter n feasible where
  run profile := by
    classical
    exact if hprofile : FeasibleProfile feasible profile then
      fixedTieLCPOOutcome feasible profile hprofile
    else fallback
  output_feasible profile := by
    classical
    split
    · exact (fixedTieLCPOOutcome_isFixedTieLCPOOutcome feasible profile _).1.1
    · exact hfallback

/-- Fixed-tie LCPO outcomes satisfy the score-maximal LCPO condition. -/
theorem isFixedTieLCPOOutcome_isLCPOOutcome
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (outcome : Ranking n) (houtcome : IsFixedTieLCPOOutcome feasible profile outcome) :
    IsLCPOOutcome feasible profile outcome := by
  refine ⟨houtcome.1, ?_⟩
  intro position candidate hcanPlace
  apply Nat.le_of_not_gt
  intro hgt
  exact houtcome.2 position candidate hcanPlace (Or.inl hgt)

/-- A fixed-tie LCPO selector uses that outcome condition on every feasible profile. -/
def IsFixedTieLCPOSelector {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop)
    (rule : LinearRankAggregationRule Voter n feasible) : Prop :=
  ∀ profile, FeasibleProfile feasible profile →
    IsFixedTieLCPOOutcome feasible profile (rule.run profile)

/-- The concrete fixed-tie rule realizes the fixed-tie LCPO selector definition. -/
theorem fixedTieLCPO_isFixedTieLCPOSelector
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (fallback : Ranking n) (hfallback : feasible fallback) :
    IsFixedTieLCPOSelector feasible (fixedTieLCPO (Voter := Voter) feasible fallback hfallback) := by
  intro profile hprofile
  simp only [fixedTieLCPO, dif_pos hprofile]
  exact fixedTieLCPOOutcome_isFixedTieLCPOOutcome feasible profile hprofile

/-- Forgetting its fixed tie break yields an ordinary LCPO selector. -/
theorem isFixedTieLCPOSelector_isLCPOSelector
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (rule : LinearRankAggregationRule Voter n feasible)
    (hselector : IsFixedTieLCPOSelector feasible rule) :
    IsLCPOSelector feasible rule := by
  intro profile hprofile
  exact isFixedTieLCPOOutcome_isLCPOOutcome feasible profile (rule.run profile)
    (hselector profile hprofile)

/-- The fixed Copeland tie break totally orders every distinct candidate pair. -/
theorem copelandBetter_or_reverse_of_ne
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) {first second : Candidate n}
    (hne : first ≠ second) :
    CopelandBetter profile first second ∨ CopelandBetter profile second first := by
  unfold CopelandBetter
  rcases lt_trichotomy (copelandScore profile first) (copelandScore profile second) with
    hscore | hscore | hscore
  · exact Or.inr (Or.inl hscore)
  · rcases lt_trichotomy first second with horder | heq | horder
    · exact Or.inl (Or.inr ⟨hscore, horder⟩)
    · exact False.elim (hne heq)
    · exact Or.inr (Or.inr ⟨hscore.symm, horder⟩)
  · exact Or.inl (Or.inl hscore)

/--
If an elevation makes `other` beat `candidate` in fixed Copeland order, then
it already did so before the elevation.
-/
theorem copelandBetter_original_of_profileElevatesCandidate
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (original updated : RankingProfile Voter n) (voter : Voter)
    (candidate other : Candidate n)
    (helevates : ProfileElevatesCandidate original updated voter candidate)
    (hother : other ≠ candidate)
    (hbetter : CopelandBetter updated other candidate) :
    CopelandBetter original other candidate := by
  have hcandidateScore : copelandScore original candidate ≤ copelandScore updated candidate :=
    copelandScore_le_of_profileElevatesCandidate original updated voter candidate helevates
  have hotherScore : copelandScore updated other ≤ copelandScore original other :=
    copelandScore_after_le_of_profileElevatesCandidate_other
      original updated voter candidate other helevates hother
  unfold CopelandBetter at hbetter ⊢
  rcases hbetter with hstrict | ⟨hequal, horder⟩
  · exact Or.inl (lt_of_lt_of_le (lt_of_le_of_lt hcandidateScore hstrict) hotherScore)
  · have hweak : copelandScore original candidate ≤ copelandScore original other := by
      calc
        copelandScore original candidate ≤ copelandScore updated candidate := hcandidateScore
        _ = copelandScore updated other := hequal.symm
        _ ≤ copelandScore original other := hotherScore
    by_cases horiginalEqual : copelandScore original candidate = copelandScore original other
    · exact Or.inr ⟨horiginalEqual.symm, horder⟩
    · exact Or.inl (lt_of_le_of_ne hweak horiginalEqual)

/--
The winner-monotonicity component of source Theorem 4.3 for fixed-tie LCPO
outcomes.  The proof follows the paper: scores of the winner can only rise,
other scores can only fall, and the updated Pareto-feasible domain is contained
in the original domain while retaining the winner-headed original outcome.
-/
theorem isFixedTieLCPOOutcome_winnerMonotonic
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (original updated : RankingProfile Voter n)
    (voter : Voter) (candidate : Candidate n)
    (originalOutcome updatedOutcome : Ranking n)
    (horiginal : IsFixedTieLCPOOutcome feasible original originalOutcome)
    (hupdated : IsFixedTieLCPOOutcome feasible updated updatedOutcome)
    (hfirst : firstChoice originalOutcome = candidate)
    (helevates : ProfileElevatesCandidate original updated voter candidate) :
    firstChoice updatedOutcome = candidate := by
  by_contra hnotFirst
  let other : Candidate n := firstChoice updatedOutcome
  have hother : other ≠ candidate := by
    intro heq
    apply hnotFirst
    simpa [other] using heq
  have horiginalRespectsUpdated : RespectsPareto updated originalOutcome :=
    respectsPareto_updated_of_respectsPareto_original_firstChoice
      original updated voter candidate helevates originalOutcome horiginal.1.2 hfirst
  have horiginalAdmissibleUpdated : ParetoFeasibleRanking feasible updated originalOutcome :=
    ⟨horiginal.1.1, horiginalRespectsUpdated⟩
  have hcandidateCanPlaceUpdated :
      CanPlaceAt feasible updated updatedOutcome 0 candidate :=
    ⟨originalOutcome, horiginalAdmissibleUpdated, by
      intro earlier hearlier
      exfalso
      exact (Nat.not_lt_zero earlier.val) hearlier, by simpa [firstChoice] using hfirst⟩
  have hnotCandidateBetter :=
    hupdated.2 0 candidate hcandidateCanPlaceUpdated
  have hbetterUpdated : CopelandBetter updated other candidate := by
    exact (copelandBetter_or_reverse_of_ne updated hother).resolve_right hnotCandidateBetter
  have hbetterOriginal : CopelandBetter original other candidate :=
    copelandBetter_original_of_profileElevatesCandidate
      original updated voter candidate other helevates hother hbetterUpdated
  have hnoOpposition : ∀ opponent, opponent ≠ candidate →
      ¬ UniversallyPreferred original opponent candidate := by
    intro opponent hopponent
    exact not_universallyPreferred_against_firstChoice_of_respectsPareto
      original originalOutcome candidate opponent horiginal.1.2 hfirst hopponent
  have hupdatedRespectsOriginal : RespectsPareto original updatedOutcome :=
    respectsPareto_original_of_respectsPareto_updated original updated voter candidate helevates
      hnoOpposition updatedOutcome hupdated.1.2
  have hupdatedAdmissibleOriginal : ParetoFeasibleRanking feasible original updatedOutcome :=
    ⟨hupdated.1.1, hupdatedRespectsOriginal⟩
  have hotherCanPlaceOriginal : CanPlaceAt feasible original originalOutcome 0 other :=
    ⟨updatedOutcome, hupdatedAdmissibleOriginal, by
      intro earlier hearlier
      exfalso
      exact (Nat.not_lt_zero earlier.val) hearlier, by simp [other]⟩
  have hbetterOriginalAt : CopelandBetter original other (originalOutcome 0) := by
    change originalOutcome 0 = candidate at hfirst
    rw [hfirst]
    exact hbetterOriginal
  exact horiginal.2 0 other hotherCanPlaceOriginal hbetterOriginalAt

/-- The winner-monotonicity component of Theorem 4.3 for a fixed-tie LCPO rule. -/
theorem fixedTieLCPOSelector_winnerMonotonic
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (rule : LinearRankAggregationRule Voter n feasible)
    (hselector : IsFixedTieLCPOSelector feasible rule) :
    WinnerMonotonic feasible rule := by
  intro original updated voter candidate horiginal hupdated hfirst helevates
  exact isFixedTieLCPOOutcome_winnerMonotonic feasible original updated voter candidate
    (rule.run original) (rule.run updated) (hselector original horiginal)
    (hselector updated hupdated) hfirst helevates

/-- Every LCPO outcome satisfies the source paper's Pareto restriction. -/
theorem isLCPOOutcome_respectsPareto
    {Voter : Type*} [Fintype Voter] {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (outcome : Ranking n)
    (houtcome : IsLCPOOutcome feasible profile outcome) :
    RespectsPareto profile outcome :=
  houtcome.1.2

/-- A Pareto-feasible top-ranked candidate is available at the first LCPO step. -/
theorem canPlaceAt_zero_of_paretoFeasibleRanking
    {Voter : Type*} {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (selectedPrefix contender : Ranking n)
    (candidate : Candidate n) (hfeasible : ParetoFeasibleRanking feasible profile contender)
    (hfirst : firstChoice contender = candidate) :
    CanPlaceAt feasible profile selectedPrefix 0 candidate := by
  refine ⟨contender, hfeasible, ?_, ?_⟩
  · intro earlier hearlier
    exfalso
    exact (Nat.not_lt_zero earlier.val) hearlier
  · simpa [firstChoice] using hfirst

/-- The first LCPO step has maximal Copeland score among admissible first choices. -/
theorem isLCPOOutcome_firstScore_maximal
    {Voter : Type*} [Fintype Voter] {n : ℕ} (feasible : Ranking n → Prop)
    (profile : RankingProfile Voter n) (outcome : Ranking n)
    (houtcome : IsLCPOOutcome feasible profile outcome) (candidate : Candidate n)
    (hcanPlace : CanPlaceAt feasible profile outcome 0 candidate) :
    copelandScore profile candidate ≤ copelandScore profile (firstChoice outcome) := by
  simpa [firstChoice] using houtcome.2 0 candidate hcanPlace

/-- A strict-majority top choice is top-ranked by at least one submitted ranking. -/
theorem exists_submittedRanking_firstChoice_of_majorityTopChoice
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (candidate : Candidate n)
    (hmajority : MajorityTopChoice profile candidate) :
    ∃ voter, firstChoice (profile voter) = candidate := by
  classical
  unfold MajorityTopChoice StrictMajority votersSatisfying at hmajority
  have hpositive : 0 < (Finset.univ.filter
      (fun voter => firstChoice (profile voter) = candidate)).card := by
    by_contra hnotpositive
    have hzero : (Finset.univ.filter
        (fun voter => firstChoice (profile voter) = candidate)).card = 0 :=
      Nat.eq_zero_of_not_pos hnotpositive
    rw [hzero] at hmajority
    omega
  obtain ⟨voter, hvoter⟩ := Finset.card_pos.mp hpositive
  refine ⟨voter, ?_⟩
  simpa only [Finset.mem_filter, Finset.mem_univ, true_and] using hvoter

/--
The majority-consistency portion of Theorem 4.3: a strict-majority top choice
is selected first by every LCPO outcome.
-/
theorem isLCPOOutcome_majorityConsistent
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (hprofile : FeasibleProfile feasible profile) (outcome : Ranking n)
    (houtcome : IsLCPOOutcome feasible profile outcome) (candidate : Candidate n)
    (hmajority : MajorityTopChoice profile candidate) :
    firstChoice outcome = candidate := by
  obtain ⟨voter, hvoter⟩ :=
    exists_submittedRanking_firstChoice_of_majorityTopChoice profile candidate hmajority
  have hinputAdmissible : ParetoFeasibleRanking feasible profile (profile voter) :=
    ⟨hprofile voter, submittedRanking_respectsPareto profile voter⟩
  have hcanPlace : CanPlaceAt feasible profile outcome 0 candidate :=
    canPlaceAt_zero_of_paretoFeasibleRanking feasible profile outcome (profile voter)
      candidate hinputAdmissible hvoter
  have hscoreLower : copelandScore profile candidate ≤
      copelandScore profile (firstChoice outcome) :=
    isLCPOOutcome_firstScore_maximal feasible profile outcome houtcome candidate hcanPlace
  have hcandidateScore : copelandScore profile candidate =
      Fintype.card (Candidate n) - 1 :=
    copelandScore_eq_numberOfOtherCandidates_of_majorityTopChoice profile candidate hmajority
  have houtcomeScore : copelandScore profile (firstChoice outcome) =
      Fintype.card (Candidate n) - 1 := by
    apply Nat.le_antisymm
    · exact copelandScore_le_numberOfOtherCandidates profile (firstChoice outcome)
    · calc
        Fintype.card (Candidate n) - 1 = copelandScore profile candidate := hcandidateScore.symm
        _ ≤ copelandScore profile (firstChoice outcome) := hscoreLower
  exact copelandScore_eq_max_implies_eq_majorityTopChoice profile candidate
    (firstChoice outcome) hmajority houtcomeScore

/-- Every unanimous comparison is, for a nonempty electorate, a strict-majority comparison. -/
theorem strictMajorityPrefers_of_universallyPreferred
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (profile : RankingProfile Voter n) {first second : Candidate n}
    (hunanimous : UniversallyPreferred profile first second) :
    StrictMajorityPrefers profile first second := by
  classical
  unfold StrictMajorityPrefers StrictMajority votersSatisfying
  have hfilter : Finset.univ.filter
      (fun voter => StrictlyPrefers (profile voter) first second) = Finset.univ :=
    Finset.filter_true_of_mem fun voter _ => hunanimous voter
  rw [hfilter, Finset.card_univ]
  have hpositive : 0 < Fintype.card Voter := Fintype.card_pos_iff.2 inferInstance
  omega

/-- A feasible PMC ranking automatically satisfies every Pareto restriction. -/
theorem pairwiseMajorityRanking_respectsPareto
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n)
    (hmajority : IsPairwiseMajorityRanking profile ranking) :
    RespectsPareto profile ranking := by
  intro first second hunanimous
  exact (hmajority first second).mpr
    (strictMajorityPrefers_of_universallyPreferred profile hunanimous)

/-- A ranking's strict-preference winners are the image of the positions below it. -/
theorem strictPreferenceWinners_eq_image_Ioi
    {n : ℕ} (ranking : Ranking n) (candidate : Candidate n) :
    strictPreferenceWinnerSet ranking candidate =
      (Finset.Ioi (rankOf ranking candidate)).image ranking := by
  classical
  unfold strictPreferenceWinnerSet
  ext opponent
  simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_image]
  constructor
  · intro hpreference
    refine ⟨rankOf ranking opponent, ?_, ?_⟩
    · simpa [StrictlyPrefers] using hpreference
    · simp [rankOf]
  · rintro ⟨position, hposition, hpositionEq⟩
    subst opponent
    simpa [StrictlyPrefers, rankOf] using hposition

/-- The number of candidates below a ranking position. -/
theorem strictPreferenceWinner_count
    {n : ℕ} (ranking : Ranking n) (candidate : Candidate n) :
    (strictPreferenceWinnerSet ranking candidate).card =
      Fintype.card (Candidate n) - 1 - (rankOf ranking candidate).val := by
  classical
  rw [strictPreferenceWinners_eq_image_Ioi]
  calc
    ((Finset.Ioi (rankOf ranking candidate)).image ranking).card =
        (Finset.Ioi (rankOf ranking candidate)).card :=
      Finset.card_image_of_injective _ ranking.injective
    _ = Fintype.card (Candidate n) - 1 - (rankOf ranking candidate).val := by
      simpa [Candidate] using Fin.card_Ioi (rankOf ranking candidate)

/-- In a PMC ranking, Copeland score is exactly the number of lower positions. -/
theorem copelandScore_eq_rankedBelow_of_pairwiseMajorityRanking
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n)
    (hmajority : IsPairwiseMajorityRanking profile ranking) (candidate : Candidate n) :
    copelandScore profile candidate =
      Fintype.card (Candidate n) - 1 - (rankOf ranking candidate).val := by
  classical
  rw [copelandScore]
  have hfilter : Finset.univ.filter
      (fun opponent => StrictMajorityPrefers profile candidate opponent) =
      strictPreferenceWinnerSet ranking candidate := by
    ext opponent
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    rw [strictPreferenceWinnerSet]
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact (hmajority candidate opponent).symm
  rw [hfilter, strictPreferenceWinner_count]

/--
Under a PMC ranking, no candidate at or below a position can share the
Copeland score of the candidate at that position unless it is that candidate.
-/
theorem eq_of_copelandScore_eq_at_rank_of_pairwiseMajorityRanking
    {Voter : Type*} [Fintype Voter] {n : ℕ}
    (profile : RankingProfile Voter n) (ranking : Ranking n)
    (hmajority : IsPairwiseMajorityRanking profile ranking)
    (position : Candidate n) (candidate : Candidate n)
    (hatOrBelow : position ≤ rankOf ranking candidate)
    (hscore : copelandScore profile candidate = copelandScore profile (ranking position)) :
    candidate = ranking position := by
  have hscoreCandidate :=
    copelandScore_eq_rankedBelow_of_pairwiseMajorityRanking profile ranking hmajority candidate
  have hscorePosition :=
    copelandScore_eq_rankedBelow_of_pairwiseMajorityRanking profile ranking hmajority
      (ranking position)
  have hpositionRank : rankOf ranking (ranking position) = position := by
    simp [rankOf]
  rw [hscoreCandidate, hscorePosition, hpositionRank] at hscore
  have hcard : Fintype.card (Candidate n) = n + 2 := by simp [Candidate]
  have hcandidateLt : (rankOf ranking candidate).val < n + 2 :=
    (rankOf ranking candidate).isLt
  have hpositionLt : position.val < n + 2 := position.isLt
  have hrankEq : rankOf ranking candidate = position := by
    apply Fin.ext
    omega
  calc
    candidate = ranking (rankOf ranking candidate) := by simp [rankOf]
    _ = ranking position := congrArg ranking hrankEq

/--
The PMC portion of Theorem 4.3.  A feasible ranking that realizes every
strict majority is selected in full, position by position, by LCPO.
-/
theorem isLCPOOutcome_pairwiseMajorityConsistent
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (profile : RankingProfile Voter n)
    (outcome majorityRanking : Ranking n) (hfeasible : feasible majorityRanking)
    (hmajority : IsPairwiseMajorityRanking profile majorityRanking)
    (houtcome : IsLCPOOutcome feasible profile outcome) :
    outcome = majorityRanking := by
  have hmajorityAdmissible : ParetoFeasibleRanking feasible profile majorityRanking :=
    ⟨hfeasible, pairwiseMajorityRanking_respectsPareto profile majorityRanking hmajority⟩
  apply Equiv.ext
  intro position
  have hall : ∀ (index : ℕ) (hindex : index < n + 2),
      outcome ⟨index, hindex⟩ = majorityRanking ⟨index, hindex⟩ := by
    intro index hindex
    induction index using Nat.strong_induction_on with
    | h index ih =>
      let current : Candidate n := ⟨index, hindex⟩
      change outcome current = majorityRanking current
      have hprefix : AgreesBefore outcome majorityRanking current := by
        intro earlier hearlier
        have hearlierEq := ih earlier.val hearlier earlier.isLt
        simpa [current] using hearlierEq.symm
      have hcanPlace : CanPlaceAt feasible profile outcome current
          (majorityRanking current) :=
        ⟨majorityRanking, hmajorityAdmissible, hprefix, rfl⟩
      have hscoreLower : copelandScore profile (majorityRanking current) ≤
          copelandScore profile (outcome current) :=
        houtcome.2 current (majorityRanking current) hcanPlace
      have hatOrBelow : current ≤ rankOf majorityRanking (outcome current) := by
        apply le_of_not_gt
        intro hlt
        have hpref := hprefix (rankOf majorityRanking (outcome current)) hlt
        have hrankApply : majorityRanking (rankOf majorityRanking (outcome current)) =
            outcome current := by
          simp [rankOf]
        have houtcomeEq : outcome (rankOf majorityRanking (outcome current)) =
            outcome current := by
          exact hpref.symm.trans hrankApply
        have hpositionEq : rankOf majorityRanking (outcome current) = current :=
          outcome.injective houtcomeEq
        exact (ne_of_lt hlt) hpositionEq
      have hscoreUpper : copelandScore profile (outcome current) ≤
          copelandScore profile (majorityRanking current) := by
        rw [copelandScore_eq_rankedBelow_of_pairwiseMajorityRanking profile majorityRanking
          hmajority (outcome current)]
        rw [copelandScore_eq_rankedBelow_of_pairwiseMajorityRanking profile majorityRanking
          hmajority (majorityRanking current)]
        have hcurrentRank : rankOf majorityRanking (majorityRanking current) = current := by
          simp [rankOf]
        rw [hcurrentRank]
        exact Nat.sub_le_sub_left hatOrBelow (Fintype.card (Candidate n) - 1)
      have hscoreEq : copelandScore profile (outcome current) =
          copelandScore profile (majorityRanking current) :=
        Nat.le_antisymm hscoreUpper hscoreLower
      exact eq_of_copelandScore_eq_at_rank_of_pairwiseMajorityRanking profile majorityRanking
        hmajority current (outcome current) hatOrBelow hscoreEq
  simpa using hall position.val position.isLt

/-- The Pareto-optimality component of Theorem 4.3 for an LCPO selector. -/
theorem lcpoSelector_paretoOptimal
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (rule : LinearRankAggregationRule Voter n feasible)
    (hselector : IsLCPOSelector feasible rule) :
    ParetoOptimal feasible rule := by
  intro profile first second hprofile hunanimous
  exact (hselector profile hprofile).1.2 first second hunanimous

/-- The pairwise-majority-consistency component of Theorem 4.3 for LCPO. -/
theorem lcpoSelector_pairwiseMajorityConsistent
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (rule : LinearRankAggregationRule Voter n feasible)
    (hselector : IsLCPOSelector feasible rule) :
    PairwiseMajorityConsistent feasible rule := by
  intro profile majorityRanking hprofile hfeasible hmajority
  exact isLCPOOutcome_pairwiseMajorityConsistent feasible profile (rule.run profile)
    majorityRanking hfeasible hmajority (hselector profile hprofile)

/-- The majority-consistency component of Theorem 4.3 for LCPO. -/
theorem lcpoSelector_majorityConsistent
    {Voter : Type*} [Fintype Voter] [Nonempty Voter] {n : ℕ}
    (feasible : Ranking n → Prop) (rule : LinearRankAggregationRule Voter n feasible)
    (hselector : IsLCPOSelector feasible rule) :
    MajorityConsistent feasible rule := by
  intro profile candidate hprofile hmajority
  exact isLCPOOutcome_majorityConsistent feasible profile hprofile (rule.run profile)
    (hselector profile hprofile) candidate hmajority

end GeEtAl2024AlignmentAxioms
