import AppliedModelingLib.Foundations.Probability.FiniteExpectation

/-!
# Finite Bernoulli best-arm model

This file gives the finite adaptive Bernoulli model used by the `K = 1`
specialization of Zhou--Chen--Li's multiple-arm identification result.  The
source describes a bounded-budget adaptive algorithm: its next pull depends
only on the rewards previously observed, and its final output is an arm.
-/

namespace ZhouChenLi2014OptimalPACMultipleArm

open AppliedModelingLib
open scoped BigOperators

/-- A finite adaptive procedure for Bernoulli best-arm identification. -/
structure FiniteAdaptiveBernoulliBestArmProcedure (Arm : Type*) (pullBudget : ℕ) where
  pull : (round : Fin pullBudget) → (Fin round.val → Bool) → Arm
  output : (Fin pullBudget → Bool) → Arm

/-- The rewards revealed strictly before one pull. -/
def rewardPrefix {pullBudget : ℕ}
    (rewards : Fin pullBudget → Bool) (round : Fin pullBudget) :
    Fin round.val → Bool := fun earlier =>
  rewards (Fin.castLT earlier (Nat.lt_trans earlier.isLt round.isLt))

/-- The arm pulled at one round of a concrete reward trace. -/
def procedurePullAt {Arm : Type*} {pullBudget : ℕ}
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (rewards : Fin pullBudget → Bool) (round : Fin pullBudget) : Arm :=
  procedure.pull round (rewardPrefix rewards round)

/-- A real-valued Bernoulli mean assignment. -/
def ValidBernoulliMeans {Arm : Type*} (mean : Arm → ℝ) : Prop :=
  ∀ arm, mean arm ∈ Set.Icc (0 : ℝ) 1

/-- The one-step Bernoulli reward law for an arm with a valid mean. -/
noncomputable def bernoulliRewardLaw {Arm : Type*} (mean : Arm → ℝ)
    (hmean : ValidBernoulliMeans mean) (arm : Arm) : PMF Bool :=
  PMF.bernoulli ⟨mean arm, (hmean arm).1⟩ (hmean arm).2

/--
The finite adaptive reward law generated by a procedure and Bernoulli arm
means.  The recursive bind samples exactly one reward after every history-
selected arm pull.
-/
noncomputable def adaptiveBernoulliRewardPrefixLaw {Arm : Type*}
    {pullBudget : ℕ} (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) :
    (roundCount : ℕ) → (hroundCount : roundCount ≤ pullBudget) →
      PMF (Fin roundCount → Bool)
  | 0, _ => PMF.pure Fin.elim0
  | roundCount + 1, hroundCount =>
      PMF.bind
        (adaptiveBernoulliRewardPrefixLaw mean hmean procedure roundCount
          (Nat.le_of_succ_le hroundCount))
        (fun history =>
          PMF.map (fun reward => Fin.snoc history reward)
            (bernoulliRewardLaw mean hmean
              (procedure.pull ⟨roundCount, Nat.lt_of_succ_le hroundCount⟩ history)))

/-- The complete finite reward trace law for an adaptive Bernoulli procedure. -/
noncomputable def adaptiveBernoulliRewardLaw {Arm : Type*}
    {pullBudget : ℕ} (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) :
    PMF (Fin pullBudget → Bool) :=
  adaptiveBernoulliRewardPrefixLaw mean hmean procedure pullBudget (le_refl _)

/-- Restrict a finite reward trace to its first `prefixCount` coordinates. -/
def rewardTracePrefix (prefixCount extraCount : ℕ)
    (rewards : Fin (prefixCount + extraCount) → Bool) : Fin prefixCount → Bool := fun earlier =>
  rewards (Fin.castAdd extraCount earlier)

/-- Restrict a finite trace to an initial prefix using only the natural
inequality supplied by a caller. -/
def rewardTracePrefixLE (prefixCount totalCount : ℕ) (hprefix : prefixCount ≤ totalCount)
    (rewards : Fin totalCount → Bool) : Fin prefixCount → Bool := fun earlier =>
  rewards (Fin.castLE hprefix earlier)

/-- The marginal law of an adaptive reward trace's first coordinates is its
recursively defined prefix law.  Later pulls may depend on that prefix, but
their fresh rewards cannot alter its distribution. -/
theorem adaptiveBernoulliRewardPrefixLaw_map_rewardTracePrefix
    {Arm : Type*} {pullBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (prefixCount : ℕ) : ∀ extraCount (hbudget : prefixCount + extraCount ≤ pullBudget),
    (adaptiveBernoulliRewardPrefixLaw mean hmean procedure (prefixCount + extraCount) hbudget).map
      (rewardTracePrefix prefixCount extraCount) =
      adaptiveBernoulliRewardPrefixLaw mean hmean procedure prefixCount
        (Nat.le_trans (Nat.le_add_right prefixCount extraCount) hbudget) := by
  intro extraCount
  induction extraCount with
  | zero =>
      intro hbudget
      have hprefixBudget : prefixCount ≤ pullBudget := by omega
      simpa [rewardTracePrefix] using
        (PMF.map_id (adaptiveBernoulliRewardPrefixLaw mean hmean procedure
          prefixCount hprefixBudget))
  | succ extraCount ih =>
      intro hbudget
      have hpreviousBudget : prefixCount + extraCount ≤ pullBudget := by
        omega
      simp only [Nat.add_succ]
      rw [adaptiveBernoulliRewardPrefixLaw, PMF.map_bind]
      have hmap : ∀ history : Fin (prefixCount + extraCount) → Bool,
          (PMF.map (rewardTracePrefix prefixCount (extraCount + 1))
            ((bernoulliRewardLaw mean hmean
              (procedure.pull ⟨prefixCount + extraCount, Nat.lt_of_succ_le hbudget⟩ history)).map
              (fun reward => Fin.snoc history reward))) =
            PMF.pure (rewardTracePrefix prefixCount extraCount history) := by
        intro history
        rw [PMF.map_comp]
        have hfunction :
            rewardTracePrefix prefixCount (extraCount + 1) ∘ (fun reward => Fin.snoc history reward) =
              Function.const Bool (rewardTracePrefix prefixCount extraCount history) := by
          funext reward
          funext earlier
          simp only [rewardTracePrefix, Function.comp_apply, Function.const_apply]
          have hcoordinate : Fin.castAdd (extraCount + 1) earlier =
              Fin.castSucc (Fin.castAdd extraCount earlier) := by
            apply Fin.ext
            rfl
          rw [hcoordinate]
          rw [Fin.snoc_castSucc]
        rw [hfunction, PMF.map_const]
      simp_rw [hmap]
      change (adaptiveBernoulliRewardPrefixLaw mean hmean procedure
        (prefixCount + extraCount) hpreviousBudget).bind
          (PMF.pure ∘ rewardTracePrefix prefixCount extraCount) = _
      rw [PMF.bind_pure_comp]
      exact ih hpreviousBudget

/-- The prefix-marginal identity in inequality-indexed form.  This avoids a
spurious arithmetic reindexing when a source block has a fixed total length
and its usable prefix is selected by a state-dependent floor allocation. -/
theorem adaptiveBernoulliRewardPrefixLaw_map_rewardTracePrefixLE
    {Arm : Type*} {pullBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) :
    ∀ (prefixCount totalCount : ℕ) (hprefix : prefixCount ≤ totalCount)
      (htotal : totalCount ≤ pullBudget),
      (adaptiveBernoulliRewardPrefixLaw mean hmean procedure totalCount htotal).map
        (rewardTracePrefixLE prefixCount totalCount hprefix) =
        adaptiveBernoulliRewardPrefixLaw mean hmean procedure prefixCount
          (Nat.le_trans hprefix htotal) := by
  intro prefixCount totalCount
  induction totalCount generalizing prefixCount with
  | zero =>
      intro hprefix htotal
      have hzero : prefixCount = 0 := Nat.eq_zero_of_le_zero hprefix
      subst prefixCount
      have hidentity : rewardTracePrefixLE 0 0 hprefix = id := by
        funext rewards earlier
        exact Fin.elim0 earlier
      rw [hidentity, PMF.map_id]
  | succ totalCount ih =>
      intro hprefix htotal
      by_cases hfull : prefixCount = totalCount + 1
      · subst prefixCount
        have hidentity : rewardTracePrefixLE (totalCount + 1) (totalCount + 1) hprefix =
            id := by
          funext rewards earlier
          apply congrArg rewards
          apply Fin.ext
          rfl
        rw [hidentity, PMF.map_id]
      · have hprefixPrevious : prefixCount ≤ totalCount := by omega
        have htotalPrevious : totalCount ≤ pullBudget := by omega
        rw [adaptiveBernoulliRewardPrefixLaw, PMF.map_bind]
        have hmap : ∀ history : Fin totalCount → Bool,
            (PMF.map (rewardTracePrefixLE prefixCount (totalCount + 1) hprefix)
              ((bernoulliRewardLaw mean hmean
                (procedure.pull ⟨totalCount, Nat.lt_of_succ_le htotal⟩ history)).map
                (fun reward => Fin.snoc history reward))) =
              PMF.pure (rewardTracePrefixLE prefixCount totalCount hprefixPrevious history) := by
          intro history
          rw [PMF.map_comp]
          have hfunction : rewardTracePrefixLE prefixCount (totalCount + 1) hprefix ∘
              (fun reward => Fin.snoc history reward) =
              Function.const Bool
                (rewardTracePrefixLE prefixCount totalCount hprefixPrevious history) := by
            funext reward earlier
            simp only [rewardTracePrefixLE, Function.comp_apply, Function.const_apply]
            have hcoordinate : Fin.castLE hprefix earlier =
                Fin.castSucc (Fin.castLE hprefixPrevious earlier) := by
              apply Fin.ext
              rfl
            rw [hcoordinate, Fin.snoc_castSucc]
          rw [hfunction, PMF.map_const]
        simp_rw [hmap]
        change (adaptiveBernoulliRewardPrefixLaw mean hmean procedure totalCount htotalPrevious).bind
            (PMF.pure ∘ rewardTracePrefixLE prefixCount totalCount hprefixPrevious) = _
        rw [PMF.bind_pure_comp]
        exact ih prefixCount hprefixPrevious htotalPrevious

/-- The conditional law of a finite continuation after a fixed revealed
prefix.  Its coordinates are indexed relative to the continuation, while
each new arm pull is evaluated on the concatenated complete history. -/
noncomputable def adaptiveBernoulliRewardSuffixLaw {Arm : Type*}
    {pullBudget : ℕ} (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (prefixCount : ℕ) (history : Fin prefixCount → Bool) :
    (suffixCount : ℕ) → (hbudget : prefixCount + suffixCount ≤ pullBudget) →
      PMF (Fin suffixCount → Bool)
  | 0, _ => PMF.pure Fin.elim0
  | suffixCount + 1, hbudget =>
      PMF.bind
        (adaptiveBernoulliRewardSuffixLaw mean hmean procedure prefixCount history suffixCount
          (by omega))
        (fun suffix =>
          PMF.map (fun reward => Fin.snoc suffix reward)
            (bernoulliRewardLaw mean hmean
              (procedure.pull
                ⟨prefixCount + suffixCount, by omega⟩
                (Fin.append history suffix))))

/-- Appending one response to a complete prefix is the same finite trace as
appending it to the continuation and then concatenating that continuation. -/
theorem finAppend_snoc {prefixCount suffixCount : ℕ}
    (history : Fin prefixCount → Bool) (suffix : Fin suffixCount → Bool) (reward : Bool) :
    Fin.snoc (Fin.append history suffix) reward =
      Fin.append history (Fin.snoc suffix reward) := by
  funext position
  refine Fin.addCases ?_ ?_ position
  · intro earlier
    have hcast : Fin.castAdd 1 earlier = Fin.castSucc earlier := by
      apply Fin.ext
      rfl
    rw [hcast, Fin.snoc_castSucc]
    refine Fin.addCases ?_ ?_ earlier
    · intro earlier'
      have hcast' : (Fin.castAdd suffixCount earlier').castSucc =
          Fin.castAdd (suffixCount + 1) earlier' := by
        apply Fin.ext
        rfl
      rw [hcast']
      simp [Fin.append]
    · intro later'
      simp [Fin.append]
  · intro later
    have hlast : Fin.natAdd (prefixCount.add suffixCount) (0 : Fin 1) =
        Fin.last (prefixCount + suffixCount) := by
      apply Fin.ext
      rfl
    rw [show later = (0 : Fin 1) by exact Subsingleton.elim _ _, hlast]
    have hsnoc : @Fin.snoc (prefixCount + suffixCount) (fun _ => Bool)
        (Fin.append history suffix) reward (Fin.last (prefixCount + suffixCount)) = reward := by
      simp
    rw [hsnoc]
    symm
    let nextSuffix : Fin (suffixCount + 1) → Bool :=
      @Fin.snoc suffixCount (fun _ => Bool) suffix reward
    let appended : Fin (prefixCount + (suffixCount + 1)) → Bool :=
      Fin.append history nextSuffix
    change appended (Fin.last (prefixCount + suffixCount)) = reward
    have hlast' : Fin.last (prefixCount + suffixCount) =
        Fin.natAdd prefixCount (Fin.last suffixCount) := by
      apply Fin.ext
      simp
    calc
      appended (Fin.last (prefixCount + suffixCount)) =
          appended (Fin.natAdd prefixCount (Fin.last suffixCount)) :=
        congrArg appended hlast'
      _ = nextSuffix (Fin.last suffixCount) :=
        Fin.addCases_right (Fin.last suffixCount)
      _ = reward := @Fin.snoc_last suffixCount (fun _ => Bool) reward suffix

/-- An adaptive finite trace factors exactly into the law of a revealed prefix
and the continuation law conditional on that full prefix.  No independence of
the continuation from the prefix is asserted or needed. -/
theorem adaptiveBernoulliRewardPrefixLaw_eq_bind_suffix
    {Arm : Type*} {pullBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (prefixCount : ℕ) : ∀ suffixCount
      (hbudget : prefixCount + suffixCount ≤ pullBudget),
    adaptiveBernoulliRewardPrefixLaw mean hmean procedure (prefixCount + suffixCount) hbudget =
      (adaptiveBernoulliRewardPrefixLaw mean hmean procedure prefixCount (by omega)).bind
        (fun history =>
          (adaptiveBernoulliRewardSuffixLaw mean hmean procedure prefixCount history
            suffixCount hbudget).map (Fin.append history)) := by
  intro suffixCount
  induction suffixCount with
  | zero =>
      intro hbudget
      simp only [Nat.add_zero] at ⊢
      simp only [adaptiveBernoulliRewardSuffixLaw, PMF.pure_map]
      have happend : ∀ history : Fin prefixCount → Bool,
          Fin.append history Fin.elim0 = history := by
        intro history
        rw [Fin.append_elim0]
        rfl
      simp_rw [happend]
      rw [PMF.bind_pure]
  | succ suffixCount ih =>
      intro hbudget
      have hprevious : prefixCount + suffixCount ≤ pullBudget := by omega
      change adaptiveBernoulliRewardPrefixLaw mean hmean procedure
        ((prefixCount + suffixCount) + 1) _ = _
      rw [adaptiveBernoulliRewardPrefixLaw, ih hprevious]
      simp only [adaptiveBernoulliRewardSuffixLaw]
      rw [PMF.bind_bind]
      apply congrArg (fun continuation =>
        (adaptiveBernoulliRewardPrefixLaw mean hmean procedure prefixCount (by omega)).bind
          continuation)
      funext history
      rw [PMF.bind_map, PMF.map_bind]
      apply congrArg (fun continuation =>
        (adaptiveBernoulliRewardSuffixLaw mean hmean procedure prefixCount history suffixCount
          hprevious).bind continuation)
      funext suffix
      rw [PMF.map_comp]
      have hmap :
          (fun reward : Bool =>
            @Fin.snoc (prefixCount + suffixCount) (fun _ => Bool)
              (Fin.append history suffix) reward) =
            (fun reward : Bool =>
              Fin.append history
                (@Fin.snoc suffixCount (fun _ => Bool) suffix reward)) := by
        funext reward
        exact finAppend_snoc history suffix reward
      change PMF.map (fun reward : Bool =>
        @Fin.snoc (prefixCount + suffixCount) (fun _ => Bool)
          (Fin.append history suffix) reward)
          (bernoulliRewardLaw mean hmean
            (procedure.pull ⟨prefixCount + suffixCount, by omega⟩
              (Fin.append history suffix))) = _
      rw [hmap]
      rw [show (Fin.append history) ∘ (fun reward : Bool =>
        @Fin.snoc suffixCount (fun _ => Bool) suffix reward) =
          (fun reward : Bool => Fin.append history
            (@Fin.snoc suffixCount (fun _ => Bool) suffix reward)) by rfl]

/-- Equal history-indexed pull decisions induce equal finite reward-prefix
laws; the output field of a best-arm procedure is irrelevant to this fact. -/
theorem adaptiveBernoulliRewardPrefixLaw_congr_pulls
    {Arm : Type*} {pullBudget : ℕ} (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (first second : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (hpull : ∀ (round : Fin pullBudget) (history : Fin round.val → Bool),
      first.pull round history = second.pull round history) :
    ∀ (roundCount : ℕ) (hroundCount : roundCount ≤ pullBudget),
      adaptiveBernoulliRewardPrefixLaw mean hmean first roundCount hroundCount =
        adaptiveBernoulliRewardPrefixLaw mean hmean second roundCount hroundCount := by
  intro roundCount
  induction roundCount with
  | zero =>
      intro _
      rfl
  | succ roundCount ih =>
      intro hroundCount
      rw [adaptiveBernoulliRewardPrefixLaw, adaptiveBernoulliRewardPrefixLaw,
        ih (Nat.le_of_succ_le hroundCount)]
      congr 1
      funext history
      rw [hpull]

/-- Two procedures with different total horizons have the same reward law on
any common finite prefix when all pull decisions on that prefix agree. -/
theorem adaptiveBernoulliRewardPrefixLaw_congr_pulls_prefix
    {Arm : Type*} {firstBudget secondBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (first : FiniteAdaptiveBernoulliBestArmProcedure Arm firstBudget)
    (second : FiniteAdaptiveBernoulliBestArmProcedure Arm secondBudget) :
    ∀ (roundCount : ℕ) (hfirst : roundCount ≤ firstBudget) (hsecond : roundCount ≤ secondBudget),
      (∀ (round : Fin roundCount) (history : Fin round.val → Bool),
        first.pull ⟨round.val, Nat.lt_of_lt_of_le round.isLt hfirst⟩ history =
          second.pull ⟨round.val, Nat.lt_of_lt_of_le round.isLt hsecond⟩ history) →
      adaptiveBernoulliRewardPrefixLaw mean hmean first roundCount hfirst =
        adaptiveBernoulliRewardPrefixLaw mean hmean second roundCount hsecond := by
  intro roundCount
  induction roundCount with
  | zero =>
      intro _ _ _
      rfl
  | succ roundCount ih =>
      intro hfirst hsecond hpull
      rw [adaptiveBernoulliRewardPrefixLaw, adaptiveBernoulliRewardPrefixLaw,
        ih (Nat.le_of_succ_le hfirst) (Nat.le_of_succ_le hsecond) (by
          intro round history
          simpa using hpull round.castSucc history)]
      congr 1
      funext history
      have hpullLast :
          first.pull ⟨roundCount, Nat.lt_of_succ_le hfirst⟩ history =
            second.pull ⟨roundCount, Nat.lt_of_succ_le hsecond⟩ history := by
        simpa using hpull (Fin.last roundCount) history
      rw [hpullLast]

/-- The adaptive procedure induced after fixing a revealed prefix.  Its
remaining pull at relative time `r` evaluates the original procedure on the
concatenation of that fixed prefix and the relative reward history. -/
noncomputable def adaptiveBernoulliContinuationProcedure
    {Arm : Type*} {pullBudget : ℕ}
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (prefixCount : ℕ) (hprefix : prefixCount ≤ pullBudget)
    (history : Fin prefixCount → Bool) :
    FiniteAdaptiveBernoulliBestArmProcedure Arm (pullBudget - prefixCount) where
  pull := fun round suffix =>
    procedure.pull ⟨prefixCount + round.val, by omega⟩
      (Fin.append history suffix)
  output := fun _ => procedure.output (fun _ => false)

/-- The conditional suffix law is exactly the corresponding prefix law of
the continuation procedure. -/
theorem adaptiveBernoulliRewardSuffixLaw_eq_continuationPrefix
    {Arm : Type*} {pullBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget)
    (prefixCount suffixCount : ℕ) (history : Fin prefixCount → Bool)
    (hbudget : prefixCount + suffixCount ≤ pullBudget) :
    adaptiveBernoulliRewardSuffixLaw mean hmean procedure prefixCount history suffixCount hbudget =
      adaptiveBernoulliRewardPrefixLaw mean hmean
        (adaptiveBernoulliContinuationProcedure procedure prefixCount (by omega) history)
        suffixCount (by omega) := by
  induction suffixCount with
  | zero =>
      simp [adaptiveBernoulliRewardSuffixLaw, adaptiveBernoulliRewardPrefixLaw]
  | succ suffixCount ih =>
      rw [adaptiveBernoulliRewardSuffixLaw, adaptiveBernoulliRewardPrefixLaw]
      rw [ih (by omega)]
      rfl

/-- A returned arm is `epsilon`-PAC when it is within `epsilon` of every mean. -/
def EpsilonPACBestArm {Arm : Type*} (mean : Arm → ℝ) (epsilon : ℝ) (selected : Arm) : Prop :=
  ∀ competitor, mean competitor - epsilon ≤ mean selected

/-- Enlarging the allowed error preserves an epsilon-PAC best-arm certificate. -/
theorem epsilonPACBestArm_mono {Arm : Type*} (mean : Arm → ℝ)
    {epsilon epsilon' : ℝ} (selected : Arm)
    (hepsilon : epsilon ≤ epsilon') :
    EpsilonPACBestArm mean epsilon selected → EpsilonPACBestArm mean epsilon' selected := by
  intro hpac competitor
  exact (sub_le_sub_left hepsilon (mean competitor)).trans (hpac competitor)

/-- The success predicate of a finite best-arm procedure on a reward trace. -/
def finiteBestArmSuccess {Arm : Type*} {pullBudget : ℕ} (mean : Arm → ℝ)
    (epsilon : ℝ) (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) :
    (Fin pullBudget → Bool) → Prop := fun rewards =>
  EpsilonPACBestArm mean epsilon (procedure.output rewards)

/-- The exact finite success probability of a best-arm procedure. -/
noncomputable def finiteBestArmSuccessProbability {Arm : Type*}
    {pullBudget : ℕ} (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean)
    (epsilon : ℝ) (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) : ℝ := by
  classical
  letI : DecidablePred (finiteBestArmSuccess mean epsilon procedure) := Classical.decPred _
  exact pmfProb (adaptiveBernoulliRewardLaw mean hmean procedure)
    (finiteBestArmSuccess mean epsilon procedure)

/-- A finite Bernoulli procedure is `epsilon`-PAC with failure at most `delta`. -/
def FinitePACBestArmGuarantee {Arm : Type*} {pullBudget : ℕ}
    (mean : Arm → ℝ) (hmean : ValidBernoulliMeans mean) (epsilon delta : ℝ)
    (procedure : FiniteAdaptiveBernoulliBestArmProcedure Arm pullBudget) : Prop :=
  1 - delta ≤ finiteBestArmSuccessProbability mean hmean epsilon procedure

end ZhouChenLi2014OptimalPACMultipleArm
