import AppliedModelingLib.Learning.OutcomeMonotoneCost

/-!
# Acceptance-favoring strategic responses and outcome thresholds

This module separates two reusable layers of strategic classification.

* A binary strategic response needs only nonnegative manipulation cost and
  zero cost for staying put.  The response convention favors an accepted
  utility maximizer at a rejection/acceptance tie, matching the convention in
  Milli--Miller--Dragan--Hardt (2019).
* Outcome-monotone cost then implies that an arbitrary nonempty acceptance set
  has the same minimum manipulation burden as the likelihood threshold at its
  least-likelihood accepted feature.

The distinction is economically useful: the tie convention is behavioral,
whereas threshold reduction is a consequence of the cost primitives.  No
generic ``no exact unit-cost tie'' assumption is needed.
-/

namespace AppliedModelingLib

/-- The usual `0/1` benefit generated by a deterministic binary classifier. -/
def binaryClassifierScore {Feature : Type*}
    (classifier : BinaryClassifier Feature) (feature : Feature) : ℝ :=
  if classifier feature then 1 else 0

/-- An accepted strategic best response exists for this initial feature. -/
def HasAcceptedStrategicBestResponse {Feature : Type*}
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial : Feature) : Prop :=
  ∃ chosen, classifier chosen = true ∧
    IsStrategicBestResponse (binaryClassifierScore classifier) cost initial chosen

/--
The source response convention: stay put when already accepted; otherwise use
an accepted maximizer whenever one exists, including at exact utility ties;
and stay put when no accepted maximizer exists.
-/
def IsAcceptanceFavoringStrategicBestResponse {Feature : Type*}
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial chosen : Feature) : Prop :=
  IsStrategicBestResponse (binaryClassifierScore classifier) cost initial chosen ∧
    (classifier initial = true → chosen = initial) ∧
    (¬ HasAcceptedStrategicBestResponse classifier cost initial → chosen = initial) ∧
    (classifier initial = false →
      HasAcceptedStrategicBestResponse classifier cost initial →
        classifier chosen = true)

/-- Canonical acceptance-favoring response on a finite feature space. -/
noncomputable def acceptanceFavoringStrategicBestResponse
    {Feature : Type*} [Fintype Feature]
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial : Feature) : Feature := by
  classical
  exact if hinitial : classifier initial = true then initial
    else if haccepted : HasAcceptedStrategicBestResponse classifier cost initial then
      Classical.choose haccepted
    else initial

/-- An accepted individual optimally stays put under nonnegative, self-zero cost. -/
theorem isStrategicBestResponse_self_of_classifier_eq_true
    {Feature : Type*} (classifier : BinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (initial : Feature)
    (hnonneg : ∀ first second, 0 ≤ cost first second)
    (hself : ∀ feature, cost feature feature = 0)
    (hinitial : classifier initial = true) :
    IsStrategicBestResponse (binaryClassifierScore classifier) cost initial initial := by
  intro action
  cases haction : classifier action
  · simp [strategicUtility, binaryClassifierScore, hinitial, haction, hself initial]
    linarith [hnonneg initial action]
  · simp [strategicUtility, binaryClassifierScore, hinitial, haction, hself initial,
      hnonneg initial action]

/-- If no accepted maximizer exists, a rejected individual optimally stays put. -/
theorem isStrategicBestResponse_self_of_classifier_eq_false_of_no_accepted
    {Feature : Type*} [Fintype Feature]
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial : Feature)
    (hnonneg : ∀ first second, 0 ≤ cost first second)
    (hself : ∀ feature, cost feature feature = 0)
    (hinitial : classifier initial = false)
    (haccepted : ¬ HasAcceptedStrategicBestResponse classifier cost initial) :
    IsStrategicBestResponse (binaryClassifierScore classifier) cost initial initial := by
  classical
  let selected := selectedStrategicBestResponse
    (binaryClassifierScore classifier) cost initial
  have hselected :
      IsStrategicBestResponse (binaryClassifierScore classifier) cost initial selected :=
    selectedStrategicBestResponse_spec
      (binaryClassifierScore classifier) cost initial
  have hselectedFalse : classifier selected = false := by
    by_contra hnot
    have htrue : classifier selected = true := Bool.eq_true_of_not_eq_false hnot
    exact haccepted ⟨selected, htrue, hselected⟩
  intro action
  calc
    strategicUtility (binaryClassifierScore classifier) cost initial action ≤
        strategicUtility (binaryClassifierScore classifier) cost initial selected :=
      hselected action
    _ ≤ 0 := by
      simp [strategicUtility, binaryClassifierScore, hselectedFalse,
        hnonneg initial selected]
    _ = strategicUtility (binaryClassifierScore classifier) cost initial initial := by
      simp [strategicUtility, binaryClassifierScore, hinitial, hself initial]

/-- The canonical response realizes the acceptance-favoring source convention. -/
theorem acceptanceFavoringStrategicBestResponse_spec
    {Feature : Type*} [Fintype Feature]
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial : Feature)
    (hnonneg : ∀ first second, 0 ≤ cost first second)
    (hself : ∀ feature, cost feature feature = 0) :
    IsAcceptanceFavoringStrategicBestResponse classifier cost initial
      (acceptanceFavoringStrategicBestResponse classifier cost initial) := by
  classical
  by_cases hinitial : classifier initial = true
  · have hresponse :
        acceptanceFavoringStrategicBestResponse classifier cost initial = initial := by
      simp [acceptanceFavoringStrategicBestResponse, hinitial]
    rw [hresponse]
    refine ⟨isStrategicBestResponse_self_of_classifier_eq_true
      classifier cost initial hnonneg hself hinitial, fun _ => rfl, fun _ => rfl, ?_⟩
    intro hfalse
    exact (Bool.false_ne_true (hinitial.symm.trans hfalse).symm).elim
  · have hinitialFalse : classifier initial = false :=
      Bool.eq_false_of_not_eq_true hinitial
    by_cases haccepted : HasAcceptedStrategicBestResponse classifier cost initial
    · have hresponse :
          acceptanceFavoringStrategicBestResponse classifier cost initial =
            Classical.choose haccepted := by
        simp [acceptanceFavoringStrategicBestResponse, hinitial, haccepted]
      rw [hresponse]
      have hchosen := Classical.choose_spec haccepted
      refine ⟨hchosen.2, ?_, ?_, ?_⟩
      · intro htrue
        exact (hinitial htrue).elim
      · intro hno
        exact (hno haccepted).elim
      · intro _ _
        exact hchosen.1
    · have hresponse :
          acceptanceFavoringStrategicBestResponse classifier cost initial = initial := by
        simp [acceptanceFavoringStrategicBestResponse, hinitial, haccepted]
      rw [hresponse]
      refine ⟨
        isStrategicBestResponse_self_of_classifier_eq_false_of_no_accepted
          classifier cost initial hnonneg hself hinitialFalse haccepted,
        fun htrue => (hinitial htrue).elim, fun _ => rfl, ?_⟩
      intro _ hexists
      exact (haccepted hexists).elim

/--
Under the source tie convention, final acceptance is equivalent to the
existence of an accepted action whose manipulation cost is at most the unit
classification reward. The selected response is itself a global best response,
so no finiteness or separate attainment premise is required.
-/
theorem IsAcceptanceFavoringStrategicBestResponse.accepted_iff_exists_cost_le_one
    {Feature : Type*}
    {classifier : BinaryClassifier Feature} {cost : Feature → Feature → ℝ}
    {initial chosen : Feature}
    (hresponse :
      IsAcceptanceFavoringStrategicBestResponse classifier cost initial chosen)
    (hnonneg : ∀ first second, 0 ≤ cost first second)
    (hself : ∀ feature, cost feature feature = 0) :
    classifier chosen = true ↔
      ∃ action, classifier action = true ∧ cost initial action ≤ 1 := by
  constructor
  · intro hchosen
    by_cases hinitial : classifier initial = true
    · exact ⟨initial, hinitial, by simp [hself initial]⟩
    · refine ⟨chosen, hchosen, ?_⟩
      have hinitialFalse : classifier initial = false :=
        Bool.eq_false_of_not_eq_true hinitial
      have hbest := hresponse.1 initial
      simp [strategicUtility, binaryClassifierScore, hinitialFalse, hchosen,
        hself initial] at hbest
      linarith
  · rintro ⟨action, haction, hcost⟩
    by_cases hinitial : classifier initial = true
    · rw [hresponse.2.1 hinitial]
      exact hinitial
    · have hinitialFalse : classifier initial = false :=
        Bool.eq_false_of_not_eq_true hinitial
      let selected := chosen
      have hselected : IsStrategicBestResponse
          (binaryClassifierScore classifier) cost initial selected := hresponse.1
      have haccepted : HasAcceptedStrategicBestResponse classifier cost initial := by
        by_cases hselectedAccepted : classifier selected = true
        · exact ⟨selected, hselectedAccepted, hselected⟩
        · have hselectedFalse : classifier selected = false :=
            Bool.eq_false_of_not_eq_true hselectedAccepted
          refine ⟨action, haction, ?_⟩
          intro alternative
          calc
            strategicUtility (binaryClassifierScore classifier) cost initial alternative ≤
                strategicUtility (binaryClassifierScore classifier) cost initial selected :=
              hselected alternative
            _ ≤ 0 := by
              simp [strategicUtility, binaryClassifierScore, hselectedFalse,
                hnonneg initial selected]
            _ ≤ strategicUtility (binaryClassifierScore classifier) cost initial action := by
              simp [strategicUtility, binaryClassifierScore, haction]
              linarith
      exact hresponse.2.2.2 hinitialFalse haccepted

/-- Minimum accepted manipulation cost is at most a bound exactly when some accepted action is. -/
theorem individualBurden_le_iff_exists_accepted_cost_le
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (cost : Feature → Feature → ℝ) (classifier : BinaryClassifier Feature)
    (initial : Feature) (haccepted : (acceptedFeatures classifier).Nonempty)
    (bound : ℝ) :
    individualBurden cost classifier initial haccepted ≤ bound ↔
      ∃ action, classifier action = true ∧ cost initial action ≤ bound := by
  classical
  constructor
  · intro hbound
    have hminimumMem :
        ((acceptedFeatures classifier).image (cost initial)).min'
            (haccepted.image (cost initial)) ∈
          (acceptedFeatures classifier).image (cost initial) :=
      Finset.min'_mem _ _
    obtain ⟨action, haction, hcost⟩ := Finset.mem_image.mp hminimumMem
    refine ⟨action, ?_, ?_⟩
    · simpa [acceptedFeatures] using haction
    · rw [hcost]
      exact hbound
  · rintro ⟨action, haction, hcost⟩
    calc
      individualBurden cost classifier initial haccepted ≤ cost initial action := by
        apply Finset.min'_le
        apply Finset.mem_image_of_mem
        simpa [acceptedFeatures] using haction
      _ ≤ bound := hcost

/-- The canonical source response accepts exactly when individual burden is at most one. -/
theorem acceptanceFavoringStrategicBestResponse_accepts_iff_individualBurden_le_one
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (classifier : BinaryClassifier Feature) (cost : Feature → Feature → ℝ)
    (initial : Feature) (haccepted : (acceptedFeatures classifier).Nonempty)
    (hnonneg : ∀ first second, 0 ≤ cost first second)
    (hself : ∀ feature, cost feature feature = 0) :
    classifier (acceptanceFavoringStrategicBestResponse classifier cost initial) = true ↔
      individualBurden cost classifier initial haccepted ≤ 1 := by
  rw [
    (acceptanceFavoringStrategicBestResponse_spec
      classifier cost initial hnonneg hself).accepted_iff_exists_cost_le_one
      hnonneg hself,
    individualBurden_le_iff_exists_accepted_cost_le]

/-- Canonical classifier that accepts exactly above a weak likelihood threshold. -/
noncomputable def likelihoodThresholdClassifier {Feature : Type*}
    (likelihood : Feature → ℝ) (threshold : ℝ) : BinaryClassifier Feature :=
  fun feature => decide (threshold ≤ likelihood feature)

@[simp] theorem likelihoodThresholdClassifier_eq_true_iff
    {Feature : Type*} (likelihood : Feature → ℝ) (threshold : ℝ) (feature : Feature) :
    likelihoodThresholdClassifier likelihood threshold feature = true ↔
      threshold ≤ likelihood feature := by
  simp [likelihoodThresholdClassifier]

/-- An outcome-monotone cost is nonnegative. -/
theorem IsOutcomeMonotoneCost.cost_nonneg
    {Feature : Type*} {likelihood : Feature → ℝ}
    {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost) (initial final : Feature) :
    0 ≤ cost initial final :=
  hcost.1 initial final

/-- Staying at the same feature has zero outcome-monotone cost. -/
theorem IsOutcomeMonotoneCost.cost_self
    {Feature : Type*} {likelihood : Feature → ℝ}
    {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost) (feature : Feature) :
    cost feature feature = 0 := by
  apply le_antisymm
  · apply le_of_not_gt
    simpa using (hcost.2.1 feature feature).not.mpr (lt_irrefl _)
  · exact hcost.cost_nonneg feature feature

/-- A feature attaining the minimum likelihood in a nonempty acceptance set exists. -/
theorem exists_accepted_feature_with_minimum_likelihood
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    ∃ feature, feature ∈ acceptedFeatures classifier ∧
      ∀ accepted, accepted ∈ acceptedFeatures classifier →
        likelihood feature ≤ likelihood accepted := by
  classical
  have hminimumMem :
      ((acceptedFeatures classifier).image likelihood).min'
          (haccepted.image likelihood) ∈
        (acceptedFeatures classifier).image likelihood :=
    Finset.min'_mem _ _
  obtain ⟨feature, hfeature, hlikelihood⟩ := Finset.mem_image.mp hminimumMem
  refine ⟨feature, hfeature, ?_⟩
  intro accepted hacceptedFeature
  rw [hlikelihood]
  exact Finset.min'_le _ _ (Finset.mem_image_of_mem likelihood hacceptedFeature)

/-- A canonically selected least-likelihood accepted feature. -/
noncomputable def leastAcceptedFeature
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) : Feature :=
  Classical.choose
    (exists_accepted_feature_with_minimum_likelihood likelihood classifier haccepted)

theorem leastAcceptedFeature_mem
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    leastAcceptedFeature likelihood classifier haccepted ∈ acceptedFeatures classifier :=
  (Classical.choose_spec
    (exists_accepted_feature_with_minimum_likelihood likelihood classifier haccepted)).1

theorem leastAcceptedFeature_likelihood_le
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty)
    (accepted : Feature) (hacceptedFeature : accepted ∈ acceptedFeatures classifier) :
    likelihood (leastAcceptedFeature likelihood classifier haccepted) ≤
      likelihood accepted :=
  (Classical.choose_spec
    (exists_accepted_feature_with_minimum_likelihood likelihood classifier haccepted)).2
      accepted hacceptedFeature

/--
For outcome-monotone cost, a least-likelihood accepted feature minimizes every
individual's manipulation cost over the entire acceptance set.
-/
theorem individualBurden_eq_cost_of_minimum_accepted_likelihood
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {likelihood : Feature → ℝ} {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost)
    (classifier : BinaryClassifier Feature) (initial least : Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty)
    (hleastAccepted : least ∈ acceptedFeatures classifier)
    (hleast : ∀ accepted, accepted ∈ acceptedFeatures classifier →
      likelihood least ≤ likelihood accepted) :
    individualBurden cost classifier initial haccepted = cost initial least := by
  classical
  have hpointwise : ∀ accepted, accepted ∈ acceptedFeatures classifier →
      cost initial least ≤ cost initial accepted := by
    intro accepted hacceptedFeature
    have hlikelihood := hleast accepted hacceptedFeature
    rcases lt_or_eq_of_le hlikelihood with hlt | heq
    · by_cases hinitial : likelihood initial < likelihood least
      · exact le_of_lt ((hcost.2.2.2 initial least accepted).mpr ⟨hinitial, hlt⟩).2
      · have hzero : cost initial least = 0 := by
          apply le_antisymm
          · exact le_of_not_gt ((hcost.2.1 initial least).not.mpr hinitial)
          · exact hcost.cost_nonneg initial least
        rw [hzero]
        exact hcost.cost_nonneg initial accepted
    · exact le_of_eq (hcost.cost_eq_of_likelihood_eq_right initial heq)
  apply le_antisymm
  · apply Finset.min'_le
    exact Finset.mem_image_of_mem (cost initial) hleastAccepted
  · apply Finset.le_min'
    intro value hvalue
    obtain ⟨accepted, hacceptedFeature, hvalueEq⟩ := Finset.mem_image.mp hvalue
    rw [← hvalueEq]
    exact hpointwise accepted hacceptedFeature

/--
Higher outcome likelihood weakly lowers the burden of reaching a fixed classifier.

The proof uses Mathlib's `Finset.min'_le` and `Finset.min'_mem` from
[`Mathlib/Data/Finset/Max.lean`](https://github.com/leanprover-community/mathlib4/blob/5450b53e5ddc75d46418fabb605edbf36bd0beb6/Mathlib/Data/Finset/Max.lean)
at pinned Apache-2.0 Mathlib revision
[`5450b53e5ddc75d46418fabb605edbf36bd0beb6`](https://github.com/leanprover-community/mathlib4/commit/5450b53e5ddc75d46418fabb605edbf36bd0beb6).
No external proof or code is copied or ported.
-/
theorem individualBurden_anti_likelihood
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {likelihood : Feature → ℝ} {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost)
    (classifier : BinaryClassifier Feature) (lower higher : Feature)
    (hlikelihood : likelihood lower ≤ likelihood higher)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    individualBurden cost classifier higher haccepted ≤
      individualBurden cost classifier lower haccepted := by
  classical
  unfold individualBurden
  have hmember :
      ((acceptedFeatures classifier).image (cost lower)).min'
          (haccepted.image (cost lower)) ∈
        (acceptedFeatures classifier).image (cost lower) :=
    Finset.min'_mem _ _
  obtain ⟨accepted, hacceptedMember, hminimum⟩ := Finset.mem_image.mp hmember
  calc
    ((acceptedFeatures classifier).image (cost higher)).min'
        (haccepted.image (cost higher)) ≤ cost higher accepted :=
      Finset.min'_le ((acceptedFeatures classifier).image (cost higher))
        (cost higher accepted)
        (Finset.mem_image_of_mem (cost higher) hacceptedMember)
    _ ≤ cost lower accepted := hcost.cost_anti_left hlikelihood accepted
    _ = ((acceptedFeatures classifier).image (cost lower)).min'
        (haccepted.image (cost lower)) := hminimum

/-- The likelihood threshold placed at an arbitrary classifier's least accepted likelihood. -/
noncomputable def leastAcceptedLikelihoodThresholdClassifier
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) : BinaryClassifier Feature :=
  likelihoodThresholdClassifier likelihood
    (likelihood (leastAcceptedFeature likelihood classifier haccepted))

/-- The least accepted feature witnesses nonemptiness of its induced threshold classifier. -/
theorem leastAcceptedLikelihoodThresholdClassifier_nonempty
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (likelihood : Feature → ℝ) (classifier : BinaryClassifier Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    (acceptedFeatures
      (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)).Nonempty := by
  classical
  refine ⟨leastAcceptedFeature likelihood classifier haccepted, ?_⟩
  simp [acceptedFeatures, leastAcceptedLikelihoodThresholdClassifier]

/-- Thresholding at the least accepted likelihood preserves every individual burden. -/
theorem individualBurden_leastAcceptedLikelihoodThresholdClassifier
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {likelihood : Feature → ℝ} {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost)
    (classifier : BinaryClassifier Feature) (initial : Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    individualBurden cost classifier initial haccepted =
      individualBurden cost
        (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)
        initial
        (leastAcceptedLikelihoodThresholdClassifier_nonempty
          likelihood classifier haccepted) := by
  classical
  let least := leastAcceptedFeature likelihood classifier haccepted
  have horiginal :
      individualBurden cost classifier initial haccepted = cost initial least := by
    apply individualBurden_eq_cost_of_minimum_accepted_likelihood
      hcost classifier initial least haccepted
    · exact leastAcceptedFeature_mem likelihood classifier haccepted
    · exact leastAcceptedFeature_likelihood_le likelihood classifier haccepted
  have hthreshold :
      individualBurden cost
          (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)
          initial
          (leastAcceptedLikelihoodThresholdClassifier_nonempty
            likelihood classifier haccepted) =
        cost initial least := by
    apply individualBurden_eq_cost_of_minimum_accepted_likelihood
      hcost
      (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)
      initial least
      (leastAcceptedLikelihoodThresholdClassifier_nonempty
        likelihood classifier haccepted)
    · simp [least, acceptedFeatures, leastAcceptedLikelihoodThresholdClassifier]
    · intro accepted hacceptedFeature
      simpa [least, acceptedFeatures, leastAcceptedLikelihoodThresholdClassifier] using
        hacceptedFeature
  exact horiginal.trans hthreshold.symm

/--
The canonical acceptance-favoring responses to a classifier and to its least-
accepted-likelihood threshold produce the same binary decision.
-/
theorem acceptanceFavoringResponse_preserved_by_leastAcceptedLikelihoodThreshold
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {likelihood : Feature → ℝ} {cost : Feature → Feature → ℝ}
    (hcost : IsOutcomeMonotoneCost likelihood cost)
    (classifier : BinaryClassifier Feature) (initial : Feature)
    (haccepted : (acceptedFeatures classifier).Nonempty) :
    classifier (acceptanceFavoringStrategicBestResponse classifier cost initial) =
      leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted
        (acceptanceFavoringStrategicBestResponse
          (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)
          cost initial) := by
  apply Bool.eq_iff_iff.mpr
  rw [
    acceptanceFavoringStrategicBestResponse_accepts_iff_individualBurden_le_one
      classifier cost initial haccepted hcost.cost_nonneg hcost.cost_self,
    acceptanceFavoringStrategicBestResponse_accepts_iff_individualBurden_le_one
      (leastAcceptedLikelihoodThresholdClassifier likelihood classifier haccepted)
      cost initial
      (leastAcceptedLikelihoodThresholdClassifier_nonempty
        likelihood classifier haccepted)
      hcost.cost_nonneg hcost.cost_self,
    individualBurden_leastAcceptedLikelihoodThresholdClassifier
      hcost classifier initial haccepted]

end AppliedModelingLib
