import GHKR22BiasBounties.TernaryCSC
import AppliedModelingLib.Learning.Statistics.VCGeneralization
import AppliedModelingLib.Learning.Statistics.ThresholdCompositionVC

/-!
# VC control for list-update certificate classes

Lemma 15 concerns the signed certificate score for a fixed current binary
model and varying `(group, replacement)` pair.  That score is exactly the
difference between the zero-one losses of the current model and its list
update.  This file supplies the missing combinatorial bridge: on every finite
sample, a list-update trace is determined by one group trace and one model
trace.  Sauer--Shelah therefore gives the product growth bound required by the
paper's `\widetilde O(d_G+d_H)` statement.
-/

namespace GHKR22BiasBounties

noncomputable section

open scoped BigOperators
open AppliedModelingLib.Statistics
open AppliedModelingLib Probability
open MeasureTheory

/-- Binary models obtainable by one list update of `current` using `G × H`. -/
def ListUpdateClass {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool)) :
    Set (BinaryClassifier X) :=
  {updated | ∃ g ∈ G, ∃ h ∈ H, updated = listUpdate current g h}

/-- The output labeling determined by a group trace and a replacement trace. -/
noncomputable def listUpdateTrace {X : Type*} (current : Model X Bool)
    (sample : Finset X) (groupLabels replacementLabels : Finset sample) :
    Finset sample := by
  classical
  exact sample.attach.filter fun point =>
    if point ∈ groupLabels then point ∈ replacementLabels
    else current point.1 = true

/-- A concrete list update realizes the trace obtained from its two component
traces. -/
theorem listUpdateTrace_eq_binaryClassifierTrace
    {X : Type*} (current : Model X Bool) (sample : Finset X)
    (g : Group X) (h : Model X Bool) :
    listUpdateTrace current sample
        (binaryClassifierTrace g sample) (binaryClassifierTrace h sample) =
      binaryClassifierTrace (listUpdate current g h) sample := by
  classical
  apply Finset.ext
  intro point
  cases hg : g point.1 <;>
    simp [listUpdateTrace, binaryClassifierTrace, listUpdate, hg]

/-- All traces generated by pairs of realized group and replacement traces. -/
noncomputable def listUpdateTraceFamily {X : Type*}
    (current : Model X Bool) (G : Set (Group X)) (H : Set (Model X Bool))
    (sample : Finset X) : Finset (Finset sample) := by
  classical
  exact ((binaryTrace G sample).product (binaryTrace H sample)).image
    (fun traces => listUpdateTrace current sample traces.1 traces.2)

/-- Every trace of the list-update class belongs to the component-trace
product family. -/
theorem binaryTrace_listUpdateClass_subset_traceFamily
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool)) (sample : Finset X) :
    binaryTrace (ListUpdateClass current G H) sample ⊆
      listUpdateTraceFamily current G H sample := by
  classical
  intro labels hlabels
  have hrealized := (Finset.mem_filter.mp hlabels).2
  rcases hrealized with ⟨updated, hupdated, hlabelsRealized⟩
  rcases hupdated with ⟨g, hg, h, hh, rfl⟩
  let groupLabels := binaryClassifierTrace g sample
  let replacementLabels := binaryClassifierTrace h sample
  have hgroupLabels : groupLabels ∈ binaryTrace G sample := by
    exact binaryClassifierTrace_mem_binaryTrace hg sample
  have hreplacementLabels : replacementLabels ∈ binaryTrace H sample := by
    exact binaryClassifierTrace_mem_binaryTrace hh sample
  have htraceEq :
      binaryClassifierTrace (listUpdate current g h) sample = labels := by
    apply Finset.ext
    intro point
    simpa [binaryClassifierTrace] using (hlabelsRealized point).symm
  refine Finset.mem_image.mpr
    ⟨(groupLabels, replacementLabels), Finset.mem_product.mpr
      ⟨hgroupLabels, hreplacementLabels⟩, ?_⟩
  rw [listUpdateTrace_eq_binaryClassifierTrace, htraceEq]

/-- Exact finite-trace factorization: list-update growth is at most the
product of group and replacement growth. -/
theorem binaryGrowth_listUpdateClass_le_mul
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool)) (sample : Finset X) :
    binaryGrowth (ListUpdateClass current G H) sample ≤
      binaryGrowth G sample * binaryGrowth H sample := by
  classical
  calc
    binaryGrowth (ListUpdateClass current G H) sample =
        (binaryTrace (ListUpdateClass current G H) sample).card := rfl
    _ ≤ (listUpdateTraceFamily current G H sample).card :=
      Finset.card_le_card
        (binaryTrace_listUpdateClass_subset_traceFamily current G H sample)
    _ ≤ ((binaryTrace G sample).product (binaryTrace H sample)).card := by
      unfold listUpdateTraceFamily
      exact Finset.card_image_le
    _ = binaryGrowth G sample * binaryGrowth H sample := by
      simp [binaryGrowth]

/-- Sauer--Shelah form of the list-update trace bound. -/
theorem binaryGrowth_listUpdateClass_le_vcBinomial
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH) (sample : Finset X) :
    binaryGrowth (ListUpdateClass current G H) sample ≤
      (∑ k ∈ Finset.Iic dG, sample.card.choose k) *
        (∑ k ∈ Finset.Iic dH, sample.card.choose k) := by
  calc
    binaryGrowth (ListUpdateClass current G H) sample ≤
        binaryGrowth G sample * binaryGrowth H sample :=
      binaryGrowth_listUpdateClass_le_mul current G H sample
    _ ≤ (∑ k ∈ Finset.Iic dG, sample.card.choose k) *
        (∑ k ∈ Finset.Iic dH, sample.card.choose k) :=
      Nat.mul_le_mul
        (binaryGrowth_le_sum_choose_of_vcDimensionAtMost hvcG sample)
        (binaryGrowth_le_sum_choose_of_vcDimensionAtMost hvcH sample)

/-- Positive total dimension used in the explicit product-growth envelope.
The `+1` on each source VC bound handles zero-dimensional classes uniformly. -/
def listUpdateVCTotal (dG dH : ℕ) : ℕ := (dG + 1) + (dH + 1)

/-- Explicit real VC bound behind Lemma 15.  It is
`O((d_G+d_H) log(d_G+d_H))`, hence gives the paper's stated soft-linear
dependence without hiding an unproved closure theorem. -/
noncomputable def sourceListUpdateVCBound (dG dH : ℕ) : ℝ :=
  2 * (listUpdateVCTotal dG dH : ℝ) *
    Real.logb 2
      (Real.exp 1 * (listUpdateVCTotal dG dH : ℝ))

/-- Once a restriction reaches the displayed source bound, the list-update
growth envelope is strictly smaller than the full Boolean cube. -/
theorem binaryGrowth_listUpdateClass_lt_two_pow_of_source_size
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH) (sample : Finset X)
    (hsize : sourceListUpdateVCBound dG dH ≤ (sample.card : ℝ)) :
    (binaryGrowth (ListUpdateClass current G H) sample : ℝ) <
      (2 : ℝ) ^ sample.card := by
  let a : ℕ := dG + 1
  let b : ℕ := dH + 1
  let total : ℕ := listUpdateVCTotal dG dH
  have ha : 0 < a := by simp [a]
  have hb : 0 < b := by simp [b]
  have htotal : 0 < total := by simp [total, listUpdateVCTotal]
  have htotalTwo : 2 ≤ total := by
    dsimp [total, listUpdateVCTotal]
    omega
  have hvcG' : VCDimensionAtMost G a := by
    intro restriction
    exact (hvcG restriction).trans (by simp [a])
  have hvcH' : VCDimensionAtMost H b := by
    intro restriction
    exact (hvcH restriction).trans (by simp [b])
  have hscale : 2 < Real.logb 2 (Real.exp 1 * (total : ℝ)) :=
    two_lt_logb_exp_one_mul_nat total htotalTwo
  have htotalLtBound : (total : ℝ) < sourceListUpdateVCBound dG dH := by
    dsimp [sourceListUpdateVCBound]
    change (total : ℝ) < 2 * (total : ℝ) *
      Real.logb 2 (Real.exp 1 * (total : ℝ))
    have htotalReal : 0 < (total : ℝ) := by exact_mod_cast htotal
    nlinarith
  have htotalLtSample : total < sample.card := by
    exact_mod_cast htotalLtBound.trans_le hsize
  have haSample : a ≤ sample.card := by
    have hatotal : a ≤ total := by simp [a, total, listUpdateVCTotal]
    exact hatotal.trans htotalLtSample.le
  have hbSample : b ≤ sample.card := by
    have hbtotal : b ≤ total := by simp [b, total, listUpdateVCTotal]
    exact hbtotal.trans htotalLtSample.le
  have hgrowthNat := binaryGrowth_listUpdateClass_le_vcBinomial
    current G H a b hvcG' hvcH' sample
  have hGEnvelope := sum_choose_le_exp_one_mul_div_pow ha haSample
  have hHEnvelope := sum_choose_le_exp_one_mul_div_pow hb hbSample
  let common : ℝ := Real.exp 1 * (sample.card : ℝ)
  have hcommonNonneg : 0 ≤ common := by positivity
  have haOne : (1 : ℝ) ≤ (a : ℝ) := by exact_mod_cast ha
  have hbOne : (1 : ℝ) ≤ (b : ℝ) := by exact_mod_cast hb
  have hbaseG : common / (a : ℝ) ≤ common := div_le_self hcommonNonneg haOne
  have hbaseH : common / (b : ℝ) ≤ common := div_le_self hcommonNonneg hbOne
  have hgrowthEnvelope :
      (binaryGrowth (ListUpdateClass current G H) sample : ℝ) ≤
        common ^ total := by
    calc
      (binaryGrowth (ListUpdateClass current G H) sample : ℝ) ≤
          ((∑ k ∈ Finset.Iic a, sample.card.choose k : ℕ) *
            (∑ k ∈ Finset.Iic b, sample.card.choose k : ℕ) : ℕ) := by
        exact_mod_cast hgrowthNat
      _ = (∑ k ∈ Finset.Iic a, (sample.card.choose k : ℝ)) *
          (∑ k ∈ Finset.Iic b, (sample.card.choose k : ℝ)) := by
        norm_cast
      _ ≤ (common / (a : ℝ)) ^ a * (common / (b : ℝ)) ^ b := by
        dsimp [common]
        gcongr
      _ ≤ common ^ a * common ^ b := by
        gcongr
      _ = common ^ total := by
        rw [← pow_add]
        rfl
  have hstrict := baumHaussler_envelope_lt_two_pow
    total total sample.card htotalTwo htotal hsize
  have hleft :
      ((total : ℝ) * Real.exp 1 * (sample.card : ℝ) / (total : ℝ)) ^ total =
        common ^ total := by
    have htotalReal : (total : ℝ) ≠ 0 := by exact_mod_cast htotal.ne'
    dsimp [common]
    congr 1
    field_simp [htotalReal]
  rw [hleft] at hstrict
  exact hgrowthEnvelope.trans_lt hstrict

/-- A restriction at the source threshold cannot be shattered. -/
theorem binaryTrace_listUpdateClass_not_shatters_univ_of_source_size
    {X : Type*} [DecidableEq X] (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH) (sample : Finset X)
    (hsize : sourceListUpdateVCBound dG dH ≤ (sample.card : ℝ)) :
    ¬ (binaryTrace (ListUpdateClass current G H) sample).Shatters
      Finset.univ := by
  intro hshatters
  have hstrict := binaryGrowth_listUpdateClass_lt_two_pow_of_source_size
    current G H dG dH hvcG hvcH sample hsize
  have hfull : binaryTrace (ListUpdateClass current G H) sample = Finset.univ :=
    Finset.shatters_univ.mp hshatters
  have hgrowthEq : binaryGrowth (ListUpdateClass current G H) sample =
      2 ^ sample.card := by
    unfold binaryGrowth
    rw [hfull]
    simp [Fintype.card_coe]
  rw [hgrowthEq] at hstrict
  norm_num at hstrict

/-- The product trace factorization gives an explicit soft-linear VC bound
for the one-step list-update class. -/
theorem vcDimension_listUpdateClass_le_source_bound
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH) :
    ∀ sample : Finset X,
      (binaryTraceVCDimension (ListUpdateClass current G H) sample : ℝ) ≤
        sourceListUpdateVCBound dG dH := by
  intro sample
  classical
  let traceFamily := binaryTrace (ListUpdateClass current G H) sample
  by_cases hnonempty : traceFamily.shatterer.Nonempty
  · rcases Finset.exists_mem_eq_sup traceFamily.shatterer hnonempty Finset.card with
      ⟨subsample, hsubsample, hsup⟩
    change (traceFamily.vcDim : ℝ) ≤ sourceListUpdateVCBound dG dH
    unfold Finset.vcDim
    rw [hsup]
    by_contra hnot
    have hboundLt : sourceListUpdateVCBound dG dH < (subsample.card : ℝ) :=
      lt_of_not_ge hnot
    have hshatters : traceFamily.Shatters subsample :=
      Finset.mem_shatterer.mp hsubsample
    let rawSample : Finset X := rawSubsample sample subsample
    have hrawCard : rawSample.card = subsample.card :=
      card_rawSubsample sample subsample
    have hrawShatters :
        (binaryTrace (ListUpdateClass current G H) rawSample).Shatters
          Finset.univ := by
      simpa [rawSample] using
        binaryTrace_shatters_univ_rawSubsample_of_shatters
          (ListUpdateClass current G H) sample subsample hshatters
    have hsourceSize : sourceListUpdateVCBound dG dH ≤ (rawSample.card : ℝ) := by
      rw [hrawCard]
      exact hboundLt.le
    exact (binaryTrace_listUpdateClass_not_shatters_univ_of_source_size
      current G H dG dH hvcG hvcH rawSample hsourceSize) hrawShatters
  · change (traceFamily.vcDim : ℝ) ≤ sourceListUpdateVCBound dG dH
    have hempty : traceFamily.shatterer = ∅ :=
      Finset.not_nonempty_iff_eq_empty.mp hnonempty
    rw [Finset.vcDim, hempty]
    simp only [Finset.sup_empty]
    unfold sourceListUpdateVCBound
    have htotal : 0 < listUpdateVCTotal dG dH := by
      simp [listUpdateVCTotal]
    have hscale : 0 < Real.logb 2
        (Real.exp 1 * (listUpdateVCTotal dG dH : ℝ)) := by
      linarith [two_lt_logb_exp_one_mul_nat (listUpdateVCTotal dG dH)
        (by dsimp [listUpdateVCTotal]; omega)]
    rw [show (⊥ : ℕ) = 0 by rfl]
    norm_num only [Nat.cast_zero]
    exact mul_nonneg
      (mul_nonneg (by norm_num) (Nat.cast_nonneg _)) hscale.le

/-- Natural-number ceiling used by the reusable finite-IID VC theorem. -/
noncomputable def listUpdateVCDimensionBound (dG dH : ℕ) : ℕ :=
  Nat.ceil (sourceListUpdateVCBound dG dH)

/-- Source VC assumptions on `G` and `H` discharge the derived list-update
class premise required by the generalization library. -/
theorem vcDimensionAtMost_listUpdateClass
    {X : Type*} (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH) :
    VCDimensionAtMost (ListUpdateClass current G H)
      (listUpdateVCDimensionBound dG dH) := by
  intro sample
  have hreal := vcDimension_listUpdateClass_le_source_bound
    current G H dG dH hvcG hvcH sample
  have hceil : sourceListUpdateVCBound dG dH ≤
      (listUpdateVCDimensionBound dG dH : ℝ) := by
    exact Nat.le_ceil _
  exact_mod_cast hreal.trans hceil

/-! ## Loss and score bridges -/

/-- The reusable binary-classification loss is definitionally the paper's
binary zero-one loss. -/
theorem binaryClassificationLoss_eq_datumLoss
    {X : Type*} (classifier : Model X Bool) (datum : X × Bool) :
    binaryClassificationLoss classifier datum =
      datumLoss binaryZeroOneLoss classifier datum := by
  unfold binaryClassificationLoss datumLoss binaryZeroOneLoss
  rfl

/-- Empirical certificate score is the empirical loss decrease of the list
update. -/
theorem empiricalSubmissionScore_eq_empiricalError_sub_listUpdate
    {X : Type*} {n : ℕ} (sample : Fin n → X × Bool)
    (current : Model X Bool) (g : Group X) (h : Model X Bool) :
    empiricalSubmissionScore binaryZeroOneLoss sample
        { current := current, group := g, replacement := h } =
      finiteBinaryEmpiricalError sample current -
        finiteBinaryEmpiricalError sample (listUpdate current g h) := by
  unfold empiricalSubmissionScore finiteBinaryEmpiricalError finiteIidScoreSum
  simp only [Fintype.card_fin]
  rw [← sub_div, ← Finset.sum_sub_distrib]
  congr 1
  apply Finset.sum_congr rfl
  intro index _
  cases hg : g (sample index).1 <;>
    simp [submissionScore, groupIndicator, datumLoss, listUpdate,
      binaryClassificationLoss, binaryZeroOneLoss, hg]

/-- Population certificate score is the population loss decrease of the list
update. -/
theorem certificateImprovementScore_eq_modelLoss_sub_listUpdate
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (current : Model X Bool)
    (g : Group X) (h : Model X Bool) :
    certificateImprovementScore law binaryZeroOneLoss current g h =
      modelLoss law binaryZeroOneLoss current -
        modelLoss law binaryZeroOneLoss (listUpdate current g h) := by
  rw [certificateImprovementScore_eq_numerator_sub_total,
    ← modelLoss_sub_listUpdate_eq_numerator_sub]

/-- With the discrete measurable structure, reusable population
classification error equals the paper's finite-PMF model loss. -/
theorem binaryPopulationError_toMeasure_eq_modelLoss
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (classifier : Model X Bool) :
    letI : MeasurableSpace X := ⊤
    binaryPopulationError law.toMeasure classifier =
      modelLoss law binaryZeroOneLoss classifier := by
  letI : MeasurableSpace X := ⊤
  unfold binaryPopulationError modelLoss
  rw [← AppliedModelingLib.pmfExp_eq_integral_toMeasure]
  apply AppliedModelingLib.pmfExp_congr
  exact binaryClassificationLoss_eq_datumLoss classifier

/-! ## A fixed classifier has zero-dimensional trace complexity -/

/-- The trace family of a singleton concept class has cardinality at most one. -/
theorem card_binaryTrace_singleton_le_one
    {X : Type*} (classifier : BinaryClassifier X) (sample : Finset X) :
    (binaryTrace ({classifier} : Set (BinaryClassifier X)) sample).card ≤ 1 := by
  classical
  rw [Finset.card_le_one]
  intro first hfirst second hsecond
  rcases (Finset.mem_filter.mp hfirst).2 with
    ⟨firstClassifier, hfirstClassifier, hfirstRealizes⟩
  rcases (Finset.mem_filter.mp hsecond).2 with
    ⟨secondClassifier, hsecondClassifier, hsecondRealizes⟩
  simp only [Set.mem_singleton_iff] at hfirstClassifier hsecondClassifier
  subst firstClassifier
  subst secondClassifier
  apply Finset.ext
  intro point
  exact (hfirstRealizes point).trans (hsecondRealizes point).symm

/-- A singleton binary concept class has VC dimension zero (and therefore at
most one, the form consumed below). -/
theorem vcDimensionAtMost_singleton
    {X : Type*} (classifier : BinaryClassifier X) :
    VCDimensionAtMost ({classifier} : Set (BinaryClassifier X)) 1 := by
  intro sample
  classical
  unfold binaryTraceVCDimension Finset.vcDim
  apply Finset.sup_le
  intro shattered hshattered
  have hshatters :
      (binaryTrace ({classifier} : Set (BinaryClassifier X)) sample).Shatters
        shattered := Finset.mem_shatterer.mp hshattered
  have hpower : shattered.powerset.card ≤
      (binaryTrace ({classifier} : Set (BinaryClassifier X)) sample).card := by
    rw [← Finset.shatters_iff.mp hshatters]
    exact Finset.card_image_le
  have hone := card_binaryTrace_singleton_le_one classifier sample
  rw [Finset.card_powerset] at hpower
  have : 2 ^ shattered.card ≤ 1 := hpower.trans hone
  by_cases hzero : shattered.card = 0
  · omega
  · have hpow := Nat.one_lt_two_pow hzero
    omega

/-! ## Lemma 15: explicit VC uniform convergence -/

/-- The source score-deviation event for a fixed current model and classes
`G × H`. -/
def certificateVCDeviationEvent
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (tolerance : ℝ) {n : ℕ} (sample : Fin n → X × Bool) : Prop :=
  ∃ g ∈ G, ∃ h ∈ H,
    tolerance <
      |empiricalSubmissionScore binaryZeroOneLoss sample
          { current := current, group := g, replacement := h } -
        certificateImprovementScore law binaryZeroOneLoss current g h|

/-- Probability of the Lemma 15 score-deviation event under literal iid
sampling from the finite PMF. -/
noncomputable def certificateVCDeviationFailure
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (tolerance : ℝ) (n : ℕ) : ℝ := by
  letI : MeasurableSpace X := ⊤
  exact (Probability.finiteIIDSampleLaw law.toMeasure n).real
    {sample | certificateVCDeviationEvent law current G H tolerance sample}

/-- The exact confidence radius obtained by controlling the list-update class
and the fixed current classifier separately. -/
noncomputable def certificateVCConfidenceRadius
    (dG dH n : ℕ) (delta : ℝ) : ℝ :=
  finiteIIDVCSourceConfidenceRadius
      (listUpdateVCDimensionBound dG dH) n (delta / 2) +
    finiteIIDVCSourceConfidenceRadius 1 n (delta / 2)

/-- The explicit real list-update VC bound is strictly positive. -/
theorem sourceListUpdateVCBound_pos (dG dH : ℕ) :
    0 < sourceListUpdateVCBound dG dH := by
  have htotal : 0 < listUpdateVCTotal dG dH := by
    simp [listUpdateVCTotal]
  have hscale : 0 < Real.logb 2
      (Real.exp 1 * (listUpdateVCTotal dG dH : ℝ)) := by
    linarith [two_lt_logb_exp_one_mul_nat (listUpdateVCTotal dG dH)
      (by dsimp [listUpdateVCTotal]; omega)]
  unfold sourceListUpdateVCBound
  positivity

/-- A score deviation larger than the sum radius forces either the current
model or its corresponding list update to violate its own VC error bound. -/
theorem certificateVCDeviationEvent_subset_errorEvents
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (updateRadius currentRadius : ℝ) (n : ℕ) :
    letI : MeasurableSpace X := ⊤
    {sample : Fin n → X × Bool |
      certificateVCDeviationEvent law current G H
        (updateRadius + currentRadius) sample} ⊆
      {sample | ∃ updated, updated ∈ ListUpdateClass current G H ∧
        updateRadius <
          |finiteBinaryEmpiricalError sample updated -
            binaryPopulationError law.toMeasure updated|} ∪
      {sample | ∃ classifier,
        classifier ∈ ({current} : Set (BinaryClassifier X)) ∧
        currentRadius <
          |finiteBinaryEmpiricalError sample classifier -
            binaryPopulationError law.toMeasure classifier|} := by
  letI : MeasurableSpace X := ⊤
  intro sample hdeviation
  rcases hdeviation with ⟨g, hg, h, hh, hscore⟩
  let updated := listUpdate current g h
  let currentGap := finiteBinaryEmpiricalError sample current -
    binaryPopulationError law.toMeasure current
  let updateGap := finiteBinaryEmpiricalError sample updated -
    binaryPopulationError law.toMeasure updated
  have hscoreEq :
      empiricalSubmissionScore binaryZeroOneLoss sample
          { current := current, group := g, replacement := h } -
        certificateImprovementScore law binaryZeroOneLoss current g h =
      currentGap - updateGap := by
    rw [empiricalSubmissionScore_eq_empiricalError_sub_listUpdate,
      certificateImprovementScore_eq_modelLoss_sub_listUpdate,
      ← binaryPopulationError_toMeasure_eq_modelLoss law current,
      ← binaryPopulationError_toMeasure_eq_modelLoss law (listUpdate current g h)]
    dsimp [currentGap, updateGap, updated]
    ring
  rw [hscoreEq] at hscore
  by_cases hupdate : updateRadius < |updateGap|
  · left
    exact ⟨updated, ⟨g, hg, h, hh, rfl⟩, hupdate⟩
  · right
    refine ⟨current, Set.mem_singleton current, ?_⟩
    have hupdateLe : |updateGap| ≤ updateRadius := le_of_not_gt hupdate
    have htriangle : |currentGap - updateGap| ≤
        |currentGap| + |updateGap| := abs_sub _ _
    change currentRadius < |currentGap|
    by_contra hcurrent
    have hcurrentLe : |currentGap| ≤ currentRadius := le_of_not_gt hcurrent
    linarith

/-- Lemma 15 with an explicit VC confidence radius.  The dimension ceiling is
the checked product-trace/Sauer--Shelah closure of the source classes, and the
only size-side condition is the standard nontrivial VC range `d ≤ 2n`. -/
theorem lemma15_vc_uniform_convergence
    {X : Type*} [Fintype X] [DecidableEq X]
    (law : Distribution X Bool) (current : Model X Bool)
    (G : Set (Group X)) (H : Set (Model X Bool))
    (dG dH : ℕ) (hvcG : VCDimensionAtMost G dG)
    (hvcH : VCDimensionAtMost H dH)
    (n : ℕ) (hcount : 0 < n)
    (hdimension : listUpdateVCDimensionBound dG dH ≤ n + n)
    (delta : ℝ) (hdelta : 0 < delta) :
    certificateVCDeviationFailure law current G H
        (certificateVCConfidenceRadius dG dH n delta) n ≤ delta := by
  letI : MeasurableSpace X := ⊤
  let updateDimension := listUpdateVCDimensionBound dG dH
  let updateRadius := finiteIIDVCSourceConfidenceRadius
    updateDimension n (delta / 2)
  let currentRadius := finiteIIDVCSourceConfidenceRadius 1 n (delta / 2)
  let updateBad : Set (Fin n → X × Bool) := {sample | ∃ updated,
    updated ∈ ListUpdateClass current G H ∧
      updateRadius <
        |finiteBinaryEmpiricalError sample updated -
          binaryPopulationError law.toMeasure updated|}
  let currentBad : Set (Fin n → X × Bool) := {sample | ∃ classifier,
    classifier ∈ ({current} : Set (BinaryClassifier X)) ∧
      currentRadius <
        |finiteBinaryEmpiricalError sample classifier -
          binaryPopulationError law.toMeasure classifier|}
  have hupdateDimensionPos : 0 < updateDimension := by
    dsimp [updateDimension, listUpdateVCDimensionBound]
    exact Nat.ceil_pos.mpr (sourceListUpdateVCBound_pos dG dH)
  have honeDimension : 1 ≤ n + n := by omega
  have hdeltaHalf : 0 < delta / 2 := half_pos hdelta
  have hmeasurable : ∀ classifier : BinaryClassifier X,
      Measurable classifier := fun _ => measurable_of_finite _
  have hupdateTail :
      (Probability.finiteIIDSampleLaw law.toMeasure n).real updateBad ≤ delta / 2 := by
    dsimp [updateBad, updateRadius, updateDimension]
    exact finiteIID_vc_generalization_theorem7 law.toMeasure
      (vcDimensionAtMost_listUpdateClass current G H dG dH hvcG hvcH)
      hcount hupdateDimensionPos hdimension
      (fun classifier _ => hmeasurable classifier) (delta / 2) hdeltaHalf
      MeasurableSet.of_discrete MeasurableSet.of_discrete
      MeasurableSet.of_discrete MeasurableSet.of_discrete
      MeasurableSet.of_discrete
  have hcurrentTail :
      (Probability.finiteIIDSampleLaw law.toMeasure n).real currentBad ≤ delta / 2 := by
    dsimp [currentBad, currentRadius]
    exact finiteIID_vc_generalization_theorem7 law.toMeasure
      (vcDimensionAtMost_singleton current) hcount (by omega) honeDimension
      (fun classifier _ => hmeasurable classifier) (delta / 2) hdeltaHalf
      MeasurableSet.of_discrete MeasurableSet.of_discrete
      MeasurableSet.of_discrete MeasurableSet.of_discrete
      MeasurableSet.of_discrete
  letI : IsProbabilityMeasure
      (Probability.finiteIIDSampleLaw law.toMeasure n) := by
    dsimp [Probability.finiteIIDSampleLaw]
    infer_instance
  have hsubset :
      {sample : Fin n → X × Bool |
        certificateVCDeviationEvent law current G H
          (updateRadius + currentRadius) sample} ⊆ updateBad ∪ currentBad := by
    simpa [updateBad, currentBad] using
      certificateVCDeviationEvent_subset_errorEvents law current G H
        updateRadius currentRadius n
  unfold certificateVCDeviationFailure
  change (Probability.finiteIIDSampleLaw law.toMeasure n).real
      {sample : Fin n → X × Bool |
        certificateVCDeviationEvent law current G H
          (updateRadius + currentRadius) sample} ≤ delta
  calc
    (Probability.finiteIIDSampleLaw law.toMeasure n).real
        {sample : Fin n → X × Bool |
          certificateVCDeviationEvent law current G H
            (updateRadius + currentRadius) sample} ≤
        (Probability.finiteIIDSampleLaw law.toMeasure n).real
          (updateBad ∪ currentBad) :=
      measureReal_mono hsubset (measure_ne_top _ _)
    _ ≤ (Probability.finiteIIDSampleLaw law.toMeasure n).real updateBad +
        (Probability.finiteIIDSampleLaw law.toMeasure n).real currentBad :=
      measureReal_union_le _ _
    _ ≤ delta / 2 + delta / 2 := add_le_add hupdateTail hcurrentTail
    _ = delta := by ring

end

end GHKR22BiasBounties
