import LG21TestOptionalPolicies.HiddenAccessTheorem31ReportRequiredLatentFairnessEndpoint
import LG21TestOptionalPolicies.HiddenAccessTheorem31ReportRequiredOutputIntegrability
import LG21TestOptionalPolicies.HiddenAccessTheorem31ReportRequiredDemographicTower

/-!
# Concrete actual-law fairness closeout for report-required LG21 Theorem 3.1

This module instantiates the paper's generic law-policy surface with the
literal source equilibrium and the actual public output generated by the
report-required protocol.  In particular, the observable and demographic
fields are not caller-supplied law equalities, and no optional score-stage
report/withhold best response is used.
-/

namespace LG21TestOptionalPolicies

noncomputable section

open AppliedModelingLib AppliedModelingLib.Probability MeasureTheory ProbabilityTheory Set
open scoped ENNReal ProbabilityTheory

/-- The concrete Definition-2--4 law surface for the literal hidden-access
report-required source model.  A tester's final public output is the reported
score payoff because reporting is required after taking. -/
def lg21HiddenAccessReportRequiredLiteralOutputLawSurface
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    (M : LG21ContinuousGaussianPopulation Feature) (testFeature : Feature)
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean) (baseVariance : ℝ) :
    LG21SourceLawPolicySurface ℝ
      (LG21NonTestFeature Feature testFeature → ℝ) ℝ (Measure ℝ) where
  Equilibrium := LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature
  latentAccessLaw := fun E latentSkill publicBase =>
    lg21HiddenAccessReportRequiredLatentAccessOutputLaw E latentSkill publicBase
  latentNoAccessLaw := fun E _latentSkill publicBase =>
    lg21HiddenAccessReportRequiredNoAccessOutputLaw E publicBase
  observableAccessLaw := fun E publicBase =>
    lg21HiddenAccessReportRequiredObservableAccessOutputLaw E publicBase
      baseMean hbaseMean baseVariance
  observableNoAccessLaw := fun E publicBase =>
    lg21HiddenAccessReportRequiredNoAccessOutputLaw E publicBase
  demographicAccessLaw := fun E =>
    lg21HiddenAccessReportRequiredActualDemographicAccessOutputLaw E
  demographicNoAccessLaw := fun E =>
    lg21HiddenAccessReportRequiredActualDemographicNoAccessOutputLaw E
  baseOnlyLaw := fun E publicBase =>
    lg21HiddenAccessReportRequiredNoAccessOutputLaw E publicBase
  fullFeatureLaw := fun E publicBase score =>
    Measure.dirac (E.source.reportedPayoff publicBase score)

/-- Definition 3 evaluated at one supplied report-required equilibrium. -/
def lg21HiddenAccessReportRequiredObservablyFairAt
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean) (baseVariance : ℝ) : Prop :=
  ∀ publicBase,
    lg21HiddenAccessReportRequiredObservableAccessOutputLaw E publicBase
        baseMean hbaseMean baseVariance =
      lg21HiddenAccessReportRequiredNoAccessOutputLaw E publicBase

/-- Definition 4 evaluated at one supplied report-required equilibrium. -/
def lg21HiddenAccessReportRequiredDemographicallyFairAt
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature) : Prop :=
  lg21HiddenAccessReportRequiredActualDemographicAccessOutputLaw E =
    lg21HiddenAccessReportRequiredActualDemographicNoAccessOutputLaw E

/-- The direct source-Gaussian latent witness refutes the generic Definition-2
predicate on the concrete actual-output surface. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_latentSkillFairAt_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean)
    (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21HiddenAccessReportRequiredLatentSkillFair E := by
  exact lg21HiddenAccessReportRequired_not_latentSkillFair_of_sourceGaussianFactor
    E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor

/-- The same fixed-equilibrium witness refutes the paper's all-equilibria
Definition 2 predicate. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_latentSkillFair_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean) (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21SourceLawLatentSkillFair
      (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
        M testFeature baseMean hbaseMean baseVariance) := by
  intro hfair
  apply lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_latentSkillFairAt_of_sourceGaussianFactor
    E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  intro latentSkill publicBase
  exact hfair E latentSkill publicBase

/-- The source factorization supplies a genuine observable-base witness
against Definition 3 on the concrete actual-output surface.  The selected
base is required to satisfy the literal PBO integrability consequence as well
as the source best-response and posterior-monotonicity facts. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_observablyFairAt_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean)
    (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21HiddenAccessReportRequiredObservablyFairAt E
      baseMean hbaseMean baseVariance := by
  let skillKernel := gaussianLocationKernel
    baseMean hbaseMean baseVariance.toNNReal
  letI : IsMarkovKernel skillKernel := gaussianLocationKernel_isMarkov
    baseMean hbaseMean baseVariance.toNNReal
  let action : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ → Bool :=
    fun publicBase latentSkill => E.source.takeDecision latentSkill publicBase
  let actionEvent : Set ((LG21NonTestFeature Feature testFeature → ℝ) × ℝ) :=
    lg21SourceLatentActionEvent action
  have htakeFibres : ∀ᵐ publicBase ∂baseLaw,
      selectionMass skillKernel actionEvent publicBase ≠ 0 := by
    simpa [skillKernel, action, actionEvent] using
      (E.ae_positive_takeSelectionMass_of_localTailStability hnoAccess hstable
        baseLaw baseMean hbaseMean baseVariance hbaseVariance htestNoiseVariance
        hsourceFactor)
  have hbest : ∀ᵐ publicBase ∂baseLaw,
      NoProfitableBinaryChoiceDeviationAE (skillKernel publicBase)
        (fun latentSkill => E.source.takeDecision latentSkill publicBase = true)
        (fun latentSkill => ∫ score,
          E.source.reportedPayoff publicBase score
            ∂E.source.testLaw latentSkill publicBase)
        (fun _ => E.source.noReportPayoff publicBase) := by
    simpa [skillKernel] using
      (E.take_best_response_ae_by_base_of_sourceGaussianFactor
        baseLaw baseMean hbaseMean baseVariance
        (M.noiseVariance testFeature : ℝ) hsourceFactor)
  have hstrict := E.takeExpectedPayoff_strictMono_ae_of_sourceGaussianFactor
    hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  have hintegrable :=
    lg21HiddenAccessReportRequired_observableOutput_integrable_ae_of_sourceGaussianFactor
      E baseLaw baseMean hbaseMean baseVariance hsourceFactor
  have hgood : ∀ᵐ publicBase ∂baseLaw,
      Integrable (fun scoreSkill : ℝ × ℝ =>
        lg21HiddenAccessReportRequiredSourceOutput E scoreSkill.2 publicBase
          scoreSkill.1)
        (gaussianSignalJointKernel baseMean hbaseMean baseVariance
          (M.noiseVariance testFeature : ℝ) publicBase) ∧
      NoProfitableBinaryChoiceDeviationAE (skillKernel publicBase)
        (fun latentSkill => E.source.takeDecision latentSkill publicBase = true)
        (fun latentSkill => ∫ score,
          E.source.reportedPayoff publicBase score
            ∂E.source.testLaw latentSkill publicBase)
        (fun _ => E.source.noReportPayoff publicBase) ∧
      StrictMono (fun latentSkill => ∫ score,
        E.source.reportedPayoff publicBase score
          ∂E.source.testLaw latentSkill publicBase) ∧
      selectionMass skillKernel actionEvent publicBase ≠ 0 := by
    filter_upwards [hintegrable, hbest, hstrict, htakeFibres] with publicBase
      hintegrable hbest hstrict htake
    exact ⟨hintegrable, hbest, hstrict, htake⟩
  rcases hgood.exists with ⟨publicBase, hintegrableBase, hbestBase,
    hstrictBase, htakePositive⟩
  have hchosen : 0 < gaussianReal (baseMean publicBase)
      baseVariance.toNNReal
      {latentSkill | E.source.takeDecision latentSkill publicBase = true} := by
    apply pos_iff_ne_zero.mpr
    simpa [selectionMass, actionEvent, action, selectedFiber,
      lg21SourceLatentActionEvent, skillKernel, gaussianLocationKernel_apply] using
      htakePositive
  have hbestBase' : NoProfitableBinaryChoiceDeviationAE
      (gaussianReal (baseMean publicBase) baseVariance.toNNReal)
      (fun latentSkill => E.source.takeDecision latentSkill publicBase = true)
      (fun latentSkill => ∫ score,
        E.source.reportedPayoff publicBase score
          ∂E.source.testLaw latentSkill publicBase)
      (fun _ => E.source.noReportPayoff publicBase) := by
    simpa [skillKernel, gaussianLocationKernel_apply] using hbestBase
  intro hfair
  exact
    (lg21HiddenAccessReportRequired_observableOutputLaw_ne_of_localFacts
      E publicBase baseMean hbaseMean baseVariance hbaseVariance hintegrableBase
      hbestBase' hstrictBase hchosen)
    (hfair publicBase)

/-- The fixed-equilibrium observable witness refutes the all-equilibria
Definition 3 predicate. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_observablyFair_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean) (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21SourceLawObservablyFair
      (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
        M testFeature baseMean hbaseMean baseVariance) := by
  intro hfair
  apply lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_observablyFairAt_of_sourceGaussianFactor
    E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  intro publicBase
  exact hfair E publicBase

/-- The source's pre-score strict-gain argument also survives integration over
public bases.  The output comparison is between expected *actual* output
conditional on a base and the no-report output, so it does not assert any
realized-score pointwise or stochastic-order comparison. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_demographicallyFairAt_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean)
    (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21HiddenAccessReportRequiredDemographicallyFairAt E := by
  let skillKernel := gaussianLocationKernel
    baseMean hbaseMean baseVariance.toNNReal
  letI : IsMarkovKernel skillKernel := gaussianLocationKernel_isMarkov
    baseMean hbaseMean baseVariance.toNNReal
  let action : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ → Bool :=
    fun publicBase latentSkill => E.source.takeDecision latentSkill publicBase
  let actionEvent : Set ((LG21NonTestFeature Feature testFeature → ℝ) × ℝ) :=
    lg21SourceLatentActionEvent action
  have htakeFibres : ∀ᵐ publicBase ∂baseLaw,
      selectionMass skillKernel actionEvent publicBase ≠ 0 := by
    simpa [skillKernel, action, actionEvent] using
      (E.ae_positive_takeSelectionMass_of_localTailStability hnoAccess hstable
        baseLaw baseMean hbaseMean baseVariance hbaseVariance htestNoiseVariance
        hsourceFactor)
  have hbest : ∀ᵐ publicBase ∂baseLaw,
      NoProfitableBinaryChoiceDeviationAE (skillKernel publicBase)
        (fun latentSkill => E.source.takeDecision latentSkill publicBase = true)
        (fun latentSkill => ∫ score,
          E.source.reportedPayoff publicBase score
            ∂E.source.testLaw latentSkill publicBase)
        (fun _ => E.source.noReportPayoff publicBase) := by
    simpa [skillKernel] using
      (E.take_best_response_ae_by_base_of_sourceGaussianFactor
        baseLaw baseMean hbaseMean baseVariance
        (M.noiseVariance testFeature : ℝ) hsourceFactor)
  have hstrict := E.takeExpectedPayoff_strictMono_ae_of_sourceGaussianFactor
    hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  have hintegrable :=
    lg21HiddenAccessReportRequired_observableOutput_integrable_ae_of_sourceGaussianFactor
      E baseLaw baseMean hbaseMean baseVariance hsourceFactor
  have hstrictBaseMean : ∀ᵐ publicBase ∂baseLaw,
      E.source.noReportPayoff publicBase <
        ∫ scoreSkill : ℝ × ℝ,
          lg21HiddenAccessReportRequiredSourceOutput E scoreSkill.2 publicBase
            scoreSkill.1
          ∂gaussianSignalJointKernel baseMean hbaseMean baseVariance
            (M.noiseVariance testFeature : ℝ) publicBase := by
    filter_upwards [hintegrable, hbest, hstrict, htakeFibres] with publicBase
      hintegrableBase hbestBase hstrictBase htakePositive
    have hchosen : 0 < gaussianReal (baseMean publicBase)
        baseVariance.toNNReal
        {latentSkill | E.source.takeDecision latentSkill publicBase = true} := by
      apply pos_iff_ne_zero.mpr
      simpa [selectionMass, actionEvent, action, selectedFiber,
        lg21SourceLatentActionEvent, skillKernel, gaussianLocationKernel_apply] using
        htakePositive
    have hbestBase' : NoProfitableBinaryChoiceDeviationAE
        (gaussianReal (baseMean publicBase) baseVariance.toNNReal)
        (fun latentSkill => E.source.takeDecision latentSkill publicBase = true)
        (fun latentSkill => ∫ score,
          E.source.reportedPayoff publicBase score
            ∂E.source.testLaw latentSkill publicBase)
        (fun _ => E.source.noReportPayoff publicBase) := by
      simpa [skillKernel, gaussianLocationKernel_apply] using hbestBase
    exact
      lg21HiddenAccessReportRequired_observableOutput_integral_gt_noReport_of_localFacts
        E publicBase baseMean hbaseMean baseVariance hbaseVariance hintegrableBase
        hbestBase' hstrictBase hchosen
  have haccessBaseIntegrable :=
    lg21HiddenAccessReportRequired_observableOutputIntegral_integrable_of_sourceGaussianFactor
      E baseLaw baseMean hbaseMean baseVariance hsourceFactor
  have hnoAccessBaseIntegrable :=
    lg21HiddenAccessReportRequired_noReportPayoff_integrable_of_sourceGaussianFactor
      E hnoAccess baseLaw baseMean hbaseMean baseVariance hsourceFactor
  have hbaseMeanStrict :
      (∫ publicBase, E.source.noReportPayoff publicBase ∂baseLaw) <
        ∫ publicBase, ∫ scoreSkill : ℝ × ℝ,
          lg21HiddenAccessReportRequiredSourceOutput E scoreSkill.2 publicBase
            scoreSkill.1
          ∂gaussianSignalJointKernel baseMean hbaseMean baseVariance
            (M.noiseVariance testFeature : ℝ) publicBase
        ∂baseLaw := by
    exact lg21_integral_lt_integral_of_ae_lt_probability baseLaw
      hnoAccessBaseIntegrable haccessBaseIntegrable hstrictBaseMean
  have hprimitiveMeanStrict :
      (∫ primitive,
        lg21HiddenAccessReportRequiredPrimitiveNoAccessOutput E primitive
          ∂lg21ContinuousGaussianStudentPrimitiveLaw M) <
        ∫ primitive,
          lg21HiddenAccessReportRequiredPrimitiveAccessOutput E primitive
            ∂lg21ContinuousGaussianStudentPrimitiveLaw M := by
    rw [lg21HiddenAccessReportRequired_primitiveNoAccessOutput_integral_eq_baseLaw_of_sourceFactor
      E hnoAccess baseLaw baseMean hbaseMean baseVariance hsourceFactor,
      lg21HiddenAccessReportRequired_primitiveAccessOutput_integral_eq_sourceGaussianTower_of_sourceFactor
        E baseLaw baseMean hbaseMean baseVariance hsourceFactor]
    exact hbaseMeanStrict
  have hprimitiveLawNe :
      lg21HiddenAccessReportRequiredDemographicAccessOutputLaw E ≠
        lg21HiddenAccessReportRequiredDemographicNoAccessOutputLaw E := by
    exact lg21_map_ne_of_integral_ne
      (lg21ContinuousGaussianStudentPrimitiveLaw M)
      (lg21HiddenAccessReportRequiredPrimitiveAccessOutput E)
      (lg21HiddenAccessReportRequiredPrimitiveNoAccessOutput E)
      (lg21HiddenAccessReportRequiredPrimitiveAccessOutput_measurable E)
      (lg21HiddenAccessReportRequiredPrimitiveNoAccessOutput_measurable E)
      E.primitiveAccessOutput_integrable
      (E.primitiveNoAccessOutput_integrable hnoAccess)
      (ne_of_gt hprimitiveMeanStrict)
  have hactualLawNe :
      lg21HiddenAccessReportRequiredActualDemographicAccessOutputLaw E ≠
        lg21HiddenAccessReportRequiredActualDemographicNoAccessOutputLaw E := by
    rw [lg21HiddenAccessReportRequired_actualDemographicAccessOutputLaw_eq_primitive E,
      lg21HiddenAccessReportRequired_actualDemographicNoAccessOutputLaw_eq_primitive
        E hnoAccess]
    exact hprimitiveLawNe
  intro hfair
  exact hactualLawNe hfair

/-- The fixed-equilibrium demographic witness refutes the all-equilibria
Definition 4 predicate. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_demographicallyFair_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean) (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21SourceLawDemographicallyFair
      (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
        M testFeature baseMean hbaseMean baseVariance) := by
  intro hfair
  exact lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_demographicallyFairAt_of_sourceGaussianFactor
    E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
    baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor (hfair E)

/-- Direct report-required Theorem-3.1 closeout on the concrete source-law
surface.  Each failure is witnessed by the literal forced-report public-output
law; none is supplied as an equality or inequality between abstract surface
fields. -/
theorem lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_fair_of_sourceGaussianFactor
    {Feature : Type*} [Fintype Feature] [DecidableEq Feature]
    {M : LG21ContinuousGaussianPopulation Feature} {testFeature : Feature}
    (E : LG21HiddenAccessReportRequiredLiteralSourceEquilibriumAE M testFeature)
    (hnoAccess : 0 < M.accessLaw {false})
    (hstable : LG21ReportRequiredStableAgainstLocalTailEntry
      (M := M) (testFeature := testFeature) E.source.takeDecision)
    (hpriorVariance : 0 < (M.priorVariance : ℝ))
    (hnonTestNoiseVariance : ∀ feature : LG21NonTestFeature Feature testFeature,
      0 < (M.noiseVariance feature.1 : ℝ))
    (htestNoiseVariance : 0 < (M.noiseVariance testFeature : ℝ))
    (baseLaw : Measure (LG21NonTestFeature Feature testFeature → ℝ))
    [IsProbabilityMeasure baseLaw]
    (baseMean : (LG21NonTestFeature Feature testFeature → ℝ) → ℝ)
    (hbaseMean : Measurable baseMean)
    (baseVariance : ℝ)
    (hbaseVariance : 0 < baseVariance)
    (hsourceFactor :
      (lg21ContinuousGaussianPopulationLaw M).map
        (lg21HiddenAccessBaseScoreSkillObservation testFeature) =
        baseLaw ⊗ₘ gaussianSignalJointKernel
          baseMean hbaseMean baseVariance (M.noiseVariance testFeature : ℝ)) :
    ¬ lg21SourceLawLatentSkillFair
        (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
          M testFeature baseMean hbaseMean baseVariance) ∧
      ¬ lg21SourceLawObservablyFair
        (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
          M testFeature baseMean hbaseMean baseVariance) ∧
        ¬ lg21SourceLawDemographicallyFair
          (lg21HiddenAccessReportRequiredLiteralOutputLawSurface
            M testFeature baseMean hbaseMean baseVariance) := by
  refine ⟨?_, ?_, ?_⟩
  · exact
      lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_latentSkillFair_of_sourceGaussianFactor
        E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
        baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  · exact
      lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_observablyFair_of_sourceGaussianFactor
        E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
        baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor
  · exact
      lg21HiddenAccessReportRequiredLiteralOutputLawSurface_not_demographicallyFair_of_sourceGaussianFactor
        E hnoAccess hstable hpriorVariance hnonTestNoiseVariance htestNoiseVariance
        baseLaw baseMean hbaseMean baseVariance hbaseVariance hsourceFactor

end

end LG21TestOptionalPolicies
