import LG21TestOptionalPolicies.Theorem32GaussianCounterexample
import Mathlib.Probability.Kernel.Basic

/-!
# The exact Gaussian-kernel counterexample to LG21 Theorem 3.2

This module closes the operational-law gap deliberately left visible in
`Theorem32GaussianCounterexample`.  There is one score-indexed estimator
kernel.  A reporting student receives that kernel at the realized Gaussian
score; a nonreporter receives the equilibrium reporter-resampling law.  The
access population law is then defined, rather than postulated, by binding the
Gaussian population law to this single individual-output kernel.

The proof exposes the whole chain:

1. the reporter branch is the conditional high/low mixture generated by the
   score kernel;
2. the access branch is the reporter sublaw plus the nonreporter base kernel;
3. the base kernel is that same reporter mixture (with the source's zero-
   reporter fallback), so the actual access and no-access laws agree;
4. both strategic payoffs are expectations of these same kernel laws.

Consequently observable fairness is proved for the actual population output
law, while the report-all equilibrium remains nonblank.
-/

namespace LG21TestOptionalPolicies

noncomputable section

open AppliedModelingLib
open AppliedModelingLib.Probability
open MeasureTheory
open ProbabilityTheory

local instance (priority := low) {α : Type*} : DecidableEq α :=
  Classical.decEq α
local instance (priority := low) {p : Prop} : Decidable p :=
  Classical.propDecidable p

/-! ## Generic measure identities used by the operational construction -/

/-- Binding a measure to a piecewise kernel splits into its two restricted branches. -/
theorem lg21_measure_bind_piecewise_kernel
    {Population Estimate : Type*}
    [MeasurableSpace Population] [MeasurableSpace Estimate]
    (populationLaw : Measure Population) (event : Set Population)
    (hevent : MeasurableSet event)
    (selected unselected : Kernel Population Estimate) :
    populationLaw.bind (Kernel.piecewise hevent selected unselected) =
      (populationLaw.restrict event).bind selected +
        (populationLaw.restrict eventᶜ).bind unselected := by
  ext target htarget
  rw [Measure.bind_apply htarget
      (Kernel.piecewise hevent selected unselected).measurable.aemeasurable]
  rw [Measure.add_apply]
  rw [Measure.bind_apply htarget selected.measurable.aemeasurable]
  rw [Measure.bind_apply htarget unselected.measurable.aemeasurable]
  simpa only [Kernel.piecewise_apply'] using
    (MeasureTheory.lintegral_piecewise (μ := populationLaw) hevent
      (fun student ↦ selected student target)
      (fun student ↦ unselected student target))

/-- The measure of a finite binary PMF mixture is the corresponding measure mixture. -/
theorem lg21_binaryMixturePMF_toMeasure
    {Estimate : Type*} [MeasurableSpace Estimate]
    (p : NNReal) (hp : p ≤ 1)
    (selected unselected : PMF Estimate) :
    (lg21BinaryMixturePMF p hp selected unselected).toMeasure =
      (p : ENNReal) • selected.toMeasure +
        ((1 - p : NNReal) : ENNReal) • unselected.toMeasure := by
  ext target htarget
  rw [Measure.add_apply]
  simp [lg21BinaryMixturePMF, AppliedModelingLib.binaryMixturePMF,
    PMF.toMeasure_bind_apply, PMF.bernoulli_apply, htarget,
    tsum_fintype, Measure.smul_apply]

/--
A probability measure bound to a high/low constant kernel is exactly the PMF
binary mixture with its actual event probability as mixture weight.
-/
theorem lg21_measure_bind_binary_kernel_eq_binaryMixture
    {Population Estimate : Type*}
    [MeasurableSpace Population] [MeasurableSpace Estimate]
    (populationLaw : Measure Population) [IsProbabilityMeasure populationLaw]
    (event : Set Population) (hevent : MeasurableSet event)
    (selected unselected : PMF Estimate) :
    populationLaw.bind
        (Kernel.piecewise hevent
          (Kernel.const Population selected.toMeasure)
          (Kernel.const Population unselected.toMeasure)) =
      (lg21BinaryMixturePMF
        (lg21EventProbabilityNNReal populationLaw event)
        (lg21EventProbabilityNNReal_le_one populationLaw event)
        selected unselected).toMeasure := by
  let p : NNReal := lg21EventProbabilityNNReal populationLaw event
  have hp : p ≤ 1 :=
    lg21EventProbabilityNNReal_le_one populationLaw event
  have hp_coe : (p : ENNReal) = populationLaw event := by
    exact ENNReal.coe_toNNReal (measure_ne_top populationLaw event)
  have hcomp_coe : ((1 - p : NNReal) : ENNReal) = populationLaw eventᶜ := by
    calc
      ((1 - p : NNReal) : ENNReal) = 1 - (p : ENNReal) := by simp
      _ = 1 - populationLaw event := by rw [hp_coe]
      _ = populationLaw eventᶜ := by
        symm
        simpa using
          (measure_compl hevent (measure_ne_top populationLaw event))
  calc
    populationLaw.bind
          (Kernel.piecewise hevent
            (Kernel.const Population selected.toMeasure)
            (Kernel.const Population unselected.toMeasure)) =
        (populationLaw.restrict event).bind
            (Kernel.const Population selected.toMeasure) +
          (populationLaw.restrict eventᶜ).bind
            (Kernel.const Population unselected.toMeasure) :=
      lg21_measure_bind_piecewise_kernel
        populationLaw event hevent _ _
    _ = populationLaw event • selected.toMeasure +
          populationLaw eventᶜ • unselected.toMeasure := by
      simp
    _ = (p : ENNReal) • selected.toMeasure +
          ((1 - p : NNReal) : ENNReal) • unselected.toMeasure := by
      rw [hp_coe, hcomp_coe]
    _ = (lg21BinaryMixturePMF p hp selected unselected).toMeasure := by
      symm
      exact lg21_binaryMixturePMF_toMeasure p hp selected unselected

/-! ## One estimator kernel and the induced individual-output kernel -/

/--
The single randomized estimator kernel.  It depends only on the reported
score: nonnegative scores receive the symmetric `{-1,1}` law and negative
scores receive the point mass at zero.
-/
def lg21GaussianRandomizedScoreEstimatorKernel :
    Kernel ℝ LG21RandomizedCounterexampleEstimate :=
  Kernel.piecewise (s := Set.Ici (0 : ℝ)) measurableSet_Ici
    (Kernel.const ℝ lg21RandomizedCounterexampleSymmetricLaw.toMeasure)
    (Kernel.const ℝ lg21RandomizedCounterexampleZeroLaw.toMeasure)

theorem lg21GaussianRandomizedScoreEstimatorKernel_apply (score : ℝ) :
    lg21GaussianRandomizedScoreEstimatorKernel score =
      (if 0 ≤ score then
        lg21RandomizedCounterexampleSymmetricLaw.toMeasure
      else
        lg21RandomizedCounterexampleZeroLaw.toMeasure) := by
  rw [lg21GaussianRandomizedScoreEstimatorKernel, Kernel.piecewise_apply]
  rfl

/-- The same estimator kernel pulled back along the source test equation. -/
def lg21GaussianRandomizedPrimitiveEstimatorKernel :
    Kernel (ℝ × ℝ) LG21RandomizedCounterexampleEstimate where
  toFun := fun student ↦
    lg21GaussianRandomizedScoreEstimatorKernel
      (lg21GaussianRandomizedPotentialTest student)
  measurable' :=
    lg21GaussianRandomizedScoreEstimatorKernel.measurable.comp
      lg21GaussianRandomizedPotentialTest_measurable

theorem lg21GaussianRandomizedPrimitiveEstimatorKernel_eq_piecewise :
    lg21GaussianRandomizedPrimitiveEstimatorKernel =
      Kernel.piecewise lg21GaussianRandomizedHighScoreEvent_measurable
        (Kernel.const (ℝ × ℝ)
          lg21RandomizedCounterexampleSymmetricLaw.toMeasure)
        (Kernel.const (ℝ × ℝ)
          lg21RandomizedCounterexampleZeroLaw.toMeasure) := by
  ext student target htarget
  change
    (lg21GaussianRandomizedScoreEstimatorKernel
        (lg21GaussianRandomizedPotentialTest student)) target = _
  rw [lg21GaussianRandomizedScoreEstimatorKernel_apply,
    Kernel.piecewise_apply]
  simp only [lg21GaussianRandomizedHighScoreEvent, Set.mem_setOf_eq]
  simp only [Kernel.const_apply]

/-- The no-report/no-access base measure used in equilibrium `E`. -/
def lg21GaussianRandomizedKernelBaseMeasure
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    Measure LG21RandomizedCounterexampleEstimate :=
  (lg21GaussianRandomizedGlobalReporterAggregate
    priorMean priorVariance noiseVariance E).toMeasure

/--
The operational individual-output kernel.  Reporters use the unique score
estimator kernel; nonreporters use the equilibrium reporter-resampling base
law.
-/
def lg21GaussianRandomizedIndividualOutputKernel
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    Kernel (ℝ × ℝ) LG21RandomizedCounterexampleEstimate :=
  Kernel.piecewise (lg21GaussianRandomizedReporterEvent_measurable E)
    lg21GaussianRandomizedPrimitiveEstimatorKernel
    (Kernel.const (ℝ × ℝ)
      (lg21GaussianRandomizedKernelBaseMeasure
        priorMean priorVariance noiseVariance E))

/--
The actual access-population output law, obtained by binding the inherited
Gaussian population to the operational individual-output kernel.
-/
def lg21GaussianRandomizedActualAccessMeasure
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    Measure LG21RandomizedCounterexampleEstimate :=
  (lg21GaussianRandomizedPrimitiveLaw
      priorMean priorVariance noiseVariance).bind
    (lg21GaussianRandomizedIndividualOutputKernel
      priorMean priorVariance noiseVariance E)

/-! ## Reporter branch and population-law derivation -/

/--
With positive reporter mass, the base measure is exactly the output law from
binding the conditional reporter population to the one estimator kernel.
-/
theorem lg21GaussianRandomizedKernelBaseMeasure_eq_conditionalReporterBind
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium)
    (hreporter :
      lg21GaussianRandomizedPrimitiveLaw
          priorMean priorVariance noiseVariance
          (lg21GaussianRandomizedReporterEvent E) ≠ 0) :
    lg21GaussianRandomizedKernelBaseMeasure
        priorMean priorVariance noiseVariance E =
      (ProbabilityTheory.cond
          (lg21GaussianRandomizedPrimitiveLaw
            priorMean priorVariance noiseVariance)
          (lg21GaussianRandomizedReporterEvent E)).bind
        lg21GaussianRandomizedPrimitiveEstimatorKernel := by
  let μ := lg21GaussianRandomizedPrimitiveLaw
    priorMean priorVariance noiseVariance
  let reporterEvent := lg21GaussianRandomizedReporterEvent E
  let highEvent := lg21GaussianRandomizedHighScoreEvent
  letI : IsProbabilityMeasure μ :=
    lg21GaussianRandomizedPrimitiveLaw_isProbability
      priorMean priorVariance noiseVariance
  letI : IsProbabilityMeasure
      (ProbabilityTheory.cond μ reporterEvent) :=
    cond_isProbabilityMeasure_of_finite hreporter
      (measure_ne_top μ reporterEvent)
  have hbind :=
    lg21_measure_bind_binary_kernel_eq_binaryMixture
      (ProbabilityTheory.cond μ reporterEvent)
      highEvent lg21GaussianRandomizedHighScoreEvent_measurable
      lg21RandomizedCounterexampleSymmetricLaw
      lg21RandomizedCounterexampleZeroLaw
  rw [lg21GaussianRandomizedPrimitiveEstimatorKernel_eq_piecewise]
  simpa [lg21GaussianRandomizedKernelBaseMeasure,
    lg21GaussianRandomizedGlobalReporterAggregate,
    lg21ConditionalReporterOutputLaw,
    lg21ReporterHighShareNNReal, hreporter, μ, reporterEvent, highEvent]
    using hbind.symm

/--
The unnormalized reporter branch is reporter mass times the common base law.
-/
theorem lg21GaussianRandomizedReporterSublaw_eq_mass_smul_base
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium)
    (hreporter :
      lg21GaussianRandomizedPrimitiveLaw
          priorMean priorVariance noiseVariance
          (lg21GaussianRandomizedReporterEvent E) ≠ 0) :
    ((lg21GaussianRandomizedPrimitiveLaw
        priorMean priorVariance noiseVariance).restrict
          (lg21GaussianRandomizedReporterEvent E)).bind
        lg21GaussianRandomizedPrimitiveEstimatorKernel =
      lg21GaussianRandomizedPrimitiveLaw
          priorMean priorVariance noiseVariance
          (lg21GaussianRandomizedReporterEvent E) •
        lg21GaussianRandomizedKernelBaseMeasure
          priorMean priorVariance noiseVariance E := by
  let μ := lg21GaussianRandomizedPrimitiveLaw
    priorMean priorVariance noiseVariance
  let reporterEvent := lg21GaussianRandomizedReporterEvent E
  letI : IsProbabilityMeasure μ :=
    lg21GaussianRandomizedPrimitiveLaw_isProbability
      priorMean priorVariance noiseVariance
  have hfinite : μ reporterEvent ≠ ⊤ := measure_ne_top μ reporterEvent
  rw [lg21GaussianRandomizedKernelBaseMeasure_eq_conditionalReporterBind
    priorMean priorVariance noiseVariance E hreporter]
  rw [ProbabilityTheory.cond, Measure.bind_smul, smul_smul]
  rw [ENNReal.mul_inv_cancel hreporter hfinite, one_smul]

/--
Exact operational-law identity: the Gaussian population bound to the single
individual-output kernel equals the no-access reporter-resampling base law.
-/
theorem lg21GaussianRandomizedActualAccessMeasure_eq_base
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    lg21GaussianRandomizedActualAccessMeasure
        priorMean priorVariance noiseVariance E =
      lg21GaussianRandomizedKernelBaseMeasure
        priorMean priorVariance noiseVariance E := by
  let μ := lg21GaussianRandomizedPrimitiveLaw
    priorMean priorVariance noiseVariance
  let reporterEvent := lg21GaussianRandomizedReporterEvent E
  letI : IsProbabilityMeasure μ :=
    lg21GaussianRandomizedPrimitiveLaw_isProbability
      priorMean priorVariance noiseVariance
  rw [lg21GaussianRandomizedActualAccessMeasure,
    lg21GaussianRandomizedIndividualOutputKernel]
  rw [lg21_measure_bind_piecewise_kernel]
  rw [Measure.const_comp, Measure.restrict_apply_univ]
  by_cases hreporter : μ reporterEvent = 0
  · have hrestrict : μ.restrict reporterEvent = 0 :=
      Measure.restrict_eq_zero.mpr hreporter
    have hcompl : μ reporterEventᶜ = 1 := by
      have htotal := prob_add_prob_compl
        (μ := μ) (lg21GaussianRandomizedReporterEvent_measurable E)
      simpa [reporterEvent, hreporter] using htotal
    rw [hrestrict, Measure.bind_zero_left, hcompl, one_smul, zero_add]
  · rw [lg21GaussianRandomizedReporterSublaw_eq_mass_smul_base
      priorMean priorVariance noiseVariance E hreporter]
    rw [← add_smul]
    rw [prob_add_prob_compl
      (μ := μ) (lg21GaussianRandomizedReporterEvent_measurable E)]
    rw [one_smul]

/-! ## Exact PMF policy surface and source-timed equilibrium -/

/-- The actual access measure packaged as a PMF on the finite output space. -/
def lg21GaussianRandomizedActualAccessPMF
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    PMF LG21RandomizedCounterexampleEstimate := by
  letI : IsProbabilityMeasure
      (lg21GaussianRandomizedActualAccessMeasure
        priorMean priorVariance noiseVariance E) := by
    rw [lg21GaussianRandomizedActualAccessMeasure_eq_base]
    unfold lg21GaussianRandomizedKernelBaseMeasure
    infer_instance
  exact
    (lg21GaussianRandomizedActualAccessMeasure
      priorMean priorVariance noiseVariance E).toPMF

theorem lg21GaussianRandomizedActualAccessPMF_toMeasure
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    (lg21GaussianRandomizedActualAccessPMF
        priorMean priorVariance noiseVariance E).toMeasure =
      lg21GaussianRandomizedActualAccessMeasure
        priorMean priorVariance noiseVariance E := by
  unfold lg21GaussianRandomizedActualAccessPMF
  rw [Measure.toPMF_toMeasure]

theorem lg21GaussianRandomizedActualAccessPMF_eq_aggregate
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    lg21GaussianRandomizedActualAccessPMF
        priorMean priorVariance noiseVariance E =
      lg21GaussianRandomizedGlobalReporterAggregate
        priorMean priorVariance noiseVariance E := by
  apply PMF.toMeasure_injective
  rw [lg21GaussianRandomizedActualAccessPMF_toMeasure]
  exact
    lg21GaussianRandomizedActualAccessMeasure_eq_base
      priorMean priorVariance noiseVariance E

/--
The source policy surface whose observable access field is the actual bound
population output law, not an independently supplied mixture field.
-/
def lg21GaussianRandomizedKernelPolicySurface
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal) :
    LG21SourcePolicySurface
      ℝ PUnit ℝ LG21RandomizedCounterexampleEstimate where
  Equilibrium := LG21GaussianRandomizedPolicyEquilibrium
  latentAccessEstimate := fun E skill _base ↦
    lg21GaussianRandomizedLatentAccessLaw
      priorMean priorVariance noiseVariance E skill
  latentNoAccessEstimate := fun E _skill _base ↦
    lg21GaussianRandomizedGlobalReporterAggregate
      priorMean priorVariance noiseVariance E
  observableAccessEstimate := fun E _base ↦
    lg21GaussianRandomizedActualAccessPMF
      priorMean priorVariance noiseVariance E
  observableNoAccessEstimate := fun E _base ↦
    lg21GaussianRandomizedGlobalReporterAggregate
      priorMean priorVariance noiseVariance E
  demographicAccessEstimate := fun E ↦
    lg21GaussianRandomizedActualAccessPMF
      priorMean priorVariance noiseVariance E
  demographicNoAccessEstimate := fun E ↦
    lg21GaussianRandomizedGlobalReporterAggregate
      priorMean priorVariance noiseVariance E
  baseOnlyEstimate := fun E _base ↦
    lg21GaussianRandomizedGlobalReporterAggregate
      priorMean priorVariance noiseVariance E
  fullFeatureEstimate := fun _E _base score ↦
    if 0 ≤ score then
      lg21RandomizedCounterexampleSymmetricLaw
    else
      lg21RandomizedCounterexampleZeroLaw

theorem lg21GaussianRandomizedKernelPolicySurface_observablyFair
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal) :
    lg21SourceObservablyFair
      (lg21GaussianRandomizedKernelPolicySurface
        priorMean priorVariance noiseVariance) := by
  intro E base
  exact
    lg21GaussianRandomizedActualAccessPMF_eq_aggregate
      priorMean priorVariance noiseVariance E

theorem lg21GaussianRandomizedKernelPolicySurface_not_testBlank
    (priorMean : ℝ) {priorVariance noiseVariance : NNReal}
    (hpriorVariance : priorVariance ≠ 0)
    (hnoiseVariance : noiseVariance ≠ 0) :
    ¬ lg21SourceTestBlank
      (lg21GaussianRandomizedKernelPolicySurface
        priorMean priorVariance noiseVariance) := by
  intro hblank
  have heq := hblank
    lg21GaussianRandomizedReportAllEquilibrium PUnit.unit (-1)
  apply
    (lg21GaussianRandomizedReportAll_aggregate_ne_zeroLaw
      priorMean hpriorVariance hnoiseVariance)
  change
    lg21GaussianRandomizedGlobalReporterAggregate
        priorMean priorVariance noiseVariance
        lg21GaussianRandomizedReportAllEquilibrium =
      (if 0 ≤ (-1 : ℝ) then
        lg21RandomizedCounterexampleSymmetricLaw
      else lg21RandomizedCounterexampleZeroLaw) at heq
  norm_num at heq
  exact heq

/--
Consistency now records both directions that were independent in the earlier
diagnostic: the actual population law is the bind of the one operational
kernel and equals the base law, while both strategic payoff functions are the
expectations of those same kernel laws.
-/
def lg21GaussianRandomizedKernelEstimationConsistent
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) : Prop :=
  lg21GaussianRandomizedActualAccessMeasure
      priorMean priorVariance noiseVariance E =
    (lg21GaussianRandomizedPrimitiveLaw
        priorMean priorVariance noiseVariance).bind
      (lg21GaussianRandomizedIndividualOutputKernel
        priorMean priorVariance noiseVariance E) ∧
  lg21GaussianRandomizedActualAccessMeasure
      priorMean priorVariance noiseVariance E =
    lg21GaussianRandomizedKernelBaseMeasure
      priorMean priorVariance noiseVariance E ∧
  (∀ score,
    pmfExp
        (if 0 ≤ score then
          lg21RandomizedCounterexampleSymmetricLaw
        else
          lg21RandomizedCounterexampleZeroLaw)
        lg21RandomizedCounterexampleEstimateValue =
      ∫ estimate,
        lg21RandomizedCounterexampleEstimateValue estimate
          ∂(lg21GaussianRandomizedScoreEstimatorKernel score)) ∧
  pmfExp
      (lg21GaussianRandomizedGlobalReporterAggregate
        priorMean priorVariance noiseVariance E)
      lg21RandomizedCounterexampleEstimateValue =
    ∫ estimate,
      lg21RandomizedCounterexampleEstimateValue estimate
        ∂(lg21GaussianRandomizedKernelBaseMeasure
          priorMean priorVariance noiseVariance E)

theorem lg21GaussianRandomizedKernelEstimationConsistent_holds
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    lg21GaussianRandomizedKernelEstimationConsistent
      priorMean priorVariance noiseVariance E := by
  refine ⟨rfl,
    lg21GaussianRandomizedActualAccessMeasure_eq_base
      priorMean priorVariance noiseVariance E, ?_, ?_⟩
  · intro score
    rw [lg21GaussianRandomizedScoreEstimatorKernel_apply]
    by_cases hscore : 0 ≤ score
    · simp only [if_pos hscore]
      exact AppliedModelingLib.pmfExp_eq_integral_toMeasure _ _
    · simp only [if_neg hscore]
      exact AppliedModelingLib.pmfExp_eq_integral_toMeasure _ _
  · exact
      AppliedModelingLib.pmfExp_eq_integral_toMeasure
        (lg21GaussianRandomizedGlobalReporterAggregate
          priorMean priorVariance noiseVariance E)
        lg21RandomizedCounterexampleEstimateValue

/-- The optional-reporting game with consistency tied to the exact kernel chain. -/
def lg21GaussianRandomizedKernelSequentialEquilibriumData
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    LG21OptionalSequentialEquilibriumData ℝ PUnit ℝ :=
  { lg21GaussianRandomizedSequentialEquilibriumData
      priorMean priorVariance noiseVariance E with
    estimationConsistent :=
      lg21GaussianRandomizedKernelEstimationConsistent
        priorMean priorVariance noiseVariance E }

/-- Every measurable pure strategy remains a weak equilibrium of the exact game. -/
theorem lg21GaussianRandomizedKernel_every_measurable_strategy_equilibrium
    (priorMean : ℝ) (priorVariance noiseVariance : NNReal)
    (E : LG21GaussianRandomizedPolicyEquilibrium) :
    lg21OptionalSequentialEquilibrium
      (lg21GaussianRandomizedKernelSequentialEquilibriumData
        priorMean priorVariance noiseVariance E) := by
  have hold :=
    lg21GaussianRandomized_every_measurable_strategy_sequential_equilibrium
      priorMean priorVariance noiseVariance E
  constructor
  · simpa [lg21GaussianRandomizedKernelSequentialEquilibriumData] using hold.1
  · constructor
    · simpa [lg21GaussianRandomizedKernelSequentialEquilibriumData] using
        hold.2.1
    · exact
        lg21GaussianRandomizedKernelEstimationConsistent_holds
          priorMean priorVariance noiseVariance E

/--
Exact source-domain refutation of Theorem 3.2 at its stated randomized-policy
generality.  The final conjunct keeps the operational construction visible in
the paper-facing theorem: for every equilibrium, the access law is the
Gaussian population bound to one estimator-derived individual kernel, and it
equals the no-access base law.
-/
theorem paper_theorem3_2_gaussian_randomized_policy_counterexample
    (priorMean : ℝ) {priorVariance noiseVariance : NNReal}
    (hpriorVariance : priorVariance ≠ 0)
    (hnoiseVariance : noiseVariance ≠ 0) :
    (∀ E : LG21GaussianRandomizedPolicyEquilibrium,
      lg21OptionalSequentialEquilibrium
        (lg21GaussianRandomizedKernelSequentialEquilibriumData
          priorMean priorVariance noiseVariance E)) ∧
      lg21SourceObservablyFair
        (lg21GaussianRandomizedKernelPolicySurface
          priorMean priorVariance noiseVariance) ∧
      ¬ lg21SourceTestBlank
        (lg21GaussianRandomizedKernelPolicySurface
          priorMean priorVariance noiseVariance) ∧
      ∀ E : LG21GaussianRandomizedPolicyEquilibrium,
        lg21GaussianRandomizedActualAccessMeasure
            priorMean priorVariance noiseVariance E =
          (lg21GaussianRandomizedPrimitiveLaw
              priorMean priorVariance noiseVariance).bind
            (lg21GaussianRandomizedIndividualOutputKernel
              priorMean priorVariance noiseVariance E) ∧
        lg21GaussianRandomizedActualAccessMeasure
            priorMean priorVariance noiseVariance E =
          lg21GaussianRandomizedKernelBaseMeasure
            priorMean priorVariance noiseVariance E := by
  refine ⟨
    lg21GaussianRandomizedKernel_every_measurable_strategy_equilibrium
      priorMean priorVariance noiseVariance,
    lg21GaussianRandomizedKernelPolicySurface_observablyFair
      priorMean priorVariance noiseVariance,
    lg21GaussianRandomizedKernelPolicySurface_not_testBlank
      priorMean hpriorVariance hnoiseVariance,
    ?_⟩
  intro E
  exact ⟨rfl,
    lg21GaussianRandomizedActualAccessMeasure_eq_base
      priorMean priorVariance noiseVariance E⟩

end

end LG21TestOptionalPolicies
