import AppliedModelingLib.Foundations.Probability.ExponentialInterarrivalPostArrival

/-!
# Canonical first-report Poisson restart for LBG24

This file proves the concrete `S = T₁` specialization of the paper's residual
waiting-time step on the canonical iid exponential-gap path.  It intentionally
does not identify the sigma-field generated by `T₁` with a general stopped
natural filtration, and does not replace the paper's broader Condition 1 for
an externally selected start time after the first report.
-/

namespace LBG24SpatialUnderreporting

open MeasureTheory
open AppliedModelingLib.Probability.PoissonProcess
open scoped ENNReal NNReal

noncomputable section

/--
Concrete first-report version of Appendix Lemma 2: conditional on the first
canonical report time, the count in a nonnegative future horizon has no-arrival
probability `exp (-rate * horizon)`.  The report path starts at an incident;
the first report is `canonicalFirstArrival`, and the post-report count is the
renewal count of the tail beginning with gap coordinate one.

This is deliberately narrower than the existing arbitrary-forward-stopping
certificate: it proves the paper's natural `S = T₁` case, rather than claiming
a continuous-time strong-Markov theorem for every valid Condition-1 start.
-/
theorem lemma2_canonical_firstReport_conditional_no_report
    {rate : ℝ} (hrate : 0 < rate) (horizon : ℝ≥0) :
    letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
      isProbabilityMeasure_exponentialInterarrivalMeasure hrate
    ∀ᵐ ω ∂exponentialInterarrivalMeasure rate,
      (ProbabilityTheory.condExpKernel (exponentialInterarrivalMeasure rate)
        (MeasurableSpace.comap canonicalFirstArrival inferInstance) ω).real
          {ω' | canonicalRenewalCount (horizon : ℝ)
            (futureInterarrival 1 ω') = 0} =
        noArrivalProb rate (horizon : ℝ) := by
  simpa only using
    canonicalFirstArrival_conditional_futureRenewalCount_zero_real
      hrate (NNReal.coe_nonneg horizon)

/--
The same concrete first-report result expressed as the exponential residual
waiting-time tail used in Appendix Lemma 2.
-/
theorem lemma2_canonical_firstReport_conditional_exponential_tail
    {rate : ℝ} (hrate : 0 < rate) (horizon : ℝ≥0) :
    letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
      isProbabilityMeasure_exponentialInterarrivalMeasure hrate
    ∀ᵐ ω ∂exponentialInterarrivalMeasure rate,
      (ProbabilityTheory.condExpKernel (exponentialInterarrivalMeasure rate)
        (MeasurableSpace.comap canonicalFirstArrival inferInstance) ω).real
          {ω' | canonicalRenewalCount (horizon : ℝ)
            (futureInterarrival 1 ω') = 0} =
        ((AppliedModelingLib.Probability.Exponential.Model.mk rate hrate).measure
          (Set.Ioi (horizon : ℝ))).toReal := by
  filter_upwards [lemma2_canonical_firstReport_conditional_no_report hrate horizon]
    with ω hω
  rw [hω]
  exact noArrivalProb_eq_exponential_tail rate hrate (NNReal.coe_nonneg horizon)

/--
Concrete report-index version of Appendix Lemma 2.  `arrivalPrefix n` is the
time at which `n` reports have occurred, so `n = 1` is the first-report start
used in the main analysis and `n = 2` is the second-report split discussed in
Appendix D.8.2.  The result is conditional on exactly that arrival time and is
proved from the canonical iid exponential path, without a stopped-process
certificate.
-/
theorem lemma2_canonical_reportIndex_conditional_no_report
    {rate : ℝ} (hrate : 0 < rate) (reportIndex : ℕ) (horizon : ℝ≥0) :
    letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
      isProbabilityMeasure_exponentialInterarrivalMeasure hrate
    ∀ᵐ ω ∂exponentialInterarrivalMeasure rate,
      (ProbabilityTheory.condExpKernel (exponentialInterarrivalMeasure rate)
        (MeasurableSpace.comap (arrivalPrefix reportIndex) inferInstance) ω).real
          {ω' | canonicalRenewalCount (horizon : ℝ)
            (futureInterarrival reportIndex ω') = 0} =
        noArrivalProb rate (horizon : ℝ) := by
  simpa only using
    arrivalPrefix_conditional_futureRenewalCount_zero_real
      hrate (NNReal.coe_nonneg horizon) reportIndex

/--
The report-index restart conclusion in the exponential survival-tail form.
This includes the paper's first-report construction and the source's optional
second-report validation construction as the `reportIndex = 1` and
`reportIndex = 2` instances respectively.
-/
theorem lemma2_canonical_reportIndex_conditional_exponential_tail
    {rate : ℝ} (hrate : 0 < rate) (reportIndex : ℕ) (horizon : ℝ≥0) :
    letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
      isProbabilityMeasure_exponentialInterarrivalMeasure hrate
    ∀ᵐ ω ∂exponentialInterarrivalMeasure rate,
      (ProbabilityTheory.condExpKernel (exponentialInterarrivalMeasure rate)
        (MeasurableSpace.comap (arrivalPrefix reportIndex) inferInstance) ω).real
          {ω' | canonicalRenewalCount (horizon : ℝ)
            (futureInterarrival reportIndex ω') = 0} =
        ((AppliedModelingLib.Probability.Exponential.Model.mk rate hrate).measure
          (Set.Ioi (horizon : ℝ))).toReal := by
  filter_upwards [lemma2_canonical_reportIndex_conditional_no_report
    hrate reportIndex horizon] with ω hω
  rw [hω]
  exact noArrivalProb_eq_exponential_tail rate hrate (NNReal.coe_nonneg horizon)

end
end LBG24SpatialUnderreporting
