import AppliedModelingLib.Queueing.NonpreemptivePriorityFixedTraceMeasurability
import AppliedModelingLib.Queueing.NonpreemptivePriorityCompletionLedger
import Mathlib.Tactic

/-!
# Fixed-skeleton steps for nonpreemptive-priority traces

The Borel response evaluator records a static service order.  This module
begins the complementary exactness layer: fixed-state operations are evaluated
pointwise by the existing literal nonpreemptive-priority dynamics.
-/

namespace AppliedModelingLib.Queueing

noncomputable section

variable {Ω : Type*} [MeasurableSpace Ω]
variable {n : ℕ} {JobId : Type*}

/-- Clear the observational completion ledger of a fixed coordinate state
without changing any live queue coordinate. -/
def NonpreemptivePriorityFixedStateCoordinate.clearCompleted
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  { currentTime := state.currentTime
    active := state.active
    waiting := state.waiting
    completed := [] }

/-- Clearing the fixed coordinate ledger agrees with literal ledger clearing. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_clearCompleted
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    (state.clearCompleted).eval omega =
      clearNonpreemptivePriorityCompletionLedger (state.eval omega) := by
  rfl

/-- Fixed ledger clearing preserves Borel coordinate data. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.clearCompleted
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    (state.clearCompleted).CoordinatesMeasurable := by
  refine ⟨hstate.1, hstate.2.1, hstate.2.2.1, ?_⟩
  intro entry hentry
  simp [NonpreemptivePriorityFixedStateCoordinate.clearCompleted] at hentry

/-- Read a fixed labelled completion ledger in chronological order, returning
zero if the requested label has not yet completed. -/
def fixedPriorityCompletionResponseFromLedger
    (identifier : JobId) :
    List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId × (Ω → ℝ)) → Ω → ℝ
  | [], _ => 0
  | entry :: entries, omega => by
      classical
      exact if entry.1.identifier = identifier then entry.2 omega
        else fixedPriorityCompletionResponseFromLedger identifier entries omega

/-- A fixed-ledger completion response is Borel whenever its retained epoch
coordinates are Borel. -/
theorem measurable_fixedPriorityCompletionResponseFromLedger
    (identifier : JobId) :
    ∀ (entries : List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId × (Ω → ℝ))),
      (∀ entry ∈ entries, Measurable entry.2) →
      Measurable (fixedPriorityCompletionResponseFromLedger identifier entries) := by
  intro entries
  induction entries with
  | nil => intro hentries; simp [fixedPriorityCompletionResponseFromLedger]
  | cons entry entries ih =>
      intro hentries
      have hepoch : Measurable entry.2 := hentries entry (by simp)
      have htail : ∀ later ∈ entries, Measurable later.2 := by
        intro later hlater
        exact hentries later (by simp [hlater])
      by_cases hidentifier : entry.1.identifier = identifier
      · simpa [fixedPriorityCompletionResponseFromLedger, hidentifier] using hepoch
      · simpa [fixedPriorityCompletionResponseFromLedger, hidentifier] using ih htail

/-- The Borel completion response generated by a static state coordinate. -/
def fixedPriorityCompletionResponse
    (identifier : JobId) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) : Ω → ℝ :=
  fixedPriorityCompletionResponseFromLedger identifier state.completed.reverse

/-- Completion response is Borel for every Borel fixed state coordinate. -/
theorem measurable_fixedPriorityCompletionResponse
    (identifier : JobId) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    Measurable (fixedPriorityCompletionResponse identifier state) := by
  apply measurable_fixedPriorityCompletionResponseFromLedger
  intro entry hentry
  exact (hstate.2.2.2 entry (by simpa [fixedPriorityCompletionResponse] using hentry)).2

/-- Evaluation preserves whether any fixed FIFO list is nonempty. -/
theorem hasPriorityWaitingJob_fixedState_eval_iff
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    hasPriorityWaitingJob (state.eval omega) ↔ hasFixedPriorityWaitingJob state := by
  constructor <;> rintro ⟨i, hi⟩ <;> refine ⟨i, ?_⟩ <;>
    simpa [hasPriorityWaitingJob, hasFixedPriorityWaitingJob,
      NonpreemptivePriorityFixedStateCoordinate.eval] using hi

/-- The priority selector is insensitive to replacing a backlog function by
an extensionally equal one. -/
theorem nextNonpreemptivePriority_eq_of_backlog_eq
    (first second : Fin n → ℕ) (hbacklog : first = second)
    (hfirst : ∃ i, 0 < first i) (hsecond : ∃ i, 0 < second i) :
    nextNonpreemptivePriority first hfirst = nextNonpreemptivePriority second hsecond := by
  subst second
  rfl

/-- The literal selector after evaluating a fixed state agrees with the
selector of its static FIFO shape. -/
theorem nextPriorityWaitingClass_fixedState_eval_eq
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (omega : Ω) (hwaiting : hasFixedPriorityWaitingJob state) :
    nextPriorityWaitingClass (state.eval omega)
      ((hasPriorityWaitingJob_fixedState_eval_iff state omega).mpr hwaiting) =
      nextNonpreemptivePriority (fun i => (state.waiting i).length) hwaiting := by
  apply nextNonpreemptivePriority_eq_of_backlog_eq
    (fun i => ((state.eval omega).waiting i).length)
    (fun i => (state.waiting i).length)
  · funext i
    simp [NonpreemptivePriorityFixedStateCoordinate.eval]

/-- Select the next waiting job using only a fixed state shape. -/
noncomputable def NonpreemptivePriorityFixedStateCoordinate.startNext
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId := by
  classical
  exact match state.active with
  | some _ => state
  | none =>
      if hwaiting : hasFixedPriorityWaitingJob state then
        let i := nextNonpreemptivePriority (fun j => (state.waiting j).length) hwaiting
        match state.waiting i with
        | [] => state
        | job :: tail =>
            { currentTime := state.currentTime
              active := some (job, job.serviceWork)
              waiting := fun j => if j = i then tail else state.waiting j
              completed := state.completed }
      else state

/-- Fixed-shape selection evaluates to the literal priority selection. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_startNext
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    (state.startNext).eval omega = startNextNonpreemptivePriorityJob (state.eval omega) := by
  classical
  cases hactive : state.active with
  | some active =>
      simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive,
        NonpreemptivePriorityFixedStateCoordinate.eval,
        startNextNonpreemptivePriorityJob]
  | none =>
      by_cases hwaiting : hasFixedPriorityWaitingJob state
      · let selected : Fin n :=
          nextNonpreemptivePriority (fun j => (state.waiting j).length) hwaiting
        have hwaitingEval : hasPriorityWaitingJob (state.eval omega) :=
          (hasPriorityWaitingJob_fixedState_eval_iff state omega).mpr hwaiting
        have hselected : nextPriorityWaitingClass (state.eval omega) hwaitingEval = selected := by
          simpa [selected] using
            nextPriorityWaitingClass_fixedState_eval_eq state omega hwaiting
        have hactiveEval : (state.eval omega).active = none := by
          simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
        cases hhead : state.waiting selected with
        | nil =>
            have hpositive : 0 < (state.waiting selected).length :=
              nextNonpreemptivePriority_positive (fun j => (state.waiting j).length)
                hwaiting
            simp [hhead] at hpositive
        | cons job tail =>
            have hfixed : state.startNext =
                { currentTime := state.currentTime
                  active := some (job, job.serviceWork)
                  waiting := fun j => if j = selected then tail else state.waiting j
                  completed := state.completed } := by
              simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive,
                hwaiting, selected, hhead]
            rw [hfixed]
            unfold startNextNonpreemptivePriorityJob
            rw [hactiveEval, dif_pos hwaitingEval, hselected]
            have hwaitingEq : (fun j =>
                (if j = selected then tail else state.waiting j).map
                  fun coordinate => coordinate.eval omega) =
                Function.update (fun j =>
                  (state.waiting j).map fun coordinate => coordinate.eval omega)
                  selected (tail.map fun coordinate => coordinate.eval omega) := by
              funext j
              by_cases hj : j = selected
              · subst j
                simp
              · simp [hj]
            simp only [NonpreemptivePriorityFixedStateCoordinate.eval]
            rw [hhead, hwaitingEq]
            simp [NonpreemptivePriorityFixedJobCoordinate.eval]
      · have hnotEval : ¬ hasPriorityWaitingJob (state.eval omega) := by
          intro h
          exact hwaiting ((hasPriorityWaitingJob_fixedState_eval_iff state omega).mp h)
        have hactiveEval : (state.eval omega).active = none := by
          simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
        have hfixed : state.startNext = state := by
          simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive, hwaiting]
        rw [hfixed]
        unfold startNextNonpreemptivePriorityJob
        rw [hactiveEval, dif_neg hnotEval]

/-- Static priority selection preserves Borel real-coordinate data. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.startNext
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    (state.startNext).CoordinatesMeasurable := by
  classical
  rcases hstate with ⟨htime, hactiveCoordinates, hwaitingCoordinates,
    hcompletedCoordinates⟩
  cases hactive : state.active with
  | some active =>
      have hfixed : state.startNext = state := by
        simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive]
      rw [hfixed]
      exact ⟨htime, hactiveCoordinates, hwaitingCoordinates, hcompletedCoordinates⟩
  | none =>
      by_cases hwaiting : hasFixedPriorityWaitingJob state
      · let selected : Fin n :=
          nextNonpreemptivePriority (fun j => (state.waiting j).length) hwaiting
        cases hhead : state.waiting selected with
        | nil =>
            have hpositive : 0 < (state.waiting selected).length :=
              nextNonpreemptivePriority_positive (fun j => (state.waiting j).length)
                hwaiting
            simp [hhead] at hpositive
        | cons job tail =>
            have hfixed : state.startNext =
                { currentTime := state.currentTime
                  active := some (job, job.serviceWork)
                  waiting := fun j => if j = selected then tail else state.waiting j
                  completed := state.completed } := by
              simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive,
                hwaiting, selected, hhead]
            have hjob : job.CoordinatesMeasurable :=
              hwaitingCoordinates selected job (by simp [hhead])
            rw [hfixed]
            refine ⟨htime, ?_, ?_, hcompletedCoordinates⟩
            · intro entry hentry
              simp at hentry
              subst entry
              exact ⟨hjob, hjob.2⟩
            · intro j later hlater
              by_cases hj : j = selected
              · subst j
                have htail : later ∈ tail := by simpa using hlater
                apply hwaitingCoordinates selected later
                rw [hhead]
                exact List.mem_cons.mpr (Or.inr htail)
              · have hprior : later ∈ state.waiting j := by
                  simpa [hj] using hlater
                exact hwaitingCoordinates j later hprior
      · have hfixed : state.startNext = state := by
          simp [NonpreemptivePriorityFixedStateCoordinate.startNext, hactive, hwaiting]
        rw [hfixed]
        exact ⟨htime, hactiveCoordinates, hwaitingCoordinates, hcompletedCoordinates⟩

/-- Admit a fixed-label job after performing the fixed-shape nonpreemptive
start-next operation. -/
noncomputable def NonpreemptivePriorityFixedStateCoordinate.admit
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  match (state.startNext).active with
  | none =>
      { currentTime := (state.startNext).currentTime
        active := some (job, job.serviceWork)
        waiting := (state.startNext).waiting
        completed := (state.startNext).completed }
  | some _ => (state.startNext).enqueue job

/-- Fixed-shape admission evaluates to the literal admission operation. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_admit
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId) (omega : Ω) :
    (state.admit job).eval omega =
      admitNonpreemptivePriorityJob (state.eval omega) (job.eval omega) := by
  classical
  have hpreparedEval : (state.startNext).eval omega =
      startNextNonpreemptivePriorityJob (state.eval omega) := by
    exact state.eval_startNext omega
  cases hactive : (state.startNext).active with
  | none =>
      have hactiveEval : ((state.startNext).eval omega).active = none := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      unfold NonpreemptivePriorityFixedStateCoordinate.admit
      rw [hactive]
      unfold admitNonpreemptivePriorityJob
      rw [← hpreparedEval]
      dsimp only
      rw [hactiveEval]
      simp [NonpreemptivePriorityFixedStateCoordinate.eval,
        NonpreemptivePriorityFixedJobCoordinate.eval]
  | some active =>
      have hactiveEval : ((state.startNext).eval omega).active =
          some (active.1.eval omega, active.2 omega) := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      unfold NonpreemptivePriorityFixedStateCoordinate.admit
      rw [hactive]
      rw [NonpreemptivePriorityFixedStateCoordinate.eval_enqueue]
      unfold admitNonpreemptivePriorityJob
      rw [← hpreparedEval]
      dsimp only
      rw [hactiveEval]

/-- Admission preserves the fixed-state Borel coordinate invariant. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.admit
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable)
    (hjob : job.CoordinatesMeasurable) :
    (state.admit job).CoordinatesMeasurable := by
  have hprepared : (state.startNext).CoordinatesMeasurable := hstate.startNext
  rcases hprepared with ⟨htime, hactiveCoordinates, hwaitingCoordinates,
    hcompletedCoordinates⟩
  cases hactive : (state.startNext).active with
  | none =>
      unfold NonpreemptivePriorityFixedStateCoordinate.admit
      rw [hactive]
      refine ⟨htime, ?_, hwaitingCoordinates, hcompletedCoordinates⟩
      intro entry hentry
      simp at hentry
      subst entry
      exact ⟨hjob, hjob.2⟩
  | some active =>
      have henqueue : ((state.startNext).enqueue job).CoordinatesMeasurable :=
        NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.enqueue
          (state.startNext) job
          ⟨htime, hactiveCoordinates, hwaitingCoordinates, hcompletedCoordinates⟩ hjob
      unfold NonpreemptivePriorityFixedStateCoordinate.admit
      rw [hactive]
      exact henqueue

/-- Complete the fixed-shape active job at the current coordinate clock, then
start the next fixed-shape waiting job. -/
noncomputable def NonpreemptivePriorityFixedStateCoordinate.complete
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  match state.active with
  | none => state
  | some (job, _) =>
      ({ currentTime := state.currentTime
         active := none
         waiting := state.waiting
         completed := (job, state.currentTime) :: state.completed } :
        NonpreemptivePriorityFixedStateCoordinate Ω n JobId).startNext

/-- Fixed-shape completion evaluates to the literal nonpreemptive completion
operation. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_complete
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    (state.complete).eval omega = completeNonpreemptivePriorityWorkJob (state.eval omega) := by
  classical
  cases hactive : state.active with
  | none =>
      simp [NonpreemptivePriorityFixedStateCoordinate.complete, hactive,
        NonpreemptivePriorityFixedStateCoordinate.eval,
        completeNonpreemptivePriorityWorkJob]
  | some active =>
      let cleared : NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
        { currentTime := state.currentTime
          active := none
          waiting := state.waiting
          completed := (active.1, state.currentTime) :: state.completed }
      have hclearedEval : cleared.eval omega =
          { (state.eval omega) with
            active := none
            completed := (active.1.eval omega, state.currentTime omega) ::
              (state.eval omega).completed } := by
        simp [cleared, NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      have hactiveEval : (state.eval omega).active =
          some (active.1.eval omega, active.2 omega) := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      have hcomplete : state.complete = cleared.startNext := by
        simp [NonpreemptivePriorityFixedStateCoordinate.complete, hactive, cleared]
      rw [hcomplete, cleared.eval_startNext, hclearedEval]
      unfold completeNonpreemptivePriorityWorkJob
      rw [hactiveEval]
      rfl

/-- Completion preserves coordinatewise Borelness, including the newly
recorded literal completion epoch. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.complete
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    (state.complete).CoordinatesMeasurable := by
  classical
  rcases hstate with ⟨htime, hactiveCoordinates, hwaitingCoordinates,
    hcompletedCoordinates⟩
  cases hactive : state.active with
  | none =>
      simp [NonpreemptivePriorityFixedStateCoordinate.complete, hactive]
      exact ⟨htime, hactiveCoordinates, hwaitingCoordinates, hcompletedCoordinates⟩
  | some active =>
      have hactiveCoordinates' := hactiveCoordinates active (by simp [hactive])
      let cleared : NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
        { currentTime := state.currentTime
          active := none
          waiting := state.waiting
          completed := (active.1, state.currentTime) :: state.completed }
      have hcleared : cleared.CoordinatesMeasurable := by
        refine ⟨htime, ?_, hwaitingCoordinates, ?_⟩
        · intro entry hentry
          simp [cleared] at hentry
        · intro entry hentry
          rcases List.mem_cons.mp (by simpa [cleared] using hentry) with hnew | hprior
          · subst entry
            exact ⟨hactiveCoordinates'.1, htime⟩
          · exact hcompletedCoordinates entry hprior
      have hcomplete : state.complete = cleared.startNext := by
        simp [NonpreemptivePriorityFixedStateCoordinate.complete, hactive, cleared]
      rw [hcomplete]
      exact hcleared.startNext

/-- Replace the clock coordinate while leaving every discrete state component
and every job coordinate fixed. -/
def NonpreemptivePriorityFixedStateCoordinate.withCurrentTime
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (time : Ω → ℝ) : NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  { currentTime := time
    active := state.active
    waiting := state.waiting
    completed := state.completed }

/-- Replacing a coordinate clock commutes with literal state evaluation. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_withCurrentTime
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (time : Ω → ℝ) (omega : Ω) :
    (state.withCurrentTime time).eval omega =
      { (state.eval omega) with currentTime := time omega } := by
  rfl

/-- A Borel replacement clock preserves the fixed-state coordinate invariant. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.withCurrentTime
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (time : Ω → ℝ) (hstate : state.CoordinatesMeasurable)
    (htime : Measurable time) :
    (state.withCurrentTime time).CoordinatesMeasurable := by
  rcases hstate with ⟨_, hactive, hwaiting, hcompleted⟩
  exact ⟨htime, hactive, hwaiting, hcompleted⟩

/-- Advance a fixed active service to its exact completion epoch and then
perform the fixed-shape completion operation.  It is a static counterpart of
the completed-service branch of the literal advance recursion. -/
noncomputable def NonpreemptivePriorityFixedStateCoordinate.finishActive
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  match state.active with
  | none => state
  | some (_, residual) =>
      (state.withCurrentTime (fun omega => state.currentTime omega + residual omega)).complete

/-- The fixed completed-service step evaluates to the corresponding literal
completion branch. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_finishActive
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    (state.finishActive).eval omega =
      match (state.eval omega).active with
      | none => state.eval omega
      | some (_, residual) => completeNonpreemptivePriorityWorkJob
          { (state.eval omega) with currentTime := state.currentTime omega + residual } := by
  cases hactive : state.active with
  | none =>
      have hactiveEval : (state.eval omega).active = none := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      simp [NonpreemptivePriorityFixedStateCoordinate.finishActive, hactive, hactiveEval]
  | some active =>
      have hactiveEval : (state.eval omega).active =
          some (active.1.eval omega, active.2 omega) := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      simp only [NonpreemptivePriorityFixedStateCoordinate.finishActive, hactive,
        NonpreemptivePriorityFixedStateCoordinate.eval_complete,
        NonpreemptivePriorityFixedStateCoordinate.eval_withCurrentTime]
      rw [hactiveEval]

/-- A completed-service fixed step preserves coordinatewise Borelness. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.finishActive
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    (state.finishActive).CoordinatesMeasurable := by
  cases hactive : state.active with
  | none =>
      simpa [NonpreemptivePriorityFixedStateCoordinate.finishActive, hactive] using hstate
  | some active =>
      have hresidual : Measurable active.2 := hstate.2.1 active (by simp [hactive]) |>.2
      have hclock : Measurable (fun omega => state.currentTime omega + active.2 omega) :=
        hstate.1.add hresidual
      simp only [NonpreemptivePriorityFixedStateCoordinate.finishActive, hactive]
      exact NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.complete
        (state.withCurrentTime (fun omega => state.currentTime omega + active.2 omega))
        (NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.withCurrentTime
          state _ hstate hclock)

/-- Advance to a target clock without completing the currently active job.
When an active job is present, its residual coordinate is reduced by exactly
the elapsed time.  This is the noncompletion branch of literal advance. -/
noncomputable def NonpreemptivePriorityFixedStateCoordinate.advanceWithoutCompletion
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (target : Ω → ℝ) : NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  match state.active with
  | none => state.withCurrentTime target
  | some (job, residual) =>
      { currentTime := target
        active := some (job, fun omega => residual omega -
          (target omega - state.currentTime omega))
        waiting := state.waiting
        completed := state.completed }

/-- The fixed noncompletion step evaluates to its literal state update. -/
theorem NonpreemptivePriorityFixedStateCoordinate.eval_advanceWithoutCompletion
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (target : Ω → ℝ) (omega : Ω) :
    (state.advanceWithoutCompletion target).eval omega =
      match (state.eval omega).active with
      | none => { (state.eval omega) with currentTime := target omega }
      | some (job, residual) =>
          { (state.eval omega) with
            currentTime := target omega
            active := some (job, residual - (target omega - state.currentTime omega)) } := by
  cases hactive : state.active with
  | none =>
      have hactiveEval : (state.eval omega).active = none := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      simp [NonpreemptivePriorityFixedStateCoordinate.advanceWithoutCompletion, hactive,
        NonpreemptivePriorityFixedStateCoordinate.eval_withCurrentTime, hactiveEval]
  | some active =>
      have hactiveEval : (state.eval omega).active =
          some (active.1.eval omega, active.2 omega) := by
        simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]
      simp [NonpreemptivePriorityFixedStateCoordinate.advanceWithoutCompletion, hactive,
        NonpreemptivePriorityFixedStateCoordinate.eval]

/-- The fixed noncompletion step has Borel coordinates whenever its target
clock does. -/
theorem NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.advanceWithoutCompletion
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (target : Ω → ℝ) (hstate : state.CoordinatesMeasurable)
    (htarget : Measurable target) :
    (state.advanceWithoutCompletion target).CoordinatesMeasurable := by
  cases hactive : state.active with
  | none =>
      simpa [NonpreemptivePriorityFixedStateCoordinate.advanceWithoutCompletion, hactive] using
        (NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.withCurrentTime
          state target hstate htarget)
  | some active =>
      have hactiveCoordinates := hstate.2.1 active (by simp [hactive])
      simp only [NonpreemptivePriorityFixedStateCoordinate.advanceWithoutCompletion, hactive]
      refine ⟨htarget, ?_, hstate.2.2.1, hstate.2.2.2⟩
      intro entry hentry
      simp at hentry
      subst entry
      exact ⟨hactiveCoordinates.1,
        hactiveCoordinates.2.sub (htarget.sub hstate.1)⟩

/-- Iterate the static completed-service transition a fixed finite number of
times.  The count is discrete skeleton data, so it introduces no random
branching. -/
noncomputable def iterateFixedPriorityCompletions : ℕ →
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId →
      NonpreemptivePriorityFixedStateCoordinate Ω n JobId
  | 0, state => state
  | count + 1, state => iterateFixedPriorityCompletions count state.finishActive

/-- A fixed number of completed-service transitions preserves Borel
coordinate data. -/
theorem coordinatesMeasurable_iterateFixedPriorityCompletions
    (count : ℕ) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    (iterateFixedPriorityCompletions count state).CoordinatesMeasurable := by
  induction count generalizing state with
  | zero => simpa [iterateFixedPriorityCompletions] using hstate
  | succ count ih =>
      simpa [iterateFixedPriorityCompletions] using
        ih state.finishActive hstate.finishActive

/-- The literal counterpart of one completion-at-residual service step. -/
noncomputable def finishActiveNonpreemptivePriorityWorkState
    (state : NonpreemptivePriorityWorkState n JobId) :
    NonpreemptivePriorityWorkState n JobId :=
  match state.active with
  | none => state
  | some (_, residual) => completeNonpreemptivePriorityWorkJob
      { state with currentTime := state.currentTime + residual }

/-- Fixed coordinate completion iterations evaluate pointwise to their literal
finite counterparts. -/
theorem eval_iterateFixedPriorityCompletions
    (count : ℕ) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (omega : Ω) :
    (iterateFixedPriorityCompletions count state).eval omega =
      Nat.iterate finishActiveNonpreemptivePriorityWorkState count (state.eval omega) := by
  induction count generalizing state with
  | zero => rfl
  | succ count ih =>
      rw [iterateFixedPriorityCompletions, ih, state.eval_finishActive]
      rfl

/-- The terminal action of one fixed finite priority-advance skeleton.  A
`hold` leaves the final static state unchanged; `advance` executes the unique
noncompletion state update to the target clock. -/
inductive NonpreemptivePriorityFixedAdvanceTerminal where
  | hold
  | advance
  deriving DecidableEq, Countable

/-- The Borel inequalities certifying a prescribed finite prefix of literal
service completions.  Each recurrence state has a fixed discrete shape, so the
only tests are inequalities between explicit real coordinates. -/
def fixedPriorityCompletionPrefixMatches
    (target : Ω → ℝ) : ℕ →
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId → Ω → Prop
  | 0, _, _ => True
  | count + 1, state, omega =>
      state.currentTime omega < target omega ∧
        match state.active with
        | none => False
        | some (_, residual) =>
            residual omega ≤ target omega - state.currentTime omega ∧
              fixedPriorityCompletionPrefixMatches target count state.finishActive omega

/-- A fixed completion prefix is a Borel fiber whenever the initial static
state and target clock have Borel coordinates. -/
theorem measurableSet_fixedPriorityCompletionPrefixMatches
    (target : Ω → ℝ) (htarget : Measurable target) :
    ∀ (count : ℕ) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId),
      state.CoordinatesMeasurable →
      MeasurableSet {omega | fixedPriorityCompletionPrefixMatches target count state omega} := by
  intro count
  induction count with
  | zero =>
      intro state hstate
      simp [fixedPriorityCompletionPrefixMatches]
  | succ count ih =>
      intro state hstate
      cases hactive : state.active with
      | none =>
          simp [fixedPriorityCompletionPrefixMatches, hactive]
      | some active =>
          have hactiveCoordinates := hstate.2.1 active (by simp [hactive])
          have hfinish := hstate.finishActive
          simpa only [fixedPriorityCompletionPrefixMatches, hactive, Set.mem_inter_iff,
            Set.mem_setOf_eq] using
            ((measurableSet_lt hstate.1 htarget).inter
              ((measurableSet_le hactiveCoordinates.2 (htarget.sub hstate.1)).inter
                (ih state.finishActive hfinish)))

/-- The Borel terminal condition left after a prescribed number of service
completions.  The zero-fuel active case is deliberately a `hold`: the literal
finite recursion cannot partially serve an active job without a remaining
completion budget. -/
def fixedPriorityAdvanceTerminalMatches
    (remainingFuel : ℕ) (target : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (terminal : NonpreemptivePriorityFixedAdvanceTerminal) (omega : Ω) : Prop :=
  match terminal with
  | .hold => target omega ≤ state.currentTime omega ∨
      (remainingFuel = 0 ∧ state.currentTime omega < target omega ∧ state.active.isSome)
  | .advance => state.currentTime omega < target omega ∧
      match state.active with
      | none => True
      | some (_, residual) => 0 < remainingFuel ∧
          target omega - state.currentTime omega < residual omega

/-- Every terminal condition of a fixed priority-advance skeleton is Borel. -/
theorem measurableSet_fixedPriorityAdvanceTerminalMatches
    (remainingFuel : ℕ) (target : Ω → ℝ) (htarget : Measurable target)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable)
    (terminal : NonpreemptivePriorityFixedAdvanceTerminal) :
    MeasurableSet {omega |
      fixedPriorityAdvanceTerminalMatches remainingFuel target state terminal omega} := by
  cases terminal with
  | hold =>
      by_cases hremaining : remainingFuel = 0
      · cases hactive : state.active with
        | none =>
            simp [fixedPriorityAdvanceTerminalMatches, hremaining, hactive,
              measurableSet_le htarget hstate.1]
        | some active =>
            convert (measurableSet_le htarget hstate.1).union
              (measurableSet_lt hstate.1 htarget) using 1
            ext omega
            simp [fixedPriorityAdvanceTerminalMatches, hremaining, hactive]
      · simp [fixedPriorityAdvanceTerminalMatches, hremaining,
          measurableSet_le htarget hstate.1]
  | advance =>
      cases hactive : state.active with
      | none =>
          convert measurableSet_lt hstate.1 htarget using 1
          ext omega
          simp [fixedPriorityAdvanceTerminalMatches, hactive]
      | some active =>
          have hresidual : Measurable active.2 := hstate.2.1 active (by simp [hactive]) |>.2
          by_cases hremaining : 0 < remainingFuel
          · convert (measurableSet_lt hstate.1 htarget).inter
                (measurableSet_lt (htarget.sub hstate.1) hresidual) using 1
            ext omega
            simp [fixedPriorityAdvanceTerminalMatches, hactive, hremaining]
          · simp [fixedPriorityAdvanceTerminalMatches, hactive, hremaining]

/-- The Borel branch predicate for one literal finite priority advance.  The
completion count and terminal choice are countable skeleton data. -/
def fixedPriorityAdvanceBranchMatches
    (fuel : ℕ) (target : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (omega : Ω) : Prop :=
  completionCount ≤ fuel ∧
    fixedPriorityCompletionPrefixMatches target completionCount state omega ∧
      fixedPriorityAdvanceTerminalMatches (fuel - completionCount) target
        (iterateFixedPriorityCompletions completionCount state) terminal omega

/-- A completion-prefix branch condition only reads the target clock at the
carrier point being tested. -/
theorem fixedPriorityCompletionPrefixMatches_congr_target
    (first second : Ω → ℝ) (omega : Ω) (hvalue : first omega = second omega) :
    ∀ (count : ℕ) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId),
      fixedPriorityCompletionPrefixMatches first count state omega ↔
        fixedPriorityCompletionPrefixMatches second count state omega := by
  intro count
  induction count with
  | zero => intro state; simp [fixedPriorityCompletionPrefixMatches]
  | succ count ih =>
      intro state
      cases hactive : state.active with
      | none => simp [fixedPriorityCompletionPrefixMatches, hactive]
      | some active =>
          simp only [fixedPriorityCompletionPrefixMatches, hactive]
          constructor
          · rintro ⟨htime, hresidual, htail⟩
            exact ⟨by simpa [hvalue] using htime,
              by simpa [hvalue] using hresidual,
              (ih state.finishActive).mp htail⟩
          · rintro ⟨htime, hresidual, htail⟩
            exact ⟨by simpa [hvalue] using htime,
              by simpa [hvalue] using hresidual,
              (ih state.finishActive).mpr htail⟩

/-- A fixed terminal branch condition only reads the target clock at the
carrier point being tested. -/
theorem fixedPriorityAdvanceTerminalMatches_congr_target
    (remainingFuel : ℕ) (first second : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (omega : Ω) (hvalue : first omega = second omega) :
    fixedPriorityAdvanceTerminalMatches remainingFuel first state terminal omega ↔
      fixedPriorityAdvanceTerminalMatches remainingFuel second state terminal omega := by
  cases terminal <;> cases hactive : state.active <;>
    simp [fixedPriorityAdvanceTerminalMatches, hactive, hvalue]

/-- A complete finite advance branch condition only reads its target clock at
the carrier point being tested. -/
theorem fixedPriorityAdvanceBranchMatches_congr_target
    (fuel : ℕ) (first second : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (omega : Ω) (hvalue : first omega = second omega) :
    fixedPriorityAdvanceBranchMatches fuel first state completionCount terminal omega ↔
      fixedPriorityAdvanceBranchMatches fuel second state completionCount terminal omega := by
  simp only [fixedPriorityAdvanceBranchMatches]
  rw [fixedPriorityCompletionPrefixMatches_congr_target first second omega hvalue,
    fixedPriorityAdvanceTerminalMatches_congr_target (fuel - completionCount)
      first second (iterateFixedPriorityCompletions completionCount state) terminal omega hvalue]

/-- Every fixed finite-priority advance branch is a Borel set. -/
theorem measurableSet_fixedPriorityAdvanceBranchMatches
    (fuel : ℕ) (target : Ω → ℝ) (htarget : Measurable target)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal) :
    MeasurableSet {omega |
      fixedPriorityAdvanceBranchMatches fuel target state completionCount terminal omega} := by
  by_cases hcount : completionCount ≤ fuel
  · simp only [fixedPriorityAdvanceBranchMatches, hcount, true_and]
    exact (measurableSet_fixedPriorityCompletionPrefixMatches target htarget
      completionCount state hstate).inter
      (measurableSet_fixedPriorityAdvanceTerminalMatches (fuel - completionCount)
        target htarget (iterateFixedPriorityCompletions completionCount state)
        (coordinatesMeasurable_iterateFixedPriorityCompletions completionCount state hstate)
        terminal)
  · simp [fixedPriorityAdvanceBranchMatches, hcount]

/-- Execute a fixed finite priority-advance skeleton without inspecting the
sample.  Equality with the literal recursive advance is proved separately on
its Borel branch fiber. -/
noncomputable def runFixedPriorityAdvanceBranch
    (target : Ω → ℝ) (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  match terminal with
  | .hold => iterateFixedPriorityCompletions completionCount state
  | .advance => (iterateFixedPriorityCompletions completionCount state).advanceWithoutCompletion target

/-- The fixed branch evaluator preserves Borel coordinate data. -/
theorem coordinatesMeasurable_runFixedPriorityAdvanceBranch
    (target : Ω → ℝ) (htarget : Measurable target)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal) :
    (runFixedPriorityAdvanceBranch target state completionCount terminal).CoordinatesMeasurable := by
  cases terminal with
  | hold =>
      simpa [runFixedPriorityAdvanceBranch] using
        coordinatesMeasurable_iterateFixedPriorityCompletions completionCount state hstate
  | advance =>
      exact NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.advanceWithoutCompletion
        (iterateFixedPriorityCompletions completionCount state) target
        (coordinatesMeasurable_iterateFixedPriorityCompletions completionCount state hstate)
        htarget

/-- Every sample belongs to some countable completion-count/terminal branch
of a finite literal priority advance.  The witness records the actual finite
completion path; it does not introduce an additional queueing assumption. -/
theorem exists_fixedPriorityAdvanceBranchMatches
    (fuel : ℕ) (target : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    ∃ completionCount terminal,
      fixedPriorityAdvanceBranchMatches fuel target state completionCount terminal omega := by
  induction fuel generalizing state with
  | zero =>
      by_cases htime : target omega ≤ state.currentTime omega
      · refine ⟨0, .hold, ?_⟩
        simp [fixedPriorityAdvanceBranchMatches,
          fixedPriorityCompletionPrefixMatches,
          fixedPriorityAdvanceTerminalMatches,
          iterateFixedPriorityCompletions, htime]
      · cases hactive : state.active with
        | none =>
            refine ⟨0, .advance, ?_⟩
            have htime' : state.currentTime omega < target omega := lt_of_not_ge htime
            simp [fixedPriorityAdvanceBranchMatches,
              fixedPriorityCompletionPrefixMatches,
              fixedPriorityAdvanceTerminalMatches,
              iterateFixedPriorityCompletions, hactive, htime']
        | some active =>
            refine ⟨0, .hold, ?_⟩
            have htime' : state.currentTime omega < target omega := lt_of_not_ge htime
            simp [fixedPriorityAdvanceBranchMatches,
              fixedPriorityCompletionPrefixMatches,
              fixedPriorityAdvanceTerminalMatches,
              iterateFixedPriorityCompletions, hactive, htime']
  | succ fuel ih =>
      by_cases htime : target omega ≤ state.currentTime omega
      · refine ⟨0, .hold, ?_⟩
        simp [fixedPriorityAdvanceBranchMatches,
          fixedPriorityCompletionPrefixMatches,
          fixedPriorityAdvanceTerminalMatches,
          iterateFixedPriorityCompletions, htime]
      · cases hactive : state.active with
        | none =>
            refine ⟨0, .advance, ?_⟩
            have htime' : state.currentTime omega < target omega := lt_of_not_ge htime
            simp [fixedPriorityAdvanceBranchMatches,
              fixedPriorityCompletionPrefixMatches,
              fixedPriorityAdvanceTerminalMatches,
              iterateFixedPriorityCompletions, hactive, htime']
        | some active =>
            by_cases hcomplete : active.2 omega ≤ target omega - state.currentTime omega
            · rcases ih state.finishActive with ⟨completionCount, terminal, htail⟩
              refine ⟨completionCount + 1, terminal, ?_⟩
              have htime' : state.currentTime omega < target omega := lt_of_not_ge htime
              simpa [fixedPriorityAdvanceBranchMatches,
                fixedPriorityCompletionPrefixMatches,
                fixedPriorityAdvanceTerminalMatches,
                iterateFixedPriorityCompletions, hactive, htime', hcomplete] using htail
            · refine ⟨0, .advance, ?_⟩
              have htime' : state.currentTime omega < target omega := lt_of_not_ge htime
              have hpartial : target omega - state.currentTime omega < active.2 omega :=
                lt_of_not_ge hcomplete
              simp [fixedPriorityAdvanceBranchMatches,
                fixedPriorityCompletionPrefixMatches,
                fixedPriorityAdvanceTerminalMatches,
                iterateFixedPriorityCompletions, hactive, htime', hpartial]

/-- On its Borel branch fiber, a fixed completion-count/terminal skeleton is
exactly the existing executable finite priority advance. -/
theorem eval_runFixedPriorityAdvanceBranch_eq_advance_of_matches
    (fuel : ℕ) (target : Ω → ℝ)
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (omega : Ω)
    (hmatches : fixedPriorityAdvanceBranchMatches fuel target state completionCount terminal omega) :
    (runFixedPriorityAdvanceBranch target state completionCount terminal).eval omega =
      advanceNonpreemptivePriorityWorkState fuel (target omega) (state.eval omega) := by
  induction fuel generalizing state completionCount terminal with
  | zero =>
      rcases hmatches with ⟨hcount, hprefix, hterminal⟩
      have hcountzero : completionCount = 0 := Nat.eq_zero_of_le_zero hcount
      subst completionCount
      cases terminal with
      | hold =>
          have hterminal' : target omega ≤ state.currentTime omega ∨
              (state.currentTime omega < target omega ∧ state.active.isSome) := by
            simpa [fixedPriorityAdvanceTerminalMatches] using hterminal
          by_cases htime : target omega ≤ state.currentTime omega
          · have htimeEval : target omega ≤ (state.eval omega).currentTime := by
              simpa using htime
            simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
              advanceNonpreemptivePriorityWorkState, htimeEval]
          · have hactive : state.active.isSome := by
              rcases hterminal' with hterminal' | hterminal'
              · exact False.elim (htime hterminal')
              · exact hterminal'.2
            cases hstateActive : state.active with
            | none => simp [hstateActive] at hactive
            | some active =>
                have hactiveEval : (state.eval omega).active =
                    some (active.1.eval omega, active.2 omega) := by
                  simp [NonpreemptivePriorityFixedStateCoordinate.eval, hstateActive]
                have htimeEval : ¬ target omega ≤ (state.eval omega).currentTime := by
                  simpa using htime
                simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
                  advanceNonpreemptivePriorityWorkState, htimeEval, hactiveEval]
      | advance =>
          cases hstateActive : state.active with
          | none =>
              have hterminal' : state.currentTime omega < target omega := by
                simpa [fixedPriorityAdvanceTerminalMatches,
                  iterateFixedPriorityCompletions, hstateActive] using hterminal
              have htime : ¬ target omega ≤ state.currentTime omega := not_le_of_gt hterminal'
              have hactiveEval : (state.eval omega).active = none := by
                simp [NonpreemptivePriorityFixedStateCoordinate.eval, hstateActive]
              have htimeEval : ¬ target omega ≤ (state.eval omega).currentTime := by
                simpa using htime
              simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
                NonpreemptivePriorityFixedStateCoordinate.eval_advanceWithoutCompletion,
                advanceNonpreemptivePriorityWorkState, htimeEval, hactiveEval]
          | some active =>
              simp [fixedPriorityAdvanceTerminalMatches,
                iterateFixedPriorityCompletions, hstateActive] at hterminal
  | succ fuel ih =>
      rcases hmatches with ⟨hcount, hprefix, hterminal⟩
      cases completionCount with
      | zero =>
          cases terminal with
          | hold =>
              have htime : target omega ≤ state.currentTime omega := by
                simpa [fixedPriorityAdvanceTerminalMatches,
                  iterateFixedPriorityCompletions] using hterminal
              have htimeEval : target omega ≤ (state.eval omega).currentTime := by
                simpa using htime
              simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
                advanceNonpreemptivePriorityWorkState, htimeEval]
          | advance =>
              cases hstateActive : state.active with
              | none =>
                  have hterminal' : state.currentTime omega < target omega := by
                    simpa [fixedPriorityAdvanceTerminalMatches,
                      iterateFixedPriorityCompletions, hstateActive] using hterminal
                  have htime : ¬ target omega ≤ state.currentTime omega := not_le_of_gt hterminal'
                  have hactiveEval : (state.eval omega).active = none := by
                    simp [NonpreemptivePriorityFixedStateCoordinate.eval, hstateActive]
                  have htimeEval : ¬ target omega ≤ (state.eval omega).currentTime := by
                    simpa using htime
                  simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
                    NonpreemptivePriorityFixedStateCoordinate.eval_advanceWithoutCompletion,
                    advanceNonpreemptivePriorityWorkState, htimeEval, hactiveEval]
              | some active =>
                  have hterminal' : state.currentTime omega < target omega ∧
                      target omega - state.currentTime omega < active.2 omega := by
                    simpa [fixedPriorityAdvanceTerminalMatches,
                      iterateFixedPriorityCompletions, hstateActive] using hterminal
                  have htime : ¬ target omega ≤ state.currentTime omega :=
                    not_le_of_gt hterminal'.1
                  have hpartial : ¬ active.2 omega ≤ target omega - state.currentTime omega :=
                    not_le_of_gt hterminal'.2
                  have hactiveEval : (state.eval omega).active =
                      some (active.1.eval omega, active.2 omega) := by
                    simp [NonpreemptivePriorityFixedStateCoordinate.eval, hstateActive]
                  have htimeEval : ¬ target omega ≤ (state.eval omega).currentTime := by
                    simpa using htime
                  have hpartialEval : ¬ active.2 omega ≤
                      target omega - (state.eval omega).currentTime := by
                    simpa using hpartial
                  simp [runFixedPriorityAdvanceBranch, iterateFixedPriorityCompletions,
                    NonpreemptivePriorityFixedStateCoordinate.eval_advanceWithoutCompletion,
                    advanceNonpreemptivePriorityWorkState, htimeEval, hactiveEval, hpartialEval]
                  rfl
      | succ completionCount =>
          cases hstateActive : state.active with
          | none => simp [fixedPriorityCompletionPrefixMatches, hstateActive] at hprefix
          | some active =>
              have hprefix' : state.currentTime omega < target omega ∧
                  active.2 omega ≤ target omega - state.currentTime omega ∧
                    fixedPriorityCompletionPrefixMatches target completionCount
                      state.finishActive omega := by
                simpa [fixedPriorityCompletionPrefixMatches, hstateActive] using hprefix
              have htailMatches : fixedPriorityAdvanceBranchMatches fuel target
                  state.finishActive completionCount terminal omega := by
                refine ⟨Nat.le_of_succ_le_succ hcount, hprefix'.2.2, ?_⟩
                simpa using hterminal
              have htail := ih state.finishActive completionCount terminal htailMatches
              have htime : ¬ target omega ≤ state.currentTime omega :=
                not_le_of_gt hprefix'.1
              have hactiveEval : (state.eval omega).active =
                  some (active.1.eval omega, active.2 omega) := by
                simp [NonpreemptivePriorityFixedStateCoordinate.eval, hstateActive]
              have hfinishEval : state.finishActive.eval omega =
                  completeNonpreemptivePriorityWorkJob
                    { (state.eval omega) with
                      currentTime := state.currentTime omega + active.2 omega } := by
                simpa [NonpreemptivePriorityFixedStateCoordinate.eval_finishActive,
                  hactiveEval]
              have htimeEval : ¬ target omega ≤ (state.eval omega).currentTime := by
                simpa using htime
              have hcompleteEval : active.2 omega ≤
                  target omega - (state.eval omega).currentTime := by
                simpa using hprefix'.2.1
              rw [show runFixedPriorityAdvanceBranch target state
                    (completionCount + 1) terminal =
                    runFixedPriorityAdvanceBranch target state.finishActive
                      completionCount terminal by
                    cases terminal <;> rfl]
              rw [htail, hfinishEval]
              simp [advanceNonpreemptivePriorityWorkState, htimeEval, hactiveEval, hcompleteEval]
              rfl

/-- The resident-job count of a static coordinate state.  Unlike residual
work, this number depends only on its fixed discrete queue shape. -/
def totalFixedNonpreemptivePriorityWorkJobs
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) : ℕ :=
  (match state.active with | none => 0 | some _ => 1) +
    ∑ i, (state.waiting i).length

/-- Evaluating a fixed state leaves its resident-job count unchanged. -/
theorem totalNonpreemptivePriorityWorkJobs_fixedState_eval
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) (omega : Ω) :
    totalNonpreemptivePriorityWorkJobs (state.eval omega) =
      totalFixedNonpreemptivePriorityWorkJobs state := by
  unfold totalNonpreemptivePriorityWorkJobs totalPriorityWaitingJobs
    totalFixedNonpreemptivePriorityWorkJobs
  cases hactive : state.active <;>
    simp [NonpreemptivePriorityFixedStateCoordinate.eval, hactive]

/-- One static arrival-trace slot: execute a fixed Borel advance skeleton to
the job's arrival clock and then admit that fixed-label job. -/
noncomputable def runFixedPriorityAdvanceThenAdmit
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal) :
    NonpreemptivePriorityFixedStateCoordinate Ω n JobId :=
  (runFixedPriorityAdvanceBranch job.arrivalTime state completionCount terminal).admit job

/-- A static arrival-trace slot is exactly the literal advance-then-admit
operation on its Borel advance branch. -/
theorem eval_runFixedPriorityAdvanceThenAdmit_eq_advanceThenAdmit_of_matches
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (omega : Ω)
    (hmatches : fixedPriorityAdvanceBranchMatches
      (totalFixedNonpreemptivePriorityWorkJobs state) job.arrivalTime state
      completionCount terminal omega) :
    (runFixedPriorityAdvanceThenAdmit state job completionCount terminal).eval omega =
      advanceThenAdmitNonpreemptivePriorityJob
        (totalNonpreemptivePriorityWorkJobs (state.eval omega))
        (state.eval omega) (job.eval omega) := by
  unfold runFixedPriorityAdvanceThenAdmit advanceThenAdmitNonpreemptivePriorityJob
  rw [NonpreemptivePriorityFixedStateCoordinate.eval_admit]
  have hadvance := eval_runFixedPriorityAdvanceBranch_eq_advance_of_matches
    (fuel := totalFixedNonpreemptivePriorityWorkJobs state)
    (target := job.arrivalTime) (state := state)
    (completionCount := completionCount) (terminal := terminal) (omega := omega) hmatches
  rw [hadvance, totalNonpreemptivePriorityWorkJobs_fixedState_eval]
  rfl

/-- A static arrival-trace slot preserves Borel coordinate data. -/
theorem coordinatesMeasurable_runFixedPriorityAdvanceThenAdmit
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (job : NonpreemptivePriorityFixedJobCoordinate Ω n JobId)
    (completionCount : ℕ) (terminal : NonpreemptivePriorityFixedAdvanceTerminal)
    (hstate : state.CoordinatesMeasurable) (hjob : job.CoordinatesMeasurable) :
    (runFixedPriorityAdvanceThenAdmit state job completionCount terminal).CoordinatesMeasurable := by
  unfold runFixedPriorityAdvanceThenAdmit
  exact NonpreemptivePriorityFixedStateCoordinate.CoordinatesMeasurable.admit
    (runFixedPriorityAdvanceBranch job.arrivalTime state completionCount terminal) job
    (coordinatesMeasurable_runFixedPriorityAdvanceBranch job.arrivalTime hjob.1
      state hstate completionCount terminal) hjob

/-- One countable static branch choice for each arrival of a finite priority
trace. -/
structure NonpreemptivePriorityFixedArrivalTraceSlot where
  completionCount : ℕ
  terminal : NonpreemptivePriorityFixedAdvanceTerminal
  deriving Countable

/-- Execute a finite sequence of fixed arrival slots.  A shape mismatch is
left explicit and is excluded by the companion branch predicate. -/
noncomputable def runFixedPriorityArrivalTraceBranch
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId) →
      List NonpreemptivePriorityFixedArrivalTraceSlot →
        NonpreemptivePriorityFixedStateCoordinate Ω n JobId
  | [], _ => state
  | job :: jobs, slot :: slots =>
      runFixedPriorityArrivalTraceBranch
        (runFixedPriorityAdvanceThenAdmit state job slot.completionCount slot.terminal)
        jobs slots
  | _ :: _, [] => state

/-- The recursive Borel fiber for a fixed finite sequence of priority
arrival slots. -/
def fixedPriorityArrivalTraceBranchMatches
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId) :
    List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId) →
      List NonpreemptivePriorityFixedArrivalTraceSlot → Ω → Prop
  | [], [], _ => True
  | [], _ :: _, _ => False
  | job :: jobs, slot :: slots, omega =>
      fixedPriorityAdvanceBranchMatches
        (totalFixedNonpreemptivePriorityWorkJobs state) job.arrivalTime state
        slot.completionCount slot.terminal omega ∧
      fixedPriorityArrivalTraceBranchMatches
        (runFixedPriorityAdvanceThenAdmit state job slot.completionCount slot.terminal)
        jobs slots omega
  | _ :: _, [], _ => False

/-- A fixed finite arrival-trace branch is Borel. -/
theorem measurableSet_fixedPriorityArrivalTraceBranchMatches
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    ∀ (jobs : List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId))
      (slots : List NonpreemptivePriorityFixedArrivalTraceSlot),
      (∀ job ∈ jobs, job.CoordinatesMeasurable) →
      MeasurableSet {omega | fixedPriorityArrivalTraceBranchMatches state jobs slots omega} := by
  intro jobs
  induction jobs generalizing state with
  | nil =>
      intro slots hjobs
      cases slots <;> simp [fixedPriorityArrivalTraceBranchMatches]
  | cons job jobs ih =>
      intro slots hjobs
      cases slots with
      | nil => simp [fixedPriorityArrivalTraceBranchMatches]
      | cons slot slots =>
          have hjob : job.CoordinatesMeasurable := hjobs job (by simp)
          have hjobsTail : ∀ later ∈ jobs, later.CoordinatesMeasurable := by
            intro later hlater
            exact hjobs later (by simp [hlater])
          exact (measurableSet_fixedPriorityAdvanceBranchMatches
            (totalFixedNonpreemptivePriorityWorkJobs state) job.arrivalTime hjob.1 state hstate
            slot.completionCount slot.terminal).inter
              (ih (runFixedPriorityAdvanceThenAdmit state job slot.completionCount slot.terminal)
                (coordinatesMeasurable_runFixedPriorityAdvanceThenAdmit state job
                  slot.completionCount slot.terminal hstate hjob) slots hjobsTail)

/-- A matching fixed arrival trace evaluates to the executable arrival trace. -/
theorem eval_runFixedPriorityArrivalTraceBranch_eq_run_of_matches
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (jobs : List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId))
    (slots : List NonpreemptivePriorityFixedArrivalTraceSlot) (omega : Ω)
    (hmatches : fixedPriorityArrivalTraceBranchMatches state jobs slots omega) :
    (runFixedPriorityArrivalTraceBranch state jobs slots).eval omega =
      runNonpreemptivePriorityArrivalTrace (state.eval omega) (jobs.map fun job => job.eval omega) := by
  induction jobs generalizing state slots with
  | nil =>
      cases slots <;>
        simp [runFixedPriorityArrivalTraceBranch,
          runNonpreemptivePriorityArrivalTrace]
  | cons job jobs ih =>
      cases slots with
      | nil => simp [fixedPriorityArrivalTraceBranchMatches] at hmatches
      | cons slot slots =>
          rcases hmatches with ⟨hhead, htail⟩
          rw [runFixedPriorityArrivalTraceBranch,
            ih _ _ htail,
            eval_runFixedPriorityAdvanceThenAdmit_eq_advanceThenAdmit_of_matches
              state job slot.completionCount slot.terminal omega hhead]
          simp [runNonpreemptivePriorityArrivalTrace]

/-- Every sample belongs to a countable fixed branch of every finite static
arrival trace.  The branch is obtained by recording the actual finite service
choices at each arrival, so this is a cover theorem rather than a new model
assumption. -/
theorem exists_fixedPriorityArrivalTraceBranchMatches
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (jobs : List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId)) (omega : Ω) :
    ∃ slots, fixedPriorityArrivalTraceBranchMatches state jobs slots omega := by
  induction jobs generalizing state with
  | nil => exact ⟨[], trivial⟩
  | cons job jobs ih =>
      rcases exists_fixedPriorityAdvanceBranchMatches
        (totalFixedNonpreemptivePriorityWorkJobs state) job.arrivalTime state omega with
        ⟨completionCount, terminal, hhead⟩
      let nextState := runFixedPriorityAdvanceThenAdmit state job completionCount terminal
      rcases ih nextState with ⟨slots, htail⟩
      refine ⟨{ completionCount := completionCount, terminal := terminal } :: slots, ?_⟩
      exact ⟨hhead, htail⟩

/-- Executing any fixed sequence of static arrival slots preserves Borel state
coordinates; branch matching is not needed for this coordinate statement. -/
theorem coordinatesMeasurable_runFixedPriorityArrivalTraceBranch
    (state : NonpreemptivePriorityFixedStateCoordinate Ω n JobId)
    (hstate : state.CoordinatesMeasurable) :
    ∀ (jobs : List (NonpreemptivePriorityFixedJobCoordinate Ω n JobId))
      (slots : List NonpreemptivePriorityFixedArrivalTraceSlot),
      (∀ job ∈ jobs, job.CoordinatesMeasurable) →
      (runFixedPriorityArrivalTraceBranch state jobs slots).CoordinatesMeasurable := by
  intro jobs
  induction jobs generalizing state with
  | nil =>
      intro slots hjobs
      simp [runFixedPriorityArrivalTraceBranch]
      exact hstate
  | cons job jobs ih =>
      intro slots hjobs
      cases slots with
      | nil =>
          simp [runFixedPriorityArrivalTraceBranch]
          exact hstate
      | cons slot slots =>
          have hjob : job.CoordinatesMeasurable := hjobs job (by simp)
          have hjobsTail : ∀ later ∈ jobs, later.CoordinatesMeasurable := by
            intro later hlater
            exact hjobs later (by simp [hlater])
          apply ih
          · exact coordinatesMeasurable_runFixedPriorityAdvanceThenAdmit state job
              slot.completionCount slot.terminal hstate hjob
          · exact hjobsTail

end

end AppliedModelingLib.Queueing
