import LG24ServiceLevelAgreements.ProposedParityKKT
import Mathlib.Tactic

/-!
# End-to-end heterogeneous all-request parity reduction

The heterogeneous reduced problem in `ProposedParityKKT` is not merely a
formal substitution.  On a finite nonempty Borough set and with strictly
positive all-request delay slopes, it is exactly the zero-range face of the
cellwise delay problem.

This file proves the complete equivalence.  Zero finite all-request range is
equivalent to a common burden level in every category; the associated delay is
uniquely `allRequestParityDelay`; reciprocal-capacity feasibility and the
arrival-weighted efficiency objective transport without loss; and minimizing
the reduced problem is equivalent both to minimizing efficiency on the
zero-range face and to lexicographically minimizing range then efficiency in
the original delay problem.  The final representation theorem records the one
necessary qualification: an arbitrary lexicographic minimizer lies on the
zero-range face only when exact parity is feasible.
-/

namespace LG24ServiceLevelAgreements

open scoped BigOperators

noncomputable section

/-! ## Zero range is exactly constancy -/

/-- A real-valued profile on a finite nonempty type has zero range exactly
when it is constant. -/
theorem finiteBoroughRange_eq_zero_iff_exists_level
    {Borough : Type*} [Fintype Borough] [Nonempty Borough]
    (burden : Borough → ℝ) :
    finiteBoroughRange burden = 0 ↔
      ∃ level, ∀ b, burden b = level := by
  classical
  constructor
  · intro hzero
    let level := Finset.univ.sup' Finset.univ_nonempty burden
    refine ⟨level, ?_⟩
    intro b
    have hupper : burden b ≤ level :=
      Finset.le_sup' burden (Finset.mem_univ b)
    have hlower : Finset.univ.inf' Finset.univ_nonempty burden ≤ burden b :=
      Finset.inf'_le burden (Finset.mem_univ b)
    have heq :
        Finset.univ.sup' Finset.univ_nonempty burden =
          Finset.univ.inf' Finset.univ_nonempty burden := by
      unfold finiteBoroughRange at hzero
      linarith
    dsimp [level] at hupper ⊢
    linarith
  · rintro ⟨level, hlevel⟩
    exact finiteBoroughRange_eq_zero_of_constant burden level hlevel

/-- A finite sum of within-category ranges is zero exactly when every category
has a common burden level. -/
theorem finiteAllRequestRangeObjective_eq_zero_iff_exists_levels
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    (burden : Category → Borough → ℝ) :
    finiteAllRequestRangeObjective burden = 0 ↔
      ∃ level : Category → ℝ, ∀ k b, burden k b = level k := by
  classical
  constructor
  · intro hzero
    have hrange : ∀ k, finiteBoroughRange (burden k) = 0 := by
      intro k
      have hall := (Finset.sum_eq_zero_iff_of_nonneg
        (fun j (_hj : j ∈ (Finset.univ : Finset Category)) ↦
          finiteBoroughRange_nonneg (burden j))).1
        (show ∑ j, finiteBoroughRange (burden j) = 0 by
          simpa [finiteAllRequestRangeObjective] using hzero)
      exact hall k (Finset.mem_univ k)
    choose level hlevel using fun k ↦
      (finiteBoroughRange_eq_zero_iff_exists_level (burden k)).1 (hrange k)
    exact ⟨level, hlevel⟩
  · rintro ⟨level, hlevel⟩
    exact finiteAllRequestRangeObjective_eq_zero_of_constant
      burden level hlevel

/-! ## Concrete cellwise maps -/

/-- Cellwise all-request burden induced by conditional delays. -/
def finiteAllRequestDelayBurden
    {Category Borough : Type*}
    (risk inspectionProbability noninspectionPenalty delay :
      Category → Borough → ℝ) :
    Category → Borough → ℝ :=
  fun k b ↦ allRequestBurden
    (risk k b) (inspectionProbability k b) (delay k b)
    (noninspectionPenalty k b)

/-- Cellwise parity delays generated by common category burden levels. -/
def finiteAllRequestParityDelay
    {Category Borough : Type*}
    (level : Category → ℝ)
    (risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ) :
    Category → Borough → ℝ :=
  fun k b ↦ allRequestParityDelay (level k)
    (risk k b) (inspectionProbability k b) (noninspectionPenalty k b)

/-- Total arrival mass in each category, the correct reduced efficiency
weight. -/
def heterogeneousParityArrivalMass
    {Category Borough : Type*} [Fintype Borough]
    (arrival : Category → Borough → ℝ) : Category → ℝ :=
  fun k ↦ ∑ b, arrival k b

/-- Arrival-weighted efficiency written directly on cell burdens. -/
def finiteAllRequestArrivalWeightedEfficiency
    {Category Borough : Type*} [Fintype Category] [Fintype Borough]
    (arrival risk inspectionProbability noninspectionPenalty delay :
      Category → Borough → ℝ) : ℝ :=
  finiteArrivalWeightedBurden arrival
    (finiteAllRequestDelayBurden risk inspectionProbability
      noninspectionPenalty delay)

/-- Feasible cellwise delays whose all-request range is exactly zero. -/
def finiteZeroRangeDelayFeasible
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    (logTail risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ)
    (excessCapacity : ℝ) : Set (Category → Borough → ℝ) :=
  {delay |
    finiteMatrixReciprocalCapacityFeasible logTail excessCapacity delay ∧
      finiteAllRequestRangeObjective
        (finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty delay) = 0}

/-- The canonical category level of a delay profile is its category maximum
burden.  On the zero-range face this is the common burden. -/
def finiteAllRequestParityLevelOfDelay
    {Category Borough : Type*} [Fintype Borough] [Nonempty Borough]
    (risk inspectionProbability noninspectionPenalty delay :
      Category → Borough → ℝ) : Category → ℝ :=
  finiteCategoryMaximum
    (finiteAllRequestDelayBurden risk inspectionProbability
      noninspectionPenalty delay)

/-! ## Unique reconstruction of delay -/

/-- Positive all-request slope implies both primitive factors are nonzero. -/
theorem nonzero_factors_of_allRequestDelaySlope_pos
    {risk inspectionProbability : ℝ}
    (hslope : 0 < allRequestDelaySlope risk inspectionProbability) :
    risk ≠ 0 ∧ inspectionProbability ≠ 0 := by
  unfold allRequestDelaySlope at hslope
  constructor
  · intro hrisk
    rw [hrisk, zero_mul] at hslope
    exact (lt_irrefl 0) hslope
  · intro hprobability
    rw [hprobability, mul_zero] at hslope
    exact (lt_irrefl 0) hslope

/-- With positive slope, a cell has burden `level` if and only if its delay is
the parity delay.  This is the missing uniqueness direction of the algebraic
substitution. -/
theorem allRequestBurden_eq_level_iff_delay_eq_parityDelay
    {level risk inspectionProbability conditionalDelay
      noninspectionPenalty : ℝ}
    (hslope : 0 < allRequestDelaySlope risk inspectionProbability) :
    allRequestBurden risk inspectionProbability conditionalDelay
        noninspectionPenalty = level ↔
      conditionalDelay = allRequestParityDelay level risk
        inspectionProbability noninspectionPenalty := by
  rw [allRequestBurden_eq_fixedOffset_add_slope_mul_delay]
  unfold allRequestParityDelay
  constructor
  · intro hlevel
    apply (eq_div_iff hslope.ne').2
    linarith
  · intro hdelay
    rw [hdelay]
    field_simp [hslope.ne']
    ring

/-- Under positive slope, positivity of the parity delay is exactly the strict
reduced-domain inequality `offset < level`. -/
theorem allRequestParityDelay_pos_iff_offset_lt_level
    {level risk inspectionProbability noninspectionPenalty : ℝ}
    (hslope : 0 < allRequestDelaySlope risk inspectionProbability) :
    0 < allRequestParityDelay level risk inspectionProbability
        noninspectionPenalty ↔
      allRequestFixedOffset risk inspectionProbability noninspectionPenalty <
        level := by
  unfold allRequestParityDelay
  constructor
  · intro hdelay
    rcases (div_pos_iff.mp hdelay) with hpos | hneg
    · exact sub_pos.mp hpos.1
    · exact False.elim (not_lt_of_ge hslope.le hneg.2)
  · intro hlevel
    exact div_pos (sub_pos.mpr hlevel) hslope

/-- Positive-slope parity delays produce their requested levels in every
cell. -/
theorem finiteAllRequestDelayBurden_parityDelay_eq_level
    {Category Borough : Type*}
    {risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    ∀ k b,
      finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty
          (finiteAllRequestParityDelay level risk inspectionProbability
            noninspectionPenalty) k b = level k := by
  intro k b
  exact (allRequestBurden_eq_level_iff_delay_eq_parityDelay
    (hslope k b)).2 rfl

/-- The canonical level of parity-generated delays is the original level. -/
theorem finiteAllRequestParityLevelOfDelay_parityDelay
    {Category Borough : Type*} [Fintype Borough] [Nonempty Borough]
    {risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    finiteAllRequestParityLevelOfDelay risk inspectionProbability
        noninspectionPenalty
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) = level := by
  classical
  funext k
  apply le_antisymm
  · apply Finset.sup'_le Finset.univ_nonempty
    intro b _hb
    exact (finiteAllRequestDelayBurden_parityDelay_eq_level level hslope k b).le
  · let b : Borough := Classical.choice (inferInstance : Nonempty Borough)
    rw [← finiteAllRequestDelayBurden_parityDelay_eq_level level hslope k b]
    exact Finset.le_sup'
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) k)
      (Finset.mem_univ b)

/-- Every zero-range delay profile is exactly reconstructed from its canonical
category levels. -/
theorem finiteAllRequestParityDelay_levelOfDelay_eq
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    {risk inspectionProbability noninspectionPenalty delay :
      Category → Borough → ℝ}
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b))
    (hzero : finiteAllRequestRangeObjective
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty delay) = 0) :
    finiteAllRequestParityDelay
        (finiteAllRequestParityLevelOfDelay risk inspectionProbability
          noninspectionPenalty delay)
        risk inspectionProbability noninspectionPenalty = delay := by
  classical
  have hconstant :=
    (finiteAllRequestRangeObjective_eq_zero_iff_exists_levels
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty delay)).1 hzero
  rcases hconstant with ⟨level, hlevel⟩
  funext k b
  have hmax : finiteAllRequestParityLevelOfDelay risk inspectionProbability
      noninspectionPenalty delay k = level k := by
    unfold finiteAllRequestParityLevelOfDelay
    apply le_antisymm
    · apply Finset.sup'_le Finset.univ_nonempty
      intro c _hc
      exact (hlevel k c).le
    · rw [← hlevel k b]
      exact Finset.le_sup'
        (finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty delay k) (Finset.mem_univ b)
  apply Eq.symm
  apply (allRequestBurden_eq_level_iff_delay_eq_parityDelay
    (hslope k b)).1
  rw [hmax]
  exact hlevel k b

/-! ## Exact feasibility and objective transport -/

/-- Cellwise reciprocal feasibility at parity is exactly the heterogeneous
reduced feasibility predicate. -/
theorem finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough]
    {logTail risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    {excessCapacity : ℝ} (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    finiteMatrixReciprocalCapacityFeasible logTail excessCapacity
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) ↔
      heterogeneousParityFeasible
        (fun k b ↦ allRequestParityCapacityCoefficient
          (logTail k b) (risk k b) (inspectionProbability k b))
        (fun k b ↦ allRequestFixedOffset
          (risk k b) (inspectionProbability k b) (noninspectionPenalty k b))
        excessCapacity level := by
  classical
  have hrisk : ∀ k b, risk k b ≠ 0 := fun k b ↦
    (nonzero_factors_of_allRequestDelaySlope_pos (hslope k b)).1
  have hprobability : ∀ k b, inspectionProbability k b ≠ 0 := fun k b ↦
    (nonzero_factors_of_allRequestDelaySlope_pos (hslope k b)).2
  constructor
  · intro hdelay
    have hdomain : heterogeneousParityDomain
        (fun k b ↦ allRequestFixedOffset
          (risk k b) (inspectionProbability k b) (noninspectionPenalty k b))
        level := by
      intro k b
      exact (allRequestParityDelay_pos_iff_offset_lt_level
        (hslope k b)).1 (hdelay.1 k b)
    have hlevel : ∀ k b,
        level k - allRequestFixedOffset (risk k b)
          (inspectionProbability k b) (noninspectionPenalty k b) ≠ 0 :=
      fun k b ↦ (sub_pos.mpr (hdomain k b)).ne'
    have hcapacity := finite_reciprocalCapacity_at_parity_eq
      logTail risk inspectionProbability noninspectionPenalty level
      hrisk hprobability hlevel
    constructor
    · exact hdomain
    · unfold heterogeneousParityCapacityUse
      rw [← hcapacity]
      exact hdelay.2
  · intro hreduced
    have hlevel : ∀ k b,
        level k - allRequestFixedOffset (risk k b)
          (inspectionProbability k b) (noninspectionPenalty k b) ≠ 0 :=
      fun k b ↦ (sub_pos.mpr (hreduced.1 k b)).ne'
    have hcapacity := finite_reciprocalCapacity_at_parity_eq
      logTail risk inspectionProbability noninspectionPenalty level
      hrisk hprobability hlevel
    constructor
    · intro k b
      exact (allRequestParityDelay_pos_iff_offset_lt_level
        (hslope k b)).2 (hreduced.1 k b)
    · unfold heterogeneousParityCapacityUse at hreduced
      change (∑ k, ∑ b, logTail k b /
        allRequestParityDelay (level k) (risk k b)
          (inspectionProbability k b) (noninspectionPenalty k b)) ≤
        excessCapacity
      rw [hcapacity]
      exact hreduced.2

/-- Arrival-weighted cell burden at parity is exactly the reduced linear
objective with category arrival masses. -/
theorem finiteAllRequestArrivalWeightedEfficiency_parityDelay_eq_reduced
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough]
    (arrival : Category → Borough → ℝ)
    {risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    finiteAllRequestArrivalWeightedEfficiency arrival risk
        inspectionProbability noninspectionPenalty
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) =
      heterogeneousParityObjective
        (heterogeneousParityArrivalMass arrival) level := by
  classical
  unfold finiteAllRequestArrivalWeightedEfficiency
    finiteArrivalWeightedBurden heterogeneousParityObjective
    heterogeneousParityArrivalMass
  calc
    ∑ k, ∑ b, arrival k b *
        finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty
          (finiteAllRequestParityDelay level risk inspectionProbability
            noninspectionPenalty) k b =
        ∑ k, ∑ b, arrival k b * level k := by
      apply Finset.sum_congr rfl
      intro k _hk
      apply Finset.sum_congr rfl
      intro b _hb
      rw [finiteAllRequestDelayBurden_parityDelay_eq_level level hslope k b]
    _ = ∑ k, (∑ b, arrival k b) * level k := by
      apply Finset.sum_congr rfl
      intro k _hk
      rw [Finset.sum_mul]

/-- The paper's fixed-load cell-cost objective has the same exact reduced
value when admitted load is inspection probability times arrival load. -/
theorem finiteFixedLoadEfficiency_parityDelay_eq_heterogeneousParityObjective
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough]
    (arrival admitted risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ)
    (level : Category → ℝ)
    (hadmitted : ∀ k b,
      admitted k b = inspectionProbability k b * arrival k b)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    (∑ k, ∑ b, fixedLoadEfficiencyCellCost
        (arrival k b) (admitted k b) (risk k b)
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty k b)
        (noninspectionPenalty k b)) =
      heterogeneousParityObjective
        (heterogeneousParityArrivalMass arrival) level := by
  have hrisk : ∀ k b, risk k b ≠ 0 := fun k b ↦
    (nonzero_factors_of_allRequestDelaySlope_pos (hslope k b)).1
  have hprobability : ∀ k b, inspectionProbability k b ≠ 0 := fun k b ↦
    (nonzero_factors_of_allRequestDelaySlope_pos (hslope k b)).2
  unfold finiteAllRequestParityDelay
  rw [finite_fixedLoadEfficiency_at_parity_eq_arrivalWeights
    arrival admitted risk inspectionProbability noninspectionPenalty level
    hadmitted hrisk hprobability]
  rfl

/-! ## Minimizer transport -/

/-- Reduced minimization is exactly efficiency minimization on the zero-range
face of the original cellwise delay problem. -/
theorem heterogeneousParity_minimizer_iff_zeroRangeDelay_minimizer
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    {logTail arrival risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    {excessCapacity : ℝ} (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    MinimizesOn
        (heterogeneousParityFeasible
          (fun k b ↦ allRequestParityCapacityCoefficient
            (logTail k b) (risk k b) (inspectionProbability k b))
          (fun k b ↦ allRequestFixedOffset
            (risk k b) (inspectionProbability k b)
            (noninspectionPenalty k b))
          excessCapacity)
        (heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival)) level ↔
      MinimizesOn
        (finiteZeroRangeDelayFeasible logTail risk inspectionProbability
          noninspectionPenalty excessCapacity)
        (finiteAllRequestArrivalWeightedEfficiency arrival risk
          inspectionProbability noninspectionPenalty)
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) := by
  classical
  let reducedFeasible := heterogeneousParityFeasible
    (fun k b ↦ allRequestParityCapacityCoefficient
      (logTail k b) (risk k b) (inspectionProbability k b))
    (fun k b ↦ allRequestFixedOffset
      (risk k b) (inspectionProbability k b) (noninspectionPenalty k b))
    excessCapacity
  let reducedObjective := heterogeneousParityObjective
    (heterogeneousParityArrivalMass arrival)
  let delayEfficiency := finiteAllRequestArrivalWeightedEfficiency arrival risk
    inspectionProbability noninspectionPenalty
  let parityDelay := finiteAllRequestParityDelay level risk
    inspectionProbability noninspectionPenalty
  have hparityZero : finiteAllRequestRangeObjective
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty parityDelay) = 0 := by
    apply finiteAllRequestRangeObjective_eq_zero_of_constant
      (level := level)
    exact finiteAllRequestDelayBurden_parityDelay_eq_level level hslope
  constructor
  · intro hmin
    have hparityFeasible : finiteMatrixReciprocalCapacityFeasible
        logTail excessCapacity parityDelay :=
      (finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
        level hslope).2 hmin.1
    refine ⟨⟨hparityFeasible, hparityZero⟩, ?_⟩
    intro delay hdelay
    let recoveredLevel := finiteAllRequestParityLevelOfDelay risk
      inspectionProbability noninspectionPenalty delay
    have hreconstruct : finiteAllRequestParityDelay recoveredLevel risk
        inspectionProbability noninspectionPenalty = delay :=
      finiteAllRequestParityDelay_levelOfDelay_eq hslope hdelay.2
    have hreducedFeasible : reducedFeasible recoveredLevel := by
      apply (finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
        recoveredLevel hslope).1
      rw [hreconstruct]
      exact hdelay.1
    have hoptimal := hmin.2 recoveredLevel hreducedFeasible
    have hleft := finiteAllRequestArrivalWeightedEfficiency_parityDelay_eq_reduced
      (noninspectionPenalty := noninspectionPenalty) arrival level hslope
    have hright := finiteAllRequestArrivalWeightedEfficiency_parityDelay_eq_reduced
      (noninspectionPenalty := noninspectionPenalty) arrival recoveredLevel hslope
    rw [hreconstruct] at hright
    calc
      finiteAllRequestArrivalWeightedEfficiency arrival risk
          inspectionProbability noninspectionPenalty parityDelay =
          heterogeneousParityObjective
            (heterogeneousParityArrivalMass arrival) level := hleft
      _ ≤ heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival) recoveredLevel := hoptimal
      _ = finiteAllRequestArrivalWeightedEfficiency arrival risk
          inspectionProbability noninspectionPenalty delay := hright.symm
  · intro hmin
    have hparityFeasible := hmin.1.1
    have hreducedFeasible : reducedFeasible level :=
      (finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
        level hslope).1 hparityFeasible
    refine ⟨hreducedFeasible, ?_⟩
    intro otherLevel hother
    have hotherFeasible : finiteMatrixReciprocalCapacityFeasible
        logTail excessCapacity
        (finiteAllRequestParityDelay otherLevel risk inspectionProbability
          noninspectionPenalty) :=
      (finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
        otherLevel hslope).2 hother
    have hotherZero : finiteAllRequestRangeObjective
        (finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty
          (finiteAllRequestParityDelay otherLevel risk inspectionProbability
            noninspectionPenalty)) = 0 := by
      apply finiteAllRequestRangeObjective_eq_zero_of_constant
        (level := otherLevel)
      exact finiteAllRequestDelayBurden_parityDelay_eq_level otherLevel hslope
    have hoptimal := hmin.2
      (finiteAllRequestParityDelay otherLevel risk inspectionProbability
        noninspectionPenalty) ⟨hotherFeasible, hotherZero⟩
    have hleft := finiteAllRequestArrivalWeightedEfficiency_parityDelay_eq_reduced
      (noninspectionPenalty := noninspectionPenalty) arrival level hslope
    have hright := finiteAllRequestArrivalWeightedEfficiency_parityDelay_eq_reduced
      (noninspectionPenalty := noninspectionPenalty) arrival otherLevel hslope
    calc
      heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival) level =
          finiteAllRequestArrivalWeightedEfficiency arrival risk
            inspectionProbability noninspectionPenalty parityDelay := hleft.symm
      _ ≤ finiteAllRequestArrivalWeightedEfficiency arrival risk
          inspectionProbability noninspectionPenalty
          (finiteAllRequestParityDelay otherLevel risk inspectionProbability
            noninspectionPenalty) := hoptimal
      _ = heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival) otherLevel := hright

/-- A reduced minimizer is exactly a lexicographic range-then-efficiency
minimizer of the original delay problem at the corresponding parity delays.
No optimizer-existence assumption is hidden: this is an equivalence for a
specified candidate level. -/
theorem heterogeneousParity_minimizer_iff_lexicographicDelay_minimizer
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    {logTail arrival risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    {excessCapacity : ℝ} (level : Category → ℝ)
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b)) :
    MinimizesOn
        (heterogeneousParityFeasible
          (fun k b ↦ allRequestParityCapacityCoefficient
            (logTail k b) (risk k b) (inspectionProbability k b))
          (fun k b ↦ allRequestFixedOffset
            (risk k b) (inspectionProbability k b)
            (noninspectionPenalty k b))
          excessCapacity)
        (heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival)) level ↔
      LexicographicallyMinimizesEquityThenEfficiencyOn
        (finiteMatrixReciprocalCapacityFeasible logTail excessCapacity)
        (fun delay ↦ finiteAllRequestRangeObjective
          (finiteAllRequestDelayBurden risk inspectionProbability
            noninspectionPenalty delay))
        (finiteAllRequestArrivalWeightedEfficiency arrival risk
          inspectionProbability noninspectionPenalty)
        (finiteAllRequestParityDelay level risk inspectionProbability
          noninspectionPenalty) := by
  let parityDelay := finiteAllRequestParityDelay level risk
    inspectionProbability noninspectionPenalty
  let equity := fun delay ↦ finiteAllRequestRangeObjective
    (finiteAllRequestDelayBurden risk inspectionProbability
      noninspectionPenalty delay)
  let efficiency := finiteAllRequestArrivalWeightedEfficiency arrival risk
    inspectionProbability noninspectionPenalty
  have hparityZero : equity parityDelay = 0 := by
    apply finiteAllRequestRangeObjective_eq_zero_of_constant
      (level := level)
    exact finiteAllRequestDelayBurden_parityDelay_eq_level level hslope
  constructor
  · intro hmin
    have hzeroMin :=
      (heterogeneousParity_minimizer_iff_zeroRangeDelay_minimizer
        level hslope).1 hmin
    refine ⟨hzeroMin.1.1, ?_, ?_⟩
    · intro delay hdelay
      have hnonneg := finiteAllRequestRangeObjective_nonneg
        (finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty delay)
      dsimp [equity] at hparityZero ⊢
      linarith
    · intro delay hdelay heq
      have hdelayZero : equity delay = 0 := by
        change equity delay = equity parityDelay at heq
        rw [heq, hparityZero]
      exact hzeroMin.2 delay ⟨hdelay, hdelayZero⟩
  · intro hlex
    apply (heterogeneousParity_minimizer_iff_zeroRangeDelay_minimizer
      level hslope).2
    refine ⟨⟨hlex.1, hparityZero⟩, ?_⟩
    intro delay hdelay
    apply hlex.2.2 delay hdelay.1
    have hdelayZero : equity delay = 0 := hdelay.2
    change equity delay = equity parityDelay
    exact hdelayZero.trans hparityZero.symm

/-- Every lexicographic minimizer is represented by a reduced minimizer once
the reduced feasible set is nonempty.  This is the exact attainment
qualification: without an exactly equitable feasible point, lexicographic
range minimization need not attain zero and no parity-level representation is
possible. -/
theorem lexicographicDelay_minimizer_has_heterogeneousParity_representation
    {Category Borough : Type*}
    [Fintype Category] [Fintype Borough] [Nonempty Borough]
    {logTail arrival risk inspectionProbability noninspectionPenalty :
      Category → Borough → ℝ}
    {excessCapacity : ℝ}
    (hslope : ∀ k b,
      0 < allRequestDelaySlope (risk k b) (inspectionProbability k b))
    (hparityFeasible : ∃ level,
      heterogeneousParityFeasible
        (fun k b ↦ allRequestParityCapacityCoefficient
          (logTail k b) (risk k b) (inspectionProbability k b))
        (fun k b ↦ allRequestFixedOffset
          (risk k b) (inspectionProbability k b)
          (noninspectionPenalty k b))
        excessCapacity level)
    {delay : Category → Borough → ℝ}
    (hlex : LexicographicallyMinimizesEquityThenEfficiencyOn
      (finiteMatrixReciprocalCapacityFeasible logTail excessCapacity)
      (fun z ↦ finiteAllRequestRangeObjective
        (finiteAllRequestDelayBurden risk inspectionProbability
          noninspectionPenalty z))
      (finiteAllRequestArrivalWeightedEfficiency arrival risk
        inspectionProbability noninspectionPenalty)
      delay) :
    ∃ level,
      delay = finiteAllRequestParityDelay level risk inspectionProbability
        noninspectionPenalty ∧
      MinimizesOn
        (heterogeneousParityFeasible
          (fun k b ↦ allRequestParityCapacityCoefficient
            (logTail k b) (risk k b) (inspectionProbability k b))
          (fun k b ↦ allRequestFixedOffset
            (risk k b) (inspectionProbability k b)
            (noninspectionPenalty k b))
          excessCapacity)
        (heterogeneousParityObjective
          (heterogeneousParityArrivalMass arrival)) level := by
  rcases hparityFeasible with ⟨witnessLevel, hwitness⟩
  let witnessDelay := finiteAllRequestParityDelay witnessLevel risk
    inspectionProbability noninspectionPenalty
  have hwitnessDelay : finiteMatrixReciprocalCapacityFeasible
      logTail excessCapacity witnessDelay :=
    (finiteAllRequestParityDelay_feasible_iff_heterogeneousParityFeasible
      witnessLevel hslope).2 hwitness
  have hwitnessZero : finiteAllRequestRangeObjective
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty witnessDelay) = 0 := by
    apply finiteAllRequestRangeObjective_eq_zero_of_constant
      (level := witnessLevel)
    exact finiteAllRequestDelayBurden_parityDelay_eq_level witnessLevel hslope
  have hdelayNonneg := finiteAllRequestRangeObjective_nonneg
    (finiteAllRequestDelayBurden risk inspectionProbability
      noninspectionPenalty delay)
  have hdelayLeZero : finiteAllRequestRangeObjective
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty delay) ≤ 0 := by
    rw [← hwitnessZero]
    exact hlex.2.1 witnessDelay hwitnessDelay
  have hdelayZero : finiteAllRequestRangeObjective
      (finiteAllRequestDelayBurden risk inspectionProbability
        noninspectionPenalty delay) = 0 :=
    le_antisymm hdelayLeZero hdelayNonneg
  let level := finiteAllRequestParityLevelOfDelay risk inspectionProbability
    noninspectionPenalty delay
  have hreconstruct : finiteAllRequestParityDelay level risk
      inspectionProbability noninspectionPenalty = delay :=
    finiteAllRequestParityDelay_levelOfDelay_eq hslope hdelayZero
  refine ⟨level, hreconstruct.symm, ?_⟩
  apply (heterogeneousParity_minimizer_iff_lexicographicDelay_minimizer
    level hslope).2
  rw [hreconstruct]
  exact hlex

end

end LG24ServiceLevelAgreements
