import AppliedModelingLib.GameTheory.PerformativePrediction
import AppliedModelingLib.Learning.StrategicResponseWelfare

/-!
# Strategic Responses as Performative Models

This module connects finite strategic classification to performative
prediction.  A deployed (possibly randomized) binary classifier induces a
best-response kernel, which pushes a fixed population law forward to the data
law seen by the learner.  Binary error is then both a Stackelberg objective and
the performative risk of that induced model.

The stochastic composition uses Mathlib's `PMF.pure`, `PMF.map`, and
`PMF.bind` at the repository's pinned commit
[`5450b53e`](https://github.com/leanprover-community/mathlib4/tree/5450b53e5ddc75d46418fabb605edbf36bd0beb6),
under Apache-2.0.  The finite best-response selector is the repository-local
`Optimization.exists_isMaximizerOn_of_finite`; no external theorem or proof is
copied or ported.
-/

namespace AppliedModelingLib

/-- The selected best-response kernel generated by each deployed randomized classifier. -/
noncomputable def selectedRandomizedClassifierResponseFamily
    {Parameter Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) : Parameter → Feature → PMF Feature :=
  fun parameter =>
    selectedRandomizedClassifierResponseKernel negativeScore positiveScore
      (classifier parameter) cost

/-- Every action in the selected response kernel maximizes expected strategic utility. -/
theorem selectedRandomizedClassifierResponseFamily_spec
    {Parameter Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    IsStrategicBestResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter)) cost
      (selectedRandomizedClassifierResponseFamily
        negativeScore positiveScore classifier cost parameter) :=
  selectedRandomizedClassifierResponseKernel_spec
    negativeScore positiveScore (classifier parameter) cost

/--
The selected best-response kernel for a heterogeneous population whose agents,
economic types, initial features, and type-dependent costs are explicit.
-/
noncomputable def selectedRandomizedClassifierAgentResponseFamily
    {Parameter Agent AgentType Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature) :
    Parameter → Agent → PMF Feature :=
  fun parameter =>
    selectedAgentStrategicResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
      environment

/-- Every selected heterogeneous-agent response maximizes expected classifier utility. -/
theorem selectedRandomizedClassifierAgentResponseFamily_spec
    {Parameter Agent AgentType Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    IsAgentStrategicBestResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
      environment
      (selectedRandomizedClassifierAgentResponseFamily
        negativeScore positiveScore classifier environment parameter) :=
  selectedAgentStrategicResponseKernel_spec
    (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
    environment

/--
The full-support uniform best-response kernel generated by each deployed
randomized classifier in a heterogeneous population.
-/
noncomputable def uniformRandomizedClassifierAgentResponseFamily
    {Parameter Agent AgentType Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature) :
    Parameter → Agent → PMF Feature :=
  fun parameter =>
    uniformAgentStrategicResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
      environment

/-- The uniform response family has exactly the best responses in its support. -/
@[simp] theorem uniformRandomizedClassifierAgentResponseFamily_support
    {Parameter Agent AgentType Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) (agent : Agent) (chosen : Feature) :
    chosen ∈
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter agent).support ↔
      IsAgentStrategicBestResponse
        (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
        environment agent chosen := by
  exact uniformAgentStrategicResponseKernel_support
    (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
    environment agent chosen

theorem uniformRandomizedClassifierAgentResponseFamily_spec
    {Parameter Agent AgentType Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    IsAgentStrategicBestResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
      environment
      (uniformRandomizedClassifierAgentResponseFamily
        negativeScore positiveScore classifier environment parameter) :=
  uniformAgentStrategicResponseKernel_spec
    (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
    environment

/-- Uniform best-response tie-breaking in the homogeneous feature-indexed model. -/
noncomputable def uniformRandomizedClassifierResponseFamily
    {Parameter Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) : Parameter → Feature → PMF Feature :=
  fun parameter =>
    uniformStrategicResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter)) cost

@[simp] theorem uniformRandomizedClassifierResponseFamily_support
    {Parameter Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ)
    (parameter : Parameter) (initial chosen : Feature) :
    chosen ∈
        (uniformRandomizedClassifierResponseFamily
          negativeScore positiveScore classifier cost parameter initial).support ↔
      IsStrategicBestResponse
        (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
        cost initial chosen := by
  exact uniformStrategicResponseKernel_support
    (randomizedBinaryScore negativeScore positiveScore (classifier parameter))
    cost initial chosen

theorem uniformRandomizedClassifierResponseFamily_spec
    {Parameter Feature : Type*} [Fintype Feature]
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    IsStrategicBestResponseKernel
      (randomizedBinaryScore negativeScore positiveScore (classifier parameter)) cost
      (uniformRandomizedClassifierResponseFamily
        negativeScore positiveScore classifier cost parameter) :=
  uniformStrategicResponseKernel_spec
    (randomizedBinaryScore negativeScore positiveScore (classifier parameter)) cost

/-!
## Parameter-indexed response welfare

The observable performative data law forgets agent identity and its original
feature.  Welfare calculations instead use the joint response trace from
`StrategicResponseWelfare`, retaining enough information to evaluate realized
manipulation cost and strategic utility under randomized response families.
-/

/-- Population expected realized score under one parameter-indexed response family. -/
noncomputable def agentPerformativeExpectedResponseScore
    {Parameter Agent Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label)) (score : Parameter → Feature → ℝ)
    (response : Parameter → Agent → PMF Feature) (parameter : Parameter) : ℝ :=
  agentPopulationExpectedResponseScore baseLaw (score parameter)
    (response parameter)

/-- Population expected realized manipulation cost under a response family. -/
noncomputable def agentPerformativeExpectedManipulationCost
    {Parameter Agent AgentType Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label))
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature) (parameter : Parameter) : ℝ :=
  agentPopulationExpectedManipulationCost baseLaw environment
    (response parameter)

/-- Population expected strategic utility under a parameter-indexed response family. -/
noncomputable def agentPerformativeExpectedResponseUtility
    {Parameter Agent AgentType Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label)) (score : Parameter → Feature → ℝ)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature) (parameter : Parameter) : ℝ :=
  agentPopulationExpectedResponseUtility baseLaw (score parameter) environment
    (response parameter)

/-- Positive-label realized response burden at one deployed parameter. -/
noncomputable def agentPerformativeResponseSocialBurden
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature) (parameter : Parameter) : ℝ :=
  agentResponseSocialBurden baseLaw environment (response parameter)

/-- Positive-label realized response burden for one economic agent type. -/
noncomputable def agentTypePerformativeResponseSocialBurden
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent] [DecidableEq AgentType]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) (agentType : AgentType) : ℝ :=
  agentTypeResponseSocialBurden baseLaw environment (response parameter) agentType

/-- Difference in realized response burden between two types at one parameter. -/
noncomputable def agentTypePerformativeResponseSocialGap
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent] [DecidableEq AgentType]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) (first second : AgentType) : ℝ :=
  agentTypePerformativeResponseSocialBurden
      baseLaw environment response parameter second -
    agentTypePerformativeResponseSocialBurden
      baseLaw environment response parameter first

/-- Performative expected utility is score minus realized manipulation cost. -/
theorem agentPerformativeExpectedResponseUtility_eq_score_sub_cost
    {Parameter Agent AgentType Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label)) (score : Parameter → Feature → ℝ)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (response : Parameter → Agent → PMF Feature) (parameter : Parameter) :
    agentPerformativeExpectedResponseUtility
        baseLaw score environment response parameter =
      agentPerformativeExpectedResponseScore baseLaw score response parameter -
        agentPerformativeExpectedManipulationCost
          baseLaw environment response parameter :=
  agentPopulationExpectedResponseUtility_eq_score_sub_cost
    baseLaw (score parameter) environment (response parameter)

/--
Expected utility is invariant across any two parameter-indexed best-response
families, even when their induced observable laws and manipulation costs differ.
-/
theorem agentPerformativeExpectedResponseUtility_eq_of_bestResponseFamilies
    {Parameter Agent AgentType Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label)) (score : Parameter → Feature → ℝ)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (first second : Parameter → Agent → PMF Feature)
    (hfirst : ∀ parameter,
      IsAgentStrategicBestResponseKernel
        (score parameter) environment (first parameter))
    (hsecond : ∀ parameter,
      IsAgentStrategicBestResponseKernel
        (score parameter) environment (second parameter))
    (parameter : Parameter) :
    agentPerformativeExpectedResponseUtility
        baseLaw score environment first parameter =
      agentPerformativeExpectedResponseUtility
        baseLaw score environment second parameter :=
  agentPopulationExpectedResponseUtility_eq_of_bestResponseKernels
    baseLaw (score parameter) environment (first parameter) (second parameter)
    (hfirst parameter) (hsecond parameter)

/--
Across best-response response families, the population score change equals the
population manipulation-cost change at every parameter.
-/
theorem agentPerformativeExpectedResponseScore_sub_eq_cost_sub_of_bestResponseFamilies
    {Parameter Agent AgentType Label Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Label] [DecidableEq Label]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Label)) (score : Parameter → Feature → ℝ)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (first second : Parameter → Agent → PMF Feature)
    (hfirst : ∀ parameter,
      IsAgentStrategicBestResponseKernel
        (score parameter) environment (first parameter))
    (hsecond : ∀ parameter,
      IsAgentStrategicBestResponseKernel
        (score parameter) environment (second parameter))
    (parameter : Parameter) :
    agentPerformativeExpectedResponseScore baseLaw score first parameter -
        agentPerformativeExpectedResponseScore baseLaw score second parameter =
      agentPerformativeExpectedManipulationCost
          baseLaw environment first parameter -
        agentPerformativeExpectedManipulationCost
          baseLaw environment second parameter :=
  agentPopulationExpectedResponseScore_sub_eq_cost_sub_of_bestResponseKernels
    baseLaw (score parameter) environment (first parameter) (second parameter)
    (hfirst parameter) (hsecond parameter)

/-- Selected and uniform best-response tie breaking give equal population utility. -/
theorem selectedRandomizedClassifierAgentPerformativeExpectedUtility_eq_uniform
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    agentPerformativeExpectedResponseUtility baseLaw
        (fun deployed => randomizedBinaryScore negativeScore positiveScore
          (classifier deployed)) environment
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter =
      agentPerformativeExpectedResponseUtility baseLaw
        (fun deployed => randomizedBinaryScore negativeScore positiveScore
          (classifier deployed)) environment
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter := by
  apply agentPerformativeExpectedResponseUtility_eq_of_bestResponseFamilies
  · exact selectedRandomizedClassifierAgentResponseFamily_spec
      negativeScore positiveScore classifier environment
  · exact uniformRandomizedClassifierAgentResponseFamily_spec
      negativeScore positiveScore classifier environment

/--
For selected versus uniform classifier best responses, the population score
difference is exactly the population manipulation-cost difference.
-/
theorem selectedRandomizedClassifierAgentPerformativeExpectedScore_sub_eq_cost_sub_uniform
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    agentPerformativeExpectedResponseScore baseLaw
        (fun deployed => randomizedBinaryScore negativeScore positiveScore
          (classifier deployed))
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter -
      agentPerformativeExpectedResponseScore baseLaw
        (fun deployed => randomizedBinaryScore negativeScore positiveScore
          (classifier deployed))
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter =
    agentPerformativeExpectedManipulationCost baseLaw environment
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter -
      agentPerformativeExpectedManipulationCost baseLaw environment
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment) parameter := by
  apply agentPerformativeExpectedResponseScore_sub_eq_cost_sub_of_bestResponseFamilies
  · exact selectedRandomizedClassifierAgentResponseFamily_spec
      negativeScore positiveScore classifier environment
  · exact uniformRandomizedClassifierAgentResponseFamily_spec
      negativeScore positiveScore classifier environment

/-- Conditional probability that a randomized classifier predicts the binary label correctly. -/
noncomputable def randomizedBinaryCorrectness
    {Parameter Feature : Type*}
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (datum : Feature × Bool) (parameter : Parameter) : ℝ :=
  if datum.2 then acceptanceProbability (classifier parameter) datum.1
  else 1 - acceptanceProbability (classifier parameter) datum.1

/-- Conditional zero-one loss of a randomized classifier. -/
noncomputable def randomizedBinaryMisclassificationLoss
    {Parameter Feature : Type*}
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (datum : Feature × Bool) (parameter : Parameter) : ℝ :=
  1 - randomizedBinaryCorrectness classifier datum parameter

/--
A randomized classifier paired with an arbitrary heterogeneous response
kernel, viewed as a performative model.  Best-response optimality is a
separate property of the kernel, so the data-law and risk identities below
also apply to behavioral or empirically estimated response maps.
-/
noncomputable def randomizedClassifierAgentPerformativeModel
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature) :
    FinitePerformativeModel Parameter (Feature × Bool) :=
  agentStrategicPerformativeModel baseLaw response
    (randomizedBinaryMisclassificationLoss classifier)

@[simp] theorem randomizedClassifierAgentPerformativeModel_dataLaw
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) :
    (randomizedClassifierAgentPerformativeModel
      baseLaw classifier response).dataLaw parameter =
      inducedAgentStrategicDataLaw baseLaw (response parameter) :=
  rfl

/-- Zero-one performative risk is the complement of induced randomized accuracy. -/
theorem performativeRisk_randomizedClassifierAgentPerformativeModel
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) :
    performativeRisk
        (randomizedClassifierAgentPerformativeModel
          baseLaw classifier response) parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (response parameter) := by
  unfold performativeRisk randomizedClassifierAgentPerformativeModel
    agentStrategicPerformativeModel randomizedBinaryMisclassificationLoss
    randomizedBinaryCorrectness randomizedAgentStrategicAccuracy
  rw [pmfExp_sub, pmfExp_const]

/-- The arbitrary-response diagonal objective in leader--follower notation. -/
noncomputable def randomizedClassifierAgentStackelbergRisk
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) : ℝ :=
  agentStackelbergRisk baseLaw response
    (randomizedBinaryMisclassificationLoss classifier) parameter

@[simp] theorem randomizedClassifierAgentStackelbergRisk_eq_performativeRisk
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) :
    randomizedClassifierAgentStackelbergRisk
        baseLaw classifier response parameter =
      performativeRisk
        (randomizedClassifierAgentPerformativeModel
          baseLaw classifier response) parameter :=
  rfl

theorem randomizedClassifierAgentStackelbergRisk_eq_one_sub_accuracy
    {Parameter Agent Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature)
    (parameter : Parameter) :
    randomizedClassifierAgentStackelbergRisk
        baseLaw classifier response parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (response parameter) := by
  rw [randomizedClassifierAgentStackelbergRisk_eq_performativeRisk,
    performativeRisk_randomizedClassifierAgentPerformativeModel]

/--
The performative model induced by full-support uniform tie-breaking among all
best responses to each deployed randomized classifier.
-/
noncomputable def uniformRandomizedClassifierAgentPerformativeModel
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature) :
    FinitePerformativeModel Parameter (Feature × Bool) :=
  randomizedClassifierAgentPerformativeModel baseLaw classifier
    (uniformRandomizedClassifierAgentResponseFamily
      negativeScore positiveScore classifier environment)

@[simp] theorem uniformRandomizedClassifierAgentPerformativeModel_dataLaw
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    (uniformRandomizedClassifierAgentPerformativeModel
      baseLaw negativeScore positiveScore classifier environment).dataLaw parameter =
      inducedAgentStrategicDataLaw baseLaw
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) :=
  rfl

theorem performativeRisk_uniformRandomizedClassifierAgentPerformativeModel
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    performativeRisk
        (uniformRandomizedClassifierAgentPerformativeModel
          baseLaw negativeScore positiveScore classifier environment) parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) := by
  exact performativeRisk_randomizedClassifierAgentPerformativeModel
    baseLaw classifier
    (uniformRandomizedClassifierAgentResponseFamily
      negativeScore positiveScore classifier environment) parameter

/-- The Stackelberg objective under uniform best-response tie-breaking. -/
noncomputable def uniformRandomizedClassifierAgentStackelbergRisk
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) : ℝ :=
  randomizedClassifierAgentStackelbergRisk baseLaw classifier
    (uniformRandomizedClassifierAgentResponseFamily
      negativeScore positiveScore classifier environment) parameter

@[simp] theorem uniformRandomizedClassifierAgentStackelbergRisk_eq_performativeRisk
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    uniformRandomizedClassifierAgentStackelbergRisk
        baseLaw negativeScore positiveScore classifier environment parameter =
      performativeRisk
        (uniformRandomizedClassifierAgentPerformativeModel
          baseLaw negativeScore positiveScore classifier environment) parameter :=
  rfl

theorem uniformRandomizedClassifierAgentStackelbergRisk_eq_one_sub_accuracy
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    uniformRandomizedClassifierAgentStackelbergRisk
        baseLaw negativeScore positiveScore classifier environment parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (uniformRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) := by
  rw [uniformRandomizedClassifierAgentStackelbergRisk_eq_performativeRisk,
    performativeRisk_uniformRandomizedClassifierAgentPerformativeModel]

/--
The performative model generated by the selected responses of a heterogeneous
population.  The base law retains agent identity and label, while the learner
observes only the post-response feature and the unchanged label.
-/
noncomputable def selectedRandomizedClassifierAgentPerformativeModel
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature) :
    FinitePerformativeModel Parameter (Feature × Bool) :=
  agentStrategicPerformativeModel baseLaw
    (selectedRandomizedClassifierAgentResponseFamily
      negativeScore positiveScore classifier environment)
    (randomizedBinaryMisclassificationLoss classifier)

@[simp] theorem selectedRandomizedClassifierAgentPerformativeModel_dataLaw
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    (selectedRandomizedClassifierAgentPerformativeModel
      baseLaw negativeScore positiveScore classifier environment).dataLaw parameter =
      inducedAgentStrategicDataLaw baseLaw
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) :=
  rfl

/--
The heterogeneous-agent performative risk is one minus accuracy under the
same selected response law.
-/
theorem performativeRisk_selectedRandomizedClassifierAgentPerformativeModel
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    performativeRisk
        (selectedRandomizedClassifierAgentPerformativeModel
          baseLaw negativeScore positiveScore classifier environment) parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) := by
  unfold performativeRisk selectedRandomizedClassifierAgentPerformativeModel
    agentStrategicPerformativeModel randomizedBinaryMisclassificationLoss
    randomizedBinaryCorrectness randomizedAgentStrategicAccuracy
  rw [pmfExp_sub, pmfExp_const]

/-- The heterogeneous leader--follower objective for the selected response family. -/
noncomputable def selectedRandomizedClassifierAgentStackelbergRisk
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) : ℝ :=
  agentStackelbergRisk baseLaw
    (selectedRandomizedClassifierAgentResponseFamily
      negativeScore positiveScore classifier environment)
    (randomizedBinaryMisclassificationLoss classifier) parameter

theorem selectedRandomizedClassifierAgentStackelbergRisk_eq_performativeRisk
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    selectedRandomizedClassifierAgentStackelbergRisk
        baseLaw negativeScore positiveScore classifier environment parameter =
      performativeRisk
        (selectedRandomizedClassifierAgentPerformativeModel
          baseLaw negativeScore positiveScore classifier environment) parameter :=
  rfl

/-- Heterogeneous Stackelberg risk is exactly one minus induced accuracy. -/
theorem selectedRandomizedClassifierAgentStackelbergRisk_eq_one_sub_accuracy
    {Parameter Agent AgentType Feature : Type*}
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (environment : StrategicAgentEnvironment Agent AgentType Feature)
    (parameter : Parameter) :
    selectedRandomizedClassifierAgentStackelbergRisk
        baseLaw negativeScore positiveScore classifier environment parameter =
      1 - randomizedAgentStrategicAccuracy baseLaw (classifier parameter)
        (selectedRandomizedClassifierAgentResponseFamily
          negativeScore positiveScore classifier environment parameter) := by
  rw [selectedRandomizedClassifierAgentStackelbergRisk_eq_performativeRisk,
    performativeRisk_selectedRandomizedClassifierAgentPerformativeModel]

/--
The performative model generated by finite-agent best responses to a deployed
randomized classifier.
-/
noncomputable def selectedRandomizedClassifierPerformativeModel
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) :
    FinitePerformativeModel Parameter (Feature × Bool) :=
  strategicPerformativeModel baseLaw
    (selectedRandomizedClassifierResponseFamily
      negativeScore positiveScore classifier cost)
    (randomizedBinaryMisclassificationLoss classifier)

@[simp] theorem selectedRandomizedClassifierPerformativeModel_dataLaw
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    (selectedRandomizedClassifierPerformativeModel
      baseLaw negativeScore positiveScore classifier cost).dataLaw parameter =
      inducedStrategicDataLaw baseLaw
        (selectedRandomizedClassifierResponseFamily
          negativeScore positiveScore classifier cost parameter) :=
  rfl

/-- The model's performative risk is one minus its strategically induced accuracy. -/
theorem performativeRisk_selectedRandomizedClassifierPerformativeModel
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    performativeRisk
        (selectedRandomizedClassifierPerformativeModel
          baseLaw negativeScore positiveScore classifier cost) parameter =
      1 - randomizedStrategicAccuracy baseLaw (classifier parameter)
        (selectedRandomizedClassifierResponseFamily
          negativeScore positiveScore classifier cost parameter) := by
  unfold performativeRisk selectedRandomizedClassifierPerformativeModel
    strategicPerformativeModel randomizedBinaryMisclassificationLoss
    randomizedBinaryCorrectness randomizedStrategicAccuracy
  rw [pmfExp_sub, pmfExp_const]

/-- The same diagonal objective, named in its leader--follower interpretation. -/
noncomputable def selectedRandomizedClassifierStackelbergRisk
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) : ℝ :=
  stackelbergRisk baseLaw
    (selectedRandomizedClassifierResponseFamily
      negativeScore positiveScore classifier cost)
    (randomizedBinaryMisclassificationLoss classifier) parameter

theorem selectedRandomizedClassifierStackelbergRisk_eq_performativeRisk
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    selectedRandomizedClassifierStackelbergRisk
        baseLaw negativeScore positiveScore classifier cost parameter =
      performativeRisk
        (selectedRandomizedClassifierPerformativeModel
          baseLaw negativeScore positiveScore classifier cost) parameter :=
  rfl

/-- Stackelberg risk is exactly one minus accuracy under the induced response law. -/
theorem selectedRandomizedClassifierStackelbergRisk_eq_one_sub_accuracy
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    selectedRandomizedClassifierStackelbergRisk
        baseLaw negativeScore positiveScore classifier cost parameter =
      1 - randomizedStrategicAccuracy baseLaw (classifier parameter)
        (selectedRandomizedClassifierResponseFamily
          negativeScore positiveScore classifier cost parameter) := by
  rw [selectedRandomizedClassifierStackelbergRisk_eq_performativeRisk,
    performativeRisk_selectedRandomizedClassifierPerformativeModel]

/-- Deterministic classifiers embed into the selected randomized-classifier model. -/
noncomputable def selectedDeterministicClassifierPerformativeModel
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → BinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) :
    FinitePerformativeModel Parameter (Feature × Bool) :=
  selectedRandomizedClassifierPerformativeModel baseLaw negativeScore positiveScore
    (fun parameter => deterministicAsRandomized (classifier parameter)) cost

/--
For deterministic classifiers, performative zero-one risk is the complement
of the strategic-classification jury accuracy under the same selected response.
-/
theorem performativeRisk_selectedDeterministicClassifierPerformativeModel
    {Parameter Feature : Type*}
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Feature × Bool))
    (negativeScore positiveScore : ℝ)
    (classifier : Parameter → BinaryClassifier Feature)
    (cost : Feature → Feature → ℝ) (parameter : Parameter) :
    performativeRisk
        (selectedDeterministicClassifierPerformativeModel
          baseLaw negativeScore positiveScore classifier cost) parameter =
      1 - strategicAccuracy baseLaw (classifier parameter)
        (selectedRandomizedClassifierResponse negativeScore positiveScore
          (deterministicAsRandomized (classifier parameter)) cost) := by
  rw [selectedDeterministicClassifierPerformativeModel,
    performativeRisk_selectedRandomizedClassifierPerformativeModel]
  simp [selectedRandomizedClassifierResponseFamily,
    selectedRandomizedClassifierResponseKernel]

/--
Agent-level response transport stability lifts to transport sensitivity of the
observable strategic performative model.  The common population draw couples
agent identity and label exactly, so the lift loses no constant.
-/
theorem agentStrategicPerformativeModel_finiteTransportSensitive_of_response
    {Parameter Agent Feature Label : Type*}
    [MetricSpace Parameter] [MetricSpace Feature] [MetricSpace Label]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Agent × Label))
    (response : Parameter → Agent → PMF Feature)
    (loss : (Feature × Label) → Parameter → ℝ) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteTransportSensitive
      (agentStrategicPerformativeModel baseLaw response loss) sensitivity := by
  intro first second
  simpa [agentStrategicPerformativeModel] using
    (inducedAgentStrategicDataLaw_hasExpectedCostLE baseLaw
      (response first) (response second) (sensitivity * dist first second)
      (fun agent => hresponse first second agent))

/-- The same primitive response condition implies finite Wasserstein sensitivity. -/
theorem agentStrategicPerformativeModel_finiteWassersteinSensitive_of_response
    {Parameter Agent Feature Label : Type*}
    [MetricSpace Parameter] [MetricSpace Feature] [MetricSpace Label]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Agent × Label))
    (response : Parameter → Agent → PMF Feature)
    (loss : (Feature × Label) → Parameter → ℝ) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteWassersteinSensitive
      (agentStrategicPerformativeModel baseLaw response loss) sensitivity :=
  IsFiniteWassersteinSensitive.of_finiteTransportSensitive _
    (agentStrategicPerformativeModel_finiteTransportSensitive_of_response
      baseLaw response loss sensitivity hresponse)

/--
Pointwise Lipschitz deterministic strategic behavior therefore supplies the
distribution-sensitivity premise used by performative convergence theorems.
-/
theorem agentStrategicPerformativeModel_finiteTransportSensitive_of_deterministic_lipschitz
    {Parameter Agent Feature Label : Type*}
    [MetricSpace Parameter] [MetricSpace Feature] [MetricSpace Label]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Agent × Label))
    (response : Parameter → Agent → Feature)
    (loss : (Feature × Label) → Parameter → ℝ) (sensitivity : NNReal)
    (hresponse : ∀ agent,
      LipschitzWith sensitivity (fun parameter => response parameter agent)) :
    IsFiniteTransportSensitive
      (agentStrategicPerformativeModel baseLaw
        (fun parameter => deterministicAgentResponseKernel (response parameter)) loss)
      (sensitivity : ℝ) :=
  agentStrategicPerformativeModel_finiteTransportSensitive_of_response
    baseLaw (fun parameter => deterministicAgentResponseKernel (response parameter))
    loss (sensitivity : ℝ)
    (isAgentResponseTransportSensitive_deterministicAgentResponseKernel
      response sensitivity hresponse)

/-- Homogeneous strategic response families inherit the same transport coefficient. -/
theorem strategicPerformativeModel_finiteTransportSensitive_of_response
    {Parameter Feature Label : Type*}
    [MetricSpace Parameter] [MetricSpace Feature] [MetricSpace Label]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Feature × Label))
    (response : Parameter → Feature → PMF Feature)
    (loss : (Feature × Label) → Parameter → ℝ) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteTransportSensitive
      (strategicPerformativeModel baseLaw response loss) sensitivity := by
  simpa only [agentStrategicPerformativeModel_featureAgents] using
    (agentStrategicPerformativeModel_finiteTransportSensitive_of_response
      baseLaw response loss sensitivity hresponse)

/-- Homogeneous transport sensitivity also yields Wasserstein sensitivity. -/
theorem strategicPerformativeModel_finiteWassersteinSensitive_of_response
    {Parameter Feature Label : Type*}
    [MetricSpace Parameter] [MetricSpace Feature] [MetricSpace Label]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Feature × Label))
    (response : Parameter → Feature → PMF Feature)
    (loss : (Feature × Label) → Parameter → ℝ) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteWassersteinSensitive
      (strategicPerformativeModel baseLaw response loss) sensitivity :=
  IsFiniteWassersteinSensitive.of_finiteTransportSensitive _
    (strategicPerformativeModel_finiteTransportSensitive_of_response
      baseLaw response loss sensitivity hresponse)

/--
An arbitrary randomized-classifier response model is transport-sensitive as
soon as its agent response family satisfies the primitive transport condition.
-/
theorem randomizedClassifierAgentPerformativeModel_finiteTransportSensitive
    {Parameter Agent Feature : Type*}
    [MetricSpace Parameter] [MetricSpace Feature]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteTransportSensitive
      (randomizedClassifierAgentPerformativeModel baseLaw classifier response)
      sensitivity := by
  exact agentStrategicPerformativeModel_finiteTransportSensitive_of_response
    baseLaw response (randomizedBinaryMisclassificationLoss classifier)
    sensitivity hresponse

/-- The randomized-classifier model consequently satisfies finite Wasserstein sensitivity. -/
theorem randomizedClassifierAgentPerformativeModel_finiteWassersteinSensitive
    {Parameter Agent Feature : Type*}
    [MetricSpace Parameter] [MetricSpace Feature]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    (baseLaw : PMF (Agent × Bool))
    (classifier : Parameter → RandomizedBinaryClassifier Feature)
    (response : Parameter → Agent → PMF Feature) (sensitivity : ℝ)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity) :
    IsFiniteWassersteinSensitive
      (randomizedClassifierAgentPerformativeModel baseLaw classifier response)
      sensitivity :=
  IsFiniteWassersteinSensitive.of_finiteTransportSensitive _
    (randomizedClassifierAgentPerformativeModel_finiteTransportSensitive
      baseLaw classifier response sensitivity hresponse)

/--
End-to-end repeated-risk-minimization convergence for a strategic population.
Agent-level transport stability supplies the performative distribution-shift
coefficient; joint gradient smoothness, pointwise strong convexity, and the
strict `sensitivity * smoothness / modulus < 1` condition then give a unique
domain-stable point and the geometric retraining rate.
-/
theorem agentStrategicPerformativeModel_rrmOn_convergesLinearly_of_responseTransportSensitive
    {Parameter Agent Feature Label : Type*}
    [NormedAddCommGroup Parameter] [InnerProductSpace ℝ Parameter]
    [CompleteSpace Parameter]
    [MetricSpace Feature] [MetricSpace Label]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Agent × Label))
    (response : Parameter → Agent → PMF Feature)
    (loss : (Feature × Label) → Parameter → ℝ)
    (gradient : (Feature × Label) → Parameter → Parameter)
    (hgradientAt : ∀ datum evaluated,
      HasGradientAt (fun parameter => loss datum parameter)
        (gradient datum evaluated) evaluated)
    {smoothness : NNReal} (hjoint : IsJointlySmoothGradient gradient smoothness)
    {sensitivity modulus : ℝ} (hsensitivity : 0 ≤ sensitivity)
    (hresponse : IsAgentResponseTransportSensitive response sensitivity)
    (hmodulus : 0 < modulus)
    (hstrong : IsPointwiseGradientStronglyConvex
      (agentStrategicPerformativeModel baseLaw response loss) gradient modulus)
    (domain : Set Parameter) (hclosed : IsClosed domain) (hconvex : Convex ℝ domain)
    (update : Parameter → Parameter)
    (hrrm : IsRepeatedRiskMinimizationOn
      (agentStrategicPerformativeModel baseLaw response loss) domain update)
    (hfactor : sensitivity * (smoothness : ℝ) / modulus < 1)
    (initial : Parameter) (hinitial : initial ∈ domain) :
    ∃ stable ∈ domain,
      IsPerformativelyStableOn
        (agentStrategicPerformativeModel baseLaw response loss) domain stable ∧
      (∀ other ∈ domain,
        IsPerformativelyStableOn
          (agentStrategicPerformativeModel baseLaw response loss) domain other →
          other = stable) ∧
      Filter.Tendsto (fun iteration => update^[iteration] initial)
        Filter.atTop (nhds stable) ∧
      ∀ iteration, ‖update^[iteration] initial - stable‖ ≤
        (sensitivity * (smoothness : ℝ) / modulus) ^ iteration *
          ‖initial - stable‖ := by
  let model := agentStrategicPerformativeModel baseLaw response loss
  have hsensitive : IsFiniteTransportSensitive model sensitivity := by
    exact agentStrategicPerformativeModel_finiteTransportSensitive_of_response
      baseLaw response loss sensitivity hresponse
  have hdistance : ∀ first ∈ domain, ∀ second ∈ domain,
      ‖update first - update second‖ ≤
        (sensitivity * (smoothness : ℝ) / modulus) * ‖first - second‖ := by
    intro first hfirst second hsecond
    exact rrm_distance_le_on_of_strongConvex_firstOrder_transport
      model gradient hjoint.2 hsensitivity hmodulus hsensitive hstrong
      domain update hrrm
      (fun deployed hdeployed =>
        isFrozenFirstOrderOptimal_on_of_hasGradientAt
          model gradient hgradientAt domain hconvex deployed (update deployed)
          (hrrm deployed hdeployed))
      first second hfirst hsecond
  have hcoefficient_nonneg :
      0 ≤ sensitivity * (smoothness : ℝ) / modulus := by positivity
  let factor : NNReal :=
    ⟨sensitivity * (smoothness : ℝ) / modulus, hcoefficient_nonneg⟩
  have hfactor_lt : factor < 1 := by simpa [factor] using hfactor
  have hdistance' : ∀ first ∈ domain, ∀ second ∈ domain,
      dist (update first) (update second) ≤ (factor : ℝ) * dist first second := by
    intro first hfirst second hsecond
    simpa only [factor, NNReal.coe_mk, dist_eq_norm] using
      hdistance first hfirst second hsecond
  have hstableFixed : ∀ parameter,
      IsPerformativelyStableOn model domain parameter → update parameter = parameter := by
    intro parameter hstable
    have hunique : ∀ deployed ∈ domain, ∀ first second,
        IsPopulationRiskMinimizerOn model domain (model.dataLaw deployed) first →
          IsPopulationRiskMinimizerOn model domain (model.dataLaw deployed) second →
          first = second := by
      intro deployed hdeployed first second hfirst hsecond
      exact populationRiskMinimizerOn_unique_of_strongConvex_firstOrder
        model gradient hmodulus hstrong domain deployed first second hfirst hsecond
        (isFrozenFirstOrderOptimal_on_of_hasGradientAt
          model gradient hgradientAt domain hconvex deployed first hfirst).2
    exact retrainingOn_fixedPoint_of_isPerformativelyStableOn_of_uniqueMinimizer
      model domain update hrrm hunique hstable
  have hconvergence :=
    repeatedRiskMinimizationOn_convergesLinearly_of_distanceBound
      model domain hclosed update hrrm factor hfactor_lt hdistance'
      hstableFixed initial hinitial
  simpa only [model, factor, NNReal.coe_mk, dist_eq_norm] using hconvergence

/--
Deterministic-response specialization with the primitive assumption exposed at
the theorem boundary: each named agent's feature response is Lipschitz in the
deployed parameter.  No separate distribution-map sensitivity certificate is
required from the caller.
-/
theorem agentStrategicPerformativeModel_rrmOn_convergesLinearly_of_deterministicResponseLipschitz
    {Parameter Agent Feature Label : Type*}
    [NormedAddCommGroup Parameter] [InnerProductSpace ℝ Parameter]
    [CompleteSpace Parameter]
    [MetricSpace Feature] [MetricSpace Label]
    [Fintype Agent] [DecidableEq Agent]
    [Fintype Feature] [DecidableEq Feature]
    [Fintype Label] [DecidableEq Label]
    (baseLaw : PMF (Agent × Label))
    (response : Parameter → Agent → Feature)
    (loss : (Feature × Label) → Parameter → ℝ)
    (gradient : (Feature × Label) → Parameter → Parameter)
    (hgradientAt : ∀ datum evaluated,
      HasGradientAt (fun parameter => loss datum parameter)
        (gradient datum evaluated) evaluated)
    {smoothness responseSensitivity : NNReal}
    (hjoint : IsJointlySmoothGradient gradient smoothness)
    (hresponse : ∀ agent,
      LipschitzWith responseSensitivity (fun parameter => response parameter agent))
    {modulus : ℝ} (hmodulus : 0 < modulus)
    (hstrong : IsPointwiseGradientStronglyConvex
      (agentStrategicPerformativeModel baseLaw
        (fun parameter => deterministicAgentResponseKernel (response parameter)) loss)
      gradient modulus)
    (domain : Set Parameter) (hclosed : IsClosed domain) (hconvex : Convex ℝ domain)
    (update : Parameter → Parameter)
    (hrrm : IsRepeatedRiskMinimizationOn
      (agentStrategicPerformativeModel baseLaw
        (fun parameter => deterministicAgentResponseKernel (response parameter)) loss)
      domain update)
    (hfactor : (responseSensitivity : ℝ) * (smoothness : ℝ) / modulus < 1)
    (initial : Parameter) (hinitial : initial ∈ domain) :
    ∃ stable ∈ domain,
      IsPerformativelyStableOn
        (agentStrategicPerformativeModel baseLaw
          (fun parameter => deterministicAgentResponseKernel (response parameter)) loss)
        domain stable ∧
      (∀ other ∈ domain,
        IsPerformativelyStableOn
          (agentStrategicPerformativeModel baseLaw
            (fun parameter => deterministicAgentResponseKernel (response parameter)) loss)
          domain other → other = stable) ∧
      Filter.Tendsto (fun iteration => update^[iteration] initial)
        Filter.atTop (nhds stable) ∧
      ∀ iteration, ‖update^[iteration] initial - stable‖ ≤
        ((responseSensitivity : ℝ) * (smoothness : ℝ) / modulus) ^ iteration *
          ‖initial - stable‖ := by
  exact
    agentStrategicPerformativeModel_rrmOn_convergesLinearly_of_responseTransportSensitive
      baseLaw
      (fun parameter => deterministicAgentResponseKernel (response parameter))
      loss gradient hgradientAt hjoint responseSensitivity.coe_nonneg
      (isAgentResponseTransportSensitive_deterministicAgentResponseKernel
        response responseSensitivity hresponse)
      hmodulus hstrong domain hclosed hconvex update hrrm hfactor initial hinitial

end AppliedModelingLib
