import KR21Monoculture.AppendixCTheorem6LemmasSource

/-!
# Appendix C Lemma 2 on an arbitrary finite candidate carrier

The paper states Lemma 2 for every finite RUM.  This module proves its
pointwise contraction argument on `Candidate n`, rather than accepting the
bottom-event inclusion as a premise.  The probability theorem then uses a
single shared innovation vector at the two accuracies, exactly as in the
source coupling.
-/

open AppliedModelingLib Filter MeasureTheory ProbabilityTheory
open AppliedModelingLib.SocialChoice.Ranking

namespace KR21Monoculture

/-- The literal raw RUM score used in Appendix C on an arbitrary finite carrier. -/
noncomputable def appendixCGeneralSourceScore {n : ℕ}
    (value noise : Candidate n -> ℝ) (theta : ℝ) (i : Candidate n) : ℝ :=
  value i + noise i / theta

/-- The ranking generated by the literal arbitrary-finite Appendix C scores. -/
noncomputable def appendixCGeneralSourceRank {n : ℕ}
    (value noise : Candidate n -> ℝ) (theta : ℝ) : Ranking n :=
  rankByScore (appendixCGeneralSourceScore value noise theta)

/--
Increasing accuracy is the source contraction of the lower-accuracy score,
coordinate by coordinate, on any finite candidate carrier.
-/
theorem appendixC_general_source_score_eq_contract_score
    {n : ℕ} {thetaA thetaH : ℝ} (hthetaA : 0 < thetaA) (hthetaH : 0 < thetaH)
    (value noise : Candidate n -> ℝ) (i : Candidate n) :
    appendixCGeneralSourceScore value noise thetaA i =
      rumContractScore (thetaH / thetaA) (value i)
        (appendixCGeneralSourceScore value noise thetaH i) := by
  unfold appendixCGeneralSourceScore rumContractScore AppliedModelingLib.Probability.rumContractScore
  field_simp [ne_of_gt hthetaA, ne_of_gt hthetaH]
  ring

/--
The pointwise content of Appendix C Lemma 2 for an arbitrary finite RUM.
When the strictly lowest-valued candidate is first after a genuine accuracy
contraction, it was already first before contraction.  This does not assume
the desired event inclusion or any ranking-law equality.
-/
theorem appendixC_general_source_bottom_first_high_accuracy_imp_low_accuracy
    {n : ℕ} {thetaA thetaH : ℝ}
    (hthetaH : 0 < thetaH) (hthetaHA : thetaH < thetaA)
    (value noise : Candidate n -> ℝ) (bottom : Candidate n)
    (hbottom : ∀ i : Candidate n, i ≠ bottom -> value bottom < value i) :
    firstChoice (appendixCGeneralSourceRank value noise thetaA) = bottom ->
      firstChoice (appendixCGeneralSourceRank value noise thetaH) = bottom := by
  intro hbetter
  have hthetaA : 0 < thetaA := lt_trans hthetaH hthetaHA
  let t : ℝ := thetaH / thetaA
  let raw : Candidate n -> ℝ :=
    appendixCGeneralSourceScore value noise thetaH
  let contracted : Candidate n -> ℝ :=
    fun i => rumContractScore t (value i) (raw i)
  have hcontract (i : Candidate n) :
      appendixCGeneralSourceScore value noise thetaA i = contracted i := by
    dsimp [contracted, raw, t]
    exact appendixC_general_source_score_eq_contract_score
      hthetaA hthetaH value noise i
  have hbetter' : firstChoice (rankByScore contracted) = bottom := by
    change firstChoice (rankByScore (appendixCGeneralSourceScore value noise thetaA)) = bottom at hbetter
    rw [show appendixCGeneralSourceScore value noise thetaA = contracted by
      funext i
      exact hcontract i] at hbetter
    exact hbetter
  let rawBest : Candidate n := firstChoice (rankByScore raw)
  have hrawMax (i : Candidate n) : raw i <= raw rawBest := by
    apply rankByScore_weaklyOrdersScores raw
    calc
      rankOf (rankByScore raw) rawBest = 0 := rankOf_firstChoice (rankByScore raw)
      _ <= rankOf (rankByScore raw) i := bot_le
  have hcontractMax (i : Candidate n) :
      rumContractScore t (value i) (raw i) <=
        rumContractScore t (value bottom) (raw bottom) := by
    change contracted i <= contracted bottom
    apply rankByScore_weaklyOrdersScores contracted
    calc
      rankOf (rankByScore contracted) bottom = 0 := by
        rw [<- hbetter']
        exact rankOf_firstChoice (rankByScore contracted)
      _ <= rankOf (rankByScore contracted) i := bot_le
  have ht0 : 0 <= t := by
    dsimp [t]
    exact le_of_lt (div_pos hthetaH hthetaA)
  have htlt1 : t < 1 := by
    dsimp [t]
    exact (div_lt_one hthetaA).mpr hthetaHA
  have hvalue : value rawBest <= value bottom :=
    rumContractScore_value_le_of_raw_max_and_contract_max
      ht0 htlt1 hrawMax hcontractMax
  have hrawBest : rawBest = bottom := by
    by_contra hne
    have hlt : value bottom < value rawBest := hbottom rawBest hne
    linarith
  change firstChoice (rankByScore raw) = bottom
  exact hrawBest

/--
Appendix C Lemma 2 at the literal arbitrary-finite source-score PMF surface.
The innovation law is deliberately left general: the conclusion only needs
the source's same-realization contraction, and hence applies in particular to
the iid product laws used by a RUM family.
-/
theorem appendixC_general_source_lemma2_bottom_first_probability
    {n : ℕ} {thetaA thetaH : ℝ}
    (mu : Measure (Candidate n -> ℝ)) [IsProbabilityMeasure mu]
    (hthetaH : 0 < thetaH) (hthetaHA : thetaH < thetaA)
    (value : Candidate n -> ℝ) (bottom : Candidate n)
    (hbottom : ∀ i : Candidate n, i ≠ bottom -> value bottom < value i) :
    firstChoiceProb (paper_appendixA_scaledNoiseRankingPMF mu value thetaA) bottom <=
      firstChoiceProb (paper_appendixA_scaledNoiseRankingPMF mu value thetaH) bottom := by
  let rankA : (Candidate n -> ℝ) -> Ranking n := fun noise =>
    appendixCGeneralSourceRank value noise thetaA
  let rankH : (Candidate n -> ℝ) -> Ranking n := fun noise =>
    appendixCGeneralSourceRank value noise thetaH
  have hrankA : Measurable rankA := by
    exact paper_appendixA_scaledNoise_rankByScore_measurable
      (fun noise : Candidate n -> ℝ => noise)
      (fun i => measurable_pi_apply i) value thetaA
  have hrankH : Measurable rankH := by
    exact paper_appendixA_scaledNoise_rankByScore_measurable
      (fun noise : Candidate n -> ℝ => noise)
      (fun i => measurable_pi_apply i) value thetaH
  change firstChoiceProb (rankingPMFOfMeasure mu rankA hrankA) bottom <=
    firstChoiceProb (rankingPMFOfMeasure mu rankH hrankH) bottom
  change AppliedModelingLib.SocialChoice.Ranking.firstChoiceProb
      (rankingPMFOfMeasure mu rankA hrankA) bottom <=
    AppliedModelingLib.SocialChoice.Ranking.firstChoiceProb
      (rankingPMFOfMeasure mu rankH hrankH) bottom
  rw [AppliedModelingLib.SocialChoice.Ranking.firstChoiceProb_rankingPMFOfMeasure,
    AppliedModelingLib.SocialChoice.Ranking.firstChoiceProb_rankingPMFOfMeasure]
  refine measureProb_le_of_measure_le mu _ _ (measure_mono ?_)
  intro noise hnoise
  exact (appendixC_general_source_bottom_first_high_accuracy_imp_low_accuracy
    hthetaH hthetaHA value noise bottom hbottom) hnoise.symm |>.symm

end KR21Monoculture
