import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Fintype.Option
import Mathlib.Data.Fintype.Pi
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import AppliedModelingLib.Foundations.Optimization.FiniteSearch

open scoped BigOperators

namespace AppliedModelingLib
namespace Auction

/--
A finite position-auction environment.

`clickThroughRate s` is the expected number of clicks generated by slot `s`.
The GSP Test-of-Time papers specialize this structure to ordered sponsored
search slots with weakly decreasing click-through rates.
-/
structure PositionEnvironment (Slot : Type*) where
  clickThroughRate : Slot → ℝ

/--
An outcome for a position auction: each bidder is either assigned a slot or left
unassigned, and each bidder has a per-click payment.
-/
structure PositionOutcome (Bidder Slot : Type*) where
  slotOf : Bidder → Option Slot
  paymentPerClick : Bidder → ℝ

namespace PositionOutcome

variable {Bidder Slot : Type*}

@[ext]
theorem ext (O P : PositionOutcome Bidder Slot)
    (hslot : ∀ i, O.slotOf i = P.slotOf i)
    (hpay : ∀ i, O.paymentPerClick i = P.paymentPerClick i) :
    O = P := by
  cases O
  cases P
  simp only at hslot hpay
  congr
  · funext i
    exact hslot i
  · funext i
    exact hpay i

/-- Quasilinear expected utility in a position auction. -/
def utility (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) : ℝ :=
  match O.slotOf i with
  | none => 0
  | some s => E.clickThroughRate s * (values i - O.paymentPerClick i)

/-- Expected revenue contribution from one bidder. -/
def revenueContribution (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (i : Bidder) : ℝ :=
  match O.slotOf i with
  | none => 0
  | some s => E.clickThroughRate s * O.paymentPerClick i

/-- Total expected revenue. -/
noncomputable def revenue [Fintype Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot) : ℝ :=
  ∑ i : Bidder, revenueContribution E O i

/-- Total expected allocative welfare. -/
noncomputable def welfare [Fintype Bidder]
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : ℝ :=
  ∑ i : Bidder,
    match O.slotOf i with
    | none => 0
    | some s => E.clickThroughRate s * values i

/-- One bidder's contribution to allocative welfare. -/
def welfareContribution
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (i : Bidder) : ℝ :=
  match O.slotOf i with
  | none => 0
  | some s => E.clickThroughRate s * values i

/-- Allocative welfare excluding one bidder. -/
noncomputable def welfareExcept [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (i : Bidder) : ℝ :=
  (Finset.univ.erase i).sum fun j => O.welfareContribution E values j

/-- Outcome with the supplied slot assignment and zero per-click payments. -/
def zeroPaymentOutcome (slotOf : Bidder → Option Slot) :
    PositionOutcome Bidder Slot where
  slotOf := slotOf
  paymentPerClick := fun _ => 0

/-- Remove one bidder's slot assignment, leaving all other assignment and payment data fixed. -/
def removeBidderSlot [DecidableEq Bidder]
    (O : PositionOutcome Bidder Slot) (i : Bidder) :
    PositionOutcome Bidder Slot where
  slotOf := Function.update O.slotOf i none
  paymentPerClick := O.paymentPerClick

/-- No slot is assigned to two different bidders. -/
def FeasibleAssignment (O : PositionOutcome Bidder Slot) : Prop :=
  ∀ ⦃i j : Bidder⦄ ⦃s : Slot⦄,
    O.slotOf i = some s → O.slotOf j = some s → i = j

/-- Every bidder receives nonnegative utility in the outcome. -/
def IndividuallyRational (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : Prop :=
  ∀ i, 0 ≤ O.utility E values i

theorem utility_eq_zero_of_unassigned
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) {i : Bidder}
    (hslot : O.slotOf i = none) :
    utility E O values i = 0 := by
  simp [utility, hslot]

theorem revenue_nonneg [Fintype Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (hctr : ∀ s, 0 ≤ E.clickThroughRate s)
    (hpay : ∀ i, 0 ≤ O.paymentPerClick i) :
    0 ≤ revenue E O := by
  classical
  unfold revenue
  exact Finset.sum_nonneg fun i _ => by
    cases hslot : O.slotOf i with
    | none =>
        simp [revenueContribution, hslot]
    | some s =>
        simpa [revenueContribution, hslot] using
          mul_nonneg (hctr s) (hpay i)

theorem revenue_le_of_same_slots_payment_le [Fintype Bidder]
    (E : PositionEnvironment Slot) (O P : PositionOutcome Bidder Slot)
    (hctr : ∀ s, 0 ≤ E.clickThroughRate s)
    (hsame_slot : ∀ i, O.slotOf i = P.slotOf i)
    (hpay_le : ∀ i, O.paymentPerClick i ≤ P.paymentPerClick i) :
    O.revenue E ≤ P.revenue E := by
  classical
  unfold revenue
  exact Finset.sum_le_sum fun i _ => by
    cases hslot : O.slotOf i with
    | none =>
        have hPslot : P.slotOf i = none := by
          simpa [hslot] using (hsame_slot i).symm
        simp [revenueContribution, hslot, hPslot]
    | some s =>
        have hPslot : P.slotOf i = some s := by
          simpa [hslot] using (hsame_slot i).symm
        simpa [revenueContribution, hslot, hPslot] using
          mul_le_mul_of_nonneg_left (hpay_le i) (hctr s)

theorem welfare_eq_contribution_add_except
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) :
    O.welfare E values =
      O.welfareContribution E values i + O.welfareExcept E values i := by
  classical
  unfold welfare welfareExcept welfareContribution
  simpa [add_comm] using
    (Finset.sum_erase_add (s := Finset.univ)
      (f := fun j : Bidder =>
        match O.slotOf j with
        | none => 0
        | some s => E.clickThroughRate s * values j)
      (Finset.mem_univ i)).symm

theorem welfareExcept_update_self
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) (value : ℝ) :
    O.welfareExcept E (Function.update values i value) i =
      O.welfareExcept E values i := by
  classical
  unfold welfareExcept welfareContribution
  refine Finset.sum_congr rfl ?_
  intro j hj
  have hji : j ≠ i := (Finset.mem_erase.mp hj).1
  simp [Function.update, hji]

theorem welfare_eq_except_of_unassigned
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) {i : Bidder}
    (hslot : O.slotOf i = none) :
    O.welfare E values = O.welfareExcept E values i := by
  rw [welfare_eq_contribution_add_except E O values i]
  simp [welfareContribution, hslot]

theorem welfare_eq_except_of_value_zero
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) {i : Bidder}
    (hvalue : values i = 0) :
    O.welfare E values = O.welfareExcept E values i := by
  rw [welfare_eq_contribution_add_except E O values i]
  cases hslot : O.slotOf i with
  | none =>
      simp [welfareContribution, hslot]
  | some s =>
      simp [welfareContribution, hslot, hvalue]

theorem welfare_of_update_self_assigned
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) {i : Bidder} {s : Slot}
    (hslot : O.slotOf i = some s) (value : ℝ) :
    O.welfare E (Function.update values i value) =
      E.clickThroughRate s * value + O.welfareExcept E values i := by
  rw [welfare_eq_contribution_add_except E O
    (Function.update values i value) i]
  rw [welfareExcept_update_self E O values i value]
  simp [welfareContribution, hslot]

theorem removeBidderSlot_feasible [DecidableEq Bidder]
    (O : PositionOutcome Bidder Slot) (i : Bidder)
    (hfeasible : O.FeasibleAssignment) :
    (O.removeBidderSlot i).FeasibleAssignment := by
  intro a b s ha hb
  by_cases hai : a = i
  · subst a
    simp [removeBidderSlot] at ha
  · by_cases hbi : b = i
    · subst b
      simp [removeBidderSlot] at hb
    · have ha' : O.slotOf a = some s := by
        simpa [removeBidderSlot, Function.update, hai] using ha
      have hb' : O.slotOf b = some s := by
        simpa [removeBidderSlot, Function.update, hbi] using hb
      exact hfeasible ha' hb'

theorem removeBidderSlot_welfareExcept
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) :
    (O.removeBidderSlot i).welfareExcept E values i =
      O.welfareExcept E values i := by
  classical
  unfold welfareExcept welfareContribution
  refine Finset.sum_congr rfl ?_
  intro j hj
  have hji : j ≠ i := (Finset.mem_erase.mp hj).1
  simp [removeBidderSlot, Function.update, hji]

theorem removeBidderSlot_welfare_eq_welfareExcept
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ) (i : Bidder) :
    (O.removeBidderSlot i).welfare E values =
      O.welfareExcept E values i := by
  have hunassigned : (O.removeBidderSlot i).slotOf i = none := by
    simp [removeBidderSlot]
  rw [welfare_eq_except_of_unassigned E (O.removeBidderSlot i) values
    hunassigned]
  exact removeBidderSlot_welfareExcept E O values i

theorem individuallyRational_of_payment_le_value
    (E : PositionEnvironment Slot) (O : PositionOutcome Bidder Slot)
    (values : Bidder → ℝ)
    (hctr : ∀ s, 0 ≤ E.clickThroughRate s)
    (hpay_le : ∀ i s, O.slotOf i = some s →
      O.paymentPerClick i ≤ values i) :
    O.IndividuallyRational E values := by
  intro i
  cases hslot : O.slotOf i with
  | none =>
      simp [utility, hslot]
  | some s =>
      have hdiff : 0 ≤ values i - O.paymentPerClick i := by
        exact sub_nonneg.mpr (hpay_le i s hslot)
      simpa [utility, hslot] using mul_nonneg (hctr s) hdiff

end PositionOutcome

/-! ## Position mechanisms and equilibrium predicates -/

/-- A position mechanism maps bid profiles to position outcomes. -/
abbrev PositionMechanism (Bidder Slot : Type*) :=
  (Bidder → ℝ) → PositionOutcome Bidder Slot

namespace PositionMechanism

variable {Bidder Slot : Type*}

/-- Utility induced by a position mechanism at a bid profile. -/
def utility (E : PositionEnvironment Slot)
    (M : PositionMechanism Bidder Slot)
    (values bids : Bidder → ℝ) (i : Bidder) : ℝ :=
  (M bids).utility E values i

/-- Dominant-strategy truthfulness for one-dimensional position-auction bids. -/
def TruthfulDominantStrategy [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot) : Prop :=
  ∀ (values : Bidder → ℝ) (i : Bidder) (report : ℝ),
    utility E M values (Function.update values i report) i ≤
      utility E M values values i

/-- Pure Nash equilibrium of a position-auction bidding game. -/
def IsNashEquilibrium [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot)
    (values bids : Bidder → ℝ) : Prop :=
  ∀ (i : Bidder) (report : ℝ),
    utility E M values (Function.update bids i report) i ≤
      utility E M values bids i

/--
VCG-style dominant-strategy certificate for position mechanisms.

The certificate avoids committing to a particular argmax implementation: it
records that the selected outcome maximizes reported welfare, and that each
bidder's utility is reported welfare with her true value substituted, minus a
tax that is independent of her own report.
-/
structure VCGDominantStrategyCertificate [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot) where
  tax : (Bidder → ℝ) → Bidder → ℝ
  welfare_maximizing :
    ∀ reports (outcome : PositionOutcome Bidder Slot),
      outcome.welfare E reports ≤ (M reports).welfare E reports
  utility_eq_welfare_minus_tax :
    ∀ values reports i,
      utility E M values reports i =
        (M reports).welfare E (Function.update reports i (values i)) -
          tax reports i
  tax_independent :
    ∀ reports i report, tax (Function.update reports i report) i = tax reports i

/--
Feasibility-aware VCG-style dominant-strategy certificate for position
mechanisms.

The older `VCGDominantStrategyCertificate` maximizes over all formal
`PositionOutcome`s, including infeasible outcomes that assign one slot to
multiple bidders. This corrected certificate is the source-faithful position
auction version: the mechanism must return feasible outcomes, and welfare
maximization is required only among feasible outcomes.
-/
structure FeasibleVCGDominantStrategyCertificate
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot) where
  tax : (Bidder → ℝ) → Bidder → ℝ
  feasible :
    ∀ reports, (M reports).FeasibleAssignment
  welfare_maximizing :
    ∀ reports (outcome : PositionOutcome Bidder Slot),
      outcome.FeasibleAssignment →
        outcome.welfare E reports ≤ (M reports).welfare E reports
  utility_eq_welfare_minus_tax :
    ∀ values reports i,
      utility E M values reports i =
        (M reports).welfare E (Function.update reports i (values i)) -
          tax reports i
  tax_independent :
    ∀ reports i report, tax (Function.update reports i report) i = tax reports i

/--
Any position mechanism with the VCG welfare-maximization and externality-tax
identity is truthful in dominant strategies.
-/
theorem truthfulDominantStrategy_of_vcgDominantStrategyCertificate
    [Fintype Bidder] [DecidableEq Bidder]
    {E : PositionEnvironment Slot} {M : PositionMechanism Bidder Slot}
    (C : VCGDominantStrategyCertificate E M) :
    TruthfulDominantStrategy E M := by
  intro values i report
  let deviatingReports := Function.update values i report
  have hrestore : Function.update deviatingReports i (values i) = values := by
    funext j
    by_cases hji : j = i
    · subst hji
      simp [deviatingReports]
    · simp [deviatingReports, Function.update, hji]
  have htruth_restore : Function.update values i (values i) = values := by
    funext j
    by_cases hji : j = i
    · subst hji
      simp
    · simp [Function.update, hji]
  have htax : C.tax deviatingReports i = C.tax values i := by
    simpa [deviatingReports] using C.tax_independent values i report
  have hwelfare :
      (M deviatingReports).welfare E values ≤ (M values).welfare E values :=
    C.welfare_maximizing values (M deviatingReports)
  rw [C.utility_eq_welfare_minus_tax values deviatingReports i,
    C.utility_eq_welfare_minus_tax values values i, hrestore, htruth_restore, htax]
  exact sub_le_sub_right hwelfare (C.tax values i)

/--
Any feasible position mechanism with feasible VCG welfare-maximization and an
externality-tax identity is truthful in dominant strategies.
-/
theorem truthfulDominantStrategy_of_feasibleVCGDominantStrategyCertificate
    [Fintype Bidder] [DecidableEq Bidder]
    {E : PositionEnvironment Slot} {M : PositionMechanism Bidder Slot}
    (C : FeasibleVCGDominantStrategyCertificate E M) :
    TruthfulDominantStrategy E M := by
  intro values i report
  let deviatingReports := Function.update values i report
  have hrestore : Function.update deviatingReports i (values i) = values := by
    funext j
    by_cases hji : j = i
    · subst hji
      simp [deviatingReports]
    · simp [deviatingReports, Function.update, hji]
  have htruth_restore : Function.update values i (values i) = values := by
    funext j
    by_cases hji : j = i
    · subst hji
      simp
    · simp [Function.update, hji]
  have htax : C.tax deviatingReports i = C.tax values i := by
    simpa [deviatingReports] using C.tax_independent values i report
  have hwelfare :
      (M deviatingReports).welfare E values ≤ (M values).welfare E values :=
    C.welfare_maximizing values (M deviatingReports) (C.feasible deviatingReports)
  rw [C.utility_eq_welfare_minus_tax values deviatingReports i,
    C.utility_eq_welfare_minus_tax values values i, hrestore, htruth_restore, htax]
  exact sub_le_sub_right hwelfare (C.tax values i)

/-- Reports with bidder `i` replaced by zero. -/
def reportsWithoutBidder [DecidableEq Bidder]
    (reports : Bidder → ℝ) (i : Bidder) : Bidder → ℝ :=
  Function.update reports i 0

theorem reportsWithoutBidder_update_self [DecidableEq Bidder]
    (reports : Bidder → ℝ) (i : Bidder) (report : ℝ) :
    reportsWithoutBidder (Function.update reports i report) i =
      reportsWithoutBidder reports i := by
  funext j
  by_cases hji : j = i
  · subst j
    simp [reportsWithoutBidder]
  · simp [reportsWithoutBidder, Function.update, hji]

/--
VCG benchmark term for a position-auction slot rule: the maximum welfare that
the other bidders obtain when bidder `i`'s report is erased.
-/
noncomputable def positionVCGBenchmark
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot)
    (slotRule : (Bidder → ℝ) → Bidder → Option Slot)
    (reports : Bidder → ℝ) (i : Bidder) : ℝ :=
  (PositionOutcome.zeroPaymentOutcome
      (slotRule (reportsWithoutBidder reports i))).welfareExcept E reports i

/--
The position-auction VCG mechanism generated by a feasible welfare-maximizing
slot rule. Payments are stored per click, so the total Clarke-pivot payment is
divided by the click-through rate of the assigned slot.
-/
noncomputable def positionVCGMechanismOfSlotRule
    [Fintype Bidder] [DecidableEq Bidder]
    (E : PositionEnvironment Slot)
    (slotRule : (Bidder → ℝ) → Bidder → Option Slot) :
    PositionMechanism Bidder Slot :=
  fun reports =>
    let chosen :=
      PositionOutcome.zeroPaymentOutcome (slotRule reports)
    { slotOf := slotRule reports
      paymentPerClick := fun i =>
        match slotRule reports i with
        | none => 0
        | some s =>
            (positionVCGBenchmark E slotRule reports i -
              chosen.welfareExcept E reports i) / E.clickThroughRate s }

theorem exists_welfareMaximizingSlotAssignment
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    (E : PositionEnvironment Slot) (reports : Bidder → ℝ) :
    ∃ slotOf : Bidder → Option Slot,
      (PositionOutcome.zeroPaymentOutcome slotOf).FeasibleAssignment ∧
        ∀ otherSlotOf : Bidder → Option Slot,
          (PositionOutcome.zeroPaymentOutcome otherSlotOf).FeasibleAssignment →
            (PositionOutcome.zeroPaymentOutcome otherSlotOf).welfare E reports ≤
              (PositionOutcome.zeroPaymentOutcome slotOf).welfare E reports := by
  classical
  let feasible : (Bidder → Option Slot) → Prop :=
    fun slotOf => (PositionOutcome.zeroPaymentOutcome slotOf).FeasibleAssignment
  let objective : (Bidder → Option Slot) → ℝ :=
    fun slotOf => (PositionOutcome.zeroPaymentOutcome slotOf).welfare E reports
  have hnonempty : ∃ slotOf : Bidder → Option Slot, feasible slotOf := by
    refine ⟨fun _ => none, ?_⟩
    intro i j s hi _hj
    simp [PositionOutcome.zeroPaymentOutcome] at hi
  obtain ⟨slotOf, hslotOf⟩ :=
    AppliedModelingLib.Optimization.exists_isMaximizerOn_of_finite
      (α := Bidder → Option Slot)
      feasible objective hnonempty
  exact ⟨slotOf, hslotOf⟩

/--
Finite welfare-maximizing feasible slot assignment for a report profile. This
is noncomputable only because it chooses a maximizer from a finite feasible set.
-/
noncomputable def welfareMaximizingSlotAssignment
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    (E : PositionEnvironment Slot) (reports : Bidder → ℝ) :
    Bidder → Option Slot :=
  Classical.choose (exists_welfareMaximizingSlotAssignment E reports)

theorem welfareMaximizingSlotAssignment_feasible
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    (E : PositionEnvironment Slot) (reports : Bidder → ℝ) :
    (PositionOutcome.zeroPaymentOutcome
      (welfareMaximizingSlotAssignment E reports)).FeasibleAssignment :=
  (Classical.choose_spec
    (exists_welfareMaximizingSlotAssignment E reports)).1

theorem welfareMaximizingSlotAssignment_welfare_maximizing
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    (E : PositionEnvironment Slot) (reports : Bidder → ℝ)
    (outcome : PositionOutcome Bidder Slot)
    (hout : outcome.FeasibleAssignment) :
    outcome.welfare E reports ≤
      (PositionOutcome.zeroPaymentOutcome
        (welfareMaximizingSlotAssignment E reports)).welfare E reports := by
  classical
  have hfeasible :
      (PositionOutcome.zeroPaymentOutcome outcome.slotOf).FeasibleAssignment := by
    simpa [PositionOutcome.zeroPaymentOutcome] using hout
  have hmax :=
    (Classical.choose_spec
      (exists_welfareMaximizingSlotAssignment E reports)).2
      outcome.slotOf hfeasible
  simpa [PositionOutcome.welfare, PositionOutcome.zeroPaymentOutcome] using hmax

/--
Canonical finite position-auction VCG mechanism: choose a feasible
welfare-maximizing slot assignment and charge Clarke-pivot per-click payments.
-/
noncomputable def positionVCGMechanism
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    (E : PositionEnvironment Slot) :
    PositionMechanism Bidder Slot :=
  positionVCGMechanismOfSlotRule E (welfareMaximizingSlotAssignment E)

noncomputable def feasibleVCGDominantStrategyCertificate_of_welfareMaximizingSlotRule
    [Fintype Bidder] [DecidableEq Bidder]
    {E : PositionEnvironment Slot}
    {slotRule : (Bidder → ℝ) → Bidder → Option Slot}
    (hclick_pos : ∀ s, 0 < E.clickThroughRate s)
    (hfeasible :
      ∀ reports,
        (PositionOutcome.zeroPaymentOutcome
          (slotRule reports)).FeasibleAssignment)
    (hmax :
      ∀ reports (outcome : PositionOutcome Bidder Slot),
        outcome.FeasibleAssignment →
          outcome.welfare E reports ≤
            (PositionOutcome.zeroPaymentOutcome
              (slotRule reports)).welfare E reports) :
    FeasibleVCGDominantStrategyCertificate E
      (positionVCGMechanismOfSlotRule E slotRule) := by
  classical
  refine
    { tax := positionVCGBenchmark E slotRule
      feasible := ?_
      welfare_maximizing := ?_
      utility_eq_welfare_minus_tax := ?_
      tax_independent := ?_ }
  · intro reports
    simpa [positionVCGMechanismOfSlotRule,
      PositionOutcome.zeroPaymentOutcome] using hfeasible reports
  · intro reports outcome hout
    simpa [positionVCGMechanismOfSlotRule,
      PositionOutcome.zeroPaymentOutcome] using hmax reports outcome hout
  · intro values reports i
    let chosen : PositionOutcome Bidder Slot :=
      PositionOutcome.zeroPaymentOutcome (slotRule reports)
    let without : PositionOutcome Bidder Slot :=
      PositionOutcome.zeroPaymentOutcome
        (slotRule (reportsWithoutBidder reports i))
    have hwithout_welfare_tax :
        without.welfare E (reportsWithoutBidder reports i) =
          positionVCGBenchmark E slotRule reports i := by
      have hzero : reportsWithoutBidder reports i i = 0 := by
        simp [reportsWithoutBidder]
      rw [PositionOutcome.welfare_eq_except_of_value_zero E without
        (reportsWithoutBidder reports i) hzero]
      change
        without.welfareExcept E (Function.update reports i 0) i =
          positionVCGBenchmark E slotRule reports i
      rw [PositionOutcome.welfareExcept_update_self E without reports i 0]
      rfl
    cases hslot : slotRule reports i with
    | none =>
        have hchosen_unassigned : chosen.slotOf i = none := by
          simpa [chosen, PositionOutcome.zeroPaymentOutcome] using hslot
        have hchosen_welfare_reports :
            chosen.welfare E reports =
              chosen.welfareExcept E reports i :=
          PositionOutcome.welfare_eq_except_of_unassigned
            E chosen reports hchosen_unassigned
        have hchosen_welfare_erased :
            chosen.welfare E (reportsWithoutBidder reports i) =
              chosen.welfareExcept E reports i := by
          rw [PositionOutcome.welfare_eq_except_of_unassigned
            E chosen (reportsWithoutBidder reports i) hchosen_unassigned]
          change
            chosen.welfareExcept E (Function.update reports i 0) i =
              chosen.welfareExcept E reports i
          rw [PositionOutcome.welfareExcept_update_self E chosen reports i 0]
        have hle_chosen_tax :
            chosen.welfareExcept E reports i ≤
              positionVCGBenchmark E slotRule reports i := by
          have hle :=
            hmax (reportsWithoutBidder reports i) chosen (hfeasible reports)
          rwa [hchosen_welfare_erased, hwithout_welfare_tax] at hle
        have hremove_feasible :
            (without.removeBidderSlot i).FeasibleAssignment :=
          PositionOutcome.removeBidderSlot_feasible without i
            (hfeasible (reportsWithoutBidder reports i))
        have htax_le_chosen :
            positionVCGBenchmark E slotRule reports i ≤
              chosen.welfareExcept E reports i := by
          have hle :=
            hmax reports (without.removeBidderSlot i) hremove_feasible
          rw [PositionOutcome.removeBidderSlot_welfare_eq_welfareExcept
            E without reports i] at hle
          simpa [chosen, hchosen_welfare_reports] using hle
        have htax_eq :
            positionVCGBenchmark E slotRule reports i =
              chosen.welfareExcept E reports i :=
          le_antisymm htax_le_chosen hle_chosen_tax
        have hwelfare_update :
            ((positionVCGMechanismOfSlotRule E slotRule) reports).welfare E
                (Function.update reports i (values i)) =
              chosen.welfareExcept E reports i := by
          have hmech_unassigned :
              ((positionVCGMechanismOfSlotRule E slotRule) reports).slotOf i =
                none := by
            simpa [positionVCGMechanismOfSlotRule] using hslot
          rw [PositionOutcome.welfare_eq_except_of_unassigned
            E ((positionVCGMechanismOfSlotRule E slotRule) reports)
            (Function.update reports i (values i)) hmech_unassigned]
          rw [PositionOutcome.welfareExcept_update_self
            E ((positionVCGMechanismOfSlotRule E slotRule) reports)
            reports i (values i)]
          simp [positionVCGMechanismOfSlotRule, chosen,
            PositionOutcome.welfareExcept,
            PositionOutcome.welfareContribution,
            PositionOutcome.zeroPaymentOutcome]
        rw [utility, PositionOutcome.utility]
        simp [positionVCGMechanismOfSlotRule, hslot]
        change
          0 =
            ((positionVCGMechanismOfSlotRule E slotRule) reports).welfare E
                (Function.update reports i (values i)) -
              positionVCGBenchmark E slotRule reports i
        rw [hwelfare_update, htax_eq]
        ring
    | some s =>
        have hchosen_assigned : chosen.slotOf i = some s := by
          simpa [chosen, PositionOutcome.zeroPaymentOutcome] using hslot
        have hmech_assigned :
            ((positionVCGMechanismOfSlotRule E slotRule) reports).slotOf i =
              some s := by
          simpa [positionVCGMechanismOfSlotRule] using hslot
        have hwelfare_update :
            ((positionVCGMechanismOfSlotRule E slotRule) reports).welfare E
                (Function.update reports i (values i)) =
              E.clickThroughRate s * values i +
                chosen.welfareExcept E reports i := by
          rw [PositionOutcome.welfare_of_update_self_assigned
            E ((positionVCGMechanismOfSlotRule E slotRule) reports)
            reports hmech_assigned (values i)]
          simp [positionVCGMechanismOfSlotRule, chosen,
            PositionOutcome.welfareExcept,
            PositionOutcome.welfareContribution,
            PositionOutcome.zeroPaymentOutcome]
        have hclick_ne : E.clickThroughRate s ≠ 0 :=
          ne_of_gt (hclick_pos s)
        have hcalc :
            E.clickThroughRate s *
                (values i -
                  (positionVCGBenchmark E slotRule reports i -
                    chosen.welfareExcept E reports i) /
                    E.clickThroughRate s) =
              E.clickThroughRate s * values i +
                  chosen.welfareExcept E reports i -
                positionVCGBenchmark E slotRule reports i := by
          field_simp [hclick_ne]
          ring
        rw [utility, PositionOutcome.utility, hmech_assigned,
          hwelfare_update]
        simp [positionVCGMechanismOfSlotRule, hslot, chosen,
          PositionOutcome.zeroPaymentOutcome]
        change
          E.clickThroughRate s *
              (values i -
                (positionVCGBenchmark E slotRule reports i -
                  chosen.welfareExcept E reports i) /
                  E.clickThroughRate s) =
            E.clickThroughRate s * values i +
                chosen.welfareExcept E reports i -
              positionVCGBenchmark E slotRule reports i
        exact hcalc
  · intro reports i report
    unfold positionVCGBenchmark
    rw [reportsWithoutBidder_update_self]
    exact
      PositionOutcome.welfareExcept_update_self E
        (PositionOutcome.zeroPaymentOutcome
          (slotRule (reportsWithoutBidder reports i)))
        reports i report

theorem truthfulDominantStrategy_positionVCGMechanismOfSlotRule
    [Fintype Bidder] [DecidableEq Bidder]
    {E : PositionEnvironment Slot}
    {slotRule : (Bidder → ℝ) → Bidder → Option Slot}
    (hclick_pos : ∀ s, 0 < E.clickThroughRate s)
    (hfeasible :
      ∀ reports,
        (PositionOutcome.zeroPaymentOutcome
          (slotRule reports)).FeasibleAssignment)
    (hmax :
      ∀ reports (outcome : PositionOutcome Bidder Slot),
        outcome.FeasibleAssignment →
          outcome.welfare E reports ≤
            (PositionOutcome.zeroPaymentOutcome
              (slotRule reports)).welfare E reports) :
    TruthfulDominantStrategy E (positionVCGMechanismOfSlotRule E slotRule) := by
  exact
    truthfulDominantStrategy_of_feasibleVCGDominantStrategyCertificate
      (feasibleVCGDominantStrategyCertificate_of_welfareMaximizingSlotRule
        hclick_pos hfeasible hmax)

theorem truthfulDominantStrategy_positionVCGMechanism
    [Fintype Bidder] [DecidableEq Bidder]
    [Fintype Slot] [DecidableEq Slot]
    {E : PositionEnvironment Slot}
    (hclick_pos : ∀ s, 0 < E.clickThroughRate s) :
    TruthfulDominantStrategy E
      (positionVCGMechanism (Bidder := Bidder) (Slot := Slot) E) := by
  simpa [positionVCGMechanism] using
    truthfulDominantStrategy_positionVCGMechanismOfSlotRule
      (Bidder := Bidder) (Slot := Slot)
      (E := E)
      (slotRule := welfareMaximizingSlotAssignment E)
      hclick_pos
      (fun reports =>
        welfareMaximizingSlotAssignment_feasible
          (Bidder := Bidder) (Slot := Slot) E reports)
      (fun reports outcome hout =>
        welfareMaximizingSlotAssignment_welfare_maximizing
          (Bidder := Bidder) (Slot := Slot) E reports outcome hout)

end PositionMechanism

/-! ## Position-outcome envy predicates -/

namespace PositionOutcome

variable {Bidder Slot : Type*}

/--
No bidder prefers another bidder's assigned slot at that other bidder's
per-click payment. This is the outcome-level envy-freeness predicate used as a
building block for GSP equilibrium analyses.
-/
def SlotEnvyFree (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : Prop :=
  ∀ (i j : Bidder) (s : Slot),
    O.slotOf j = some s →
      E.clickThroughRate s * (values i - O.paymentPerClick j) ≤
        O.utility E values i

theorem slotEnvyFree_own_comparison
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (h : O.SlotEnvyFree E values) :
    ∀ (i : Bidder) (s : Slot),
      O.slotOf i = some s →
        E.clickThroughRate s * (values i - O.paymentPerClick i) ≤
          O.utility E values i := by
  intro i s hslot
  exact h i i s hslot

/--
Outcome-level GSP equilibrium certificate: no bidder can improve by taking any
currently assigned slot at that slot winner's per-click payment.
-/
def NoProfitableAssignedSlotDeviation (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : Prop :=
  ∀ (i j : Bidder) (s : Slot),
    O.slotOf j = some s →
      E.clickThroughRate s * (values i - O.paymentPerClick j) ≤
        O.utility E values i

/--
Outcome-level stable assignment predicate for an assignment-game bridge. It
records the finite assignment feasibility, bidder-side individual rationality,
and absence of a profitable rematch with any assigned slot at the current
per-click payment.
-/
def StableAssignment (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) : Prop :=
  O.FeasibleAssignment ∧
    O.IndividuallyRational E values ∧
      O.NoProfitableAssignedSlotDeviation E values

theorem slotEnvyFree_iff_noProfitableAssignedSlotDeviation
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ) :
    O.SlotEnvyFree E values ↔
      O.NoProfitableAssignedSlotDeviation E values := by
  rfl

theorem noProfitableAssignedSlotDeviation_of_slotEnvyFree
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (h : O.SlotEnvyFree E values) :
    O.NoProfitableAssignedSlotDeviation E values := by
  exact h

theorem stableAssignment_of_slotEnvyFree
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (hfeasible : O.FeasibleAssignment)
    (hIR : O.IndividuallyRational E values)
    (h : O.SlotEnvyFree E values) :
    O.StableAssignment E values := by
  exact ⟨hfeasible, hIR,
    O.noProfitableAssignedSlotDeviation_of_slotEnvyFree E values h⟩

theorem slotEnvyFree_of_stableAssignment
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (h : O.StableAssignment E values) :
    O.SlotEnvyFree E values := by
  exact h.2.2

theorem noProfitableAssignedSlotDeviation_of_stableAssignment
    (E : PositionEnvironment Slot)
    (O : PositionOutcome Bidder Slot) (values : Bidder → ℝ)
    (h : O.StableAssignment E values) :
    O.NoProfitableAssignedSlotDeviation E values := by
  exact h.2.2

end PositionOutcome

namespace PositionMechanism

variable {Bidder Slot : Type*}

/--
Static locally envy-free equilibrium for a position mechanism: bids are a pure
Nash equilibrium of the induced complete-information bidding game, and the
resulting outcome is slot-envy-free.
-/
def LocallyEnvyFreeEquilibrium [DecidableEq Bidder]
    (E : PositionEnvironment Slot) (M : PositionMechanism Bidder Slot)
    (values bids : Bidder → ℝ) : Prop :=
  M.IsNashEquilibrium E values bids ∧
    (M bids).SlotEnvyFree E values

end PositionMechanism

/-!
## A small GSP non-truthfulness witness

The 2018 SIGecom Test-of-Time award recognized the first analyses of GSP-style
position auctions.  A basic reason these papers are needed is that GSP is not a
truthful mechanism.  The following concrete three-bidder/two-slot outcome is a
minimal reusable witness: bidder `0` has value `10`, receives the top slot and
pays `8` per click when bidding truthfully, but can lower her bid to receive the
second slot and pay only `1` per click.  With click-through rates `1` and `1/2`,
that deviation improves utility from `2` to `9/2`.
-/

noncomputable def gspCounterexampleEnvironment : PositionEnvironment (Fin 2) where
  clickThroughRate s := if s = (0 : Fin 2) then 1 else 1 / 2

def gspCounterexampleValues (i : Fin 3) : ℝ :=
  match i with
  | ⟨0, _⟩ => 10
  | ⟨1, _⟩ => 8
  | ⟨_, _⟩ => 1

def gspCounterexampleLowerBids (i : Fin 3) : ℝ :=
  match i with
  | ⟨0, _⟩ => 7
  | ⟨1, _⟩ => 8
  | ⟨_, _⟩ => 1

theorem gspCounterexampleLowerBids_eq_update :
    gspCounterexampleLowerBids =
      Function.update gspCounterexampleValues (0 : Fin 3) 7 := by
  funext i
  fin_cases i <;> norm_num [gspCounterexampleLowerBids,
    gspCounterexampleValues, Function.update]

/--
Truthful GSP-style next-price outcome for values/bids `(10, 8, 1)`.
Bidder `0` wins slot `0` and pays bidder `1`'s bid.
-/
def gspCounterexampleTruthfulOutcome : PositionOutcome (Fin 3) (Fin 2) where
  slotOf i :=
    if i = (0 : Fin 3) then some (0 : Fin 2)
    else if i = (1 : Fin 3) then some (1 : Fin 2)
    else none
  paymentPerClick i :=
    if i = (0 : Fin 3) then 8
    else if i = (1 : Fin 3) then 1
    else 0

/--
GSP-style next-price outcome after bidder `0` lowers her bid below bidder `1`
but above bidder `2`.  Bidder `0` receives slot `1` and pays bidder `2`'s bid.
-/
def gspCounterexampleLowerBidOutcome : PositionOutcome (Fin 3) (Fin 2) where
  slotOf i :=
    if i = (1 : Fin 3) then some (0 : Fin 2)
    else if i = (0 : Fin 3) then some (1 : Fin 2)
    else none
  paymentPerClick i :=
    if i = (1 : Fin 3) then 7
    else if i = (0 : Fin 3) then 1
    else 0

/-! ## A concrete sorted GSP mechanism for three bidders and two slots -/

/-- Highest bidder among three bidders, with deterministic tie-breaking. -/
noncomputable def topBidder3 (bids : Fin 3 → ℝ) : Fin 3 :=
  if bids (0 : Fin 3) < bids (1 : Fin 3) then
    if bids (1 : Fin 3) < bids (2 : Fin 3) then
      (2 : Fin 3)
    else
      (1 : Fin 3)
  else
    if bids (0 : Fin 3) < bids (2 : Fin 3) then
      (2 : Fin 3)
    else
      (0 : Fin 3)

/-- Second-highest bidder among three bidders, with deterministic tie-breaking. -/
noncomputable def secondBidder3 (bids : Fin 3 → ℝ) : Fin 3 :=
  if bids (0 : Fin 3) < bids (1 : Fin 3) then
    if bids (1 : Fin 3) < bids (2 : Fin 3) then
      (1 : Fin 3)
    else if bids (0 : Fin 3) < bids (2 : Fin 3) then
      (2 : Fin 3)
    else
      (0 : Fin 3)
  else
    if bids (0 : Fin 3) < bids (2 : Fin 3) then
      (0 : Fin 3)
    else if bids (1 : Fin 3) < bids (2 : Fin 3) then
      (2 : Fin 3)
    else
      (1 : Fin 3)

/-- Third-highest bidder among three bidders, with deterministic tie-breaking. -/
noncomputable def thirdBidder3 (bids : Fin 3 → ℝ) : Fin 3 :=
  if bids (0 : Fin 3) < bids (1 : Fin 3) then
    if bids (1 : Fin 3) < bids (2 : Fin 3) then
      (0 : Fin 3)
    else if bids (0 : Fin 3) < bids (2 : Fin 3) then
      (0 : Fin 3)
    else
      (2 : Fin 3)
  else
    if bids (0 : Fin 3) < bids (2 : Fin 3) then
      (1 : Fin 3)
    else if bids (1 : Fin 3) < bids (2 : Fin 3) then
      (1 : Fin 3)
    else
      (2 : Fin 3)

/--
Sorted three-bidder/two-slot GSP mechanism.

The highest bidder gets slot `0` and pays the second-highest bid per click; the
second-highest bidder gets slot `1` and pays the third-highest bid per click.
-/
noncomputable def gsp3TwoSlotMechanism :
    PositionMechanism (Fin 3) (Fin 2) :=
  fun bids =>
    { slotOf := fun i =>
        if i = topBidder3 bids then some (0 : Fin 2)
        else if i = secondBidder3 bids then some (1 : Fin 2)
        else none
      paymentPerClick := fun i =>
        if i = topBidder3 bids then bids (secondBidder3 bids)
        else if i = secondBidder3 bids then bids (thirdBidder3 bids)
        else 0 }

/--
A minimal GSP-style mechanism sufficient to expose the profitable deviation in
the counterexample. If bidder `0` bids below bidder `1`, bidder `0` receives the
second slot and pays bidder `2`'s bid; otherwise bidder `0` receives the top
slot and pays bidder `1`'s bid.
-/
noncomputable def gspCounterexampleMechanism :
    PositionMechanism (Fin 3) (Fin 2) :=
  fun bids =>
    if bids (0 : Fin 3) < bids (1 : Fin 3) then
      gspCounterexampleLowerBidOutcome
    else
      gspCounterexampleTruthfulOutcome

theorem gspCounterexample_truthfulUtility_bidder0 :
    gspCounterexampleTruthfulOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) = 2 := by
  norm_num [PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleTruthfulOutcome]

theorem gspCounterexample_lowerBidUtility_bidder0 :
    gspCounterexampleLowerBidOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) = 9 / 2 := by
  norm_num [PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleLowerBidOutcome]

/--
Concrete witness that GSP-style position auctions are not dominant-strategy
truthful: bidder `0` benefits by lowering her bid in this two-slot instance.
-/
theorem gspCounterexample_lowerBid_profitable :
    gspCounterexampleTruthfulOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) <
    gspCounterexampleLowerBidOutcome.utility
      gspCounterexampleEnvironment gspCounterexampleValues (0 : Fin 3) := by
  rw [gspCounterexample_truthfulUtility_bidder0,
    gspCounterexample_lowerBidUtility_bidder0]
  norm_num

theorem gspCounterexampleMechanism_truthfulUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gspCounterexampleMechanism
      gspCounterexampleValues gspCounterexampleValues (0 : Fin 3) = 2 := by
  norm_num [PositionMechanism.utility, gspCounterexampleMechanism,
    PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleTruthfulOutcome]

theorem gspCounterexampleMechanism_lowerBidUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gspCounterexampleMechanism
      gspCounterexampleValues
      (Function.update gspCounterexampleValues (0 : Fin 3) 7)
      (0 : Fin 3) = 9 / 2 := by
  norm_num [PositionMechanism.utility, gspCounterexampleMechanism,
    PositionOutcome.utility, gspCounterexampleEnvironment,
    gspCounterexampleValues, gspCounterexampleLowerBidOutcome,
    Function.update]

/--
Mechanism-level version of the GSP counterexample: truthful bidding is not a
dominant strategy for this two-slot GSP-style mechanism.
-/
theorem gspCounterexampleMechanism_not_truthful :
    ¬ PositionMechanism.TruthfulDominantStrategy
      gspCounterexampleEnvironment gspCounterexampleMechanism := by
  intro htruth
  have hle := htruth gspCounterexampleValues (0 : Fin 3) 7
  rw [gspCounterexampleMechanism_lowerBidUtility_bidder0,
    gspCounterexampleMechanism_truthfulUtility_bidder0] at hle
  norm_num at hle

theorem gsp3TwoSlot_truthfulUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gsp3TwoSlotMechanism
      gspCounterexampleValues gspCounterexampleValues (0 : Fin 3) = 2 := by
  have hmech :
      gsp3TwoSlotMechanism gspCounterexampleValues =
        gspCounterexampleTruthfulOutcome := by
    ext i <;> fin_cases i <;>
      norm_num [gsp3TwoSlotMechanism, gspCounterexampleTruthfulOutcome,
        gspCounterexampleValues, topBidder3, secondBidder3, thirdBidder3]
  rw [PositionMechanism.utility, hmech]
  exact gspCounterexample_truthfulUtility_bidder0

theorem gsp3TwoSlot_lowerBidUtility_bidder0 :
    PositionMechanism.utility gspCounterexampleEnvironment
      gsp3TwoSlotMechanism
      gspCounterexampleValues
      (Function.update gspCounterexampleValues (0 : Fin 3) 7)
      (0 : Fin 3) = 9 / 2 := by
  have hmech :
      gsp3TwoSlotMechanism
          (Function.update gspCounterexampleValues (0 : Fin 3) 7) =
        gspCounterexampleLowerBidOutcome := by
    rw [← gspCounterexampleLowerBids_eq_update]
    ext i <;> fin_cases i <;>
      norm_num [gsp3TwoSlotMechanism, gspCounterexampleLowerBidOutcome,
        gspCounterexampleLowerBids, topBidder3, secondBidder3, thirdBidder3]
  rw [PositionMechanism.utility, hmech]
  exact gspCounterexample_lowerBidUtility_bidder0

/--
Sorted three-bidder/two-slot GSP is not dominant-strategy truthful.
-/
theorem gsp3TwoSlot_not_truthful :
    ¬ PositionMechanism.TruthfulDominantStrategy
      gspCounterexampleEnvironment gsp3TwoSlotMechanism := by
  intro htruth
  have hle := htruth gspCounterexampleValues (0 : Fin 3) 7
  rw [gsp3TwoSlot_lowerBidUtility_bidder0,
    gsp3TwoSlot_truthfulUtility_bidder0] at hle
  norm_num at hle

end Auction
end AppliedModelingLib
