import AppliedModelingLib.Foundations.Probability.OrderStatistics
import AppliedModelingLib.Foundations.Probability.MeasureInequalities
import AppliedModelingLib.Markets.Matching.ContinuumCutoff
import Mathlib.MeasureTheory.Measure.Real
import Mathlib.Tactic

/-!
# Cutoff Affordability and Maximum-Crossing Bridges

This module connects cutoff-market affordability events to the reusable
order-statistics API.  It is the paper-neutral bridge needed by matching-market
papers where a student can afford some college iff one independent noisy score
crosses a cutoff.
-/

namespace AppliedModelingLib
namespace Matching

open AppliedModelingLib.Probability
open Filter Topology
open MeasureTheory

universe u

/-- A score vector crosses at least one cutoff. -/
def cutoffCrossed {College : Type u} (score cutoff : College → ℝ) : Prop :=
  ∃ c : College, cutoff c < score c

/-- A score vector crosses at least one cutoff in a finite active set. -/
def cutoffCrossedOn {College : Type u} (active : Finset College)
    (score cutoff : College → ℝ) : Prop :=
  ∃ c : College, c ∈ active ∧ cutoff c < score c

/-- A score vector weakly crosses at least one cutoff in a finite active set. -/
def cutoffWeaklyCrossedOn {College : Type u} (active : Finset College)
    (score cutoff : College → ℝ) : Prop :=
  ∃ c : College, c ∈ active ∧ cutoff c ≤ score c

/-- Scores generated by a true value plus college-specific noise. -/
def noisyScore {College : Type u} (v : ℝ) (noise : College → ℝ) :
    College → ℝ :=
  fun c => v + noise c

/-- Total capacity of a finite active college set. -/
noncomputable def activeCapacity {College : Type u}
    (active : Finset College) (capacity : College → ℝ) : ℝ :=
  ∑ c ∈ active, capacity c

/-- Coordinates whose cutoff is below a scalar floor. -/
noncomputable def lowCutoffIndexSet {n : ℕ}
    (cutoff : Fin n → ℝ) (floor : ℝ) : Finset (Fin n) :=
  Finset.univ.filter (fun c : Fin n => cutoff c < floor)

/--
Sorted cutoff coordinates have the advertised suffix floor once fewer than
`k` coordinates lie below the scalar floor.

This is the finite combinatorial step behind sorted-prefix deletion arguments:
after sorting cutoffs increasingly, a cardinality bound on below-floor
coordinates implies every coordinate past that prefix is above the floor.
-/
theorem suffix_floor_of_sorted_lowCutoffIndexSet_card_le
    {n k : ℕ} {cutoff : Fin n → ℝ} {floor : ℝ}
    (hsorted :
      ∀ i j : Fin n, (i : ℕ) ≤ (j : ℕ) → cutoff i ≤ cutoff j)
    (hcard : (lowCutoffIndexSet cutoff floor).card ≤ k)
    {c : Fin n} (hc : k ≤ (c : ℕ)) :
    floor ≤ cutoff c := by
  classical
  by_contra hnot
  have hc_lt : cutoff c < floor := lt_of_not_ge hnot
  let embed :
      Fin ((c : ℕ) + 1) →
        {i : Fin n // i ∈ lowCutoffIndexSet cutoff floor} :=
    fun j =>
      ⟨⟨j.1, Nat.lt_of_lt_of_le j.2 (Nat.succ_le_of_lt c.2)⟩, by
        have hjle : (j.1 : ℕ) ≤ (c : ℕ) := Nat.le_of_lt_succ j.2
        have hle :
            cutoff ⟨j.1, Nat.lt_of_lt_of_le j.2 (Nat.succ_le_of_lt c.2)⟩ ≤
              cutoff c :=
          hsorted ⟨j.1, Nat.lt_of_lt_of_le j.2 (Nat.succ_le_of_lt c.2)⟩
            c hjle
        simp [lowCutoffIndexSet, lt_of_le_of_lt hle hc_lt]⟩
  have hinj : Function.Injective embed := by
    intro a b hab
    have hval :
        ((embed a).1 : Fin n).val = ((embed b).1 : Fin n).val :=
      congrArg (fun x : {i : Fin n // i ∈ lowCutoffIndexSet cutoff floor} =>
        (x.1 : Fin n).val) hab
    exact Fin.ext hval
  have hcard_lower : (c : ℕ) + 1 ≤ (lowCutoffIndexSet cutoff floor).card := by
    have h := Fintype.card_le_of_injective embed hinj
    simpa [Fintype.card_fin, Fintype.card_coe] using h
  have hsucc_le_self : (c : ℕ) + 1 ≤ (c : ℕ) :=
    le_trans hcard_lower (le_trans hcard hc)
  exact (Nat.not_succ_le_self (c : ℕ)) hsucc_le_self

/-- Every member of `lowCutoffIndexSet cutoff floor` has cutoff at most `floor`. -/
theorem cutoff_le_floor_of_mem_lowCutoffIndexSet
    {n : ℕ} {cutoff : Fin n → ℝ} {floor : ℝ}
    {c : Fin n} (hc : c ∈ lowCutoffIndexSet cutoff floor) :
    cutoff c ≤ floor := by
  exact le_of_lt ((Finset.mem_filter.mp hc).2)

/-- Real-valued mass of an event in an outcome space. -/
noncomputable def eventMass {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (event : Ω → Prop) : ℝ :=
  AppliedModelingLib.measureProb μ event

/-- A choice rule selects some member of a finite active block. -/
def chosenInActive {Ω : Type*} {College : Type u}
    (choice : Ω → Option College) (active : Finset College) (ω : Ω) : Prop :=
  ∃ c ∈ active, choice ω = some c

/-- Real-valued mass of outcomes whose chosen college lies in `active`. -/
noncomputable def choiceMass {Ω : Type*} [MeasurableSpace Ω]
    {College : Type u} (μ : Measure Ω) (choice : Ω → Option College)
    (active : Finset College) : ℝ :=
  eventMass μ (chosenInActive choice active)

/--
Choice mass over an active block is the sum of the disjoint singleton choice
events.  The measurability premise is intentionally explicit because concrete
source models should prove their choice rule is measurable.
-/
theorem choiceMass_eq_sum_singleton_eventMass
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u}
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (choice : Ω → Option College) (active : Finset College)
    (hmeas :
      ∀ c ∈ active, MeasurableSet {ω : Ω | choice ω = some c}) :
    choiceMass μ choice active =
      ∑ c ∈ active, eventMass μ (fun ω : Ω => choice ω = some c) := by
  classical
  let f : College → Set Ω := fun c => {ω : Ω | choice ω = some c}
  have hset :
      {ω : Ω | chosenInActive choice active ω} =
        ⋃ c ∈ active, f c := by
    ext ω
    simp [chosenInActive, f]
  have hdisj : (↑active : Set College).PairwiseDisjoint f := by
    intro c hc d hd hne
    change Disjoint (f c) (f d)
    rw [Set.disjoint_left]
    intro ω hcω hdω
    exact hne (Option.some.inj (hcω.symm.trans hdω))
  unfold choiceMass eventMass AppliedModelingLib.measureProb
  rw [hset]
  simpa [f, AppliedModelingLib.measureProb] using
    (measureReal_biUnion_finset (μ := μ) (s := active) (f := f)
      hdisj hmeas (by
        intro c _hc
        exact measure_ne_top μ (f c)))

/--
If singleton choice-event masses equal aggregate demand at each active college,
then the whole active block's choice mass equals aggregate demand summed over
the block.
-/
theorem choiceMass_eq_sum_aggregateDemand_of_singleton_eventMass_eq
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u}
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (choice : Ω → Option College) (active : Finset College)
    {aggregateDemand : College → ℝ}
    (hmeas :
      ∀ c ∈ active, MeasurableSet {ω : Ω | choice ω = some c})
    (hsingle :
      ∀ c ∈ active,
        eventMass μ (fun ω : Ω => choice ω = some c) =
          aggregateDemand c) :
    choiceMass μ choice active = ∑ c ∈ active, aggregateDemand c := by
  rw [choiceMass_eq_sum_singleton_eventMass μ choice active hmeas]
  exact Finset.sum_congr rfl (by
    intro c hc
    exact hsingle c hc)

/-- Event mass is monotone under pointwise implication. -/
theorem eventMass_mono {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsFiniteMeasure μ] {p q : Ω → Prop}
    (h : ∀ ω, p ω → q ω) :
    eventMass μ p ≤ eventMass μ q := by
  unfold eventMass AppliedModelingLib.measureProb
  exact measureReal_mono (μ := μ) h (measure_ne_top μ _)

/-- If an event always chooses inside an active block, its mass is bounded by the block mass. -/
theorem eventMass_le_choiceMass_of_imp {Ω : Type*} [MeasurableSpace Ω]
    {College : Type u} (μ : Measure Ω) [IsFiniteMeasure μ]
    {choice : Ω → Option College} {event : Ω → Prop}
    {active : Finset College}
    (h : ∀ ω, event ω → chosenInActive choice active ω) :
    eventMass μ event ≤ choiceMass μ choice active :=
  eventMass_mono μ h

/--
If choosing inside an active block always implies an event, then the active
choice mass is bounded by that event's mass.
-/
theorem choiceMass_le_eventMass_of_imp {Ω : Type*} [MeasurableSpace Ω]
    {College : Type u} (μ : Measure Ω) [IsFiniteMeasure μ]
    {choice : Ω → Option College} {event : Ω → Prop}
    {active : Finset College}
    (h : ∀ ω, chosenInActive choice active ω → event ω) :
    choiceMass μ choice active ≤ eventMass μ event :=
  eventMass_mono μ h

/--
Loss-tolerant variant of `choiceMass_le_eventMass_of_imp`, used when a paper
allows an outside-window error term before comparing to an event.
-/
theorem choiceMass_sub_nonneg_le_eventMass_of_imp
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u}
    (μ : Measure Ω) [IsFiniteMeasure μ]
    {choice : Ω → Option College} {event : Ω → Prop}
    {active : Finset College} {epsilon : ℝ}
    (hepsilon_nonneg : 0 ≤ epsilon)
    (h : ∀ ω, chosenInActive choice active ω → event ω) :
    choiceMass μ choice active - epsilon ≤ eventMass μ event := by
  have hchoice_le : choiceMass μ choice active ≤ eventMass μ event :=
    choiceMass_le_eventMass_of_imp μ h
  linarith

/-- Choice mass is monotone in the active college block. -/
theorem choiceMass_mono_active {Ω : Type*} [MeasurableSpace Ω]
    {College : Type u} (μ : Measure Ω) [IsFiniteMeasure μ]
    {choice : Ω → Option College} {active larger : Finset College}
    (hsubset : active ⊆ larger) :
    choiceMass μ choice active ≤ choiceMass μ choice larger := by
  refine eventMass_mono μ ?_
  intro ω hω
  rcases hω with ⟨c, hc, hchoice⟩
  exact ⟨c, hsubset hc, hchoice⟩

/--
If aggregate demand equals capacity on every college in a finite active set,
then aggregate demand over that set equals active capacity.
-/
theorem activeAggregateDemand_eq_activeCapacity_of_forall_eq {College : Type u}
    (active : Finset College) {aggregateDemand capacity : College → ℝ}
    (h : ∀ c ∈ active, aggregateDemand c = capacity c) :
    (∑ c ∈ active, aggregateDemand c) = activeCapacity active capacity := by
  unfold activeCapacity
  exact Finset.sum_congr rfl (by intro c hc; exact h c hc)

/--
If a block mass is represented by aggregate demand and market clearing
identifies aggregate demand with capacity on that block, then the block mass is
the active capacity of the block.
-/
theorem mass_eq_activeCapacity_of_aggregateDemand_eq_capacity
    {College : Type u} (active : Finset College) {mass : ℝ}
    {aggregateDemand capacity : College → ℝ}
    (hmass : mass = ∑ c ∈ active, aggregateDemand c)
    (hclear : ∀ c ∈ active, aggregateDemand c = capacity c) :
    mass = activeCapacity active capacity := by
  calc
    mass = ∑ c ∈ active, aggregateDemand c := hmass
    _ = activeCapacity active capacity :=
      activeAggregateDemand_eq_activeCapacity_of_forall_eq active hclear

/--
Choice-mass specialization of
`mass_eq_activeCapacity_of_aggregateDemand_eq_capacity`.
-/
theorem choiceMass_eq_activeCapacity_of_aggregateDemand_eq_capacity
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u}
    (μ : Measure Ω) (choice : Ω → Option College) (active : Finset College)
    {aggregateDemand capacity : College → ℝ}
    (hchoice :
      choiceMass μ choice active = ∑ c ∈ active, aggregateDemand c)
    (hclear : ∀ c ∈ active, aggregateDemand c = capacity c) :
    choiceMass μ choice active = activeCapacity active capacity :=
  mass_eq_activeCapacity_of_aggregateDemand_eq_capacity
    active hchoice hclear

/--
If an event always chooses inside an active block, and the block choice mass is
identified with market-clearing capacity, then the event mass is at most active
capacity.  This is the reusable bridge from explicit outcome events to the
capacity bounds used in cutoff-market proofs.
-/
theorem eventMass_le_activeCapacity_of_imp_aggregateDemand_eq_capacity
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u}
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (choice : Ω → Option College) (active : Finset College)
    {event : Ω → Prop} {aggregateDemand capacity : College → ℝ}
    (himp : ∀ ω, event ω → chosenInActive choice active ω)
    (hchoice :
      choiceMass μ choice active = ∑ c ∈ active, aggregateDemand c)
    (hclear : ∀ c ∈ active, aggregateDemand c = capacity c) :
    eventMass μ event ≤ activeCapacity active capacity := by
  calc
    eventMass μ event ≤ choiceMass μ choice active :=
      eventMass_le_choiceMass_of_imp μ himp
    _ = activeCapacity active capacity :=
      choiceMass_eq_activeCapacity_of_aggregateDemand_eq_capacity
        μ choice active hchoice hclear

/--
Whole-market version of `eventMass_le_activeCapacity_of_imp_aggregateDemand_eq_capacity`.
If every outcome in an event is matched somewhere and the market clears at
total capacity, the event mass is bounded by total capacity.
-/
theorem eventMass_le_totalCapacity_of_imp_aggregateDemand_eq_capacity
    {Ω : Type*} [MeasurableSpace Ω] {College : Type u} [Fintype College]
    (μ : Measure Ω) [IsFiniteMeasure μ]
    (choice : Ω → Option College)
    {event : Ω → Prop} {aggregateDemand capacity : College → ℝ}
    (himp :
      ∀ ω, event ω →
        chosenInActive choice (Finset.univ : Finset College) ω)
    (hchoice :
      choiceMass μ choice (Finset.univ : Finset College) =
        ∑ c : College, aggregateDemand c)
    (hclear : ∀ c : College, aggregateDemand c = capacity c) :
    eventMass μ event ≤ ∑ c : College, capacity c := by
  classical
  simpa using
    eventMass_le_activeCapacity_of_imp_aggregateDemand_eq_capacity
      μ choice (Finset.univ : Finset College) himp
      (by simpa using hchoice)
      (by intro c _hc; exact hclear c)

/-- Active capacity is monotone under subset when capacities are nonnegative. -/
theorem activeCapacity_mono_of_nonneg {College : Type u}
    {active larger : Finset College} {capacity : College → ℝ}
    (hsubset : active ⊆ larger)
    (hnonneg : ∀ c ∈ larger, 0 ≤ capacity c) :
    activeCapacity active capacity ≤ activeCapacity larger capacity := by
  unfold activeCapacity
  exact
    Finset.sum_le_sum_of_subset_of_nonneg hsubset
      (fun c hc _hnot => hnonneg c hc)

/-- Active capacity is additive over disjoint finite active sets. -/
theorem activeCapacity_union_of_disjoint {College : Type u}
    [DecidableEq College] {left right : Finset College}
    (capacity : College → ℝ) (hdisj : Disjoint left right) :
    activeCapacity (left ∪ right) capacity =
      activeCapacity left capacity + activeCapacity right capacity := by
  classical
  unfold activeCapacity
  exact Finset.sum_union hdisj

/-- Active capacity over all colleges is the ordinary finite sum. -/
@[simp]
theorem activeCapacity_univ {College : Type u} [Fintype College]
    (capacity : College → ℝ) :
    activeCapacity (Finset.univ : Finset College) capacity =
      ∑ c : College, capacity c := by
  classical
  simp [activeCapacity]

/-- Active capacity of a finite partition is the sum of the parts. -/
theorem activeCapacity_eq_add_of_partition {College : Type u}
    [DecidableEq College] {total left right : Finset College}
    (capacity : College → ℝ) (hpartition : total = left ∪ right)
    (hdisj : Disjoint left right) :
    activeCapacity total capacity =
      activeCapacity left capacity + activeCapacity right capacity := by
  rw [hpartition]
  exact activeCapacity_union_of_disjoint capacity hdisj

/--
If a finite active set is partitioned into a small and large part, a lower
bound on total capacity and an upper bound on small capacity give a lower
bound on large capacity.
-/
theorem activeCapacity_right_ge_totalLower_sub_leftUpper_of_partition
    {College : Type u} [DecidableEq College]
    {total left right : Finset College} (capacity : College → ℝ)
    {totalLower leftUpper : ℝ}
    (hpartition : total = left ∪ right) (hdisj : Disjoint left right)
    (htotal : totalLower ≤ activeCapacity total capacity)
    (hleft : activeCapacity left capacity ≤ leftUpper) :
    totalLower - leftUpper ≤ activeCapacity right capacity := by
  have hsum :=
    activeCapacity_eq_add_of_partition capacity hpartition hdisj
  linarith

/--
If every active college has capacity at most `capBound`, the active set's
total capacity is at most its cardinality times `capBound`.
-/
theorem activeCapacity_le_card_mul_of_forall_le {College : Type u}
    (active : Finset College) (capacity : College → ℝ) {capBound : ℝ}
    (hcap : ∀ c ∈ active, capacity c ≤ capBound) :
    activeCapacity active capacity ≤ (active.card : ℝ) * capBound := by
  classical
  unfold activeCapacity
  have hsum :
      (∑ c ∈ active, capacity c) ≤ active.card • capBound :=
    Finset.sum_le_card_nsmul active capacity capBound hcap
  simpa [nsmul_eq_mul] using hsum

/--
Capacity bound with a separate real-valued cardinal upper bound.  This is the
finite arithmetic step used when a paper has at most `cardBound` colleges in a
special subset and each has capacity at most `capBound`.
-/
theorem activeCapacity_le_cardBound_mul_of_card_le {College : Type u}
    (active : Finset College) (capacity : College → ℝ)
    {cardBound capBound : ℝ}
    (hcard : (active.card : ℝ) ≤ cardBound) (hcap_nonneg : 0 ≤ capBound)
    (hcap : ∀ c ∈ active, capacity c ≤ capBound) :
    activeCapacity active capacity ≤ cardBound * capBound := by
  calc
    activeCapacity active capacity ≤ (active.card : ℝ) * capBound :=
      activeCapacity_le_card_mul_of_forall_le active capacity hcap
    _ ≤ cardBound * capBound :=
      mul_le_mul_of_nonneg_right hcard hcap_nonneg

/--
If two finite sets have the same cardinality and every element of the first
has utility at most every element of the second, then the first set's total
utility is at most the second set's total utility.
-/
theorem sum_le_sum_of_forall_le_of_card_eq {College : Type u}
    [DecidableEq College] {first second : Finset College}
    {utility : College → ℝ}
    (hcard : first.card = second.card)
    (hle : ∀ a ∈ first, ∀ b ∈ second, utility a ≤ utility b) :
    (∑ a ∈ first, utility a) ≤ ∑ b ∈ second, utility b := by
  classical
  let e : {a // a ∈ first} ≃ {b // b ∈ second} :=
    Fintype.equivOfCardEq (by
      simpa [Fintype.card_coe] using hcard)
  calc
    (∑ a ∈ first, utility a) = ∑ a : {a // a ∈ first}, utility a.1 := by
      exact (Finset.sum_attach first utility).symm
    _ = ∑ b : {b // b ∈ second}, utility (e.symm b).1 := by
      symm
      exact Fintype.sum_equiv e.symm
        (fun b : {b // b ∈ second} => utility (e.symm b).1)
        (fun a : {a // a ∈ first} => utility a.1)
        (by intro b; rfl)
    _ ≤ ∑ b : {b // b ∈ second}, utility b.1 := by
      refine Finset.sum_le_sum ?_
      intro b _
      exact hle (e.symm b).1 (e.symm b).2 b.1 b.2
    _ = ∑ b ∈ second, utility b := by
      exact Finset.sum_attach second utility

/--
Top-k exchange lemma for matching applications.  If `top` contains only firms
that are weakly preferred to firms outside `top`, then among application sets
of the same size, applying to `top` weakly maximizes total utility.
-/
theorem applicationUtility_sum_le_topSet_sum {College : Type u}
    [DecidableEq College] {top deviation : Finset College}
    {utility : College → ℝ}
    (hcard : deviation.card = top.card)
    (htop :
      ∀ c ∈ top, ∀ d, d ∉ top → utility d ≤ utility c) :
    (∑ c ∈ deviation, utility c) ≤ ∑ c ∈ top, utility c := by
  classical
  have hcard_diff :
      (deviation \ top).card = (top \ deviation).card := by
    simpa [eq_comm] using
      (Finset.card_sdiff_eq_card_sdiff_iff (s := top) (t := deviation)).2
        hcard.symm
  have hdiff_le :
      (∑ c ∈ deviation \ top, utility c) ≤
        ∑ c ∈ top \ deviation, utility c :=
    sum_le_sum_of_forall_le_of_card_eq hcard_diff (by
      intro d hd c hc
      have hd' := Finset.mem_sdiff.mp hd
      have hc' := Finset.mem_sdiff.mp hc
      exact htop c hc'.1 d hd'.2)
  have hdev_union :
      deviation = (deviation ∩ top) ∪ (deviation \ top) := by
    ext c
    by_cases hctop : c ∈ top <;> simp [hctop]
  have htop_union :
      top = (deviation ∩ top) ∪ (top \ deviation) := by
    ext c
    by_cases hcdev : c ∈ deviation <;> simp [hcdev, and_comm]
  have hdev_disj : Disjoint (deviation ∩ top) (deviation \ top) := by
    exact Finset.disjoint_left.2 (by
    intro c hc hdiff
    exact (Finset.mem_sdiff.mp hdiff).2 (Finset.mem_inter.mp hc).2)
  have htop_disj : Disjoint (deviation ∩ top) (top \ deviation) := by
    exact Finset.disjoint_left.2 (by
    intro c hc hdiff
    exact (Finset.mem_sdiff.mp hdiff).2 (Finset.mem_inter.mp hc).1)
  have hdev_sum :
      (∑ c ∈ deviation, utility c) =
        (∑ c ∈ deviation ∩ top, utility c) +
          ∑ c ∈ deviation \ top, utility c := by
    calc
      (∑ c ∈ deviation, utility c) =
          ∑ c ∈ (deviation ∩ top) ∪ (deviation \ top), utility c := by
        exact Finset.sum_congr hdev_union (by intro c _; rfl)
      _ = (∑ c ∈ deviation ∩ top, utility c) +
            ∑ c ∈ deviation \ top, utility c := by
        exact Finset.sum_union hdev_disj
  have htop_sum :
      (∑ c ∈ top, utility c) =
        (∑ c ∈ deviation ∩ top, utility c) +
          ∑ c ∈ top \ deviation, utility c := by
    calc
      (∑ c ∈ top, utility c) =
          ∑ c ∈ (deviation ∩ top) ∪ (top \ deviation), utility c := by
        exact Finset.sum_congr htop_union (by intro c _; rfl)
      _ = (∑ c ∈ deviation ∩ top, utility c) +
            ∑ c ∈ top \ deviation, utility c := by
        exact Finset.sum_union htop_disj
  rw [hdev_sum, htop_sum]
  exact add_le_add (le_refl _) hdiff_le

/--
PG-style per-college capacity bound: if every active college has capacity at
most `alpha / C`, the active set's total capacity is at most
`|active| * alpha / C`.
-/
theorem activeCapacity_le_card_mul_alpha_div_of_forall_le {College : Type u}
    (active : Finset College) (capacity : College → ℝ)
    {alpha : ℝ} {C : ℕ}
    (hcap : ∀ c ∈ active, capacity c ≤ alpha / (C : ℝ)) :
    activeCapacity active capacity ≤ (active.card : ℝ) * (alpha / (C : ℝ)) :=
  activeCapacity_le_card_mul_of_forall_le active capacity hcap

/--
PG-style small-subset capacity bound: if a subset has at most `epsilon * C`
colleges and every college has capacity at most `alpha / C`, then its total
capacity is at most `epsilon * alpha`.
-/
theorem activeCapacity_le_epsilon_mul_alpha_of_card_le_mul {College : Type u}
    (active : Finset College) (capacity : College → ℝ)
    {epsilon alpha : ℝ} {C : ℕ}
    (hcard : (active.card : ℝ) ≤ epsilon * (C : ℝ))
    (halpha_nonneg : 0 ≤ alpha) (hC_pos : 0 < (C : ℝ))
    (hcap : ∀ c ∈ active, capacity c ≤ alpha / (C : ℝ)) :
    activeCapacity active capacity ≤ epsilon * alpha := by
  have hbound :
      activeCapacity active capacity ≤
        (epsilon * (C : ℝ)) * (alpha / (C : ℝ)) :=
    activeCapacity_le_cardBound_mul_of_card_le
      active capacity hcard (div_nonneg halpha_nonneg (le_of_lt hC_pos)) hcap
  have hmul :
      (epsilon * (C : ℝ)) * (alpha / (C : ℝ)) = epsilon * alpha := by
    field_simp [ne_of_gt hC_pos]
  simpa [hmul] using hbound

theorem cutoffCrossedOn_mono_active {College : Type u}
    {active larger : Finset College} {score cutoff : College → ℝ}
    (hsubset : active ⊆ larger) :
    cutoffCrossedOn active score cutoff →
      cutoffCrossedOn larger score cutoff := by
  rintro ⟨c, hc, hcross⟩
  exact ⟨c, hsubset hc, hcross⟩

theorem cutoffCrossedOn_mono_cutoff {College : Type u}
    {active : Finset College} {score cutoff lowerCutoff : College → ℝ}
    (hlower : ∀ c ∈ active, lowerCutoff c ≤ cutoff c) :
    cutoffCrossedOn active score cutoff →
      cutoffCrossedOn active score lowerCutoff := by
  rintro ⟨c, hc, hcross⟩
  exact ⟨c, hc, lt_of_le_of_lt (hlower c hc) hcross⟩

theorem cutoffCrossedOn_mono_score {College : Type u}
    {active : Finset College} {score higherScore cutoff : College → ℝ}
    (hhigher : ∀ c ∈ active, score c ≤ higherScore c) :
    cutoffCrossedOn active score cutoff →
      cutoffCrossedOn active higherScore cutoff := by
  rintro ⟨c, hc, hcross⟩
  exact ⟨c, hc, lt_of_lt_of_le hcross (hhigher c hc)⟩

theorem cutoffCrossedOn_univ_iff_cutoffCrossed {College : Type u}
    [Fintype College] {score cutoff : College → ℝ} :
    cutoffCrossedOn Finset.univ score cutoff ↔ cutoffCrossed score cutoff := by
  constructor
  · rintro ⟨c, _hc, hcross⟩
    exact ⟨c, hcross⟩
  · rintro ⟨c, hcross⟩
    exact ⟨c, by simp, hcross⟩

/--
Crossing a cutoff on a union of active finite sets is the disjunction of
crossing it on either active set.  This is the deterministic event
decomposition behind matching-market small/large-firm probability splits.
-/
theorem cutoffCrossedOn_union_iff {College : Type u}
    [DecidableEq College]
    {left right : Finset College} {score cutoff : College → ℝ} :
    cutoffCrossedOn (left ∪ right) score cutoff ↔
      cutoffCrossedOn left score cutoff ∨
        cutoffCrossedOn right score cutoff := by
  constructor
  · rintro ⟨c, hc, hcross⟩
    rw [Finset.mem_union] at hc
    rcases hc with hleft | hright
    · exact Or.inl ⟨c, hleft, hcross⟩
    · exact Or.inr ⟨c, hright, hcross⟩
  · rintro (⟨c, hc, hcross⟩ | ⟨c, hc, hcross⟩)
    · exact ⟨c, by rw [Finset.mem_union]; exact Or.inl hc, hcross⟩
    · exact ⟨c, by rw [Finset.mem_union]; exact Or.inr hc, hcross⟩

/--
Real-valued probability that a random finite noise vector lets a value-`v`
student cross at least one active cutoff.
-/
noncomputable def cutoffCrossingProbability {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) : ℝ :=
  μ.real {noise : College → ℝ |
    cutoffCrossedOn active (noisyScore v noise) cutoff}

/--
Real-valued probability that a random finite noise vector weakly crosses at
least one active cutoff.
-/
noncomputable def cutoffWeakCrossingProbability {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) : ℝ :=
  μ.real {noise : College → ℝ |
    cutoffWeaklyCrossedOn active (noisyScore v noise) cutoff}

/--
Weak and strict finite cutoff-crossing probabilities agree when every active
boundary event has zero mass.  This is the reusable no-indifference bridge
between source models using weak affordability and strict noisy-score
crossing formulas.
-/
theorem cutoffWeakCrossingProbability_eq_cutoffCrossingProbability_of_boundary_null
    {College : Type u} [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    (active : Finset College) (v : ℝ) (cutoff : College → ℝ)
    (hboundary :
      ∀ c ∈ active,
        μ {noise : College → ℝ | noisyScore v noise c = cutoff c} = 0) :
    cutoffWeakCrossingProbability μ active v cutoff =
      cutoffCrossingProbability μ active v cutoff := by
  classical
  let strictSet : Set (College → ℝ) :=
    {noise : College → ℝ | cutoffCrossedOn active (noisyScore v noise) cutoff}
  let weakSet : Set (College → ℝ) :=
    {noise : College → ℝ | cutoffWeaklyCrossedOn active (noisyScore v noise) cutoff}
  have hstrict_subset : strictSet ⊆ weakSet := by
    intro noise hnoise
    rcases hnoise with ⟨c, hc, hcross⟩
    exact ⟨c, hc, le_of_lt hcross⟩
  have hdiff_subset :
      weakSet \ strictSet ⊆
        ⋃ c ∈ active,
          {noise : College → ℝ | noisyScore v noise c = cutoff c} := by
    intro noise hnoise
    rcases hnoise with ⟨hweak, hnot_strict⟩
    rcases hweak with ⟨c, hc, hle⟩
    have hnot_lt : ¬ cutoff c < noisyScore v noise c := by
      intro hlt
      exact hnot_strict ⟨c, hc, hlt⟩
    have heq : noisyScore v noise c = cutoff c :=
      le_antisymm (le_of_not_gt hnot_lt) hle
    exact Set.mem_iUnion.2 ⟨c, Set.mem_iUnion.2 ⟨hc, heq⟩⟩
  have hdiff_real_zero : μ.real (weakSet \ strictSet) = 0 := by
    have hle_union :
        μ.real (weakSet \ strictSet) ≤
          μ.real
            (⋃ c ∈ active,
              {noise : College → ℝ | noisyScore v noise c = cutoff c}) :=
      measureReal_mono (μ := μ) hdiff_subset (measure_ne_top μ _)
    have hle_sum :
        μ.real
            (⋃ c ∈ active,
              {noise : College → ℝ | noisyScore v noise c = cutoff c}) ≤
          ∑ c ∈ active,
            μ.real {noise : College → ℝ | noisyScore v noise c = cutoff c} :=
      measureReal_biUnion_finset_le active
        (fun c : College =>
          {noise : College → ℝ | noisyScore v noise c = cutoff c})
    have hsum_zero :
        (∑ c ∈ active,
          μ.real {noise : College → ℝ | noisyScore v noise c = cutoff c}) = 0 := by
      refine Finset.sum_eq_zero ?_
      intro c hc
      simp [Measure.real, hboundary c hc]
    have hnonneg : 0 ≤ μ.real (weakSet \ strictSet) := measureReal_nonneg
    exact le_antisymm (by linarith) hnonneg
  have hreal_eq : μ.real strictSet = μ.real weakSet :=
    measureReal_eq_measureReal_of_null_diff
      (μ := μ) hstrict_subset hdiff_real_zero (measure_ne_top μ _)
  simpa [cutoffWeakCrossingProbability, cutoffCrossingProbability,
    strictSet, weakSet] using hreal_eq.symm

/--
Iid nonatomic noise discharges the boundary-null condition in the weak/strict
cutoff-crossing bridge.
-/
theorem cutoffWeakCrossingProbability_iidProduct_eq_cutoffCrossingProbability_of_noAtoms
    {n : ℕ} [NeZero n]
    (μ : Measure ℝ) [IsProbabilityMeasure μ] [NoAtoms μ]
    (active : Finset (Fin n)) (v : ℝ) (cutoff : Fin n → ℝ) :
    cutoffWeakCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        active v cutoff =
      cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        active v cutoff := by
  classical
  refine
    cutoffWeakCrossingProbability_eq_cutoffCrossingProbability_of_boundary_null
      (Measure.pi (fun _ : Fin n => μ)) active v cutoff ?_
  intro c _hc
  have hpre :
      {noise : Fin n → ℝ | noisyScore v noise c = cutoff c} =
        (Function.eval c) ⁻¹' ({cutoff c - v} : Set ℝ) := by
    ext noise
    constructor
    · intro hnoise
      simp [noisyScore] at hnoise ⊢
      linarith
    · intro hnoise
      simp [noisyScore] at hnoise ⊢
      linarith
  rw [hpre]
  rw [← Measure.map_apply (by fun_prop : Measurable (Function.eval c))
    (measurableSet_singleton (cutoff c - v))]
  rw [Measure.pi_map_eval]
  simp [measure_singleton (cutoff c - v)]

/-- Cutoff-crossing probabilities are nonnegative. -/
theorem cutoffCrossingProbability_nonneg {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) :
    0 ≤ cutoffCrossingProbability μ active v cutoff := by
  simp [cutoffCrossingProbability]

/-- Under a probability noise law, cutoff-crossing probabilities are at most one. -/
theorem cutoffCrossingProbability_le_one {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsProbabilityMeasure μ]
    (active : Finset College) (v : ℝ) (cutoff : College → ℝ) :
    cutoffCrossingProbability μ active v cutoff ≤ 1 := by
  simpa [cutoffCrossingProbability] using
    (measureReal_le_one
      (μ := μ)
      (s := {noise : College → ℝ |
        cutoffCrossedOn active (noisyScore v noise) cutoff}))

/-- Real-valued probability that one named college's noisy score crosses its cutoff. -/
noncomputable def singleCutoffCrossingProbability {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (v : ℝ) (cutoff : College → ℝ)
    (c : College) : ℝ :=
  μ.real {noise : College → ℝ | cutoff c < noisyScore v noise c}

/-- Single-college cutoff-crossing probabilities are nonnegative. -/
theorem singleCutoffCrossingProbability_nonneg {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (v : ℝ) (cutoff : College → ℝ)
    (c : College) :
    0 ≤ singleCutoffCrossingProbability μ v cutoff c := by
  simp [singleCutoffCrossingProbability]

/-- Under a probability noise law, single-college cutoff-crossing probabilities are at most one. -/
theorem singleCutoffCrossingProbability_le_one {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsProbabilityMeasure μ]
    (v : ℝ) (cutoff : College → ℝ) (c : College) :
    singleCutoffCrossingProbability μ v cutoff c ≤ 1 := by
  simpa [singleCutoffCrossingProbability] using
    (measureReal_le_one
      (μ := μ)
      (s := {noise : College → ℝ | cutoff c < noisyScore v noise c}))

/--
If one named active college's noisy score crosses its cutoff, then the
student crosses at least one active cutoff.
-/
theorem singleCutoffCrossingProbability_le_cutoffCrossingProbability
    {College : Type u} [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    (active : Finset College) {c : College} (hc : c ∈ active)
    (v : ℝ) (cutoff : College → ℝ) :
    singleCutoffCrossingProbability μ v cutoff c ≤
      cutoffCrossingProbability μ active v cutoff := by
  unfold singleCutoffCrossingProbability cutoffCrossingProbability
  exact measureReal_mono
    (μ := μ)
    (fun _noise hnoise => ⟨c, hc, hnoise⟩)
    (measure_ne_top μ _)

/--
Lowering one named college's cutoff weakly increases the chance that this
college's noisy score crosses its cutoff.
-/
theorem singleCutoffCrossingProbability_mono_lowerCutoff {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {v : ℝ} {cutoff lowerCutoff : College → ℝ} {c : College}
    (hlower : lowerCutoff c ≤ cutoff c) :
    singleCutoffCrossingProbability μ v cutoff c ≤
      singleCutoffCrossingProbability μ v lowerCutoff c := by
  unfold singleCutoffCrossingProbability
  exact measureReal_mono
    (μ := μ)
    (fun noise hnoise => by
      exact lt_of_le_of_lt hlower hnoise)
    (measure_ne_top μ _)

/--
For a fixed college and value, a larger constant cutoff weakly lowers the
single-college crossing probability.
-/
theorem singleCutoffCrossingProbability_constant_mono_cutoff {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    (v : ℝ) (c : College) {lower upper : ℝ}
    (hcutoff : lower ≤ upper) :
    singleCutoffCrossingProbability μ v (fun _ => upper) c ≤
      singleCutoffCrossingProbability μ v (fun _ => lower) c :=
  singleCutoffCrossingProbability_mono_lowerCutoff
    μ (v := v) (c := c) hcutoff

/--
For iid noise, a named college's crossing probability at a constant cutoff is
the upper-tail probability of the one-dimensional noise law.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_eq_upperTailMass
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (v P : ℝ) (c : Fin n) :
    singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c =
      upperTailMass μ (P - v) := by
  unfold singleCutoffCrossingProbability upperTailMass
  have hset :
      {noise : Fin n → ℝ | P < noisyScore v noise c} =
        (Function.eval c) ⁻¹' Set.Ioi (P - v) := by
    ext noise
    simp [noisyScore]
    constructor <;> intro h <;> linarith
  rw [hset]
  rw [← map_measureReal_apply (μ := Measure.pi (fun _ : Fin n => μ))
    (f := Function.eval c) (by fun_prop) measurableSet_Ioi]
  rw [Measure.pi_map_eval]
  simp

/--
For iid noise, a named college's crossing probability at its heterogeneous
cutoff is the upper-tail probability of the one-dimensional noise law.
-/
theorem singleCutoffCrossingProbability_iidProduct_eq_upperTailMass
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (v : ℝ) (cutoff : Fin n → ℝ) (c : Fin n) :
    singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v cutoff c =
      upperTailMass μ (cutoff c - v) := by
  unfold singleCutoffCrossingProbability upperTailMass
  have hset :
      {noise : Fin n → ℝ | cutoff c < noisyScore v noise c} =
        (Function.eval c) ⁻¹' Set.Ioi (cutoff c - v) := by
    ext noise
    simp [noisyScore]
    constructor <;> intro h <;> linarith
  rw [hset]
  rw [← map_measureReal_apply (μ := Measure.pi (fun _ : Fin n => μ))
    (f := Function.eval c) (by fun_prop) measurableSet_Ioi]
  rw [Measure.pi_map_eval]
  simp

/--
For iid noise, a named college's crossing probability at a constant cutoff has
the source CDF form `1 - F(P - v)`.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (v P : ℝ) (c : Fin n) :
    singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c =
      1 - lowerCDFMass μ (P - v) := by
  rw [singleCutoffCrossingProbability_iidProduct_constant_eq_upperTailMass]
  have hsum := lowerCDFMass_add_upperTailMass_eq_one μ (P - v)
  linarith

/--
If there is positive one-dimensional mass weakly below the shifted cutoff, the
single-college iid crossing probability is strictly below one.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_lt_one_of_lowerCDFMass_pos
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    {v P : ℝ} (c : Fin n)
    (hpos : 0 < lowerCDFMass μ (P - v)) :
    singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c < 1 := by
  rw [singleCutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass]
  linarith

/--
If the one-dimensional lower-tail mass below the shifted cutoff is below one,
then the single-college iid crossing probability is strictly positive.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_pos_of_lowerCDFMass_lt_one
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    {v P : ℝ} (c : Fin n)
    (hlt : lowerCDFMass μ (P - v) < 1) :
    0 <
      singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c := by
  rw [singleCutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass]
  linarith

/--
For iid noise and a constant cutoff, the named-college crossing probability is
measurable as a function of applicant value.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_measurable
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (P : ℝ) (c : Fin n) :
    Measurable
      (fun v : ℝ =>
        singleCutoffCrossingProbability
          (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c) := by
  have hcdf_meas :
      Measurable (fun x : ℝ => lowerCDFMass μ x) :=
    (lowerCDFMass_mono μ).measurable
  have hshift_meas : Measurable (fun v : ℝ => P - v) :=
    measurable_const.sub measurable_id
  have hformula :
      (fun v : ℝ =>
        singleCutoffCrossingProbability
          (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c) =
        fun v : ℝ => 1 - lowerCDFMass μ (P - v) := by
    funext v
    exact singleCutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass
      μ v P c
  rw [hformula]
  exact measurable_const.sub (hcdf_meas.comp hshift_meas)

/--
For iid noise and a constant cutoff, the named-college crossing probability is
integrable against any finite value measure.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_integrable
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η] (P : ℝ) (c : Fin n) :
    Integrable
      (fun v : ℝ =>
        singleCutoffCrossingProbability
          (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c) η := by
  refine Integrable.of_bound
    (singleCutoffCrossingProbability_iidProduct_constant_measurable
      μ P c).aestronglyMeasurable 1 ?_
  filter_upwards with v
  have hnonneg :
      0 ≤
        singleCutoffCrossingProbability
          (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c :=
    singleCutoffCrossingProbability_nonneg
      (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c
  have hle :
      singleCutoffCrossingProbability
          (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c ≤ 1 :=
    singleCutoffCrossingProbability_le_one
      (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c
  simpa [Real.norm_eq_abs, abs_of_nonneg hnonneg] using hle

/--
For iid noise and a constant cutoff, value times named-college crossing
probability is integrable whenever applicant value has integrable absolute
value.
-/
theorem singleCutoffCrossingProbability_iidProduct_constant_value_mul_integrable_of_abs_integrable
    {n : ℕ} [NeZero n] (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η] (P : ℝ) (c : Fin n)
    (habs_integrable : Integrable (fun v : ℝ => |v|) η) :
    Integrable
      (fun v : ℝ =>
        v *
          singleCutoffCrossingProbability
            (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c) η := by
  have hq_meas :
      AEStronglyMeasurable
        (fun v : ℝ =>
          singleCutoffCrossingProbability
            (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c) η :=
    (singleCutoffCrossingProbability_iidProduct_constant_measurable
      μ P c).aestronglyMeasurable
  refine Integrable.mono' habs_integrable
    (measurable_id.aestronglyMeasurable.mul hq_meas) ?_
  filter_upwards with v
  let q : ℝ :=
    singleCutoffCrossingProbability
      (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c
  have hq_nonneg : 0 ≤ q :=
    singleCutoffCrossingProbability_nonneg
      (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c
  have hq_le_one : q ≤ 1 :=
    singleCutoffCrossingProbability_le_one
      (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c
  have hq_abs : |q| ≤ 1 := by
    simpa [abs_of_nonneg hq_nonneg] using hq_le_one
  calc
    ‖v * q‖ = |v * q| := Real.norm_eq_abs _
    _ = |v| * |q| := abs_mul v q
    _ ≤ |v| * 1 := mul_le_mul_of_nonneg_left hq_abs (abs_nonneg v)
    _ = |v| := by ring

/--
For iid one-dimensional noise, the probability of crossing some active
heterogeneous cutoff is one minus the product of the lower-tail probabilities
at each shifted cutoff.
-/
theorem cutoffCrossingProbability_iidProduct_eq_one_sub_prod_lowerCDFMass
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (active : Finset (Fin n)) (v : ℝ) (cutoff : Fin n → ℝ) :
    cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ)) active v cutoff =
      1 - ∏ c ∈ active, lowerCDFMass μ (cutoff c - v) := by
  classical
  let productMeasure : Measure (Fin n → ℝ) := Measure.pi (fun _ : Fin n => μ)
  haveI : IsProbabilityMeasure productMeasure := by
    dsimp [productMeasure]
    infer_instance
  let crossingSet : Set (Fin n → ℝ) :=
    {noise : Fin n → ℝ | cutoffCrossedOn active (noisyScore v noise) cutoff}
  let noCrossingSet : Set (Fin n → ℝ) :=
    Set.pi Set.univ
      (fun c : Fin n =>
        if c ∈ active then Set.Iic (cutoff c - v) else Set.univ)
  have hcompl : crossingSetᶜ = noCrossingSet := by
    ext noise
    constructor
    · intro h
      rw [show noCrossingSet =
          Set.pi Set.univ
            (fun c : Fin n =>
              if c ∈ active then Set.Iic (cutoff c - v) else Set.univ) by rfl]
      intro c _hc_univ
      by_cases hactive : c ∈ active
      · simp [hactive]
        have hle : ¬ cutoff c < v + noise c := by
          intro hlt
          exact h ⟨c, hactive, hlt⟩
        linarith
      · simp [hactive]
    · intro h hcross
      rcases hcross with ⟨c, hc, hlt⟩
      have hmem :
          noise c ∈
            (if c ∈ active then Set.Iic (cutoff c - v) else Set.univ) :=
        h c (by simp)
      have hle : noise c ≤ cutoff c - v := by
        simpa [hc] using hmem
      have hlt' : cutoff c < v + noise c := by
        simpa [noisyScore] using hlt
      linarith
  have hno_meas : MeasurableSet noCrossingSet := by
    refine MeasurableSet.pi Set.countable_univ ?_
    intro c _hc
    by_cases hactive : c ∈ active
    · simpa [noCrossingSet, hactive] using
        (measurableSet_Iic : MeasurableSet (Set.Iic (cutoff c - v)))
    · simpa [noCrossingSet, hactive] using
        (MeasurableSet.univ : MeasurableSet (Set.univ : Set ℝ))
  have hcross_meas : MeasurableSet crossingSet := by
    have hcross_eq : crossingSet = noCrossingSetᶜ := by
      rw [← hcompl]
      simp
    rw [hcross_eq]
    exact hno_meas.compl
  have hno_real :
      productMeasure.real noCrossingSet =
        ∏ c ∈ active, lowerCDFMass μ (cutoff c - v) := by
    have hmeasure :
        productMeasure noCrossingSet =
          ∏ c : Fin n,
            μ (if c ∈ active then Set.Iic (cutoff c - v) else Set.univ) := by
      dsimp [productMeasure, noCrossingSet]
      rw [Measure.pi_pi]
    rw [Measure.real, hmeasure, ENNReal.toReal_prod]
    calc
      ∏ c : Fin n,
          (μ (if c ∈ active then Set.Iic (cutoff c - v) else Set.univ)).toReal =
          ∏ c : Fin n,
            if c ∈ active then lowerCDFMass μ (cutoff c - v) else 1 := by
            refine Finset.prod_congr rfl ?_
            intro c _hc
            by_cases hactive : c ∈ active
            · simp [hactive, lowerCDFMass, Measure.real]
            · simp [hactive]
      _ = ∏ c ∈ active, lowerCDFMass μ (cutoff c - v) := by
            simpa using
              (Finset.prod_filter
                (s := (Finset.univ : Finset (Fin n)))
                (p := fun c : Fin n => c ∈ active)
                (f := fun c : Fin n => lowerCDFMass μ (cutoff c - v))).symm
  have hcompl_real :
      productMeasure.real noCrossingSet =
        1 - productMeasure.real crossingSet := by
    rw [← hcompl]
    exact probReal_compl_eq_one_sub (μ := productMeasure) hcross_meas
  have htarget :
      productMeasure.real crossingSet =
        1 - ∏ c ∈ active, lowerCDFMass μ (cutoff c - v) := by
    linarith
  simpa [cutoffCrossingProbability, productMeasure, crossingSet] using htarget

/--
For iid one-dimensional noise and a constant cutoff on a finite active set,
the crossing probability is `1 - F(P-v) ^ |active|`.
-/
theorem cutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass_pow_card
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (active : Finset (Fin n)) (v P : ℝ) :
    cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ)) active v
        (fun _ => P) =
      1 - (lowerCDFMass μ (P - v)) ^ active.card := by
  rw [cutoffCrossingProbability_iidProduct_eq_one_sub_prod_lowerCDFMass]
  congr 1
  simp [Finset.prod_const]

/--
Equivalent iid product formula using upper-tail crossing probabilities at
each active shifted cutoff.
-/
theorem cutoffCrossingProbability_iidProduct_eq_one_sub_prod_one_sub_upperTailMass
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (active : Finset (Fin n)) (v : ℝ) (cutoff : Fin n → ℝ) :
    cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ)) active v cutoff =
      1 - ∏ c ∈ active, (1 - upperTailMass μ (cutoff c - v)) := by
  rw [cutoffCrossingProbability_iidProduct_eq_one_sub_prod_lowerCDFMass]
  congr 1
  refine Finset.prod_congr rfl ?_
  intro c _hc
  have hsum := lowerCDFMass_add_upperTailMass_eq_one μ (cutoff c - v)
  linarith

/--
Finite union bound for affordability: the probability of crossing some active
cutoff is at most the sum of the single-college crossing probabilities.
-/
theorem cutoffCrossingProbability_le_sum_singleCutoffCrossingProbability
    {College : Type u} [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) :
    cutoffCrossingProbability μ active v cutoff ≤
      ∑ c ∈ active, singleCutoffCrossingProbability μ v cutoff c := by
  unfold cutoffCrossingProbability singleCutoffCrossingProbability cutoffCrossedOn
  simpa [AppliedModelingLib.measureProb, Measure.real] using
    (AppliedModelingLib.measureProb_biUnion_finset_le
      (μ := μ) (s := active)
      (p := fun c noise => cutoff c < noisyScore v noise c))

/--
Uniform single-college crossing bound: if every active single-college crossing
probability is at most `q`, then the active-set affordability probability is at
most `|active| * q`.
-/
theorem cutoffCrossingProbability_le_card_mul_of_singleCutoffCrossingProbability_le
    {College : Type u} [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) {q : ℝ}
    (hbound :
      ∀ c ∈ active, singleCutoffCrossingProbability μ v cutoff c ≤ q) :
    cutoffCrossingProbability μ active v cutoff ≤ (active.card : ℝ) * q := by
  calc
    cutoffCrossingProbability μ active v cutoff ≤
        ∑ c ∈ active, singleCutoffCrossingProbability μ v cutoff c :=
      cutoffCrossingProbability_le_sum_singleCutoffCrossingProbability
        μ active v cutoff
    _ ≤ active.card • q :=
      Finset.sum_le_card_nsmul active
        (fun c => singleCutoffCrossingProbability μ v cutoff c)
        q hbound
    _ = (active.card : ℝ) * q := by
      simp [nsmul_eq_mul]

/--
Uniform single-college crossing bound with a real-valued cardinal upper bound.
-/
theorem cutoffCrossingProbability_le_cardBound_mul_of_singleCutoffCrossingProbability_le
    {College : Type u} [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (active : Finset College)
    (v : ℝ) (cutoff : College → ℝ) {cardBound q : ℝ}
    (hcard : (active.card : ℝ) ≤ cardBound) (hq_nonneg : 0 ≤ q)
    (hbound :
      ∀ c ∈ active, singleCutoffCrossingProbability μ v cutoff c ≤ q) :
    cutoffCrossingProbability μ active v cutoff ≤ cardBound * q := by
  calc
    cutoffCrossingProbability μ active v cutoff ≤ (active.card : ℝ) * q :=
      cutoffCrossingProbability_le_card_mul_of_singleCutoffCrossingProbability_le
        μ active v cutoff hbound
    _ ≤ cardBound * q :=
      mul_le_mul_of_nonneg_right hcard hq_nonneg

theorem cutoffCrossingProbability_mono_active {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {active larger : Finset College} {v : ℝ} {cutoff : College → ℝ}
    (hsubset : active ⊆ larger) :
    cutoffCrossingProbability μ active v cutoff ≤
      cutoffCrossingProbability μ larger v cutoff := by
  unfold cutoffCrossingProbability
  exact measureReal_mono
    (μ := μ)
    (fun noise hnoise => cutoffCrossedOn_mono_active hsubset hnoise)
    (measure_ne_top μ _)

/--
Union bound for cutoff-crossing probabilities over a split active set.  The
left side is the probability of affording at least one college in
`left ∪ right`; the right side is the sum of the probabilities for the two
pieces.
-/
theorem cutoffCrossingProbability_union_le {College : Type u}
    [DecidableEq College] [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) (left right : Finset College)
    (v : ℝ) (cutoff : College → ℝ) :
    cutoffCrossingProbability μ (left ∪ right) v cutoff ≤
      cutoffCrossingProbability μ left v cutoff +
        cutoffCrossingProbability μ right v cutoff := by
  unfold cutoffCrossingProbability
  have hset :
      {noise : College → ℝ |
          cutoffCrossedOn (left ∪ right) (noisyScore v noise) cutoff} =
        {noise : College → ℝ |
            cutoffCrossedOn left (noisyScore v noise) cutoff} ∪
          {noise : College → ℝ |
            cutoffCrossedOn right (noisyScore v noise) cutoff} := by
    ext noise
    simp [cutoffCrossedOn_union_iff]
  rw [hset]
  exact measureReal_union_le _ _

theorem cutoffCrossingProbability_mono_lowerCutoff {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {active : Finset College} {v : ℝ}
    {cutoff lowerCutoff : College → ℝ}
    (hlower : ∀ c ∈ active, lowerCutoff c ≤ cutoff c) :
    cutoffCrossingProbability μ active v cutoff ≤
      cutoffCrossingProbability μ active v lowerCutoff := by
  unfold cutoffCrossingProbability
  exact measureReal_mono
    (μ := μ)
    (fun noise hnoise => cutoffCrossedOn_mono_cutoff hlower hnoise)
    (measure_ne_top μ _)

theorem constantCutoffProbability_le_of_cutoff_le {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {active : Finset College} {v P : ℝ} {cutoff : College → ℝ}
    (hupper : ∀ c ∈ active, cutoff c ≤ P) :
    cutoffCrossingProbability μ active v (fun _ => P) ≤
      cutoffCrossingProbability μ active v cutoff :=
  cutoffCrossingProbability_mono_lowerCutoff
    μ (cutoff := fun _ => P) (lowerCutoff := cutoff) hupper

/--
Iid lower bound from a uniform upper bound on active cutoffs.  If every active
cutoff is at most `P`, then affording at least one active college is at least
as likely as crossing a constant cutoff `P` on the same active block.
-/
theorem one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_of_cutoff_le
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (active : Finset (Fin n)) {v P : ℝ} {cutoff : Fin n → ℝ}
    (hupper : ∀ c ∈ active, cutoff c ≤ P) :
    1 - (lowerCDFMass μ (P - v)) ^ active.card ≤
      cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        active v cutoff := by
  rw [← cutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass_pow_card
    μ active v P]
  exact
    constantCutoffProbability_le_of_cutoff_le
      (Measure.pi (fun _ : Fin n => μ)) hupper

/--
Strict version of
`one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_of_cutoff_le`.
-/
theorem lt_cutoffCrossingProbability_iidProduct_of_lt_one_sub_lowerCDFMass_pow_card_of_cutoff_le
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (active : Finset (Fin n)) {v P threshold : ℝ} {cutoff : Fin n → ℝ}
    (hupper : ∀ c ∈ active, cutoff c ≤ P)
    (hprob : threshold <
      1 - (lowerCDFMass μ (P - v)) ^ active.card) :
    threshold <
      cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        active v cutoff :=
  lt_of_lt_of_le hprob
    (one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_of_cutoff_le
      μ active hupper)

/--
Direct low-cutoff-set version of the iid lower bound.  This is the finite
probability step used when many sorted cutoffs lie below a scalar floor.
-/
theorem lt_cutoffCrossingProbability_iidProduct_lowCutoffIndexSet_of_lt_one_sub_lowerCDFMass_pow_card
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    {cutoff : Fin n → ℝ} {v floor threshold : ℝ}
    (hprob : threshold <
      1 - (lowerCDFMass μ (floor - v)) ^
        (lowCutoffIndexSet cutoff floor).card) :
    threshold <
      cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        (lowCutoffIndexSet cutoff floor) v cutoff :=
  lt_cutoffCrossingProbability_iidProduct_of_lt_one_sub_lowerCDFMass_pow_card_of_cutoff_le
    μ (lowCutoffIndexSet cutoff floor)
    (fun c hc => cutoff_le_floor_of_mem_lowCutoffIndexSet hc)
    hprob

/--
The constant-cutoff lower-bound integrand is integrable against any finite
value law.
-/
theorem one_sub_lowerCDFMass_pow_integrable_value
    (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η] (floor : ℝ) (m : ℕ) :
    Integrable
      (fun v : ℝ => 1 - (lowerCDFMass μ (floor - v)) ^ m) η := by
  have hcdf_meas : Measurable (fun x : ℝ => lowerCDFMass μ x) :=
    (lowerCDFMass_mono μ).measurable
  have haff_meas : Measurable (fun v : ℝ => floor - v) := by
    fun_prop
  have hbase_meas :
      Measurable (fun v : ℝ => lowerCDFMass μ (floor - v)) :=
    hcdf_meas.comp haff_meas
  have hmeas :
      AEStronglyMeasurable
        (fun v : ℝ => 1 - (lowerCDFMass μ (floor - v)) ^ m) η := by
    exact (aestronglyMeasurable_const.sub
      (hbase_meas.aestronglyMeasurable.pow m))
  refine Integrable.of_bound hmeas 1 ?_
  filter_upwards with v
  have hbase_nonneg : 0 ≤ lowerCDFMass μ (floor - v) :=
    lowerCDFMass_nonneg μ _
  have hbase_le_one : lowerCDFMass μ (floor - v) ≤ 1 :=
    lowerCDFMass_le_one μ _
  have hpow_nonneg : 0 ≤ (lowerCDFMass μ (floor - v)) ^ m :=
    pow_nonneg hbase_nonneg m
  have hpow_le_one : (lowerCDFMass μ (floor - v)) ^ m ≤ 1 :=
    pow_le_one₀ hbase_nonneg hbase_le_one
  have hval_nonneg : 0 ≤ 1 - (lowerCDFMass μ (floor - v)) ^ m := by
    linarith
  have hval_le_one : 1 - (lowerCDFMass μ (floor - v)) ^ m ≤ 1 := by
    linarith
  have habs :
      |1 - (lowerCDFMass μ (floor - v)) ^ m| ≤ 1 :=
    abs_le.mpr ⟨by linarith, by linarith⟩
  simpa [Real.norm_eq_abs] using habs

/--
If a value region has a uniform CDF cap `q` at the scalar floor, the
constant-cutoff maximum-crossing integral is bounded below by the region mass
times `1 - q^m`.

This is the reusable integral step behind maximum-crossing arguments: once
many colleges have cutoff below a scalar floor, a positive value region with a
uniformly nonterminal noise CDF forces the integrated maximum-crossing lower
bound above any target below this two-piece lower bound.
-/
theorem lt_integral_one_sub_lowerCDFMass_pow_of_region_cdf_le
    (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsProbabilityMeasure η]
    {floor q target : ℝ} {m : ℕ} {region : Set ℝ}
    (hregion_meas : MeasurableSet region)
    (hq_nonneg : 0 ≤ q)
    (hcdf : ∀ v : ℝ, v ∈ region → lowerCDFMass μ (floor - v) ≤ q)
    (htarget : target < (1 - q ^ m) * η.real region) :
    target <
      ∫ v : ℝ, 1 - (lowerCDFMass μ (floor - v)) ^ m ∂η := by
  have hint :
      Integrable
        (fun v : ℝ => 1 - (lowerCDFMass μ (floor - v)) ^ m) η :=
    one_sub_lowerCDFMass_pow_integrable_value μ η floor m
  have hlow :
      ∀ v : ℝ, v ∈ region →
        1 - q ^ m ≤ 1 - (lowerCDFMass μ (floor - v)) ^ m := by
    intro v hv
    have hpow :
        (lowerCDFMass μ (floor - v)) ^ m ≤ q ^ m :=
      pow_le_pow_left₀ (lowerCDFMass_nonneg μ _) (hcdf v hv) m
    linarith
  have hnonneg_compl :
      ∀ v : ℝ, v ∉ region →
        0 ≤ 1 - (lowerCDFMass μ (floor - v)) ^ m := by
    intro v _hv
    have hbase_nonneg : 0 ≤ lowerCDFMass μ (floor - v) :=
      lowerCDFMass_nonneg μ _
    have hbase_le_one : lowerCDFMass μ (floor - v) ≤ 1 :=
      lowerCDFMass_le_one μ _
    have hpow_le_one :
        (lowerCDFMass μ (floor - v)) ^ m ≤ 1 :=
      pow_le_one₀ hbase_nonneg hbase_le_one
    linarith
  exact
    htarget.trans_le
      (AppliedModelingLib.measureReal_mul_le_integral_of_le_on_of_nonneg_on_compl
        η hregion_meas hint hlow hnonneg_compl)

theorem cutoffCrossingProbability_le_constantCutoff_of_le {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {active : Finset College} {v P : ℝ} {cutoff : College → ℝ}
    (hlower : ∀ c ∈ active, P ≤ cutoff c) :
    cutoffCrossingProbability μ active v cutoff ≤
      cutoffCrossingProbability μ active v (fun _ => P) :=
  cutoffCrossingProbability_mono_lowerCutoff
    μ (cutoff := cutoff) (lowerCutoff := fun _ => P) hlower

theorem cutoffCrossingProbability_mono_value {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    {active : Finset College} {v w : ℝ} {cutoff : College → ℝ}
    (hvw : v ≤ w) :
    cutoffCrossingProbability μ active v cutoff ≤
      cutoffCrossingProbability μ active w cutoff := by
  unfold cutoffCrossingProbability
  exact measureReal_mono
    (μ := μ)
    (fun noise hnoise =>
      cutoffCrossedOn_mono_score
        (fun c _hc => by
          dsimp [noisyScore]
          linarith)
        hnoise)
    (measure_ne_top μ _)

/-- Cutoff-crossing probability is monotone in the student's value. -/
theorem cutoffCrossingProbability_monotone_value {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    (active : Finset College) (cutoff : College → ℝ) :
    Monotone (fun v : ℝ => cutoffCrossingProbability μ active v cutoff) := by
  intro v w hvw
  exact cutoffCrossingProbability_mono_value μ hvw

/--
As a function of the student's value, cutoff-crossing probability is
integrable against any finite value law.
-/
theorem cutoffCrossingProbability_integrable_value {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η]
    (active : Finset College) (cutoff : College → ℝ) :
    Integrable (fun v : ℝ => cutoffCrossingProbability μ active v cutoff) η := by
  have hmono :
      Monotone (fun v : ℝ => cutoffCrossingProbability μ active v cutoff) :=
    cutoffCrossingProbability_monotone_value μ active cutoff
  refine Integrable.of_bound hmono.measurable.aestronglyMeasurable 1 ?_
  filter_upwards with v
  have hnonneg :
      0 ≤ cutoffCrossingProbability μ active v cutoff :=
    cutoffCrossingProbability_nonneg μ active v cutoff
  have hle :
      cutoffCrossingProbability μ active v cutoff ≤ 1 :=
    cutoffCrossingProbability_le_one μ active v cutoff
  have habs :
      |cutoffCrossingProbability μ active v cutoff| ≤ 1 := by
    exact abs_le.mpr ⟨by linarith, hle⟩
  simpa [Real.norm_eq_abs] using habs

/--
Integrated version of the low-cutoff-set iid lower bound.  This is the
measure-theoretic step from the constant-cutoff lower-bound integral to the
actual heterogeneous low-cutoff affordability integral.
-/
theorem integral_one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_lowCutoffIndexSet
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η]
    {cutoff : Fin n → ℝ} {floor : ℝ} :
    (∫ v : ℝ,
      1 - (lowerCDFMass μ (floor - v)) ^
        (lowCutoffIndexSet cutoff floor).card ∂η) ≤
      ∫ v : ℝ,
        cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
          (lowCutoffIndexSet cutoff floor) v cutoff ∂η := by
  have hleft :
      Integrable
        (fun v : ℝ =>
          1 - (lowerCDFMass μ (floor - v)) ^
            (lowCutoffIndexSet cutoff floor).card) η :=
    one_sub_lowerCDFMass_pow_integrable_value μ η floor
      (lowCutoffIndexSet cutoff floor).card
  have hright :
      Integrable
        (fun v : ℝ =>
          cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
            (lowCutoffIndexSet cutoff floor) v cutoff) η :=
    cutoffCrossingProbability_integrable_value
      (Measure.pi (fun _ : Fin n => μ)) η
      (lowCutoffIndexSet cutoff floor) cutoff
  exact MeasureTheory.integral_mono hleft hright (fun v =>
    one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_of_cutoff_le
      μ (lowCutoffIndexSet cutoff floor)
      (fun c hc => cutoff_le_floor_of_mem_lowCutoffIndexSet hc))

/--
Strict integrated low-cutoff-set lower bound from the constant-cutoff lower
bound integral.
-/
theorem lt_integral_cutoffCrossingProbability_iidProduct_lowCutoffIndexSet_of_lt_integral_one_sub_lowerCDFMass_pow_card
    {n : ℕ} (μ : Measure ℝ) [IsProbabilityMeasure μ]
    (η : Measure ℝ) [IsFiniteMeasure η]
    {cutoff : Fin n → ℝ} {floor threshold : ℝ}
    (hprob :
      threshold <
        ∫ v : ℝ,
          1 - (lowerCDFMass μ (floor - v)) ^
            (lowCutoffIndexSet cutoff floor).card ∂η) :
    threshold <
      ∫ v : ℝ,
        cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
          (lowCutoffIndexSet cutoff floor) v cutoff ∂η :=
  lt_of_lt_of_le hprob
    (integral_one_sub_lowerCDFMass_pow_card_le_cutoffCrossingProbability_iidProduct_lowCutoffIndexSet
      μ η)

/--
The value-weighted cutoff-crossing probability is a.e. strongly measurable as
a function of the student's value.
-/
theorem cutoffCrossingProbability_value_mul_aestronglyMeasurable {College : Type u}
    [MeasurableSpace (College → ℝ)]
    (μ : Measure (College → ℝ)) [IsFiniteMeasure μ]
    (η : Measure ℝ)
    (active : Finset College) (cutoff : College → ℝ) :
    AEStronglyMeasurable
      (fun v : ℝ => v * cutoffCrossingProbability μ active v cutoff) η := by
  have hmono :
      Monotone (fun v : ℝ => cutoffCrossingProbability μ active v cutoff) :=
    cutoffCrossingProbability_monotone_value μ active cutoff
  exact
    measurable_id.aestronglyMeasurable.mul
      hmono.measurable.aestronglyMeasurable

/--
Compatibility alias for the shared top rank.  The reusable order-statistic
facts live in `AppliedModelingLib.Probability`; this module only adds cutoff semantics.
-/
noncomputable abbrev topSampleRank {n : ℕ} [NeZero n] : Fin n :=
  AppliedModelingLib.Probability.topSampleRank (n := n)

theorem exists_lt_iff_iidSuccessCount_pos {n : ℕ}
    (sample : Fin n → ℝ) (x : ℝ) :
    (∃ i : Fin n, x < sample i) ↔
      0 < iidSuccessCount (Set.Ioi x) sample :=
  AppliedModelingLib.Probability.exists_lt_iff_iidSuccessCount_pos sample x

theorem exists_lt_iff_topOrderStatistic_gt {n : ℕ} [NeZero n]
    (sample : Fin n → ℝ) (x : ℝ) :
    (∃ i : Fin n, x < sample i) ↔
      x < upperOrderStatistic sample (topSampleRank (n := n)) :=
  AppliedModelingLib.Probability.exists_lt_iff_topOrderStatistic_gt sample x

/--
For a constant cutoff `P`, the event that some noisy score `v + X_i` crosses
`P` is exactly the event that the maximum noise order statistic crosses
`P - v`.
-/
theorem exists_constant_cutoff_noisyScore_iff_topOrderStatistic_gt
    {n : ℕ} [NeZero n] (noise : Fin n → ℝ) (v P : ℝ) :
    (∃ i : Fin n, P < noisyScore v noise i) ↔
      P - v < upperOrderStatistic noise (topSampleRank (n := n)) := by
  have hshift :
      (∃ i : Fin n, P < noisyScore v noise i) ↔
        ∃ i : Fin n, P - v < noise i := by
    constructor
    · rintro ⟨i, hi⟩
      exact ⟨i, by simp [noisyScore] at hi ⊢; linarith⟩
    · rintro ⟨i, hi⟩
      exact ⟨i, by simp [noisyScore] at hi ⊢; linarith⟩
  rw [hshift]
  exact exists_lt_iff_topOrderStatistic_gt noise (P - v)

/-- Compatibility alias for the shared top-order crossing probability. -/
noncomputable abbrev topOrderCrossingProbability {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) (x : ℝ) : ℝ :=
  AppliedModelingLib.Probability.topOrderCrossingProbability μ x

/-- Compatibility alias for the shared top-order deviation probability. -/
noncomputable abbrev topOrderDeviationProbability {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) (center ε : ℝ) : ℝ :=
  AppliedModelingLib.Probability.topOrderDeviationProbability μ center ε

theorem topOrderCrossingSet_measurable {n : ℕ} [NeZero n]
    (x : ℝ) :
    MeasurableSet {noise : Fin n → ℝ |
      x < upperOrderStatistic noise (topSampleRank (n := n))} :=
  AppliedModelingLib.Probability.topOrderCrossingSet_measurable (n := n) x

theorem topOrderDeviationSet_measurable {n : ℕ} [NeZero n]
    (center ε : ℝ) :
    MeasurableSet {noise : Fin n → ℝ |
      ε < |upperOrderStatistic noise (topSampleRank (n := n)) - center|} :=
  AppliedModelingLib.Probability.topOrderDeviationSet_measurable (n := n) center ε

theorem topOrderCrossingProbability_le_deviationProbability_of_center_add_le
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsFiniteMeasure μ]
    {x center ε : ℝ} (hsep : center + ε ≤ x) :
    topOrderCrossingProbability μ x ≤
      topOrderDeviationProbability μ center ε :=
  AppliedModelingLib.Probability.topOrderCrossingProbability_le_deviationProbability_of_center_add_le
    μ hsep

theorem one_sub_topOrderCrossingProbability_le_deviationProbability_of_lt_center_sub
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsProbabilityMeasure μ]
    {x center ε : ℝ} (hε : 0 < ε) (hsep : x < center - ε) :
    1 - topOrderCrossingProbability μ x ≤
      topOrderDeviationProbability μ center ε :=
  AppliedModelingLib.Probability.one_sub_topOrderCrossingProbability_le_deviationProbability_of_lt_center_sub
    μ hε hsep

theorem cutoffCrossingProbability_univ_constant_eq_topOrderCrossingProbability
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) (v P : ℝ) :
    cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v (fun _ => P) =
      topOrderCrossingProbability μ (P - v) := by
  unfold cutoffCrossingProbability topOrderCrossingProbability
  congr 1
  ext noise
  change
    cutoffCrossedOn (Finset.univ : Finset (Fin n)) (noisyScore v noise)
        (fun _ => P) ↔
      P - v < upperOrderStatistic noise (topSampleRank (n := n))
  rw [cutoffCrossedOn_univ_iff_cutoffCrossed, cutoffCrossed]
  exact exists_constant_cutoff_noisyScore_iff_topOrderStatistic_gt noise v P

/--
For iid noise and a constant cutoff, the universal active-set crossing
probability has the source CDF formula `1 - F(P - v)^n`.
-/
theorem cutoffCrossingProbability_univ_constant_iidProduct_eq_one_sub_lowerCDFMass_pow
    {n : ℕ} [NeZero n]
    (μ : Measure ℝ) [IsProbabilityMeasure μ] (v P : ℝ) :
    cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        (Finset.univ : Finset (Fin n)) v (fun _ => P) =
      1 - (lowerCDFMass μ (P - v)) ^ n := by
  rw [cutoffCrossingProbability_univ_constant_eq_topOrderCrossingProbability]
  exact
    AppliedModelingLib.Probability.topOrderCrossingProbability_iidProduct_eq_one_sub_lowerCDFMass_pow
      μ (P - v)

/--
For iid noise and a constant cutoff, if the one-dimensional CDF at `P - v` is
strictly below one, then the all-college crossing probability tends to one as
the number of colleges grows.
-/
theorem cutoffCrossingProbability_univ_constant_iidProduct_tendsto_one_of_lowerCDFMass_lt_one
    (μ : Measure ℝ) [IsProbabilityMeasure μ] {v P : ℝ}
    (hlt : lowerCDFMass μ (P - v) < 1) :
    Tendsto
      (fun n : ℕ =>
        cutoffCrossingProbability
          (Measure.pi (fun _ : Fin (n + 1) => μ))
          (Finset.univ : Finset (Fin (n + 1))) v (fun _ => P))
      atTop (nhds 1) := by
  rw [show
      (fun n : ℕ =>
        cutoffCrossingProbability
          (Measure.pi (fun _ : Fin (n + 1) => μ))
          (Finset.univ : Finset (Fin (n + 1))) v (fun _ => P)) =
        (fun n : ℕ =>
          topOrderCrossingProbability
            (Measure.pi (fun _ : Fin (n + 1) => μ)) (P - v)) by
    funext n
    exact cutoffCrossingProbability_univ_constant_eq_topOrderCrossingProbability
      (Measure.pi (fun _ : Fin (n + 1) => μ)) v P]
  exact
    AppliedModelingLib.Probability.topOrderCrossingProbability_iidProduct_tendsto_one_of_lowerCDFMass_lt_one
      μ hlt

/--
Endpoint form for constant cutoffs: if every threshold below an upper endpoint
has CDF mass below one, then any shifted constant cutoff below that endpoint is
crossed with probability tending to one.
-/
theorem cutoffCrossingProbability_univ_constant_iidProduct_tendsto_one_of_lt_endpoint
    (μ : Measure ℝ) [IsProbabilityMeasure μ] {v P M : ℝ}
    (hcdf_lt_top : ∀ y : ℝ, y < M → lowerCDFMass μ y < 1)
    (hshift : P - v < M) :
    Tendsto
      (fun n : ℕ =>
        cutoffCrossingProbability
          (Measure.pi (fun _ : Fin (n + 1) => μ))
          (Finset.univ : Finset (Fin (n + 1))) v (fun _ => P))
      atTop (nhds 1) :=
  cutoffCrossingProbability_univ_constant_iidProduct_tendsto_one_of_lowerCDFMass_lt_one
    μ (hcdf_lt_top (P - v) hshift)

/--
For iid noise and a constant cutoff, the all-college crossing probability is
strictly larger than one named college's crossing probability when there are at
least two colleges and the shifted cutoff has interior one-dimensional CDF mass.
-/
theorem singleCutoffCrossingProbability_lt_cutoffCrossingProbability_univ_constant_iidProduct
    {n : ℕ} [NeZero n]
    (μ : Measure ℝ) [IsProbabilityMeasure μ] {v P : ℝ} (c : Fin n)
    (hn : 1 < n)
    (hcdf : lowerCDFMass μ (P - v) ∈ Set.Ioo (0 : ℝ) 1) :
    singleCutoffCrossingProbability
        (Measure.pi (fun _ : Fin n => μ)) v (fun _ : Fin n => P) c <
      cutoffCrossingProbability (Measure.pi (fun _ : Fin n => μ))
        (Finset.univ : Finset (Fin n)) v (fun _ => P) := by
  rw [singleCutoffCrossingProbability_iidProduct_constant_eq_one_sub_lowerCDFMass]
  rw [cutoffCrossingProbability_univ_constant_iidProduct_eq_one_sub_lowerCDFMass_pow]
  have hpow :
      (lowerCDFMass μ (P - v)) ^ n <
        (lowerCDFMass μ (P - v)) ^ (1 : ℕ) :=
    pow_lt_pow_right_of_lt_one₀ hcdf.1 hcdf.2 hn
  have hstrict :
      1 - lowerCDFMass μ (P - v) <
        1 - (lowerCDFMass μ (P - v)) ^ n := by
    simpa using (sub_lt_sub_left hpow 1)
  simpa using hstrict

theorem cutoffCrossingProbability_univ_constant_le_topOrderDeviationProbability_of_center_add_le
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsFiniteMeasure μ]
    {v P center ε : ℝ} (hsep : center + ε ≤ P - v) :
    cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v (fun _ => P) ≤
      topOrderDeviationProbability μ center ε := by
  rw [cutoffCrossingProbability_univ_constant_eq_topOrderCrossingProbability]
  exact topOrderCrossingProbability_le_deviationProbability_of_center_add_le
    μ hsep

theorem cutoffCrossingProbability_univ_le_topOrderDeviationProbability_of_constant_le_cutoff
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsFiniteMeasure μ]
    {v P center ε : ℝ} {cutoff : Fin n → ℝ}
    (hlower : ∀ c : Fin n, P ≤ cutoff c)
    (hsep : center + ε ≤ P - v) :
    cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v cutoff ≤
      topOrderDeviationProbability μ center ε := by
  calc
    cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v cutoff ≤
        cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v
          (fun _ => P) :=
      cutoffCrossingProbability_le_constantCutoff_of_le
        μ (fun c _hc => hlower c)
    _ ≤ topOrderDeviationProbability μ center ε :=
      cutoffCrossingProbability_univ_constant_le_topOrderDeviationProbability_of_center_add_le
        μ hsep

theorem one_sub_cutoffCrossingProbability_univ_constant_le_topOrderDeviationProbability_of_lt_center_sub
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsProbabilityMeasure μ]
    {v P center ε : ℝ} (hε : 0 < ε) (hsep : P - v < center - ε) :
    1 - cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v (fun _ => P) ≤
      topOrderDeviationProbability μ center ε := by
  rw [cutoffCrossingProbability_univ_constant_eq_topOrderCrossingProbability]
  exact
    one_sub_topOrderCrossingProbability_le_deviationProbability_of_lt_center_sub
      μ hε hsep

theorem one_sub_cutoffCrossingProbability_univ_le_topOrderDeviationProbability_of_cutoff_le_constant
    {n : ℕ} [NeZero n]
    (μ : Measure (Fin n → ℝ)) [IsProbabilityMeasure μ]
    {v P center ε : ℝ} {cutoff : Fin n → ℝ}
    (hupper : ∀ c : Fin n, cutoff c ≤ P)
    (hε : 0 < ε) (hsep : P - v < center - ε) :
    1 - cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v cutoff ≤
      topOrderDeviationProbability μ center ε := by
  haveI : IsFiniteMeasure μ := inferInstance
  have hmono :
      cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v
          (fun _ => P) ≤
        cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v cutoff :=
    constantCutoffProbability_le_of_cutoff_le
      μ (fun c _hc => hupper c)
  have hconst :
      1 - cutoffCrossingProbability μ (Finset.univ : Finset (Fin n)) v
          (fun _ => P) ≤
        topOrderDeviationProbability μ center ε :=
    one_sub_cutoffCrossingProbability_univ_constant_le_topOrderDeviationProbability_of_lt_center_sub
      μ hε hsep
  linarith

theorem cutoffCrossingProbability_univ_tendsto_zero_of_eventually_constant_le_cutoff
    {sampleLaw : ∀ n : ℕ, Measure (Fin (n + 1) → ℝ)}
    {center threshold : ℕ → ℝ}
    {cutoff : ∀ n : ℕ, Fin (n + 1) → ℝ}
    (v : ℝ)
    (hfinite : ∀ n, IsFiniteMeasure (sampleLaw n))
    (hconc : TopOrderDeviationConcentrating sampleLaw center)
    {ε : ℝ} (hε : 0 < ε)
    (hlower : ∀ᶠ n : ℕ in atTop, ∀ c : Fin (n + 1), threshold n ≤ cutoff n c)
    (hsep : ∀ᶠ n : ℕ in atTop, center n + ε ≤ threshold n - v) :
    Tendsto
      (fun n : ℕ =>
        cutoffCrossingProbability (sampleLaw n)
          (Finset.univ : Finset (Fin (n + 1))) v (cutoff n))
      atTop (nhds 0) := by
  have hdev_zero :
      Tendsto
        (fun n : ℕ =>
          topOrderDeviationProbability (sampleLaw n) (center n) ε)
        atTop (nhds 0) :=
    hconc ε hε
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le'
    tendsto_const_nhds hdev_zero ?_ ?_
  · filter_upwards with n
    exact measureReal_nonneg
  · filter_upwards [hlower, hsep] with n hn_lower hn_sep
    haveI : IsFiniteMeasure (sampleLaw n) := hfinite n
    exact
      cutoffCrossingProbability_univ_le_topOrderDeviationProbability_of_constant_le_cutoff
        (sampleLaw n) hn_lower hn_sep

theorem one_sub_cutoffCrossingProbability_univ_tendsto_zero_of_eventually_cutoff_le_constant
    {sampleLaw : ∀ n : ℕ, Measure (Fin (n + 1) → ℝ)}
    {center threshold : ℕ → ℝ}
    {cutoff : ∀ n : ℕ, Fin (n + 1) → ℝ}
    (v : ℝ)
    (hprob : ∀ n, IsProbabilityMeasure (sampleLaw n))
    (hconc : TopOrderDeviationConcentrating sampleLaw center)
    {ε : ℝ} (hε : 0 < ε)
    (hupper : ∀ᶠ n : ℕ in atTop, ∀ c : Fin (n + 1), cutoff n c ≤ threshold n)
    (hsep : ∀ᶠ n : ℕ in atTop, threshold n - v < center n - ε) :
    Tendsto
      (fun n : ℕ =>
        1 - cutoffCrossingProbability (sampleLaw n)
          (Finset.univ : Finset (Fin (n + 1))) v (cutoff n))
      atTop (nhds 0) := by
  have hdev_zero :
      Tendsto
        (fun n : ℕ =>
          topOrderDeviationProbability (sampleLaw n) (center n) ε)
        atTop (nhds 0) :=
    hconc ε hε
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le'
    tendsto_const_nhds hdev_zero ?_ ?_
  · filter_upwards with n
    haveI : IsProbabilityMeasure (sampleLaw n) := hprob n
    have hle_one :
        cutoffCrossingProbability (sampleLaw n)
          (Finset.univ : Finset (Fin (n + 1))) v (cutoff n) ≤ 1 := by
      simpa [cutoffCrossingProbability] using
        measureReal_le_one (μ := sampleLaw n)
          (s := {noise : Fin (n + 1) → ℝ |
            cutoffCrossedOn (Finset.univ : Finset (Fin (n + 1)))
              (noisyScore v noise) (cutoff n)})
    linarith
  · filter_upwards [hupper, hsep] with n hn_upper hn_sep
    haveI : IsProbabilityMeasure (sampleLaw n) := hprob n
    exact
      one_sub_cutoffCrossingProbability_univ_le_topOrderDeviationProbability_of_cutoff_le_constant
        (sampleLaw n) hn_upper hε hn_sep

end Matching
end AppliedModelingLib
