import PKG25NoFreeLunch.JointSourceModel

open MeasureTheory

/-!
# PKG25 explicit source-model conventions

This file holds paper-facing conventions that are needed to give a source
display its ordinary mathematical meaning but are not stated as standalone
hypotheses in the paper.  They must remain visible to the audit workflow.
-/

namespace PKG25NoFreeLunch

/--
On an arbitrary probability space, predictors must be measurable for the
source's random-variable and calibration expressions to be defined.  The
source treats this as implicit in writing `P(X)` and conditional probability;
the raw model makes it a structural convention.

Source anchor: `source_tex/sections/theorem.tex`, lines 2--18.
-/
abbrev source_assumption_predictor_measurability {n : ℕ}
    (S : JointLawCollaborationSetting n) : Prop :=
  ∀ i : Fin n, Measurable (S.pred i)

/--
The source's point-conditioned calibration display is given the standard
event-calibration meaning on the sigma algebra generated by a reported
probability.  This avoids silently treating null prediction fibres as
positive-probability conditional events.

Source anchor: `source_tex/sections/theorem.tex`, lines 6--10.
-/
abbrev source_assumption_event_calibration {n : ℕ}
    (S : JointLawCollaborationSetting n) : Prop :=
  ∀ i : Fin n, ∀ A : Set ℝ, MeasurableSet A →
    (∫ z,
      ({z | S.pred i z.1 ∈ A ∧ z.2 = true}.indicator fun _ => (1 : ℝ)) z
        ∂S.joint) =
      ∫ z, ({z | S.pred i z.1 ∈ A}.indicator fun z => S.pred i z.1) z
        ∂S.joint

/--
The source permits arbitrary deterministic collaboration strategies.  On an
arbitrary measurable input space, the induced correctness indicator must be
integrable before the displayed `acc_C(S)` is an expected accuracy.  This is an
analytic well-formedness convention, not a claim that every deterministic
function is measurable.

Source anchor: `source_tex/sections/theorem.tex`, lines 26--34; the same
expectation notation is used in `source_tex/sections/proof.tex`, lines 26--32.
-/
abbrev source_assumption_strategy_expectation_well_formed {n : ℕ}
    (S : JointLawCollaborationSetting n) (C : CollaborationStrategy n) :=
  JointLawCollaborationSetting.StrategyWellFormed S C

end PKG25NoFreeLunch
