import AppliedModelingLib.Learning.ReinforcementLearning.Preference.Trajectory
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.UtilityComparison
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.Logistic
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PolicyComparison
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.TrajectoryEmbedding
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.RewardAgnostic
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.FiniteHorizonSimulation
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PreferenceRegret
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PreferenceOccupancy
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.StageIndexedOccupancy
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.StageIndexedOptimalValue
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.StageIndexedVisitation
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.StageIndexedPerformanceDifference
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.StageIndexedTrajectoryConcentration
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PreferenceBellman
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.Robustness
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.LinkRegularity
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.Confidence
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.IIDConcentration
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.AdaptiveQueries
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.AdaptiveConcentration
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.AdaptiveChangeOfMeasure
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.Eluder
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.ApproximateDynamicProgramming
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PlanningProblemCongruence
import AppliedModelingLib.Learning.ReinforcementLearning.Preference.PAC

/-!
# Preference-based reinforcement learning

Curated entrypoint for trajectory-level preference-RL primitives, confidence
and change-of-measure tools, planning, occupancy, and regret. The declarations
retain their established `AppliedModelingLib.PreferenceRL` mathematical namespace while
their module ownership follows the learning hierarchy.
-/
