import AppliedModelingLib.Foundations.Probability.ExponentialInterarrivalDeterministicResidualTail
import AppliedModelingLib.Foundations.Probability.ForwardPoisson

/-!
# Canonical forward Poisson process from exponential interarrivals

This module turns the canonical iid exponential interarrival path into an
actual `ForwardHomogeneousPoissonCountingProcessByLaw`.  The key result is a
finite independent-increments proof for the renewal count.  It is deliberately
forward-time only: it supplies no fictitious nonnegative count process before
the tagged origin and makes no stationarity or Palm claim.
-/

namespace AppliedModelingLib.Probability.PoissonProcess

open MeasureTheory Filter
open scoped ENNReal NNReal ProbabilityTheory

noncomputable section

/-- The first `n` renewal increments generated by recursively restarting at
each deterministic duration. -/
private def renewalIncrementVector : (n : ℕ) → (Fin n → ℝ) →
    Fin n → (ℕ → ℝ) → ℕ
  | 0, _ => fun i => Fin.elim0 i
  | n + 1, d =>
      Fin.cons (α := fun _ : Fin (n + 1) => (ℕ → ℝ) → ℕ)
        (canonicalRenewalCount (d 0))
        (fun i => renewalIncrementVector n (fun j => d j.succ) i ∘
          residualTail (d 0))

/-- The deterministic clock obtained by concatenating a starting time and a
finite family of nonnegative durations. -/
private def renewalTimeline : (start : ℝ) → (n : ℕ) → (Fin n → ℝ) →
    Fin (n + 1) → ℝ
  | start, 0, _ => fun _ => start
  | start, n + 1, d =>
      Fin.cons (α := fun _ : Fin ((n + 1) + 1) => ℝ) start
        (fun i => renewalTimeline (start + d 0) n (fun j => d j.succ) i)

private theorem renewalTimeline_zero (start : ℝ) (n : ℕ) (d : Fin n → ℝ) :
    renewalTimeline start n d 0 = start := by
  cases n <;> rfl

private def timelineDurations {n : ℕ} (t : Fin (n + 1) → ℝ) : Fin n → ℝ :=
  fun i => t i.succ - t i.castSucc

private theorem renewalTimeline_eq_timeline :
    ∀ (n : ℕ) (t : Fin (n + 1) → ℝ) (i : Fin (n + 1)),
      renewalTimeline (t 0) n (timelineDurations t) i = t i := by
  intro n
  induction n with
  | zero =>
      intro t i
      have hi : i = 0 := Fin.eq_zero i
      subst i
      rfl
  | succ n ih =>
      intro t i
      cases i using Fin.cases with
      | zero => simp [renewalTimeline]
      | succ i =>
          let tTail : Fin (n + 1) → ℝ := fun j => t j.succ
          have hih := ih tTail i
          have hfirst : t 0 + (t 1 - t 0) = t 1 := by ring
          simp only [renewalTimeline, Fin.cons_succ]
          rw [show t 0 + timelineDurations t 0 = t 1 by
            simpa [timelineDurations] using hfirst]
          simpa [renewalTimeline, timelineDurations, tTail] using hih

private theorem measurable_renewalIncrementVector
    (n : ℕ) (d : Fin n → ℝ) (i : Fin n) :
    Measurable (renewalIncrementVector n d i) := by
  induction n with
  | zero => exact Fin.elim0 i
  | succ n ih =>
      cases i using Fin.cases with
      | zero => simpa [renewalIncrementVector] using measurable_canonicalRenewalCount (d 0)
      | succ i =>
          simpa [renewalIncrementVector] using
            (ih (fun j => d j.succ) i).comp (measurable_residualTail (d 0))

/-- Restarting first at `s` and then after a further duration `h` agrees
almost surely with restarting once at `s + h`. -/
theorem ae_residualTail_add_eq_residualTail_comp
    {rate s h : ℝ} (hrate : 0 < rate) (hh : 0 ≤ h) :
    ∀ᵐ ω ∂exponentialInterarrivalMeasure rate,
      residualTail (s + h) ω = residualTail h (residualTail s ω) := by
  filter_upwards [ae_canonicalRenewalCount_add_eq_residualTailCount hrate s h hh]
    with ω hω
  funext k
  cases k with
  | zero =>
      rw [residualTail, residualTail, hω, arrivalTime_residualTail]
      ring
  | succ k =>
      simp only [residualTail]
      have hindex : canonicalRenewalCount h (residualTail s ω) + (k + 1) =
          (canonicalRenewalCount h (residualTail s ω) + k) + 1 := by omega
      rw [hindex]
      simp [interarrival, residualTail, hω, Nat.add_assoc]

private theorem iIndepFun_comp_of_hasLaw
    {Ω S ι : Type*} [MeasurableSpace Ω] [MeasurableSpace S]
    [Fintype ι] {P : Measure Ω} {μ : Measure S}
    [IsProbabilityMeasure P] [IsProbabilityMeasure μ]
    {Y : Ω → S} {A : ι → Type*} {mA : ∀ i, MeasurableSpace (A i)}
    (hY : Measurable Y) (hYlaw : ProbabilityTheory.HasLaw Y μ P)
    (Z : ∀ i, S → A i) (hZ : ∀ i, Measurable (Z i))
    (hZindep : ProbabilityTheory.iIndepFun Z μ) :
    ProbabilityTheory.iIndepFun (fun i => Z i ∘ Y) P := by
  rw [ProbabilityTheory.iIndepFun_iff_map_fun_eq_pi_map
    (fun i => ((hZ i).comp hY).aemeasurable)]
  change P.map ((fun x i => Z i x) ∘ Y) =
    Measure.pi (fun i => P.map (Z i ∘ Y))
  rw [← Measure.map_map (measurable_pi_iff.2 hZ) hY, hYlaw.map_eq,
    (ProbabilityTheory.iIndepFun_iff_map_fun_eq_pi_map
      (fun i => (hZ i).aemeasurable)).mp hZindep]
  congr 2
  funext i
  rw [← Measure.map_map (hZ i) hY, hYlaw.map_eq]

private theorem iIndepFun_fin_cons_of_indepFun_head_tail
    {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    {n : ℕ} (X : Ω → ℕ) (Y : Fin n → Ω → ℕ)
    (hX : Measurable X) (hY : ∀ i, Measurable (Y i))
    (hXY : ProbabilityTheory.IndepFun X (fun ω i => Y i ω) μ)
    (hYindep : ProbabilityTheory.iIndepFun Y μ) :
    ProbabilityTheory.iIndepFun
      (Fin.cons (α := fun _ : Fin (n + 1) => Ω → ℕ) X Y) μ := by
  rw [ProbabilityTheory.iIndepFun_iff_map_fun_eq_pi_map (fun i => by
    cases i using Fin.cases with
    | zero => exact hX.aemeasurable
    | succ i => exact (hY i).aemeasurable)]
  let e := MeasurableEquiv.piFinSuccAbove (fun _ : Fin (n + 1) => ℕ) 0
  apply e.map_measurableEquiv_injective
  rw [Measure.map_map e.measurable
    (measurable_pi_iff.2 (fun i => by
      cases i using Fin.cases with
      | zero => exact hX
      | succ i => exact hY i))]
  change μ.map (fun ω => (X ω, fun i => Y i ω)) =
    Measure.map e (Measure.pi (fun i =>
      μ.map (Fin.cons (α := fun _ : Fin (n + 1) => Ω → ℕ) X Y i)))
  rw [(measurePreserving_piFinSuccAbove
    (fun i : Fin (n + 1) =>
      μ.map (Fin.cons (α := fun _ : Fin (n + 1) => Ω → ℕ) X Y i)) 0).map_eq]
  change μ.map (fun ω => (X ω, fun i => Y i ω)) =
    (μ.map X).prod (Measure.pi (fun i => μ.map (Y i)))
  rw [(ProbabilityTheory.indepFun_iff_map_prod_eq_prod_map_map hX.aemeasurable
    (measurable_pi_iff.2 hY).aemeasurable).mp hXY,
    (ProbabilityTheory.iIndepFun_iff_map_fun_eq_pi_map
      (fun i => (hY i).aemeasurable)).mp hYindep]

private theorem iIndepFun_renewalIncrementVector
    {rate : ℝ} (hrate : 0 < rate) :
    ∀ (n : ℕ) (d : Fin n → ℝ), (∀ i, 0 ≤ d i) →
      ProbabilityTheory.iIndepFun (renewalIncrementVector n d)
        (exponentialInterarrivalMeasure rate) := by
  intro n
  induction n with
  | zero =>
      intro d hd
      letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
        isProbabilityMeasure_exponentialInterarrivalMeasure hrate
      exact ProbabilityTheory.iIndepFun.of_subsingleton
  | succ n ih =>
      intro d hd
      let μ : Measure (ℕ → ℝ) := exponentialInterarrivalMeasure rate
      letI : IsProbabilityMeasure μ := by
        simpa [μ] using isProbabilityMeasure_exponentialInterarrivalMeasure hrate
      let dTail : Fin n → ℝ := fun i => d i.succ
      let Y : Fin n → (ℕ → ℝ) → ℕ := renewalIncrementVector n dTail
      have hdTail : ∀ i, 0 ≤ dTail i := by
        intro i
        exact hd i.succ
      have hYmeas : ∀ i, Measurable (Y i) := by
        intro i
        exact measurable_renewalIncrementVector n dTail i
      have hYindep : ProbabilityTheory.iIndepFun Y μ := by
        exact ih dTail hdTail
      have htailIndep : ProbabilityTheory.iIndepFun
          (fun i => Y i ∘ residualTail (d 0)) μ := by
        exact iIndepFun_comp_of_hasLaw
          (measurable_residualTail (d 0))
          (residualTail_hasLaw_path hrate (hd 0)) Y hYmeas hYindep
      have hheadTail : ProbabilityTheory.IndepFun
          (canonicalRenewalCount (d 0))
          (fun ω i => (Y i ∘ residualTail (d 0)) ω) μ := by
        simpa [Function.comp_def] using
          (canonicalRenewalCount_indep_residualTail hrate (hd 0)).comp
            measurable_id (measurable_pi_iff.2 hYmeas)
      simpa [renewalIncrementVector, μ, dTail, Y] using
        iIndepFun_fin_cons_of_indepFun_head_tail
          (canonicalRenewalCount (d 0))
          (fun i => Y i ∘ residualTail (d 0))
          (measurable_canonicalRenewalCount (d 0))
          (fun i => (hYmeas i).comp (measurable_residualTail (d 0)))
          hheadTail htailIndep

private theorem ae_renewalTimeline_increment_eq_renewalIncrementVector
    {rate start : ℝ} (hrate : 0 < rate) :
    ∀ (n : ℕ) (d : Fin n → ℝ), (∀ i, 0 ≤ d i) →
      ∀ᵐ ω ∂exponentialInterarrivalMeasure rate, ∀ i : Fin n,
        canonicalRenewalCount (renewalTimeline start n d i.succ) ω -
          canonicalRenewalCount (renewalTimeline start n d i.castSucc) ω =
        renewalIncrementVector n d i (residualTail start ω) := by
  intro n
  induction n generalizing start with
  | zero =>
      intro d hd
      filter_upwards [] with ω
      exact fun i => Fin.elim0 i
  | succ n ih =>
      intro d hd
      let dTail : Fin n → ℝ := fun i => d i.succ
      have hdTail : ∀ i, 0 ≤ dTail i := by
        intro i
        exact hd i.succ
      have htail := ih (start := start + d 0) dTail hdTail
      have hfirst := ae_canonicalRenewalCount_increment_eq_residualTailCount
        hrate start (d 0) (hd 0)
      have hcocycle := ae_residualTail_add_eq_residualTail_comp
        (s := start) hrate (hd 0)
      filter_upwards [hfirst, htail, hcocycle] with ω hfirst htail hcocycle
      intro i
      cases i using Fin.cases with
      | zero =>
          simp only [renewalTimeline, renewalIncrementVector, Fin.cons_zero, Fin.cons_succ]
          rw [renewalTimeline_zero]
          exact hfirst
      | succ i =>
          have hcast : i.succ.castSucc = i.castSucc.succ := by
            apply Fin.ext
            rfl
          rw [hcast]
          simp only [renewalTimeline, renewalIncrementVector, Fin.cons_succ]
          rw [htail i, hcocycle]
          rfl

/-- The canonical renewal count has independent increments on nonnegative
time.  This is the concrete independent-increments proof used by the forward
Poisson constructor below. -/
theorem canonicalForwardCount_hasIndepIncrements
    {rate : ℝ} (hrate : 0 < rate) :
    ProbabilityTheory.HasIndepIncrements
      (fun (t : ℝ≥0) (ω : ℕ → ℝ) => canonicalRenewalCount (t : ℝ) ω)
      (exponentialInterarrivalMeasure rate) := by
  letI : IsProbabilityMeasure (exponentialInterarrivalMeasure rate) :=
    isProbabilityMeasure_exponentialInterarrivalMeasure hrate
  intro n t ht
  let r : Fin (n + 1) → ℝ := fun i => (t i : ℝ)
  let d : Fin n → ℝ := timelineDurations r
  have hd : ∀ i, 0 ≤ d i := by
    intro i
    exact sub_nonneg.mpr (NNReal.coe_le_coe.mpr (ht (Fin.castSucc_le_succ i)))
  have hvector := iIndepFun_renewalIncrementVector hrate n d hd
  have hcomp : ProbabilityTheory.iIndepFun
      (fun i => renewalIncrementVector n d i ∘ residualTail (r 0))
      (exponentialInterarrivalMeasure rate) := by
    exact iIndepFun_comp_of_hasLaw
      (measurable_residualTail (r 0))
      (residualTail_hasLaw_path hrate (by simp [r]))
      (renewalIncrementVector n d)
      (fun i => measurable_renewalIncrementVector n d i) hvector
  refine ProbabilityTheory.iIndepFun.congr (fun i => ?_) hcomp
  have hactual := ae_renewalTimeline_increment_eq_renewalIncrementVector
    (start := r 0) hrate n d hd
  filter_upwards [hactual] with ω hactual
  change renewalIncrementVector n d i (residualTail (r 0) ω) = _
  rw [← hactual i]
  rw [show renewalTimeline (r 0) n d i.succ = (t i.succ : ℝ) by
    simpa [r, d] using renewalTimeline_eq_timeline n r i.succ,
    show renewalTimeline (r 0) n d i.castSucc = (t i.castSucc : ℝ) by
      simpa [r, d] using renewalTimeline_eq_timeline n r i.castSucc]

/-- A canonical positive-rate homogeneous Poisson counting process indexed by
forward (`ℝ≥0`) time, constructed from iid exponential interarrivals. -/
def canonicalForwardHomogeneousPoissonCountingProcessByLaw
    {rate : ℝ} (hrate : 0 < rate) :
    ForwardHomogeneousPoissonCountingProcessByLaw (ℕ → ℝ)
      (exponentialInterarrivalMeasure rate) where
  isProbability := isProbabilityMeasure_exponentialInterarrivalMeasure hrate
  rate := rate
  rate_pos := hrate
  count := fun t ω => canonicalRenewalCount (t : ℝ) ω
  count_measurable := fun t => measurable_canonicalRenewalCount (t : ℝ)
  count_zero_ae := by
    filter_upwards [ae_all_interarrival_positive hrate] with ω hpos
    rw [canonicalRenewalCount_eq_zero_iff]
    left
    simpa [arrivalTime] using hpos 0
  count_mono_ae := by
    filter_upwards [ae_canonicalRenewalCount_monotone hrate] with ω hmono
    intro s t hst
    exact hmono (NNReal.coe_le_coe.mpr hst)
  hasIndepIncrements := canonicalForwardCount_hasIndepIncrements hrate
  increment_hasLaw := by
    intro s t hst
    have hs : 0 ≤ (s : ℝ) := NNReal.coe_nonneg s
    have hh : 0 ≤ (t : ℝ) - (s : ℝ) :=
      sub_nonneg.mpr (NNReal.coe_le_coe.mpr hst)
    simpa [rateExposureParam] using
      (canonicalRenewalCount_increment_hasLaw_poisson
        (s := (s : ℝ)) (h := (t : ℝ) - (s : ℝ)) hrate hs hh)

end

end AppliedModelingLib.Probability.PoissonProcess
