import AppliedModelingLib.Foundations.Probability.IidStatePrefixStopping
import AppliedModelingLib.Foundations.Probability.MeasureInequalities

/-!
# Maximal control for externally weighted IID rewards

This module supplies the finite martingale estimate for centered IID rewards
whose predictable coefficient is read from an independent external state.
The filtration retains that external state together with the consumed IID
prefix, so the next coordinate remains fresh while the coefficient is known.
-/

namespace AppliedModelingLib.Probability.IIDStream

open Filter MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal

noncomputable section

variable {σ α : Type*} [MeasurableSpace σ] [MeasurableSpace α]

/-- The filtration generated by an external state and the IID coordinates
through the indicated index. -/
noncomputable def stateStreamPrefixFiltration :
    Filtration ℕ (inferInstance : MeasurableSpace (σ × (ℕ → α))) where
  seq n := MeasurableSpace.comap (stateStreamPrefix (σ := σ) (α := α) n) inferInstance
  mono' m n hmn := by
    have hmeas : Measurable[MeasurableSpace.comap
        (stateStreamPrefix (σ := σ) (α := α) n) inferInstance]
        (stateStreamPrefix (σ := σ) (α := α) m) := by
      rw [← StatePrefixStoppingIndex.statePrefixRestriction_stateStreamPrefix
        (σ := σ) (α := α) m n hmn]
      exact (StatePrefixStoppingIndex.measurable_statePrefixRestriction
        (σ := σ) (α := α) m n hmn).comp
        (comap_measurable _)
    exact hmeas.comap_le
  le' n := (measurable_stateStreamPrefix (σ := σ) (α := α) n).comap_le

/-- The centered reward at coordinate `n + 1`, weighted by an independent
external state.  The shift makes the coordinate fresh relative to the prefix
filtration at time `n`. -/
def externalWeightedShiftedReward
    (weight : ℕ → σ → ℝ) (reward : α → ℝ) (n : ℕ) :
    σ × (ℕ → α) → ℝ :=
  fun z => weight n z.1 * reward (coordinate (n + 1) z.2)

/-- Finite prefix sums of externally weighted centered IID rewards. -/
def externalWeightedShiftedPartialSum
    (weight : ℕ → σ → ℝ) (reward : α → ℝ) (steps : ℕ) :
    σ × (ℕ → α) → ℝ :=
  fun z => ∑ n ∈ Finset.range steps,
    externalWeightedShiftedReward weight reward n z

/-- One IID coordinate weighted by an independent external state.  This
unshifted form is useful for a distinguished initial reward. -/
def externalWeightedCoordinateReward
    (weight : σ → ℝ) (reward : α → ℝ) (index : ℕ) :
    σ × (ℕ → α) → ℝ :=
  fun z => weight z.1 * reward (coordinate index z.2)

/-- An external-state weighted IID coordinate is measurable. -/
theorem measurable_externalWeightedCoordinateReward
    (weight : σ → ℝ) (reward : α → ℝ) (index : ℕ)
    (hweight : Measurable weight) (hreward : Measurable reward) :
    Measurable (externalWeightedCoordinateReward weight reward index) := by
  exact (hweight.comp measurable_fst).mul
    (hreward.comp ((measurable_coordinate (α := α) index).comp measurable_snd))

/-- The second moment of one external-state weighted IID coordinate is bounded
by the square coefficient bound times the reward second moment. -/
theorem integral_sq_externalWeightedCoordinateReward_le
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : σ → ℝ) (reward : α → ℝ) (index : ℕ)
    (hweight : Measurable weight) (hreward : Measurable reward)
    (bound : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ state, ‖weight state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ) :
    (∫ z, (externalWeightedCoordinateReward weight reward index z) ^ 2
      ∂(ρ.prod (measure μ))) ≤ bound ^ 2 * ∫ x, reward x ^ 2 ∂μ := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  have hweight_sq_meas : Measurable (fun state : σ => (weight state) ^ 2) :=
    hweight.pow_const 2
  have hweight_sq_int : Integrable (fun state : σ => (weight state) ^ 2) ρ := by
    apply Integrable.of_bound hweight_sq_meas.aestronglyMeasurable (bound ^ 2)
    filter_upwards with state
    have hsquare : (weight state) ^ 2 ≤ bound ^ 2 := by
      exact sq_le_sq.2 (by
        simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound state))
    simpa [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg (weight state))] using hsquare
  have hcoordinate_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (reward (coordinate index z.2)) ^ 2) ν := by
    simpa [ν] using StatePrefixStoppingIndex.integrable_state_coordinate
      ρ μ (fun x => reward x ^ 2) hreward_sq_int index
  have hreward_sq_meas : Measurable (fun x : α => reward x ^ 2) := hreward.pow_const 2
  have hY_sq_meas : Measurable (fun z : σ × (ℕ → α) =>
      (externalWeightedCoordinateReward weight reward index z) ^ 2) :=
    (measurable_externalWeightedCoordinateReward weight reward index hweight hreward).pow_const 2
  have hY_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (externalWeightedCoordinateReward weight reward index z) ^ 2) ν := by
    refine Integrable.mono' (hcoordinate_sq_int.const_mul (bound ^ 2))
      hY_sq_meas.aestronglyMeasurable ?_
    filter_upwards with z
    have hweight_bound : (weight z.1) ^ 2 ≤ bound ^ 2 := by
      exact sq_le_sq.2 (by
        simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound z.1))
    have hreward_sq_nonneg : 0 ≤ (reward (coordinate index z.2)) ^ 2 := sq_nonneg _
    change ‖(weight z.1 * reward (coordinate index z.2)) ^ 2‖ ≤
      bound ^ 2 * (reward (coordinate index z.2)) ^ 2
    rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _), mul_pow]
    exact mul_le_mul_of_nonneg_right hweight_bound hreward_sq_nonneg
  have hindep := indepFun_state_coordinate ρ μ index
  have hfactor := hindep.integral_comp_mul_comp
    measurable_fst.aemeasurable
    ((measurable_coordinate (α := α) index).comp measurable_snd).aemeasurable
    hweight_sq_meas.aestronglyMeasurable hreward_sq_meas.aestronglyMeasurable
  have hleft :
      (fun z : σ × (ℕ → α) => (weight z.1) ^ 2 *
        (reward (coordinate index z.2)) ^ 2) =
        fun z => (externalWeightedCoordinateReward weight reward index z) ^ 2 := by
    funext z
    simp only [externalWeightedCoordinateReward, mul_pow]
  have hweight_integral :
      (∫ z : σ × (ℕ → α), (weight z.1) ^ 2 ∂ν) =
        ∫ state, (weight state) ^ 2 ∂ρ := by
    simpa [ν] using (measurePreserving_fst : MeasurePreserving Prod.fst
      (ρ.prod (measure μ)) ρ).hasLaw.integral_comp hweight_sq_meas.aestronglyMeasurable
  have hreward_integral :
      (∫ z : σ × (ℕ → α), (reward (coordinate index z.2)) ^ 2 ∂ν) =
        ∫ x, reward x ^ 2 ∂μ := by
    simpa [ν] using ((coordinate_measurePreserving μ index).comp
      (measurePreserving_snd : MeasurePreserving Prod.snd
        (ρ.prod (measure μ)) (measure μ))).hasLaw.integral_comp
          hreward_sq_meas.aestronglyMeasurable
  have hfactor' :
      (∫ z : σ × (ℕ → α), (externalWeightedCoordinateReward weight reward index z) ^ 2 ∂ν) =
        (∫ state, (weight state) ^ 2 ∂ρ) * ∫ x, reward x ^ 2 ∂μ := by
    rw [← hleft]
    calc
      ∫ z : σ × (ℕ → α), (weight z.1) ^ 2 *
          (reward (coordinate index z.2)) ^ 2 ∂ν =
          (∫ z : σ × (ℕ → α), (weight z.1) ^ 2 ∂ν) *
            ∫ z, (reward (coordinate index z.2)) ^ 2 ∂ν := by
              simpa [ν, Function.comp_def] using hfactor
      _ = (∫ state, (weight state) ^ 2 ∂ρ) * ∫ x, reward x ^ 2 ∂μ := by
        rw [hweight_integral, hreward_integral]
  have hweight_second : (∫ state, (weight state) ^ 2 ∂ρ) ≤ bound ^ 2 := by
    apply AppliedModelingLib.integral_sq_le_sq_of_ae_abs_le hweight_sq_int hbound_nonneg
    filter_upwards with state
    simpa [Real.norm_eq_abs] using (hbound state)
  have hreward_second_nonneg : 0 ≤ ∫ x, reward x ^ 2 ∂μ :=
    integral_nonneg fun x => sq_nonneg (reward x)
  change (∫ z, (externalWeightedCoordinateReward weight reward index z) ^ 2 ∂ν) ≤ _
  rw [hfactor']
  exact mul_le_mul_of_nonneg_right hweight_second hreward_second_nonneg

/-- A bounded external-state weighted IID coordinate is square integrable
whenever the IID reward has a finite second moment. -/
theorem integrable_sq_externalWeightedCoordinateReward_of_bound
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : σ → ℝ) (reward : α → ℝ) (index : ℕ)
    (hweight : Measurable weight) (hreward : Measurable reward)
    (bound : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ state, ‖weight state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ) :
    Integrable (fun z => (externalWeightedCoordinateReward weight reward index z) ^ 2)
      (ρ.prod (measure μ)) := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  have hcoordinate_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (reward (coordinate index z.2)) ^ 2) ν := by
    simpa [ν] using StatePrefixStoppingIndex.integrable_state_coordinate
      ρ μ (fun x => reward x ^ 2) hreward_sq_int index
  have hY_sq_meas : Measurable (fun z : σ × (ℕ → α) =>
      (externalWeightedCoordinateReward weight reward index z) ^ 2) :=
    (measurable_externalWeightedCoordinateReward weight reward index hweight hreward).pow_const 2
  refine Integrable.mono' (hcoordinate_sq_int.const_mul (bound ^ 2))
    hY_sq_meas.aestronglyMeasurable ?_
  filter_upwards with z
  have hweight_bound : (weight z.1) ^ 2 ≤ bound ^ 2 := by
    exact sq_le_sq.2 (by
      simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound z.1))
  have hreward_sq_nonneg : 0 ≤ (reward (coordinate index z.2)) ^ 2 := sq_nonneg _
  change ‖(weight z.1 * reward (coordinate index z.2)) ^ 2‖ ≤
    bound ^ 2 * (reward (coordinate index z.2)) ^ 2
  rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _), mul_pow]
  exact mul_le_mul_of_nonneg_right hweight_bound hreward_sq_nonneg

/-- A one-coordinate square-event estimate for an external-state weighted IID
reward. -/
theorem ennreal_mul_measure_externalWeightedCoordinateSqEvent_le
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : σ → ℝ) (reward : α → ℝ) (index : ℕ)
    (hweight : Measurable weight) (hreward : Measurable reward)
    (bound variance : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ state, ‖weight state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ)
    (hvariance : (∫ x, reward x ^ 2 ∂μ) ≤ variance)
    (threshold : ℝ≥0) :
    threshold * (ρ.prod (measure μ)) {z |
      (threshold : ℝ) ≤ (externalWeightedCoordinateReward weight reward index z) ^ 2} ≤
      ENNReal.ofReal (bound ^ 2 * variance) := by
  have hmoment := integral_sq_externalWeightedCoordinateReward_le
    ρ μ weight reward index hweight hreward bound hbound_nonneg hbound hreward_sq_int
  have hsq_int := integrable_sq_externalWeightedCoordinateReward_of_bound
    ρ μ weight reward index hweight hreward bound hbound_nonneg hbound hreward_sq_int
  have hmarkov := AppliedModelingLib.ennreal_mul_measure_sq_event_le_integral_sq
    (X := externalWeightedCoordinateReward weight reward index) hsq_int threshold
  calc
    threshold * (ρ.prod (measure μ)) {z |
        (threshold : ℝ) ≤ (externalWeightedCoordinateReward weight reward index z) ^ 2} ≤
        ENNReal.ofReal (∫ z,
          (externalWeightedCoordinateReward weight reward index z) ^ 2 ∂(ρ.prod (measure μ))) := hmarkov
    _ ≤ ENNReal.ofReal (bound ^ 2 * variance) := ENNReal.ofReal_le_ofReal
      (hmoment.trans (mul_le_mul_of_nonneg_left hvariance (sq_nonneg bound)))

/-- One external-state weighted fresh reward is measurable. -/
theorem measurable_externalWeightedShiftedReward
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward) (n : ℕ) :
    Measurable (externalWeightedShiftedReward weight reward n) := by
  exact ((hweight n).comp measurable_fst).mul
    (hreward.comp ((measurable_coordinate (α := α) (n + 1)).comp measurable_snd))

/-- External-state weighted fresh rewards are integrable under a uniform
coefficient bound. -/
theorem integrable_externalWeightedShiftedReward_of_bound
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound : ℝ)
    (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hintegrable : Integrable reward μ) (n : ℕ) :
    Integrable (externalWeightedShiftedReward weight reward n)
      (ρ.prod (measure μ)) := by
  have hmeas := measurable_externalWeightedShiftedReward weight reward hweight hreward n
  have hcoordinate : Integrable (fun z : σ × (ℕ → α) =>
      reward (coordinate (n + 1) z.2)) (ρ.prod (measure μ)) :=
    StatePrefixStoppingIndex.integrable_state_coordinate
      ρ μ reward hintegrable (n + 1)
  refine Integrable.mono' (hcoordinate.norm.const_mul bound)
    hmeas.aestronglyMeasurable ?_
  filter_upwards with z
  change ‖weight n z.1 * reward (coordinate (n + 1) z.2)‖ ≤
    bound * ‖reward (coordinate (n + 1) z.2)‖
  rw [norm_mul]
  exact mul_le_mul_of_nonneg_right (hbound n z.1) (norm_nonneg _)

/-- The shifted partial sums are adapted to the filtration revealing the
external state and exactly the already-consumed IID coordinates. -/
theorem stronglyAdapted_externalWeightedShiftedPartialSum
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward) :
    StronglyAdapted (stateStreamPrefixFiltration (σ := σ) (α := α))
      (externalWeightedShiftedPartialSum weight reward) := by
  intro steps
  unfold externalWeightedShiftedPartialSum
  have hsum_eq : (fun z : σ × (ℕ → α) =>
      ∑ n ∈ Finset.range steps, externalWeightedShiftedReward weight reward n z) =
      ∑ n ∈ Finset.range steps, externalWeightedShiftedReward weight reward n := by
    funext z
    simp
  rw [hsum_eq]
  change StronglyMeasurable[MeasurableSpace.comap
    (stateStreamPrefix (σ := σ) (α := α) steps) inferInstance]
    (∑ n ∈ Finset.range steps, externalWeightedShiftedReward weight reward n)
  refine Finset.stronglyMeasurable_sum (Finset.range steps) ?_
  intro index hindex
  have hindex_lt : index < steps := Finset.mem_range.mp hindex
  have hcoordinate_lt : index + 1 < steps + 1 := Nat.succ_lt_succ hindex_lt
  let coordinateIndex : Finset.range (steps + 1) :=
    ⟨index + 1, Finset.mem_range.mpr hcoordinate_lt⟩
  let F : σ × (Finset.range (steps + 1) → α) → ℝ := fun visible =>
    weight index visible.1 * reward (visible.2 coordinateIndex)
  have hF : Measurable F := by
    exact ((hweight index).comp measurable_fst).mul
      (hreward.comp ((measurable_pi_apply coordinateIndex).comp measurable_snd))
  have hF_eq : F ∘ stateStreamPrefix (σ := σ) (α := α) steps =
      externalWeightedShiftedReward weight reward index := by
    funext z
    rfl
  rw [← hF_eq]
  exact (hF.comp (comap_measurable _)).stronglyMeasurable

/-- A centered fresh reward has conditional mean zero after revealing the
external state and all preceding IID coordinates. -/
theorem condExp_externalWeightedShiftedReward_ae_eq_zero
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound : ℝ) (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hintegrable : Integrable reward μ) (hmean : ∫ x, reward x ∂μ = 0) (n : ℕ) :
    (ρ.prod (measure μ))[externalWeightedShiftedReward weight reward n |
      stateStreamPrefixFiltration (σ := σ) (α := α) n] =ᵐ[ρ.prod (measure μ)] 0 := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  letI : IsFiniteMeasure ν := by infer_instance
  have hYint : Integrable (externalWeightedShiftedReward weight reward n) ν := by
    simpa [ν] using integrable_externalWeightedShiftedReward_of_bound
      ρ μ weight reward hweight hreward bound hbound hintegrable n
  change ν[externalWeightedShiftedReward weight reward n |
    stateStreamPrefixFiltration (σ := σ) (α := α) n] =ᵐ[ν] 0
  symm
  refine ae_eq_condExp_of_forall_setIntegral_eq
    ((stateStreamPrefixFiltration (σ := σ) (α := α)).le n) hYint
    (fun s _ _ => (integrable_const _).integrableOn) ?_
      stronglyMeasurable_const.aestronglyMeasurable
  intro s hs _
  change MeasurableSet[MeasurableSpace.comap
    (stateStreamPrefix (σ := σ) (α := α) n) inferInstance] s at hs
  rcases hs with ⟨historyEvent, hhistoryEvent, rfl⟩
  let F : σ × (Finset.range (n + 1) → α) → ℝ :=
    historyEvent.indicator (fun visible => weight n visible.1)
  let G : (Fin 1 → α) → ℝ := fun fresh => reward (fresh 0)
  have hF : Measurable F :=
    ((hweight n).comp measurable_fst).indicator hhistoryEvent
  have hG : Measurable G := hreward.comp (measurable_pi_apply 0)
  have hindep := indepFun_state_streamPrefix_block ρ μ n 1
  have hfactor := hindep.integral_comp_mul_comp
    (measurable_stateStreamPrefix (σ := σ) (α := α) n).aemeasurable
    ((measurable_block (α := α) (n + 1) 1).comp measurable_snd).aemeasurable
    hF.aestronglyMeasurable hG.aestronglyMeasurable
  have hleft :
      (fun z : σ × (ℕ → α) => F (stateStreamPrefix (σ := σ) (α := α) n z) *
          G (block (α := α) (n + 1) 1 z.2)) =
        (stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent).indicator
          (externalWeightedShiftedReward weight reward n) := by
    funext z
    by_cases h : stateStreamPrefix (σ := σ) (α := α) n z ∈ historyEvent
    · have hpre : z ∈ stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent := h
      simp only [F, G, Set.indicator_of_mem h, Set.indicator_of_mem hpre]
      rfl
    · have hpre : z ∉ stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent := h
      simp only [F, G, Set.indicator_of_notMem h, Set.indicator_of_notMem hpre]
      exact zero_mul _
  have hprefix_meas : MeasurableSet
      (stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent) :=
    hhistoryEvent.preimage (measurable_stateStreamPrefix (σ := σ) (α := α) n)
  have hG_integral :
      (∫ z : σ × (ℕ → α), G (block (α := α) (n + 1) 1 z.2) ∂ν) =
        ∫ x, reward x ∂μ := by
    simpa [ν, G, block, coordinate] using
      ((coordinate_measurePreserving μ (n + 1)).comp
        (measurePreserving_snd : MeasurePreserving Prod.snd
          (ρ.prod (measure μ)) (measure μ))).hasLaw.integral_comp
            hreward.aestronglyMeasurable
  rw [← integral_indicator hprefix_meas, ← integral_indicator hprefix_meas]
  calc
    ∫ x, (stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent).indicator
        (fun _ => (0 : ℝ)) x ∂ν = 0 := by simp
    _ = (∫ z : σ × (ℕ → α), F (stateStreamPrefix (σ := σ) (α := α) n z) ∂ν) *
        ∫ z : σ × (ℕ → α), G (block (α := α) (n + 1) 1 z.2) ∂ν := by
          rw [hG_integral, hmean, mul_zero]
    _ = ∫ z : σ × (ℕ → α), F (stateStreamPrefix (σ := σ) (α := α) n z) *
        G (block (α := α) (n + 1) 1 z.2) ∂ν := by
          simpa [ν, Function.comp_def] using hfactor.symm
    _ = ∫ z, (stateStreamPrefix (σ := σ) (α := α) n ⁻¹' historyEvent).indicator
        (externalWeightedShiftedReward weight reward n) z ∂ν := by rw [hleft]

/-- Centered externally weighted IID prefix sums are a martingale for the
external-state/IID-prefix filtration. -/
theorem externalWeightedShiftedPartialSum_martingale
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound : ℝ) (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hintegrable : Integrable reward μ) (hmean : ∫ x, reward x ∂μ = 0) :
    Martingale (externalWeightedShiftedPartialSum weight reward)
      (stateStreamPrefixFiltration (σ := σ) (α := α)) (ρ.prod (measure μ)) := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  letI : IsFiniteMeasure ν := by infer_instance
  have hadapted := stronglyAdapted_externalWeightedShiftedPartialSum
    weight reward hweight hreward
  have hintegrable_sum : ∀ steps : ℕ,
      Integrable (fun z : σ × (ℕ → α) => ∑ n ∈ Finset.range steps,
        externalWeightedShiftedReward weight reward n z) ν := by
    intro steps
    apply integrable_finset_sum
    intro n _
    simpa [ν] using integrable_externalWeightedShiftedReward_of_bound
      ρ μ weight reward hweight hreward bound hbound hintegrable n
  have hcond : ∀ n : ℕ, ν[externalWeightedShiftedReward weight reward n |
      stateStreamPrefixFiltration (σ := σ) (α := α) n] =ᵐ[ν] 0 := by
    intro n
    simpa [ν] using condExp_externalWeightedShiftedReward_ae_eq_zero
      ρ μ weight reward hweight hreward bound hbound hintegrable hmean n
  simpa [ν, externalWeightedShiftedPartialSum] using
    AppliedModelingLib.martingale_partial_sum_of_condExp_eq_zero
      (Y := externalWeightedShiftedReward weight reward)
      hadapted hintegrable_sum hcond

/-- The second moment of one externally weighted IID reward is bounded by the
square coefficient bound times the IID reward's second moment. -/
theorem integral_sq_externalWeightedShiftedReward_le
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ) (n : ℕ) :
    (∫ z, (externalWeightedShiftedReward weight reward n z) ^ 2
      ∂(ρ.prod (measure μ))) ≤ bound ^ 2 * ∫ x, reward x ^ 2 ∂μ := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  have hweight_sq_meas : Measurable (fun state : σ => (weight n state) ^ 2) :=
    (hweight n).pow_const 2
  have hweight_sq_int : Integrable (fun state : σ => (weight n state) ^ 2) ρ := by
    apply Integrable.of_bound hweight_sq_meas.aestronglyMeasurable (bound ^ 2)
    filter_upwards with state
    have hsquare : (weight n state) ^ 2 ≤ bound ^ 2 := by
      exact sq_le_sq.2 (by
        simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound n state))
    simpa [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg (weight n state))] using hsquare
  have hcoordinate_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (reward (coordinate (n + 1) z.2)) ^ 2) ν := by
    simpa [ν] using StatePrefixStoppingIndex.integrable_state_coordinate
      ρ μ (fun x => reward x ^ 2) hreward_sq_int (n + 1)
  have hreward_sq_meas : Measurable (fun x : α => reward x ^ 2) := hreward.pow_const 2
  have hY_sq_meas : Measurable (fun z : σ × (ℕ → α) =>
      (externalWeightedShiftedReward weight reward n z) ^ 2) :=
    (measurable_externalWeightedShiftedReward weight reward hweight hreward n).pow_const 2
  have hY_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (externalWeightedShiftedReward weight reward n z) ^ 2) ν := by
    refine Integrable.mono' (hcoordinate_sq_int.const_mul (bound ^ 2))
      hY_sq_meas.aestronglyMeasurable ?_
    filter_upwards with z
    have hweight_bound : (weight n z.1) ^ 2 ≤ bound ^ 2 := by
      exact sq_le_sq.2 (by
        simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound n z.1))
    have hreward_sq_nonneg : 0 ≤ (reward (coordinate (n + 1) z.2)) ^ 2 := sq_nonneg _
    change ‖(weight n z.1 * reward (coordinate (n + 1) z.2)) ^ 2‖ ≤
      bound ^ 2 * (reward (coordinate (n + 1) z.2)) ^ 2
    rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _)]
    rw [mul_pow]
    exact mul_le_mul_of_nonneg_right hweight_bound hreward_sq_nonneg
  have hindep := indepFun_state_coordinate ρ μ (n + 1)
  have hfactor := hindep.integral_comp_mul_comp
    measurable_fst.aemeasurable
    ((measurable_coordinate (α := α) (n + 1)).comp measurable_snd).aemeasurable
    hweight_sq_meas.aestronglyMeasurable hreward_sq_meas.aestronglyMeasurable
  have hleft :
      (fun z : σ × (ℕ → α) => (weight n z.1) ^ 2 *
        (reward (coordinate (n + 1) z.2)) ^ 2) =
        fun z => (externalWeightedShiftedReward weight reward n z) ^ 2 := by
    funext z
    simp only [externalWeightedShiftedReward, mul_pow]
  have hweight_integral :
      (∫ z : σ × (ℕ → α), (weight n z.1) ^ 2 ∂ν) =
        ∫ state, (weight n state) ^ 2 ∂ρ := by
    simpa [ν] using (measurePreserving_fst : MeasurePreserving Prod.fst
      (ρ.prod (measure μ)) ρ).hasLaw.integral_comp hweight_sq_meas.aestronglyMeasurable
  have hreward_integral :
      (∫ z : σ × (ℕ → α), (reward (coordinate (n + 1) z.2)) ^ 2 ∂ν) =
        ∫ x, reward x ^ 2 ∂μ := by
    simpa [ν] using ((coordinate_measurePreserving μ (n + 1)).comp
      (measurePreserving_snd : MeasurePreserving Prod.snd
        (ρ.prod (measure μ)) (measure μ))).hasLaw.integral_comp
          hreward_sq_meas.aestronglyMeasurable
  have hfactor' :
      (∫ z : σ × (ℕ → α), (externalWeightedShiftedReward weight reward n z) ^ 2 ∂ν) =
        (∫ state, (weight n state) ^ 2 ∂ρ) * ∫ x, reward x ^ 2 ∂μ := by
    rw [← hleft]
    calc
      ∫ z : σ × (ℕ → α), (weight n z.1) ^ 2 *
          (reward (coordinate (n + 1) z.2)) ^ 2 ∂ν =
          (∫ z : σ × (ℕ → α), (weight n z.1) ^ 2 ∂ν) *
            ∫ z : σ × (ℕ → α), (reward (coordinate (n + 1) z.2)) ^ 2 ∂ν := by
              simpa [ν, Function.comp_def] using hfactor
      _ = (∫ state, (weight n state) ^ 2 ∂ρ) * ∫ x, reward x ^ 2 ∂μ := by
        rw [hweight_integral, hreward_integral]
  have hweight_second : (∫ state, (weight n state) ^ 2 ∂ρ) ≤ bound ^ 2 := by
    apply AppliedModelingLib.integral_sq_le_sq_of_ae_abs_le hweight_sq_int hbound_nonneg
    filter_upwards with state
    simpa [Real.norm_eq_abs] using (hbound n state)
  have hreward_second_nonneg : 0 ≤ ∫ x, reward x ^ 2 ∂μ :=
    integral_nonneg fun x => sq_nonneg (reward x)
  change (∫ z, (externalWeightedShiftedReward weight reward n z) ^ 2 ∂ν) ≤ _
  rw [hfactor']
  exact mul_le_mul_of_nonneg_right hweight_second hreward_second_nonneg

/-- A finite second moment of the IID reward gives square integrability of
every bounded externally weighted fresh reward. -/
theorem integrable_sq_externalWeightedShiftedReward_of_bound
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ) (n : ℕ) :
    Integrable (fun z => (externalWeightedShiftedReward weight reward n z) ^ 2)
      (ρ.prod (measure μ)) := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  have hcoordinate_sq_int : Integrable (fun z : σ × (ℕ → α) =>
      (reward (coordinate (n + 1) z.2)) ^ 2) ν := by
    simpa [ν] using StatePrefixStoppingIndex.integrable_state_coordinate
      ρ μ (fun x => reward x ^ 2) hreward_sq_int (n + 1)
  have hY_sq_meas : Measurable (fun z : σ × (ℕ → α) =>
      (externalWeightedShiftedReward weight reward n z) ^ 2) :=
    (measurable_externalWeightedShiftedReward weight reward hweight hreward n).pow_const 2
  refine Integrable.mono' (hcoordinate_sq_int.const_mul (bound ^ 2))
    hY_sq_meas.aestronglyMeasurable ?_
  filter_upwards with z
  have hweight_bound : (weight n z.1) ^ 2 ≤ bound ^ 2 := by
    exact sq_le_sq.2 (by
      simpa [Real.norm_eq_abs, abs_of_nonneg hbound_nonneg] using (hbound n z.1))
  have hreward_sq_nonneg : 0 ≤ (reward (coordinate (n + 1) z.2)) ^ 2 := sq_nonneg _
  change ‖(weight n z.1 * reward (coordinate (n + 1) z.2)) ^ 2‖ ≤
    bound ^ 2 * (reward (coordinate (n + 1) z.2)) ^ 2
  rw [Real.norm_eq_abs, abs_of_nonneg (sq_nonneg _), mul_pow]
  exact mul_le_mul_of_nonneg_right hweight_bound hreward_sq_nonneg

/-- Doob's finite-prefix estimate for bounded coefficients read from an
independent external state and centered IID rewards. -/
theorem ennreal_mul_measure_externalWeightedShiftedMaximumSq_le
    (ρ : Measure σ) (μ : Measure α) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (weight : ℕ → σ → ℝ) (reward : α → ℝ)
    (hweight : ∀ n, Measurable (weight n)) (hreward : Measurable reward)
    (bound variance : ℝ) (hbound_nonneg : 0 ≤ bound)
    (hbound : ∀ n state, ‖weight n state‖ ≤ bound)
    (hreward_sq_int : Integrable (fun x => reward x ^ 2) μ)
    (hmean : ∫ x, reward x ∂μ = 0)
    (hvariance : (∫ x, reward x ^ 2 ∂μ) ≤ variance)
    (cap : ℕ) (threshold : ℝ≥0) :
    threshold * (ρ.prod (measure μ)) {z |
      (threshold : ℝ) ≤ (Finset.range (cap + 1)).sup'
        Finset.nonempty_range_add_one
        (fun steps => (externalWeightedShiftedPartialSum weight reward steps z) ^ 2)} ≤
      ENNReal.ofReal ((cap : ℝ) * (bound ^ 2 * variance)) := by
  let ν : Measure (σ × (ℕ → α)) := ρ.prod (measure μ)
  letI : IsProbabilityMeasure (measure μ) := by
    dsimp [measure]
    infer_instance
  letI : IsProbabilityMeasure ν := by
    dsimp [ν]
    infer_instance
  letI : IsFiniteMeasure ν := by infer_instance
  have hreward_memLp : MemLp reward 2 μ :=
    (memLp_two_iff_integrable_sq hreward.aestronglyMeasurable).2 hreward_sq_int
  have hreward_int : Integrable reward μ := hreward_memLp.integrable one_le_two
  have hmartingale := externalWeightedShiftedPartialSum_martingale
    ρ μ weight reward hweight hreward bound hbound hreward_int hmean
  have hadapted := stronglyAdapted_externalWeightedShiftedPartialSum
    weight reward hweight hreward
  have hY_sq_int : ∀ n : ℕ, Integrable (fun z =>
      (externalWeightedShiftedReward weight reward n z) ^ 2) ν := by
    intro n
    simpa [ν] using integrable_sq_externalWeightedShiftedReward_of_bound
      ρ μ weight reward hweight hreward bound hbound_nonneg hbound hreward_sq_int n
  have hY_memLp : ∀ n : ℕ, MemLp (externalWeightedShiftedReward weight reward n) 2 ν := by
    intro n
    have hraw_meas : Measurable (externalWeightedShiftedReward weight reward n) :=
      measurable_externalWeightedShiftedReward weight reward hweight hreward n
    have hmeas : AEStronglyMeasurable
        (externalWeightedShiftedReward weight reward n) ν :=
      hraw_meas.aestronglyMeasurable
    exact (memLp_two_iff_integrable_sq hmeas).2 (hY_sq_int n)
  have hS_memLp : ∀ steps : ℕ,
      MemLp (externalWeightedShiftedPartialSum weight reward steps) 2 ν := by
    intro steps
    have hsum : MemLp (fun z : σ × (ℕ → α) => ∑ n ∈ Finset.range steps,
        externalWeightedShiftedReward weight reward n z) 2 ν :=
      MeasureTheory.memLp_finset_sum (Finset.range steps) (fun n _ => hY_memLp n)
    simpa [externalWeightedShiftedPartialSum] using hsum
  have hY_int : ∀ n : ℕ, Integrable (externalWeightedShiftedReward weight reward n) ν := by
    intro n
    exact (hY_memLp n).integrable one_le_two
  have hcond : ∀ n : ℕ, ν[externalWeightedShiftedReward weight reward n |
      stateStreamPrefixFiltration (σ := σ) (α := α) n] =ᵐ[ν] 0 := by
    intro n
    simpa [ν] using condExp_externalWeightedShiftedReward_ae_eq_zero
      ρ μ weight reward hweight hreward bound hbound hreward_int hmean n
  have hsum_sq_int : ∀ steps : ℕ, Integrable (fun z =>
      (∑ n ∈ Finset.range steps, externalWeightedShiftedReward weight reward n z) ^ 2) ν := by
    intro steps
    simpa [externalWeightedShiftedPartialSum] using (hS_memLp steps).integrable_sq
  have hcross_int : ∀ n : ℕ, Integrable (fun z =>
      (∑ i ∈ Finset.range n, externalWeightedShiftedReward weight reward i z) *
        externalWeightedShiftedReward weight reward n z) ν := by
    intro n
    have hproduct : MemLp (fun z =>
        externalWeightedShiftedPartialSum weight reward n z *
          externalWeightedShiftedReward weight reward n z) 1 ν :=
      (hY_memLp n).mul' (hS_memLp n)
    simpa [externalWeightedShiftedPartialSum] using hproduct.integrable
  have hcross_nonpos : ∀ n : ℕ,
      (∫ z, (∑ i ∈ Finset.range n,
        externalWeightedShiftedReward weight reward i z) *
          externalWeightedShiftedReward weight reward n z ∂ν) ≤ 0 := by
    exact AppliedModelingLib.partial_sum_cross_integral_nonpos_of_condExp_eq_zero
      hadapted hcross_int hY_int hcond
  have hY_second : ∀ n : ℕ,
      (∫ z, (externalWeightedShiftedReward weight reward n z) ^ 2 ∂ν) ≤
        bound ^ 2 * variance := by
    intro n
    calc
      (∫ z, (externalWeightedShiftedReward weight reward n z) ^ 2 ∂ν) ≤
          bound ^ 2 * ∫ x, reward x ^ 2 ∂μ := by
        simpa [ν] using integral_sq_externalWeightedShiftedReward_le
          ρ μ weight reward hweight hreward bound hbound_nonneg hbound hreward_sq_int n
      _ ≤ bound ^ 2 * variance := by
        exact mul_le_mul_of_nonneg_left hvariance (sq_nonneg bound)
  have hsecond := AppliedModelingLib.partial_sum_secondMoment_le_sum_of_cross_nonpos
    (Y := externalWeightedShiftedReward weight reward)
    (b := fun _ => bound ^ 2 * variance)
    hsum_sq_int hcross_int hY_sq_int hY_second hcross_nonpos cap
  have hterminal_second :
      (∫ z, (externalWeightedShiftedPartialSum weight reward cap z) ^ 2 ∂ν) ≤
        (cap : ℝ) * (bound ^ 2 * variance) := by
    simpa [externalWeightedShiftedPartialSum] using hsecond
  have hmax := AppliedModelingLib.ennreal_mul_measure_range_sup_sq_le_integral_sq
    hmartingale hS_memLp threshold cap
  change threshold * ν {z |
    (threshold : ℝ) ≤ (Finset.range (cap + 1)).sup'
      Finset.nonempty_range_add_one
      (fun steps => (externalWeightedShiftedPartialSum weight reward steps z) ^ 2)} ≤ _
  calc
    threshold * ν {z |
        (threshold : ℝ) ≤ (Finset.range (cap + 1)).sup'
          Finset.nonempty_range_add_one
          (fun steps => (externalWeightedShiftedPartialSum weight reward steps z) ^ 2)} ≤
        ENNReal.ofReal (∫ z,
          (externalWeightedShiftedPartialSum weight reward cap z) ^ 2 ∂ν) := by
          simpa [ν] using hmax
    _ ≤ ENNReal.ofReal ((cap : ℝ) * (bound ^ 2 * variance)) :=
      ENNReal.ofReal_le_ofReal hterminal_second

end

end AppliedModelingLib.Probability.IIDStream
